### ISSUE TITLE
Next

### ISSUE THREAD

**Issue by faustoct** [filipedeschamps/video-maker#103]
Pessoal, se alguém puder documentar ou divulgar os próximos passos eu agradeço. Tenho algumas ideias e to trabalhando nelas no tempo livre. Vou colocar um app no ar que usa os robos.. se alguem tiver alinhado com essa ideia seria otimo..

Meu objetivo é deixar opensource assim como esse projeto. Sendo esse projeto o core do negócio.. Vi comentarem de um org, site, etc.. Ainda nao entendi bem como isso vai funcionar..

**Comment by danielschmitz** [comment]
Acompanhe o #77
