### ISSUE TITLE
Erro depois de executar o index.js e escolher a opção...

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#104]
Alguém sabe porque está dando esse problema?
![image](https://user-images.githubusercontent.com/48515934/55398256-81688000-551e-11e9-97ef-53522b3ac07c.png)

Fiz as seguintes instalações:
npm i
npm i algorithmia
npm i watson-developer-cloud

Alterei as seguintes API Keys:
Algorithmia (algorithmia.json)
Watson (warson-nlu.json)

Não coloquei API Key:
Google Search (google-search.json)
OBS.: Não fiz instalação do Google Search, se é que é necessário.

**Comment by AnibalDuarte** [comment]
Isso é um erro em alguma das APIs utilizadas, dizendo que o uso gratuito diário sem autenticação foi excedido. Verifica todas as credenciais e instala o Google Search, só por via das dúvidas.

**Comment by VinyciusC** [comment]
@AnibalDuarte obrigado pela resposta, fiz o que você disse (instalei o Google Search, verifiquei as credenciais), e agora está dando o seguinte erro depois de instalar o Google Search:
![image](https://user-images.githubusercontent.com/48515934/55437223-c7e8c980-5574-11e9-837b-ff123f137b94.png)

**Comment by AnibalDuarte** [comment]
@VinyciusC não tenho a menor ideia do que é esse Gaxios, mas tenho ele aqui também e nunca causou nenhum erro parecido.... 

No geral esse erro acontece porque alguma função com Promise dentro de uma função async não tem um bloco de captura de erros.

Faz o seguinte: testa os robôs um por um até o erro acontecer. Quando chegar no robô que estoura o erro busca a função com essas características (com Promise). 

Em último caso faz checkout do projeto em uma nova pasta e vai alterando novamente os arquivos um a um.

**Comment by danielschmitz** [comment]
Olá,
você baixou o projeto e executou, ou está escrevendo o código?
seguiu os passos em #89 ?

**Comment by VinyciusC** [comment]
Olá @danielschmitz , sim fiz o que está nessa issue:

Fiz as seguintes instalações:
`npm i`
`npm i algorithmia`
`npm i watson-developer-cloud`

API Keys:
Algorithmia (algorithmia.json)
Watson (warson-nlu.json)
Google Search (google-search.json)

De resto não fiz mais nada, só vi os videos do Algorithmia, Watson e Google Search.
Removi todas as alterações que eu mesmo fiz (Tradução e a remoção das opções)
Já removi a pasta `node_modules`

**Comment by vsalbuq** [comment]
@VinyciusC, coloca o seu código aqui (`text.js` e `input.js`).

**Comment by VinyciusC** [comment]
**text.js**

`const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')

const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js')
 
const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
})

const state = require('./state.js')

async function robot() {
  const content = state.load()

  await fetchContentFromWikipedia(content)
  sanitizeContent(content)
  breakContentIntoSentences(content)
  limitMaximumSentences(content)
  await fetchKeywordsOfAllSentences(content)

  state.save(content)

  async function fetchContentFromWikipedia(content) {
    const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
    const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
    const wikipediaContent = wikipediaResponse.get()

    content.sourceContentOriginal = wikipediaContent.content
  }

  function sanitizeContent(content) {
    const withoutBlankLinesAndMarkdown = removeBlankLinesAndMarkdown(content.sourceContentOriginal)
    const withoutDatesInParentheses = removeDatesInParentheses(withoutBlankLinesAndMarkdown)

    content.sourceContentSanitized = withoutDatesInParentheses

    function removeBlankLinesAndMarkdown(text) {
      const allLines = text.split('\n')

      const withoutBlankLinesAndMarkdown = allLines.filter((line) => {
        if (line.trim().length === 0 || line.trim().startsWith('=')) {
          return false
        }

        return true
      })

      return withoutBlankLinesAndMarkdown.join(' ')
    }
  }

  function removeDatesInParentheses(text) {
    return text.replace(/\((?:\([^()]*\)|[^()])*\)/gm, '').replace(/  /g,' ')
  }

  function breakContentIntoSentences(content) {
    content.sentences = []

    const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
    sentences.forEach((sentence) => {
      content.sentences.push({
        text: sentence,
        keywords: [],
        images: []
      })
    })
  }

  function limitMaximumSentences(content) {
    content.sentences = content.sentences.slice(0, content.maximumSentences)
  }

  async function fetchKeywordsOfAllSentences(content) {
    for (const sentence of content.sentences) {
      sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)
    }
  }

  async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
      nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
      }, (error, response) => {
        if (error) {
          throw error
        }

        const keywords = response.keywords.map((keyword) => {
          return keyword.text
        })

        resolve(keywords)
      })
    })
  }

}

module.exports = robot
`

______________________________________________________________

**input.js**

`const readline = require('readline-sync')
const state = require('./state.js')

function robot() {
  const content = {
    maximumSentences: 7
  }

  content.searchTerm = askAndReturnSearchTerm()
  content.prefix = askAndReturnPrefix()
  state.save(content)

  function askAndReturnSearchTerm() {
    return readline.question('Procure pelo termo na Wikepedia: ')
  }

  function askAndReturnPrefix() {
    const prefixes = ['Who is', 'What is', 'The history of']
    const selectedPrefixIndex = readline.keyInSelect(prefixes, 'Choose one option: ')
    const selectedPrefixText = prefixes[selectedPrefixIndex]

    return selectedPrefixText
  }

}

module.exports = robot
`

**Comment by hebertlima** [comment]
@VinyciusC você precisa a cessar o [Custom Search Enginer](https://cse.google.com/cse/create/new) e habilitar a opção **Pesquisa de imagens**, eu atualizei a issue #89 explicando essa parte da uma olhada 😉

**Comment by VinyciusC** [comment]
@hebertlima parece ter funcionado, porém deu um outro problema agora:
![image](https://user-images.githubusercontent.com/48515934/55628807-0c987e80-5788-11e9-8833-6a494ae72304.png)
Pelo que vi é nessa parte:
```})

    const imagesUrl = response.data.items.map((item) => {
      return item.link
    })```

**Comment by hebertlima** [comment]
Você esta realizando a pesquisa no site google.com? o seu cse está configurado corretamente? pelo arquivo que deu erro, você deve ter pego o ultimo commit que o Filipe fez, que nesse caso ainda não saiu o vídeo, sendo assim vai ser tentativa e erro pra saber onde corrigir, vou tentr reproduzir aqui e ver se consigo te ajudar

**Comment by VinyciusC** [comment]
É que eu não clonei, eu baixei ele :D

**Comment by danielschmitz** [comment]
> @hebertlima parece ter funcionado, porém deu um outro problema agora:
> ![image](https://user-images.githubusercontent.com/48515934/55628807-0c987e80-5788-11e9-8833-6a494ae72304.png)
> Pelo que vi é nessa parte:
> ![image](https://user-images.githubusercontent.com/48515934/55628935-60a36300-5788-11e9-9fb2-c4ee1171eb13.png)

Eu tive esse erro ao pesquisar por "bacon"

A segunda sentença retonava nulo, como se não houvesse imagens para ela. Enfim, resolvi assim:

![image](https://user-images.githubusercontent.com/1509692/56080442-97582980-5dd7-11e9-96b2-0d59931b7f49.png)

**Comment by MatheusRV** [comment]
@VinyciusC Conseguiu resolver? Posso fechar.
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
O projeto não possui erros quanto ao consumo de credenciais.
Por inatividade, estou fechando a issue.
Utilize o Discord para perguntas e dúvidas.
