### ISSUE TITLE
função sanitizedContent

### ISSUE THREAD

**Issue by marcosfpinheiro** [filipedeschamps/video-maker#105]
Pessoal, nem sei se é aqui que devo colocar esse tipo de duvida, mas se não for, desculpe e me informem onde é por favor!
Parabéns ao Filipe, Esse projeto é como aprender plugando o cabo na nuca e fazendo o upload do conteúdo! rs

A duvida é a seguinte, eu tenho reparado bastante na estruturação do código para aprender e notei que na função sanitizedContent foram criadas duas "sub"-funções que a função usa. Só que uma foi interna e outra externa. 

Tem algum motivo para isso?

**Comment by AnibalDuarte** [comment]
Vou responder pelo que eu entendi até agora e como funciona no PHP:

Se você pegar um robô ele é programado inteiro dentro de uma função chamada robot. 

Quando você exporta essa função como módulo, como no input.js :

[module.export = robot](https://github.com/filipedeschamps/video-maker/blob/af49ce76624ba7e159f52f7285d60ebc76740a74/robots/input.js#L27)
Isso permite que onde quer que esse robô seja importado você tenha acesso às subfunções de robot.

Se a função estiver fora do módulo você não conseguirá acessar ela, exceto se exportar a função separada. Essa exportação separada acontece [no state.js](https://github.com/filipedeschamps/video-maker/blob/af49ce76624ba7e159f52f7285d60ebc76740a74/robots/state.js#L22) onde são exportadasa s funções uma por uma.

**Comment by leodutra** [comment]
Não é assim que funciona.

O module.exports é um objeto. A ele pode ser atribuída uma função (que no
JS também é um objeto), pode receber a atribuição de um novo objeto ou
apenas de propriedades.

O que está sendo usado no projeto são closures de funções (ou função
declarada no escopo de função). Isso é uma herança direto do C e, muito
raramente deve ser usado pois as funções internas tendem a perder diversas
otimizações de baixo nível, apesar de parecer um syntax sugar ou forma de
organizar a semântica do código.

Entretanto, têm seu uso, não no caso do video maker; mas em um caso em que
haja real necessidade de retornar uma função que compartilhe o os escopos
"de fora".

Um caso clássico e até adequado de uso é o da técnica funcional de
"currying".

No mais, tudo o que está em um .js, no Node.js, e não está sendo
referenciado pelo module.exports não será acessível, por vias normais, onde
quer que o módulo seja importado.  Por isso, podemos criar inúmeras
classes, funções e variáveis sem que eles extravasem para outros módulos.

Isso é uma herança também do C, onde os arquivos de módulos são chamados de
object files e o module.exports se dá pelo uso do modificador "extern".

Prefiram funções soltas no arquivo do módulo e utilizem classe (ou
prototipacao) para domain models (como um User em um MVC) ou objetos que
são criados centenas de vezes e precisam de alta performance (como um node
de uma linked list que você está implementado).

**Comment by leodutra** [comment]
Acredite, já fiz jogos em DHTML, lidei com IE5.5 e 6, criei minha própria
jQuery em 2007 (http://github.com/leodutra/leaf - © 2009), colaborei com
Highcharts, engines de jogos e o mais.

Hoje em dia temos apenas o V8 e alguns poucos desbravadores, mas quando o
JS era menos otimizado, tínhamos que tomar muito cuidado para não
atrapalhar a UX.

Claro que isso é um detalhe em um Ryzen 2700x, como o meu, mas a computação
sempre volta atrás e talvez lidando com um tessel.io ou johnny five estas
dicas reduzam centenas de ms de execução.

**Comment by danielschmitz** [comment]
Também não gosto de criar funções dentro de funções. 

Em todos os meus projetos JS eu crio um objeto e coloco as funcoes nele. Como se fosse uma classe

por exemplo:

```js
const pessoaService = {
  var1: 'valor',
  var2: 'valor',
  func1: () => {  ... }
  func2: () => { ... }
}
export default pessoaService
```

**Comment by leodutra** [comment]
Exato, ou no formato de module exports:
```js
const foo = 'valor'

module.exports = {
  foo,                  // referência direta de variável local
  var1: 'valor',
  var2: 'valor',
  func1: () => {  ... }
  func2: () => { ... }
}
```
ou o mais "sujo", apenas para entendimento:
```js
module.exports.foo = foo
module.exports.var1 = 'valor'
module.exports.var2 = 'valor'
module.exports.func1 =  () => {  ... }
module.exports.func2 = () => { ... }
```

**Comment by leodutra** [comment]
Exato, ou no formato de module exports:
```js
const foo = 'valor'

module.exports = {
  foo, // referência direta de variável local
  var1: 'valor',
  var2: 'valor',
  func1: () => {  ... }
  func2: () => { ... }
}
```
ou o mais "sujo", apenas para entendimento:
```js
const foo = 'valor'

module.exports.foo = foo
module.exports.var1 = 'valor'
module.exports.var2 = 'valor'
module.exports.func1 = () => {  ... }
module.exports.func2 = () => { ... }
```

**Comment by leodutra** [comment]
Fechando por inatividade.
Por favor reabra caso encontre algum erro + log do mesmo.
