### ISSUE TITLE
Compilar

### ISSUE THREAD

**Issue by feraujo** [filipedeschamps/video-maker#106]
Boa tarde, não sei programar nem compilar, gostaria que alguém compilasse o código para que possamos usar depois de pronto

**Comment by feraujo** [comment]
Posso contribuir com ideias para esse projeto, exemplo: incrementem o código para buscar textos somente em português, e configurar os locais de busca e etc

**Comment by danielschmitz** [comment]
Javascript é interpretado, ou seja, basta executar "node index.js"

Se você quer um ".exe", acompanhe o #107 talvez saia algo legal de lá

**Comment by feraujo** [comment]
Amigo só que eu não sei programar mas gostaria muito de usar os robôs para postar vídeo no YouTube. Pelo que eu entendi o código já está feito mas como eu uso esse código ? tem que transformar em um executável ou é só copiar e colar onde for usar? exemplo youtube.

________________________________
De: Daniel Schmitz <notifications@github.com>
Enviado: quarta-feira, 3 de abril de 2019 07:39
Para: filipedeschamps/video-maker
Cc: feraujo; Author
Assunto: Re: [filipedeschamps/video-maker] Compilar (#106)


Javascript é interpretado, ou seja, basta executar "node index.js"

Se você quer um ".exe", acompanhe o #107<https://github.com/filipedeschamps/video-maker/issues/107> talvez saia algo legal de lá

**Comment by hebertlima** [comment]
@feraujo da uma olha no readme do projeto, tem um passo a passo pra vc poder clonar o projeto e testar mesmo sem saber programar a única coisa que vai precisar fazer é criar as credenciais do projeto alem de precisar instalar na sua maquina o node.js, imagemagick e o after effects com o um plugin mas boa parte disso esta explicado no read do projeto
