### ISSUE TITLE
Erro ao trazer dados Wikipedia

### ISSUE THREAD

**Issue by bs2stk** [filipedeschamps/video-maker#108]
Boa noite!

Estou tendo um erro com relação a trazer os dados em strings do Wikipedia.

No exemplo "Jackson's" estou tendo como resultado "Jackson\\'s".

Alguém poderia me auxiliar? desde já, obrigado!

**Comment by danilosales** [comment]
essa barra é um escape da aspa, tente pegar esta mensagem e imprimir no console, é muito provável que ele imprima sem essa barra.

**Comment by bs2stk** [comment]
Beleza.
Obrigado!
