### ISSUE TITLE
Erro ao decodificar a array com a resposta do Watson

### ISSUE THREAD

**Issue by AndreGanzarolli** [filipedeschamps/video-maker#109]
Oi gente, primeiramente to gostando muito do canal e da comunidade. Meu primeiro contato com NodeJS. Sou iniciante em programação, ou seja, tenho só algumas noções. 

Meu problema é com o ultimo vídeo do text.js. 

mesmo colocando o 

  console.log(JSON.stringify(content, null, 4))

  } //Fim da Function Start

  start() 

A resposta do Watson fica assim: 

        'His music videos, including those for "Beat It", "Billie Jean", and "Thriller" from his 1982 album Thriller, are credited with breaking racial barriers and transforming the medium into an art form and promotional tool.',
       keywords: [Array],
       images: [] } ] }
MBP-de-Andre:video-maker andre$ 

Como eu resolvo esse [Array] ??

Muito obrigado.

**Comment by cabral-ricardo** [comment]
@AndreGanzarolli tenta colocar na linha: resolve(keywords) substituir por: resolve(keywords.join())

**Comment by AndreGanzarolli** [comment]
Deu certo @cabral-ricardo ! Muito obrigado pela ajuda!
