### ISSUE TITLE
Faltou dopamina...

### ISSUE THREAD

**Issue by diegodorgam** [filipedeschamps/video-maker#11]
Putz mano, mais um projeto abandonado...
desse jeito seu cérebro nunca vai confiar em você....

Manda o resto do código pra gente poder dar pitaco, de repente assim da uma estimulada na dopamina ;)

**Comment by ptcmariano** [comment]
Sem ansiedade @diegodorgam, recomendo enquanto aguarda os próximos passos do projeto ver o vídeo que o Filipe "3 dicas simples para tratamento de ansiedade". hehe

> https://www.youtube.com/watch?v=n9XX83Du8xo

Tem também outros muito massa tb:

> https://www.youtube.com/watch?v=nEEUjIjK-bE

> https://www.youtube.com/watch?v=Si5XRhO2e6E

**Comment by filipedeschamps** [comment]
ahhahaahha sensacional a resposta @ptcmariano não teria conseguido sugerir coisa melhor:) 

@diegodorgam não sei de onde você tirou a sensação de que o projeto abandonado, mas gostaria de esclarecer que não foi. Inclusive, fiquei ontem até quase 1h da madrugada e vou passar o restinho dessa semana editando o próximo vídeo que vai ser lançado na segunda-feira.

Vamo que vamo!

**Comment by Azorrague** [comment]
> ahhahaahha sensacional a resposta @ptcmariano não sugestionar conseguido sugerir coisa melhor :)
> 
> @diegodorgam não sei de onde você tirou uma sensação de que o projeto foi abandonado, mas é um esclarecimento que não foi feito. Inclusive, fiquei até quase 1h da madrugada e vou passar o resto da semana editando o próximo vídeo que vai ser lançado na segunda-feira.
> 
> Vamo que vamo!

Filipe, só uma coisa, muita gente que tá chegando não entende nada do mundo de programação então acho que pra estimular a galera seria interessante passar detalhes mais profundos do processo, programas usados, hardware necessário, leitura/video indicado, ect... Desta forma a galera que foi atraída pelo "Robô" entra mais no jogo da programação em si.
