### ISSUE TITLE
Erro com GraphicMagick no windows

### ISSUE THREAD

**Issue by diegohamaz** [filipedeschamps/video-maker#110]
Galera , 

ao cropar as imagens 

`  gm()
        .in(inputFile)
        .out('(')
          .out('-clone')
          .out('0')
          .out('-background', 'white')
          .out('-blur', '0x9')
          .out('-resize', `${width}x${height}^`)`

recebo o seguinte erro

 **UnhandledPromiseRejectionWarning: Error: Command failed: Parametro Invalido - /content**

instalei o imagemagick o graphicimagic e nada ! nao roda , alguem sabe como resolvo isso? no liinux ta funfando mas meu after effects esta no windows

**Comment by maycrodrigues** [comment]
Meu deu isso também! Não consegui resolver ainda. Se alguém tiver ideia. Valeu

**Comment by diegohamaz** [comment]
Pra resolver isso troquei o after pela biblioteca ffmpeg

**Comment by EmersonFurlan** [comment]
@diegohamaz é tranquilo de usar? pq já passei horas tentando resolver isso e até agora nada kkk

**Comment by maykbrito** [comment]
> Galera ,
> 
> ao cropar as imagens
> 
> ` gm() .in(inputFile) .out('(') .out('-clone') .out('0') .out('-background', 'white') .out('-blur', '0x9') .out('-resize',`${width}x${height}^`)`
> 
> recebo o seguinte erro
> 
> **UnhandledPromiseRejectionWarning: Error: Command failed: Parametro Invalido - /content**
> 
> instalei o imagemagick o graphicimagic e nada ! nao roda , alguem sabe como resolvo isso? no liinux ta funfando mas meu after effects esta no windows

manin eu tava tem o mesmo erro.. pra resolver fiz assim.


baixar o ImageMagick-7.0.8-39-Q16-x64-dll.exe no site https://imagemagick.org/script/download.php#windows


Nos passos da instalação, marcar a opção
Install legacy utilities (e.g. convert)
(esse é o pulo do gato pra versão 7)

abra o cmd (se estiver aberto, fecha e abre novamente)
digite: 
magick identify --version

Se aparecer a versão 7, então deu certo =)
obs.: caso esteja usando o terminal via vs code, reinicie o vs code (eu tinha esquecido de reiniciar o meu)

Aí é só rodar o robo e essa parte da conversão de imagens vai estar show! =)

**Comment by cabral-ricardo** [comment]
#126

**Comment by Preddo** [comment]
Outra solução, além dessa oferecida pelo @maykbrito, é ir em node_modules/gm/index.js e alterar a propriedade "_subCommand" para "magick" (por padrão é "convert") no construto gm .

![image](https://user-images.githubusercontent.com/45718525/56869134-e35bbe80-69d2-11e9-98ed-bdc3c62d6def.png)

**Comment by Abraaozuza** [comment]
pra mim não está funcionando. Instalei o imagick também, mas a mensagem de erro que eu vejo é a seguinte:

Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
Type a Wikipedia search term: Jesus Christ

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
(node:5012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'm
ap' of undefined
    at fetchGoogleAndReturnImagesLinks (C:\Users\Abraao\Videos\VIDEO MAKER\video
-maker\robots\image.js:32:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5012) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>

Alguém sabe como resolver?

**Comment by diegohamaz** [comment]
> pra mim não está funcionando. Instalei o imagick também, mas a mensagem de erro que eu vejo é a seguinte:
> 
> Microsoft Windows [versão 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.
> 
> C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
> Type a Wikipedia search term: Jesus Christ
> 
> [1] Who is
> [2] What is
> [3] The history of
> [0] CANCEL
> 
> Choose one option [1, 2, 3, 0]: 1
> (node:5012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'm
> ap' of undefined
> at fetchGoogleAndReturnImagesLinks (C:\Users\Abraao\Videos\VIDEO MAKER\video
> -maker\robots\image.js:32:43)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:5012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> error originated either by throwing inside of an async function without a catch
> block, or by rejecting a promise which was not handled with .catch(). (rejection
> id: 1)
> (node:5012) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
> cated. In the future, promise rejections that are not handled will terminate the
> Node.js process with a non-zero exit code.
> 
> C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
> C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
> 
> Alguém sabe como resolver?

sua autenticação com o google search está incorreta

**Comment by Abraaozuza** [comment]
Sendo assim, o melhor é refazer do zero todos os passos da autenticação?

**Comment by Abraaozuza** [comment]
> > pra mim não está funcionando. Instalei o imagick também, mas a mensagem de erro que eu vejo é a seguinte:
> > Microsoft Windows [versão 6.1.7601]
> > Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.
> > C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
> > Type a Wikipedia search term: Jesus Christ
> > [1] Who is
> > [2] What is
> > [3] The history of
> > [0] CANCEL
> > Choose one option [1, 2, 3, 0]: 1
> > (node:5012) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'm
> > ap' of undefined
> > at fetchGoogleAndReturnImagesLinks (C:\Users\Abraao\Videos\VIDEO MAKER\video
> > -maker\robots\image.js:32:43)
> > at process._tickCallback (internal/process/next_tick.js:68:7)
> > (node:5012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
> > error originated either by throwing inside of an async function without a catch
> > block, or by rejecting a promise which was not handled with .catch(). (rejection
> > id: 1)
> > (node:5012) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
> > cated. In the future, promise rejections that are not handled will terminate the
> > Node.js process with a non-zero exit code.
> > C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
> > C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
> > Alguém sabe como resolver?
> 
> sua autenticação com o google search está incorreta

Sendo assim, o ideal é refazer do zero os passos para a autenticação do google search?
Pergunto isso porque atualizei tudo, editei o arquivo google.search.json e ainda ta dando erro, mas agora assim
Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
Type a Wikipedia search term: Jesus Christ

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
(node:3652) UnhandledPromiseRejectionWarning: Error: null
    at Gaxios.<anonymous> (C:\Users\Abraao\Videos\VIDEO MAKER\video-maker\node_m
odules\gaxios\build\src\gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Abraao\Videos\VIDEO MAKER\video-maker\node_modules\ga
xios\build\src\gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3652) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:3652) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>

**Comment by educartj** [comment]
![erro](https://user-images.githubusercontent.com/897260/57181277-0b7e6e00-6e68-11e9-80d3-94380ebeb463.png)

exatamente o que @maykbrito e @cabral-ricardo falaram.

![solução](https://user-images.githubusercontent.com/897260/57181279-0b7e6e00-6e68-11e9-9af9-b2b60fb02ffe.png)

**Comment by Laferu** [comment]
> > Galera ,
> > ao cropar as imagens
> > ` gm() .in(inputFile) .out('(') .out('-clone') .out('0') .out('-background', 'white') .out('-blur', '0x9') .out('-resize',`${width}x${height}^`)`
> > recebo o seguinte erro
> > **UnhandledPromiseRejectionWarning: Error: Command failed: Parametro Invalido - /content**
> > instalei o imagemagick o graphicimagic e nada ! nao roda , alguem sabe como resolvo isso? no liinux ta funfando mas meu after effects esta no windows
> 
> manin eu tava tem o mesmo erro.. pra resolver fiz assim.
> 
> baixar o ImageMagick-7.0.8-39-Q16-x64-dll.exe no site https://imagemagick.org/script/download.php#windows
> 
> Nos passos da instalação, marcar a opção
> Install legacy utilities (e.g. convert)
> (esse é o pulo do gato pra versão 7)
> 
> abra o cmd (se estiver aberto, fecha e abre novamente)
> digite:
> magick identify --version
> 
> Se aparecer a versão 7, então deu certo =)
> obs.: caso esteja usando o terminal via vs code, reinicie o vs code (eu tinha esquecido de reiniciar o meu)
> 
> Aí é só rodar o robo e essa parte da conversão de imagens vai estar show! =)

Nossa eu fiquei sem acompanhar 3 vídeos por causa desse erro, achando que era o meu código e tentava arrumar. Era só coisa do Magick mesmo kkkkkkk valeu por postar a solução.

**Comment by guipassos** [comment]
Complementando sobre esse problema, eu segui os passos relatados pela galera e deu certo, só cabe ressaltar que precisei fechar o terminal e reabrir (no meu caso fechei todo o vscode) e com isso passou a considerar a nova instalação.
