### ISSUE TITLE
Criar um Robo que verifica os requisitos para o uso.

### ISSUE THREAD

**Issue by Rodrigo54** [filipedeschamps/video-maker#111]
A ideia aqui seria criar um robo que cheque se as dependências do projeto estão disponíveis na maquina. Fariamos algo semelhante ao que o ionic cli faz. No momento que se compila um app ele verifica se o android studio e o sdk do java estão instalados na maquina. Caso alguém esteja faltando é apresentado instruções de como colocar o que falta.

**Comment by nandumoura** [comment]
o npm e o yarn já não faz isso?

**Comment by leodutra** [comment]
Acho que ele esta pensando no After Effects, por exemplo.

**Comment by Rodrigo54** [comment]
@leodutra foi pensando no After Effects mesmo que eu deu essa sugestão.

**Comment by eliaskill** [comment]
projeto legal :) evita de tomar um erro quando tiver quase com o  ouro na mão!

**Comment by danielschmitz** [comment]
Gostei da ideia, vale lembrar que temos que testar as APIs tb, e suas respectivas chaves. 
referenciando no #77 para que possamos discutir um dia
