### ISSUE TITLE
Duvida Keywords?!

### ISSUE THREAD

**Issue by bvrpythondev** [filipedeschamps/video-maker#113]
Bom Dia
@filipedeschamps 
@danielschmitz 
Desculpem a minha ignorancia mas n entendi como Deschamps conseguiu eliminar a possibilidade da query ou seja searchterm + keyword[0] de nao repetirem uma a outra ou coisas parecidas.

Se alguem puder ajudar adoraria muito.

**Comment by wsj1983** [comment]
Na verdade ele não eliminou essa possibilidade.
Com o código como está agora, se você fizer um teste aí jogando por exemplo "Harry Potter" como searchTerm, você vai ver que as imagens das duas primeiras sentenças vão tá com googleSearchQuery: "harry potter harry potter".

Também queria corrigir isso. A solução parece simples, mas não sei como escreve o código.
A lógica acho que seria simples:

No images.js, dentro da função fetchImagesOfAllSentences, precisa criar um loop para verificar se o conteúdo de content.searchTerm é igual ao de sentence.keywords[0], e se for igual aí é só incrementar 1 no índex do sentence.keywords.

Até tentei aqui fazer um código, mas como não sei a linguagem obviamente não deu certo hehe (última vez que programei foi uns 14 anos atrás), mas a solução parece ser simples, né.

Escrevi isso aqui, se alguém que manje de JS puder corrigir:
[sintaxe totalmente errada, tá... só fiz me baseando no que vi no restante do código nesse projeto]
```
      for (let sentence.keywords = 0; sentence.keywords = content.searchTerm; sentence.key++) {
      }
```

**Comment by bvrpythondev** [comment]
Ss existe uma repetição do searchTerm.A lógica é essa mesma obrigado 😀👍.Vou ver se consigo criar algo baseado no que vc fez se funcionar eu posto aqui.

**Comment by bvrpythondev** [comment]
Ok achei uma solução em python: N fiz uma função porque isso é um teste

`counter = 0
while counter < 7:
    textnlu = content['sentences'][counter123]['text']

    resultado = returnWatson(textnlu)
    for item1 in resultado:
        for word in item1.split(" "):
            for word2 in term.split(" "):
                if word == word2:
                    print("True",word,word2)
                    resultado.remove(item1)


    content['sentences'][counter123]['keyword'] = resultado

    if counter == 7:
        break
    else:
        counter += 1
        continue`

**Comment by bvrpythondev** [comment]
Serio é muito estranho o insert de codigo em python.Mas basicamente o code itera sobre as palavras tanto das keywords e do searchTerm e sempre tenta comparar quando encontra ele remove o da lista

**Comment by leodutra** [comment]
Isso não é necessário, até onde entendi.
As imagens são para cada sentença, então, se duas frases têm relevância em
keyword repetida, mesmo assim a keyword é importante para a ilustração da
frase.

Quanto à repetição de imagem, o algoritmo usa um sistema simples ainda, que
apenas evita duplicação por fonte de download ao invés de comparar se as
imagens possuem byte arrays parecidos.

Pode ser que futuramente isso tudo siga uma regra mais apurada, mas ainda
há muito a melhorar.

Se quiserem tentar explorar mais este detalhe, fico feliz em ajudar.

**Comment by wsj1983** [comment]
A questão não é essa, @leodutra .
É sobre fazer a busca no Google Images por um "tema" + "keyword" iguais.

Se os dois são iguais, a nossa keyword não está trazendo uma informação importante para esta busca da imagem.

É como no exemplo que eu dei, veja qual foi o googleSearchQuery:
<img src="https://3.bp.blogspot.com/-rWu611T3rjE/XK1b8SxOsXI/AAAAAAABO-I/PsCFzMaFdC0x-487ggacoHuwgh9k_8rtgCLcBGAs/s1600/keywords.png">

Isso pode fazer uma diferença qualitativa pra encontrar uma imagem que tenha mais a ver com o contexto da sentença que ela vai ilustrar.

**Comment by leodutra** [comment]
Havia entendido de outra perspectiva, desculpem.
 
Condições indevidas como esta tem muitas, aliás até na obtenção de trends e de conteúdo propriamente dito. Fiz inúmeros merges e, enquanto isso, pude notar diversos casos similares.

Vamos ter que realmente dar uns tapas nisso aí.
Vou criar umas TODOs aqui e ver o que consigo adiantar.

**Comment by leodutra** [comment]
Quanto a evitar que keywords principais sejam repetidas entre sentenças, enquanto testava vi que dependendo do termo, a busca de imagem pode não ter lá um bom retorno de conteúdo.

Uma keyword repetida parece ter uma tendência com um conteúdo não muito rico, e ajustes como este pode jogar o critério numa zona pobre.

Tá aí um fine tuning que vai ser legal de pensar.

**Comment by bvrpythondev** [comment]
Extamente quando se repetem a keyword e o term as imagens retornadas se tornam piores.O codigo que coloquei ali em cima ele resolve 80% dos casos mais n todos pois a vezes que no ingles existe Jackson’s o que o código não indentifica.
Realmente pensar nisso seria muito bom e vamos continuar tentando
