### ISSUE TITLE
Erro após implementação do robo de imagem

### ISSUE THREAD

**Issue by diovanii** [filipedeschamps/video-maker#114]
Não sei se posso perguntar isso aqui mas após implementar o robo de texto no meu código não tenho mais nenhum log no console simplesmente não aparece nada e nem salva as imagens.

**Comment by Ruttmann** [comment]
Primeira pergunta: você teve problemas após fazer o robô de imagens ou de texto? Você diz uma coisa no título e outra na descrição.

Segundo: Seu repositório é [esse](https://github.com/diovanii/fazedor-de-videos)? Dei uma olhada nele rapidinho mas não consegui encontrar algum problema. Te sugiro a abrir o _index.js_ e ir testando robô por robô. Primeiro testa o de input e vê se tudo funciona certinho. Se funcionar adiciona o próximo e vai testando. Em algum momento você vai encontrar algum problema.

**Comment by diovanii** [comment]
Na verdade é o robo de imagem mesmo eu que escrevi errado. E [esse](https://github.com/diovanii/fazedor-de-videos) é sim meu repositório
