### ISSUE TITLE
erro com content.sentences i not iterable

### ISSUE THREAD

**Issue by Patricia7sp** [filipedeschamps/video-maker#120]
Boa noite!
Pessoal como estao?  

Eu estou com  um problema com content.setence, nao sei alguem se deparou com este mesmo erro, estou enviando o erro abaixo. 

Eu estou criando do zero, mas olhei no codigo do felipe e nao consegui ver nada que esteja diferente do meu. Vou  mandar meu image.js

para que possam ver tambem.

(node:11419) UnhandledPromiseRejectionWarning: TypeError: content.sentences is not iterable
    at fetchImagesOfAllSentences (/home/patricia/rob-s-maker/robots/image.js:17:36)
    at Object.robot [as image] (/home/patricia/rob-s-maker/robots/image.js:11:11)
    at start (/home/patricia/rob-s-maker/index.js:11:16)
    at Object.<anonymous> (/home/patricia/rob-s-maker/index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
(node:11419) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11419) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
patricia@patricia-UX330UAK:~/rob-s-maker$ node index.js
(node:11982) UnhandledPromiseRejectionWarning: TypeError: content.sentences is not iterable
    at fetchImagesOfAllSentences (/home/patricia/rob-s-maker/robots/image.js:17:36)
    at Object.robot [as image] (/home/patricia/rob-s-maker/robots/image.js:11:11)
    at start (/home/patricia/rob-s-maker/index.js:11:16)
    at Object.<anonymous> (/home/patricia/rob-s-maker/index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
(node:11982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
patricia@patricia-UX330UAK:~/rob-s-maker$ ^C

**Comment by Patricia7sp** [comment]
`const imageDownloader = require('image-downloader')
const google = require('googleapis').google
const customSearch = google.customsearch('v1')
const state = require('./state.js')

const googleSearchCredentials = require('../credentials/google-search.json')

async function robot(){
    const content = state.load()
    
    await fetchImagesOfAllSentences(content)
    await downloadAllImages(content)

   state.save(content)

   async function fetchImagesOfAllSentences(content) {
    for (const sentence of content.sentences) {
      const query = `${content.searchTerm} ${sentence.keywords[0]}`
      sentence.images = await fetchGoogleAndReturnImagesLinks(query)

      sentence.googleSearchQuery = query
    }
  }

 async function fetchGoogleAndReturnImagesLinks(query) {
    const response  = await customSearch.cse.list({
        auth: googleSearchCredentials.apiKey,
        cx: googleSearchCredentials.searchEngineId,
        q: query,
        searchType: 'image',
        imgSize: 'huge', // imagens em alta resolucao.
        num: 3
   })  

   const imageUrl = response.data.items.map((item) => {
       return  item.link // extrair de cada item so o link.
   })
   return imagesUrl

 }
 async function downloadAllImages(content) {
    content.downloadedImages = []

    for (let sentenceIndex = 0; sentenceIndex < content.sentences.length; sentenceIndex++) {
        const images = content.sentences[sentenceIndex].images

        for (let imageIndex = 0; imageIndex < images.length; imageIndex++) {
            const imageUrl = images[imageIndex]

              try {
          if (content.downloadedImages.includes(imageUrl)) {
            throw new Error('Imagem já foi baixada')
          }
          await downloadAndSave(imageUrl, `${sentenceIndex}-original.png`)
          content.downloadedImages.push(imageUrl)
          console.log(`> [${sentenceIndex}][${imageIndex}] Baixou imagem com sucesso: ${imageUrl}`)
          break
        } catch(error) {
            console.log(`> [${sentenceIndex}][${imageIndex}] Erro ao baixar (${imageUrl}): ${error}`)
          }
        }
      }
    }
  
    async function downloadAndSave(url, fileName) {
        return imageDownloader.image({
          url, url,
          url, url,
          dest: `./content/${fileName}`
       })
   }  
}


module.exports = robot
`

**Comment by leodutra** [comment]
Tinha um erro deste ocorrendo quando a Wikipedia não retornava resultado. 
A melhor forma de descobrir, é usar um debugger.
https://code.visualstudio.com/docs/editor/debugging

**Comment by Patricia7sp** [comment]
[https://github.com/Patricia7sp/rob-s-maker/blob/master/robots/image.js](url)

**Comment by Patricia7sp** [comment]
@leodutra ola, tudo bem?  Muito obrigada pelo atencao.

**Comment by danielschmitz** [comment]
Olá @Patricia7sp 

na linha 17 do seu image.js tem 

```js
 for (const sentence of content.sentences) 
```

eu faria um console.log desse `content.sentences` e verificaria o que tem lá, e então depois disso eu verificaria como o `content.sentences` é preenchido.

Que bom que está criando  o projeto do zero e escrevendo, é assim que se aprende

**Comment by Patricia7sp** [comment]
@leodutra Eu achei complexo para mim no momento para tentar resolver desta forma,  deu um no na minha cabeca.  nao consegui resolver

**Comment by Patricia7sp** [comment]
@danielschmitz  desculpe minha ignorancia,  como eu faria esse console.log? logo abaixo de for (const sentence of content.sentences)   assim?

` for (const sentence of content.sentences) {
 console.log(content.sentences`
}

**Comment by Patricia7sp** [comment]
eu ainda sou um pouco leiga na programacao, nestas questoes de codigos

**Comment by Patricia7sp** [comment]
@danielschmitz  queria entender pq esta dando este erro,  pq estou fazendo tudo certinho, seguindo os passo a passo do felipe

**Comment by danielschmitz** [comment]
seria antes do for.  Já que ele está reclamando do `content.sentences`, seria interessante ver o que tem nele.

**Comment by Patricia7sp** [comment]
node index.js
### undefined
(node:5022) UnhandledPromiseRejectionWarning: TypeError: content.sentences is not iterable
    at fetchImagesOfAllSentences (/home/patricia/rob-s-maker/robots/image.js:18:36)
    at Object.robot [as image] (/home/patricia/rob-s-maker/robots/image.js:11:11)
    at start (/home/patricia/rob-s-maker/index.js:11:16)
    at Object.<anonymous> (/home/patricia/rob-s-maker/index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
(node:5022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Patricia7sp** [comment]
esta indefinido, vazio esta contente.sentence

**Comment by MatheusDeAquino** [comment]
To com o mesmo problema.

**Comment by MatheusDeAquino** [comment]
> seria antes do for. Já que ele está reclamando do `content.sentences`, seria interessante ver o que tem nele.

Eu fiz isso no meu e mostrou "undifined".
Como resolver?

**Comment by MatheusDeAquino** [comment]
> esta indefinido, vazio esta contente.sentence

**Copia e cola aqui o teu "async function start()**
