### ISSUE TITLE
Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT

### ISSUE THREAD

**Issue by agenciatsantosi** [filipedeschamps/video-maker#121]
![Screenshot_1](https://user-images.githubusercontent.com/47331847/56083259-dea2e200-5df8-11e9-9948-0e72e443f120.png)

**Comment by rrfaria** [comment]
talvez isso ajude

na função renderVideoWithAfterEffects

```js
  async function renderVideoWithAfterEffects() {
    return new Promise((resolve, reject) => {
      const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects CS6\\Support Files\\aerender.exe'
      const templateFilePath = `${rootPath}/templates/1/template.aep`
      const destinationFilePath = `${rootPath}/content/output.mov`

      console.log('> Starting After Effects')

      const aerender = spawn(aerenderFilePath, [
        '-comp', 'main',
        '-project', templateFilePath,
        '-output', destinationFilePath
      ], 
      {
        env: {
            PATH: path.dirname(aerenderFilePath)
        }
      }
      )

      aerender.stdout.on('data', (data) => {
        process.stdout.write(data)
      })

      aerender.on('close', () => {
        console.log('> After Effects closed')
        resolve()
      })
    })
  }
```

No meu deu problema com template porque a versão é a cs6 então nao rolou mas pra vc deve funcionar.

**Comment by rrfaria** [comment]
Alguem podia por favor converter o template para dar suporte para versoes mais antigas do after effects?

**Comment by DENISBruno** [comment]
Rodei aqui e consegui gerar o video, mas ele fica com mais de 700MB mesmo? e .MOB?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
