### ISSUE TITLE
Error: Insufficient credentials provided in constructor argument

### ISSUE THREAD

**Issue by juriswikibr** [filipedeschamps/video-maker#122]
Olá ! Primeiramente, parabéns a todos pelo brilhantismo deste projeto. Acompanhando os vídeos, tudo ia bem até a **instalação** do _watson-cloud-developer._ Assim, ainda que leigo em programação, espero contribuir com este projeto apontando este erro - que pode também vir a ocorrer para outras pessoas - e ao mesmo tempo solicitar o auxílio de vocês para solucioná-lo.

![77](https://user-images.githubusercontent.com/30419643/56082086-e8254d80-5dea-11e9-8207-9fda6318b552.PNG)
![78](https://user-images.githubusercontent.com/30419643/56082089-ecea0180-5dea-11e9-9f27-ca957ae7eb32.PNG)

Percebendo o **deprecated**, constatei que o package watson-developer-cloud agora está em **ibm-watson**

![git01](https://user-images.githubusercontent.com/30419643/56082173-e6a85500-5deb-11e9-90d5-e32a270ae818.PNG)
![git02](https://user-images.githubusercontent.com/30419643/56082207-47d02880-5dec-11e9-9714-ad2adf0446b8.PNG)

Procedi para a alteração do **text.js** 

![git03](https://user-images.githubusercontent.com/30419643/56082217-764e0380-5dec-11e9-81a5-fbbbd4ec9677.PNG)

Infelizmente, o erro (apontado no título desta issue) persiste:

![git04](https://user-images.githubusercontent.com/30419643/56082240-bb723580-5dec-11e9-8a66-d50843ab0f48.PNG)

Alguém tem ideia do que pode estar acontecendo?

Obrigado antecipadamente,

Edpo

**Comment by JhonatanVM** [comment]
Esse erro aconteceu comigo também, eu percebi que no meu text.js quando eu fiz o require para pegar a apikey do watson eu escrevi ela de forma errada, eu tinha escrito ".apiKey" mas o correto seria ".apikey" com todas as letras minúsculas, eu acredito que seja o mesmo caso.

**Comment by juriswikibr** [comment]
Precisamente @JhonatanVM. Na mosca! Muitíssimo obrigado e Deus lhe abençoe. Confira:

![DEBUGGED 0](https://user-images.githubusercontent.com/30419643/56091833-4b19f180-5e8a-11e9-8df6-55b5239e58c0.PNG)

Ainda no nlu.analyze:

![DEBUGGED 1](https://user-images.githubusercontent.com/30419643/56091818-07bf8300-5e8a-11e9-8828-9d6aa34c3172.PNG)

**Comment by juriswikibr** [comment]
Sobre aquela "1" vulnerabilidade no package **ibm-watson**, devemos nos preocupar?

**Comment by JhonatanVM** [comment]
Eu não tenho certeza mas eu acho que não precisa se preocupar com isso agora, até porque mesmo com  o npm audit fix não deu pra arrumar e parece que essa vulnerabilidade não esta gerando nenhum outro problema.

**Comment by leodutra** [comment]
Se tratando de uma app CLI, sem problema a vulnerabilidade. Elas afetam mais libs e serviços públicos.

**Comment by juriswikibr** [comment]
Na conclusão do robô de texto, eu devo ter perdido alguma rotina quando da transferência para o **/robots/input.js**, porque o **content.json** está registrado mas não está tratado:

`{"maximumSentences":7,"searchTerm":"Ulpianus","prefix":0,"sourceContentOriginal":"Ulpian (; Latin: Gnaeus Domitius Annius Ulpianus; c. 170 – 223) was a prominent Roman jurist  of Tyrian ancestry.  He was considered one of the great legal authorities of his time and was one of the five jurists upon whom decisions were to be based according to the Law of Citations of Valentinian III.\n\n\n== Biography ==\nThe exact time and place of his birth are unknown, but the period of his literary activity was between AD 211 and 222. He made his first appearance in public life as assessor in the auditorium of Papinian and member of the council of Septimius Severus; under Caracalla he was master of the requests (magister libellorum). Elagabalus (also known as Heliogabalus) banished him from Rome, but on the accession of Severus Alexander (222) he was reinstated, and finally became the emperor's chief adviser and Praefectus Praetorio.\nDuring the Severan dynasty, the position of Praetorian prefect in Italy came increasingly to resemble a general administrative post, and there was a tendency to appoint jurists such as Aemilius Papinianus, who occupied the post from 203 until his elimination and execution at the ascent of Caracalla. Under Severus Alexander the Praetorian prefecture was held by Ulpian until his assassination by the Guard in the presence of the Emperor himself.\nHis curtailment of the privileges granted to the Praetorian Guard by Elagabalus provoked their enmity, and he narrowly escaped their vengeance; ultimately he was murdered in the palace by the Guard, in the course of a riot between the soldiers and the mob.\n\n\n== Works ==\nHis works include Ad Sabinum, a commentary on the jus civile, in over 50 books; Ad edictum, a commentary on the Edict, in 83 books; collections of opinions, responses and disputations; books of rules and institutions; treatises on the functions of the different magistrates — one of them, the De officio proconsulis libri x., being a comprehensive exposition of the criminal law; monographs on various statutes, on testamentary trusts, and a variety of other works. His writings altogether have supplied to Justinian's Digest about a third of its contents, and his commentary on the Edict alone about a fifth. As an author, he is characterized by doctrinal exposition of a high order, judiciousness of criticism, and lucidity of arrangement, style and language. He is also credited with the first life table ever.Domitii Ulpiani fragmenta, consisting of 29 titles, were first edited by Tilius (Paris, 1549). Other editions are by Hugo (Berlin, 1834), Booking (Bonn, 1836), containing fragments of the first book of the Institutiones discovered by Endlicher at Vienna in 1835, and in Girard's Textes de droit romain (Paris, 1890).\n\n\n== Legacy ==\nIt had been assumed for a long time that Ulpian of Tyre was a model for Athenaeus' Ulpian in The Deipnosophists — or The Banquet of the Learned.  Athenaeus makes 'Ulpian' out to be a grammarian and philologist, characterised by his customary interjections: \"Where does this word occur in writing?\".  He is represented as a symposiarch and he occupies a couch alone; his death is passed over in silence in Book XV 686 c.\nScholars today agree that Athenaeus's Ulpian is not the historical Ulpian, but possibly his father.\nThe date of the real Ulpian's death in 223 AD has been wrongly used to estimate the date of completion of The Deipnosophists.\nIn the study of law, he is mostly remembered for the phrase \"Juris praecepta sunt haec: honeste vivere, alterum non laedere, suum cuique tribuere (The basic principles of law are: to live honorably, not to harm any other person, to render each his own)\".\n\n\n== See also ==\nPraetorian prefect\nPandects\nAemilius Papinianus\nJulius Paulus Prudentissimus\n\n\n== Notes ==\n\n\n== References ==\nTony Honoré, Ulpian: Pioneer of Human Rights, Oxford University Press, 2002.\n\n\n== External links ==\nLedlie, James Crawford (1913). \"ULPIAN\".  In Macdonell, John; Manson,  Edward William Donoghue. Great Jurists of the World. London: John Murray. pp. 32–44. Retrieved 9 March 2019  – via Internet Archive.\nFrier, B (1982). \"Roman Life Expectancy: Ulpian's Evidence\". Harvard Studies in Classical Philology. United States. 86: 213–51. doi:10.2307/311195. ISSN 0073-0688. JSTOR 311195. PMID 16437859.\nHassl, Andreas R (2008). \"The Significance of Malaria in the Western Roman Empire: A text passage in the Digesta\". Wien. Klin. Wochenschr. Austria. 120 (19-20 Suppl 4): 11–14. doi:10.1007/s00508-008-1033-2. ISSN 0043-5325. PMID 19066765.","sourceContentSanitized":"Ulpian was a prominent Roman jurist of Tyrian ancestry. He was considered one of the great legal authorities of his time and was one of the five jurists upon whom decisions were to be based according to the Law of Citations of Valentinian III.The exact time and place of his birth are unknown, but the period of his literary activity was between AD 211 and 222. He made his first appearance in public life as assessor in the auditorium of Papinian and member of the council of Septimius Severus; under Caracalla he was master of the requests . Elagabalus banished him from Rome, but on the accession of Severus Alexander he was reinstated, and finally became the emperor's chief adviser and Praefectus Praetorio.During the Severan dynasty, the position of Praetorian prefect in Italy came increasingly to resemble a general administrative post, and there was a tendency to appoint jurists such as Aemilius Papinianus, who occupied the post from 203 until his elimination and execution at the ascent of Caracalla. Under Severus Alexander the Praetorian prefecture was held by Ulpian until his assassination by the Guard in the presence of the Emperor himself.His curtailment of the privileges granted to the Praetorian Guard by Elagabalus provoked their enmity, and he narrowly escaped their vengeance; ultimately he was murdered in the palace by the Guard, in the course of a riot between the soldiers and the mob.His works include Ad Sabinum, a commentary on the jus civile, in over 50 books; Ad edictum, a commentary on the Edict, in 83 books; collections of opinions, responses and disputations; books of rules and institutions; treatises on the functions of the different magistrates — one of them, the De officio proconsulis libri x., being a comprehensive exposition of the criminal law; monographs on various statutes, on testamentary trusts, and a variety of other works. His writings altogether have supplied to Justinian's Digest about a third of its contents, and his commentary on the Edict alone about a fifth. As an author, he is characterized by doctrinal exposition of a high order, judiciousness of criticism, and lucidity of arrangement, style and language. He is also credited with the first life table ever.Domitii Ulpiani fragmenta, consisting of 29 titles, were first edited by Tilius . Other editions are by Hugo , Booking , containing fragments of the first book of the Institutiones discovered by Endlicher at Vienna in 1835, and in Girard's Textes de droit romain .It had been assumed for a long time that Ulpian of Tyre was a model for Athenaeus' Ulpian in The Deipnosophists — or The Banquet of the Learned. Athenaeus makes 'Ulpian' out to be a grammarian and philologist, characterised by his customary interjections: \"Where does this word occur in writing?\". He is represented as a symposiarch and he occupies a couch alone; his death is passed over in silence in Book XV 686 c.Scholars today agree that Athenaeus's Ulpian is not the historical Ulpian, but possibly his father.The date of the real Ulpian's death in 223 AD has been wrongly used to estimate the date of completion of The Deipnosophists.In the study of law, he is mostly remembered for the phrase \"Juris praecepta sunt haec: honeste vivere, alterum non laedere, suum cuique tribuere \".Praetorian prefectPandectsAemilius PapinianusJulius Paulus PrudentissimusTony Honoré, Ulpian: Pioneer of Human Rights, Oxford University Press, 2002.Ledlie, James Crawford . \"ULPIAN\". In Macdonell, John; Manson, Edward William Donoghue. Great Jurists of the World. London: John Murray. pp. 32–44. Retrieved 9 March 2019 – via Internet Archive.Frier, B . \"Roman Life Expectancy: Ulpian's Evidence\". Harvard Studies in Classical Philology. United States. 86: 213–51. doi:10.2307/311195. ISSN 0073-0688. JSTOR 311195. PMID 16437859.Hassl, Andreas R . \"The Significance of Malaria in the Western Roman Empire: A text passage in the Digesta\". Wien. Klin. Wochenschr. Austria. 120 : 11–14. doi:10.1007/s00508-008-1033-2. ISSN 0043-5325. PMID 19066765.","sentences":[{"text":"Ulpian was a prominent Roman jurist of Tyrian ancestry.","keywords":["prominent Roman jurist of Tyrian ancestry","Ulpian"],"images":[]},{"text":"He was considered one of the great legal authorities of his time and was one of the five jurists upon whom decisions were to be based according to the Law of Citations of Valentinian III","keywords":["great legal authorities of his time","jurists","decisions","Law of Citations of Valentinian III"],"images":[]},{"text":"The exact time and place of his birth are unknown, but the period of his literary activity was between AD 211 and 222.","keywords":["exact time","place of his birth","AD","period of his literary activity"],"images":[]},{"text":"He made his first appearance in public life as assessor in the auditorium of Papinian and member of the council of Septimius Severus; under Caracalla he was master of the requests .","keywords":["public life","first appearance","member of the council of Septimius Severus","auditorium of Papinian","assessor","Caracalla","master of the requests"],"images":[]},{"text":"Elagabalus banished him from Rome, but on the accession of Severus Alexander he was reinstated, and finally became the emperor's chief adviser and Praefectus Praetorio","keywords":["accession of Severus Alexander","Elagabalus","Rome","emperor's chief adviser","Praefectus Praetorio"],"images":[]},{"text":"During the Severan dynasty, the position of Praetorian prefect in Italy came increasingly to resemble a general administrative post, and there was a tendency to appoint jurists such as Aemilius Papinianus, who occupied the post from 203 until his elimination and execution at the ascent of Caracalla.","keywords":["Severan dynasty","position of Praetorian prefect","general administrative post","Italy","tendency","jurists","Aemilius Papinianus","post","elimination","execution","ascent of Caracalla"],"images":[]},{"text":"Under Severus Alexander the Praetorian prefecture was held by Ulpian until his assassination by the Guard in the presence of the Emperor himself","keywords":["Severus Alexander","Praetorian prefecture","assassination","Guard","presence of the Emperor","Ulpian"],"images":[]}]}`
