### ISSUE TITLE
Error pathspac

### ISSUE THREAD

**Issue by gabrielguarido** [filipedeschamps/video-maker#123]
![error](https://user-images.githubusercontent.com/47127807/56095276-5e8c8300-5eb1-11e9-904b-23a8f37a9147.png)
 
Alguem pode me dar uma maozinha aqui, por favor? Sou iniciante em programação e estou tentando acompanhar esse projeto dos BOTs, estou na parte de dar os commits no terminal, porém quando eu digito  o ( git commit -m 'feat: add package.json' ) ele me retorna 2 erros:
error: pathspec 'add' did not match any file(s) known to git.
error: pathspec 'package.json'' did not match any file(s) known to git.

**Comment by danielschmitz** [comment]
Tenta trocar o ' por "

**Comment by gabrielguarido** [comment]
Cara, muito obrigado... era so isso mesmo, valeu
