### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: Parâmetro Inválido - /content

### ISSUE THREAD

**Issue by JoaoPedroCJ** [filipedeschamps/video-maker#126]
```
(node:18780) UnhandledPromiseRejectionWarning: Error: Command failed: Parâmetro Inválido - /content

    at ChildProcess.onExit (S:\node\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:193:13)
    at ChildProcess.cp.emit (S:\node\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
(node:18780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
quando eu executo o node estou tendo esse erro como retorno e não estou sabendo o que fazer

Node v11.14.0
NPM v6.7.0

```js
async function convertAllImages(content){
    for (let sentenceIndex = 0; sentenceIndex < content.sentences.length; sentenceIndex++) {
      await convertImage(sentenceIndex)
    }
  }

  async function convertImage(sentenceIndex) {
    return new Promise((resolve, reject) => {
      const inputFile = `./content/${sentenceIndex}-original.png[0]`
      const outputFile = `./content/${sentenceIndex}-converted.png`
      const width = 1920
      const height = 1080

      gm()
        .in(inputFile)
        .out('(')
          .out('-clone')
          .out('0')
          .out('-background', 'white')
          .out('-blur', '0x9')
          .out('-resize', `${width}x${height}^`)
        .out(')')
        .out('(')
          .out('-clone')
          .out('0')
          .out('-background', 'white')
          .out('-resize', `${width}x${height}`)
        .out(')')
        .out('-delete', '0')
        .out('-gravity', 'center')
        .out('-compose', 'over')
        .out('-composite')
        .out('-extent', `${width}x${height}`)
        .write(outputFile, (error) => {
          if (error) {
            return reject(error)
          }

          console.log(`> Image converted: ${inputFile}`)
          resolve()
        })

    })
  }

**Comment by yagoernandes** [comment]
Aparentemente se você usa windows tem que colocar barra invertida, fica assim as linhas: 

```javascript
const inputFile = `.\\content\\${sentenceIndex}-original.png[0]`
const outputFile = `.\\content\\${sentenceIndex}-converted.png`
```

Eu coloquei isso e o erro mudou kkkkk, passou a dar isso:

> UnhandledPromiseRejectionWarning: Error: Command failed: Parâmetro Inválido - (

**Comment by JoaoPedroCJ** [comment]
fiz essa alteração e caiu no mesmo erro, aparentemente quando entra no gm() começa a dar problema primeiro no `.in(inputFile)`, quando alterou as barras ele começa a dar erro no `.out('(')`

**Comment by hudsonsr** [comment]
dá uma olhada na issue "Erro com GraphicMagick no windows #110", lá tem como resolver isso.

**Comment by cabral-ricardo** [comment]
Infelizmente temos que fazer uma gambis para rodar no windows.
* Instale a versão do image magick no windows (https://imagemagick.org/download/binaries/ImageMagick-7.0.8-40-Q16-x64-dll.exe)
* Durante a instalação check a opção de objetos legados (legacy....)
* Instale o pacote npm: "npm install imagemagick --save"
* No arquivo video.js
     - Inclua a referencia do modulo no arquivo video.js:  "const im = require("imagemagick")"
     - Substitua o processo gm()..... pelo:
     ```
          im.resize(
        {
          srcPath: inputFile,
          dstPath: outputFile,
          width: width,
          height: height
          
        },
        function(err, stdout, stderr) {
          if (err) throw err;
          console.log("sucesso");
        }
      );
     ```
* por fim vá nos módulos encontre o arquivo imagemagick.js dentro do modulo imagemagick
* Substitua a linha `exports.convert.path = 'convert';` por `exports.convert.path = "C:\\Program Files\\ImageMagick-7.0.8-Q16\\convert.exe";`

**Comment by JoaoPedroCJ** [comment]
> Infelizmente temos que fazer uma gambis para rodar no windows.
> 
> * Instale a versão do image magick no windows (https://imagemagick.org/download/binaries/ImageMagick-7.0.8-40-Q16-x64-dll.exe)
> * Durante a instalação check a opção de objetos legados (legacy....)
> * Instale o pacote npm: "npm install imagemagick --save"
> * No arquivo video.js
>   
>   * Inclua a referencia do modulo no arquivo video.js:  "const im = require("imagemagick")"
>   * Substitua o processo gm()..... pelo:
>   
>   ```
>        im.resize(
>      {
>        srcPath: inputFile,
>        dstPath: outputFile,
>        width: width,
>        height: height
>        
>      },
>      function(err, stdout, stderr) {
>        if (err) throw err;
>        console.log("sucesso");
>      }
>    );
>   ```
> * por fim vá nos módulos encontre o arquivo imagemagick.js dentro do modulo imagemagick
> * Substitua a linha `exports.convert.path = 'convert';` por `exports.convert.path = "C:\\Program Files\\ImageMagick-7.0.8-Q16\\convert.exe";`

não precisei de tantas gabiarras, só de marcar a opção legacy resolveu o problema

**Comment by yagoernandes** [comment]
Eu havia instalado com 'legacy' da primeira vez, mas reinstalei aqui e passou a funcionar. Caso alguém encontre o mesmo problema, reinstale antes, e se mesmo assim não funcionar, parta pra solução do @cabral-ricardo, que por sinal ta muito bem documentada, obrigado!
