### ISSUE TITLE
Erro na keyword

### ISSUE THREAD

**Issue by Ooliveiraaaa** [filipedeschamps/video-maker#128]
Alguem por favor pode me jaudar, eu estava seguindo os passos do video e acabou ocorrendo o seguinte erro : 
![Screenshot_1](https://user-images.githubusercontent.com/49662977/56173564-891b3080-5fc4-11e9-8fc8-d2c08f605fd9.png)
Segue meu text.js : const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')
const watsonApiKey = require ('../credentials/watson-nlu.json').apiKey

const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
 
const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'

})

async function robot(content) {
  await fetchContentFromWikipedia(content)
  sanatizeContent(content)
  breakContentIntoSentences(content)
  limitMaximumSentences(content)
  await fetchKeywordsOfAllSentences(content)

async function fetchContentFromWikipedia(content) {
  const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
  const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
  const wikipediaResponde = await wikipediaAlgorithm.pipe(content.searchTerm)
  const wikipediaContent = wikipediaResponde.get()
  content.sourceContentOriginal = wikipediaContent.content

}

function sanatizeContent(content) {

const withoutBlankLinesAndMarkdown = removeBlankLinesAndMarkdown(content.sourceContentOriginal)
const withoutDatesInParentheses = removeDatesInParentheses(withoutBlankLinesAndMarkdown)

 content.sourceContentSanitized = withoutDatesInParentheses

    function removeBlankLinesAndMarkdown(text) {
      const allLines = text.split('\n')

      const withoutBlankLinesAndMarkdown = allLines.filter((line) => {
        if (line.trim().length === 0 || line.trim().startsWith('=')) {
          return false
        }

        return true
      })

      return withoutBlankLinesAndMarkdown.join(' ')
    }
  }

  function removeDatesInParentheses(text) {

return text.replace(/\((?:\([^()]*\)|[^()])*\)/gm, '').replace(/  /g,' ')

  }

  
  function breakContentIntoSentences(content) {

   content.sentences = []

   const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
   sentences.forEach((sentence) => {

   content.sentences.push({
   text: sentence,
   keywords: [],
   images: []

  })

   })
   console.log(sentences)
 

  }

  function limitMaximumSentences(content) {

 	content.sentences = content.sentences.slice(0, content.maximumSentences)

  }

  async function fetchKeywordsOfAllSentences(content){

  	for(const sentence of content.sentences){

  		sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)
  	}

  }

async function fetchWatsonAndReturnKeywords(sentence){
    return new Promise((resolve, reject) => {
	 nlu.analyze({ 
	  text: sentence,
	  features: {
		keywords: {}
	  }
	}, (error, response) => {
	  if(error) {
	  throw error
	  
	  }
	const keywords = response.keywords.map((keyword) => {

		return keyword.text

	})
	resolve(keywords)
	})
 })
}

}

module.exports = robot

Alguem pode me ajudar por favor, ja tentei de tudo

**Comment by shido76** [comment]
Suas credenciais no ibm watson estão corretas?

**Comment by Ooliveiraaaa** [comment]
@shido76 Mano sim , eu percebi uma coisa, que quando estou instalando a npm install watson-developer-cloud isso aqui aparece, voce sabe me dizer se é normal?
![Screenshot_4](https://user-images.githubusercontent.com/49662977/56259029-0f5c7300-60a8-11e9-9ff9-1beb673eb807.png)

**Comment by shido76** [comment]
Vc tem q rodar o comando npm na raiz do diretório do projeto. Vc está rodando o comando dentro de Desktop

**Comment by danielschmitz** [comment]
O @shido76 está certo. você não instalou o pacote no seu projeto. Vou fechar a issue, se tiver mais algum outro problema, só abrir outra issue
