### ISSUE TITLE
(node:12788) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

### ISSUE THREAD

**Issue by BrouWilliam** [filipedeschamps/video-maker#130]
![HHH](https://user-images.githubusercontent.com/36682030/56243504-25027600-6071-11e9-8e05-cb0e0c308aad.PNG)

Acredito que o erro esteja no Magic e no gm

- Após instalar o magic.exe e o npm install gm o comando convert não é um parâmetro valido. Fiz apenas isso nada mais, e logo após comecei fazer o código.

- Consegui fazer a converção usando 'magick' ao invés de usar o 'convert' e funcionou.
exemplo:  'magick 0-original.png -resize 50% 0-converted.png'

Tudo estava funcionando normal antes disso, ele baixa as imagens, apenas não faz a converção.

 * Node: 10.15.3
 * Wind10

**Comment by caufom** [comment]
No instalador do imageMagick marque a opção de file associations (eg. convert) que irá funcionar.

**Comment by taciobn** [comment]
Aqui funcionou!!! muito abrigado.
