### ISSUE TITLE
Ajuda em uma implementação

### ISSUE THREAD

**Issue by Ooliveiraaaa** [filipedeschamps/video-maker#131]
Opa iae pessoal, tranquilo(a)?
Eu gostaria de saber como que eu posso fazer para que no momento que o usuario digita o :
"Tema da pesquisa" aparece a exibição da pesquisa no cmd, depois disso ele gera um log em JSON na raiz do projeto, o **"content.json"**, queria saber se tem como enviar pro "content.json" somente as sentencas(Sentences)  ja resumidas, eliminando o log do "sourceContentSanitized" e o "sourceContentOriginal"

Gostaria de saber se tem como fazer somente essas sentenças aparecerem :
![Screenshot_3](https://user-images.githubusercontent.com/49662977/56258368-b4c21780-60a5-11e9-89f4-19fd1b91f469.png)

**Comment by ocoiel** [comment]
Olá. Como você colocou em português?

**Comment by GabrielF9** [comment]
A maneira rápida e fácil que imagino no momento, seria criando outro objeto que tenha os mesmos parâmetros que a const content, porém, sem a sourceContentOriginal e sema sourceContentSanitized. Mais ou menos algo do tipo:

```js
const content = {...} // Essa é a que você já tem

const resumeContent = {
  ...
  sentences: content.sentences
  ...
}
```

E por aí vai, essa é uma forma de resolver hehe

**Comment by Ooliveiraaaa** [comment]
@GabrielF9 , cara eu juro que não consegui compreender muito bem como montar essa "resumeContent"

**Comment by GabrielF9** [comment]
@Ooliveiraaaa man, desculpa a demora kkk não vi a notificação, tentar explicar:

Basicamente, o que você faria seria criar outra estrutura de dados, só com os campos que lhe convém, ou seja, em um exemplo simples, minha estrutura é essa:

Um objeto pessoa, que tem nome, idade e sexo:

```js
const personOriginal = {
  name: "...",
  age: "...",
  sex: "..."
}
```

Mas só me interessam os campos `name` e `age` desse objeto pessoa. O que eu faria então, seria construir minha nova estrutura de dados, com base na que eu já tenho:

```js
const personSanitized = {
  name: person.name,
  age: person.age
}
```

Acho que expliquei melhor agora, espero que ajude, mas não se sinta obrigao a entender kkk qualquer coisa tamo aí!!

**Comment by Ooliveiraaaa** [comment]
@GabrielF9  Man mas eu não entendi o seguinte, eu quero que apareça na **content.json** somente a sentences, ou seja, as sentenças geradas e nao o sanatizedContent e nem o Content original, o problema é,  a SENTENCES tem dependencia direta do sanatizedContent que por sua vez tem dependencia direta do Content original, entao se eu tento "filtrá-los"  para exibição somente da SENTENCES ele nao aparece nada,  porque suas dependencias foram filtradas.

**Comment by aguedes2** [comment]
Oi @Ooliveiraaaa no teu log está aparecendo so 3 textos e você quer que apareca somente o resultado final, é isso? já na hora q roda o código? veja se não tem 3 console.log que estão rodando e por isso aparecendo o contentOriginal, contentSanitized e as Sentenças. 
Veja se não está tendo 2 console.log() na index.js do orquestrador e o console.log() de dentro do robo de texto, e por isso está aparecendo todos os resultados no teu prompt.

**Comment by MatheusRV** [comment]
@Ooliveiraaaa Ainda está com o problema? Posso fechar a issue?
