### ISSUE TITLE
Converter o template do After effects para versoes mais antigas

### ISSUE THREAD

**Issue by rrfaria** [filipedeschamps/video-maker#133]
Eai pessoal eu tenho o after effects em uma maquina antiga que usa o after effects na versao CS6 

Sera que uma boa alma poderia me ajudar e converter o arquivo para que eu consiga abrir?

**Comment by leocavalcante** [comment]
Da uma olhada se ajuda: https://github.com/leocavalcante/video-maker/blob/master/templates/1/template%20copy%20CC%20(14.x).aep

**Comment by dionesrosa** [comment]
Me ajudou muito esta template para versões anteriores a 2019. Vlw

**Comment by C-Miriane** [comment]
Oi @leocavalcante a versão do meu AF é CS4, você sabe dizer como faço para converter o template para conseguir abrir nele?

**Comment by Cinmiber** [comment]
Eu preciso da mesma ajuda, mas vi que o link expirou. Alguma outra sugestão?

**Comment by leocavalcante** [comment]
CC 15.x foi o mínimo que deu pra chegar, meu patrão.
[template copy CC (15.x).aep.zip](https://github.com/filipedeschamps/video-maker/files/5388480/template.copy.CC.15.x.aep.zip)
