### ISSUE TITLE
Erro na impressao da pesquisa

### ISSUE THREAD

**Issue by Ooliveiraaaa** [filipedeschamps/video-maker#134]
Alguem poderia me dizer por que isso ta acontencendo : 
![Screenshot_5](https://user-images.githubusercontent.com/49662977/56325474-b1339c80-6148-11e9-9e25-6fde30c52d9e.png)

Toda vez que digito um conteudo com acento , seja ele um nome de uma pessoa ou livro, ele retorna esse erro, alguem tem ideia do que possa ser?

**Comment by hebertlima** [comment]
veja se resolve mudando o idioma do [Google CSE](https://cse.google.com/cse/setup/basic?cx=002527716722989368095%3Agbsrnyxoak4) para Portugues, posso estar errado, mas deve ser os caracteres especiais no ingles não tem
