### ISSUE TITLE
Erro na implementação do ESLINT

### ISSUE THREAD

**Issue by vncsgonca23** [filipedeschamps/video-maker#137]
eslint(no-shadow)
eslint(no-param-reassign)

esses são os erros que aparecem ao utilizar o eslint. alguem saberia me informar como que os conserta?

**Comment by matheusfrancisco** [comment]
@vncsgonca23  tem como tu postar teu arquivo .eslintrc.json, mas talvez isso te ajude.
no seu arquivo eslintrc.json tu 
"rules": {
  "no-param-reassign": [2, { "props": false }],
   "no-shadow": ["error", { "builtinGlobals": false, "hoist": "functions", "allow": [] }]
}

não tenho certeza, caso não funcione vou dar uma pesquisada melhor!
Abrçs
