### ISSUE TITLE
Error: Cannot find module './robots/user-input.js'

### ISSUE THREAD

**Issue by gabrielguarido** [filipedeschamps/video-maker#139]
Fala pessoal, beleza?
To com um erro aqui quando tento rodar o 'node index.js' no CMD
![image](https://user-images.githubusercontent.com/47127807/56474239-6a49ed80-644d-11e9-8b9e-9148a4b04eec.png)

alguem pode dar um help, pfv?

creio que tenha a ver com algum erro na organização das pastas.

![image](https://user-images.githubusercontent.com/47127807/56474258-a8dfa800-644d-11e9-9fa9-1108c1c0f5fd.png)

**Comment by dionesrosa** [comment]
O erro ta no index. Você está requirindo o arquivo robots/user-input.js que não existe.
