### ISSUE TITLE
UnhandledPromiseRejectionWarning: Bad Request: unsupported text language: mg

### ISSUE THREAD

**Issue by gabrielguarido** [filipedeschamps/video-maker#141]
Fala pessoal, após a implementação do watson-nlu estou recebendo esse erro ao tentar rodar o index.js no terminal

![image](https://user-images.githubusercontent.com/47127807/56514669-4dc0ba80-650c-11e9-9b53-1bff730b89c9.png)

Alguém sabe me dizer o que há de errado no código, pfv?

**Comment by gabrielguarido** [comment]
Obs: Esse erro so aparece em determinados termos do wikipedia, se eu digitar 'Michael Jackson' por exemplo, ele me retorna esse erro...Porem se eu digitar algo como 'bacon', ele retorna normalmente

**Comment by leodutra** [comment]
O erro parece não acontecer na versão atual.
Fechando por agora, pf reabra se tornar a acontecer.
