### ISSUE TITLE
Como gerar o json de credentials do youtube

### ISSUE THREAD

**Issue by rrfaria** [filipedeschamps/video-maker#144]
Olá pessoal, 
estou testando aqui o app e cheguei até a parte do youtube, porém não tem explicação nenhuma sobre como gerar as credentials do youtube. Se alguém souber como faz e qual é o payload desse json seria bem legal.

**Comment by nathan-schroeder** [comment]
Olá,

Creio que [esse](https://developers.google.com/youtube/registering_an_application) passo a passo pode te ajudar.

**Comment by filipedeschamps** [comment]
Opa! Próxima segunda-feira vai sair o vídeo com todos os passos 👍

**Comment by jpfurlan** [comment]
> Olá pessoal,
> estou testando aqui o app e cheguei até a parte do youtube, porém não tem explicação nenhuma sobre como gerar as credentials do youtube. Se alguém souber como faz e qual é o payload desse json seria bem legal.

Cria um arquivo google-youtube.json e cola o código que você pegou no google cloud platform, nesse formato(o felipe faz download do arquivo no quarto(4º) minuto do vídeo de Youtube Api)
>{"web":{"client_id":"xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxng8jv2ppdjjh0om.apps.googleusercontent.com","project_id":"video-maker-upload-239312","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxxxxxxbJCX1_8Gi_XmtiIjN","redirect_uris":["http://localhost:5000/oauth2callback"],"javascript_origins":["http://localhost:5000"]}}

**Comment by hebertlima** [comment]
atualizei o guia com as configurações da api do YouTube #89
