### ISSUE TITLE
ERRO apos a criacao de arquivo de video. = Cannot find module

### ISSUE THREAD

**Issue by Patricia7sp** [filipedeschamps/video-maker#147]
Ola pessoal, boa noite!

Desculpem ai pelo incomodo toda hora, toda hora me deparo com um erro diferente.

 Nao se alguem ja se deparou com este tipo de erro, ja dei uma pesquisada e nao consegui encontrar nada.

Erro abaixo....

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '/home/patricia/rob-s-maker/content/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11

Alguem conseguiria me dizer como resolver isso?

Desde de ja muito obrigada.

**Comment by aguedes2** [comment]
Oi Patrícia, teria como mostrar teu código do index.js?

**Comment by MatheusRV** [comment]
@Patricia7sp Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Por favor, reabra caso necessário e caso tenha mais informações.
