### ISSUE TITLE
Criar app para android/ios

### ISSUE THREAD

**Issue by danrleydfl** [filipedeschamps/video-maker#150]
A ideia é criarmos um app em ionic assim estaria disponível para todas as plataformas mobile.tive essa ideias quando vi  o issue #107

**Comment by leogaletti** [comment]
Bora começar esse APP, acho melhor fazer em React Native por ser nativo e termos uma performance maior. Podemos pensar em como ele vai ser, criar o repo e depois as tarefas e ir fazendo! Bora?

**Comment by leogaletti** [comment]
Repositório criado e comecei a detalhar as tarefas! 

https://github.com/leogaletti/app-video-maker

**Comment by MatheusRV** [comment]
Visto que o papo será direcionado em outro repo, posso fechar essa issue?

**Comment by leodutra** [comment]
Projeto inativo, fechando.
Reabra caso volte à atividade.
