### ISSUE TITLE
Erros ao gerar thumbs

### ISSUE THREAD

**Issue by willianbs** [filipedeschamps/video-maker#151]
Acontece depois de enviar o vídeo para o YT. Alguma ideia? 

O Upload do video completa certinho. (Thumb é PNG)

`UnhandledPromiseRejectionWarning: Error: The authenticated user doesnt have permissions to upload and set custom video thumbnails.`

**Comment by filipedeschamps** [comment]
É bem possível que a sua conta no YouTube ainda não esteja habilitada para customizar thumbnail (nem pela interface deles). Você precisa confirmar a conta com seu celular (pelo menos para mim foi isso)

**Comment by willianbs** [comment]
Valeu @filipedeschamps , vou testar ao chegar em casa. Fiz o meu gerando text2speech para ter alguém falando os textos das captions.

**Comment by willianbs** [comment]
Funcionou!
Seria legal colocar essa observação em algum lugar.

Valeu!
