### ISSUE TITLE
Erro (node:10028) UnhandledPromiseRejectionWarning: authorization required

### ISSUE THREAD

**Issue by Leandro3231** [filipedeschamps/video-maker#156]
Fiz tudo "certinho" e da-me sempre este erro, já tentei remover os modulos, dar denovo o npm install e nada, alguem sabe como resolver?
Abraço

(node:10028) UnhandledPromiseRejectionWarning: authorization required
(node:10028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
cola ai a mensagem completa do erro, porque nesse trecho não diz qual foi o arquivo do erro

**Comment by Leandro3231** [comment]
Consegui arrumar isso mas agora aparece
C:\Users\leo\video-maker>
C:\Users\leo\video-maker>node index.js
Type a Wikipedia search term: aa

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:3540) UnhandledPromiseRejectionWarning: authorization required
(node:3540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Leandro3231** [comment]
> cola ai a mensagem completa do erro, porque nesse trecho não diz qual foi o arquivo do erro

Já criei uma nova api do watson e também nao da :/

**Comment by jpfurlan** [comment]
Alguma credencial está com problemas, refaça todos seguindo o passo a passo do hebertlima aqui https://github.com/filipedeschamps/video-maker/issues/89

**Comment by hebertlima** [comment]
nesse caso o problema é a api do algorithmia, ela deve se parecer com isso:
´´´js
{
  "apiKey": "simRTtFZyLcmARxkb30zAQdzXwv1"
}
´´´

**Comment by Leandro3231** [comment]
> Alguma credencial está com problemas, refaça todos seguindo o passo a passo do hebertlima aqui #89

eu já fiz tudo de novo umas 3x e nada :/

**Comment by Leandro3231** [comment]
> nesse caso o problema é a credencial do **algorithmia.json**, ela deve se parecer com isso:
> 
> ```js
> {
>   "apiKey": "sua_api_key"
> }
> ```

tentei e da o erro na mesma

**Comment by jpfurlan** [comment]
lá em tipo de arquivo está arquivo json ?
![image](https://user-images.githubusercontent.com/50157736/57045068-eeb52100-6c42-11e9-91f4-35a2a4d9d600.png)

**Comment by Leandro3231** [comment]
![image](https://user-images.githubusercontent.com/50182970/57045414-6eec7e00-6c65-11e9-8a12-835b7125f7d2.png)
sim

**Comment by jpfurlan** [comment]
apaga o .json do nome do arquivo
e tenta

**Comment by Leandro3231** [comment]
Ele nao tem o .json, eu é que nas definiçoes do windows coloquei para aparecer as terminais dos ficheiros... :/

**Comment by paulo-santana** [comment]
Leandro, como a gente não está conseguindo enxergar direito exatamente qual é o erro, faz o seguinte:

coloca todo o bloco de código relacionado ao Algorithmia dentro de um try/catch, quando capturar o erro dá um console.log() nele e manda pra gente o que sai dele.

Tipo assim
```Javascript
// ...

async function fetchContentFromWikipedia(content) {
  console.log('> [text-robot] Fetching content from Wikipedia')

  try {
    const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
    const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
    const wikipediaContent = wikipediaResponse.get()
  } catch (error) {
    console.log(error)
  }

  content.sourceContentOriginal = wikipediaContent.content
  console.log('> [text-robot] Fetching done!')
}

// ...
```

**Comment by hebertlima** [comment]
Leandro se ainda estiver com problema atualiza seu repositório assim conseguimos ver melhor e até testar

**Comment by jprodrigues1981** [comment]
Olá Pessoal,
Graças aos erros de todos postados aqui consegui resolver muito deles, fiz tudo certo, mas anda a dar um erro com uma credencial, que já fiz e refiz tudo como indicado e não consigo livrar-me deste erro! já fiz vários testes, e já adicionei mais a credencial da api do google cloud alem do OAuth 2.0, alguém pode ajudar? Obrigadíssimo 

![image](https://user-images.githubusercontent.com/48494302/57584544-9f89ae80-74d4-11e9-8ddd-2e7632643527.png)

**Comment by hebertlima** [comment]
Olá @jprodrigues1981, esse erro é com as credenciais do Watson da IBM, veja se esta correta as credenciais e se você está fazendo a chamada na url correta da api, a url correta é 
```js
'https://gateway.watsonplatform.net/natural-language-understanding/api/'
```

**Comment by jprodrigues1981** [comment]
Olá Hebert! Tudo beleza? sangue bom, até fiz umas try aqui no código a procura do erro como o exemplo do Paulo Santana, mas não desvendo isso, já vi e revi os vídeos do Filipe.. o Watson está tudo ok, na url da minha tem apenas um "-lon", retirei e deixei idêntico ao seu. mas da no mesmo.

![image](https://user-images.githubusercontent.com/48494302/57585904-17140980-74e6-11e9-829d-86a0d9d4db35.png)

**Comment by jprodrigues1981** [comment]
As minha credenciais tinham sido instaladas com a Região London, exclui e adicionei Dallas, acho que isso não era motivo pra dar tanta dor de cabeça.. mas já correu mais qualquer coisa.. Agora está neste erro e acho que já o vi por ai no ISSUES ;)

![image](https://user-images.githubusercontent.com/48494302/57586088-707d3800-74e8-11e9-96e4-ef5c5a935a96.png)

**Comment by hebertlima** [comment]
Agora é `Bad Request ` significa que a url pode estar errada, se for e me parece ser na hora de pesquisar as imagens, da uma olhada no google custom searche console veja se está pesquisando no google.com com *imagens ativas* e *em toda a web*

**Comment by jprodrigues1981** [comment]
Olá @hebertlima ! desculpa está a chatear, se poder ajudar-me, fico imensamente granto, não sei por que não consigo nem ao menos que me apareça o pedido de consentimento na pagina de login do youtube como aparece no vídeo do @filipedeschamps, as credenciais estão corretas, já a dois dias que tento e fico a espera, pensei em ter de espera 24h para o youtube autoriza, mas também minha conta não é nova.
![image](https://user-images.githubusercontent.com/48494302/57812409-ebeb1d80-7764-11e9-9e14-0bb98fdccd02.png)

o Mov é efetuado tudo direitinho, só não dá sinal de vida a entrada de login do youtube :(

**Comment by hebertlima** [comment]
> 
> 
> Olá @hebertlima ! desculpa está a chatear, se poder ajudar-me, fico imensamente granto, não sei por que não consigo nem ao menos que me apareça o pedido de consentimento na pagina de login do youtube como aparece no vídeo do @filipedeschamps, as credenciais estão corretas, já a dois dias que tento e fico a espera, pensei em ter de espera 24h para o youtube autoriza, mas também minha conta não é nova.
> ![image](https://user-images.githubusercontent.com/48494302/57812409-ebeb1d80-7764-11e9-9e14-0bb98fdccd02.png)
> 
> o Mov é efetuado tudo direitinho, só não dá sinal de vida a entrada de login do youtube :(

olá @jprodrigues1981 por acaso existe um arquivo chamado **google-youtube.js** dentro da pasta **../credentials/?

**Comment by jprodrigues1981** [comment]
Existe, nas minhas tentativas cheguei a deixar apenas youtube.json e google.json, mas como disseste lá no outro comment, tenho que criar outra porta! posso colocar qualquer número? sou lego nesse assunto.. posso tentar uma 6000? valew

**Comment by MatheusRV** [comment]
Ainda estão com problema? Posso ajudar?

**Comment by silviobonilha** [comment]
Olá pessoal!
Será que algum de vocês poderiam dar uma ajuda com esse erro?
"
(node:20273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

Obrigado

**Comment by iamgoncalo** [comment]
Olá a todoo!
Não estou a conseguir resolver.

(```
base) MacBook-Pro-de-Goncalo:video-maker goncalo$ node index.js
Type a Wikipedia search term: Michael Jackson

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:85096) UnhandledPromiseRejectionWarning: authorization required
(node:85096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:85096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(base) MacBook-Pro-de-Goncalo:video-maker goncalo$ 
```

Vocês sabem quais são as possibilidades que possam ser?

Abraço,
Gonçalo

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
