### ISSUE TITLE
alguém sabe consertar esse erro?

### ISSUE THREAD

**Issue by Abraaozuza** [filipedeschamps/video-maker#157]
Aliás eu nem sei o que se trata, até onde eu procurei eu fiz exatamente como nos vídeos

![ERRO](https://user-images.githubusercontent.com/22822088/57045224-4784b980-6c43-11e9-9827-198eb0437237.jpg)

**Comment by paulo-santana** [comment]
Esse erro é sobre o arquivo google-search.json, que está na pasta /credentials. Erros de sintaxe em arquivos JSON são na maioria das vezes algumas aspas ou virgulas no lugar errado, tenta olhar nesse arquivo e vê se consegue identificar algum erro desse tipo.

Se você puder mandar o conteúdo desse arquivo, a gente pode dar uma olhada também.

**Comment by Abraaozuza** [comment]
De fato era esse o erro sim, faltava uma vírgula exatamente na posição indicada.
Agora o problema que apareceu foi outro mas como tem uma questão dessas aberta já, eu vou postar por lá.
Muitíssimo obrigado!
