### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'm ap' of undefined

### ISSUE THREAD

**Issue by Abraaozuza** [filipedeschamps/video-maker#158]
Boa noite pessoal.
Eu tive alguns erros quando tentei iniciar o projeto. Então, o que eu fiz basicamente foi deletar tudo e recomeçar do zero! Só que agora, me apareceu o erro abaixo que eu não estou sabendo lidar. Parece ser algum problema com a busca de imagens do google, mas não tenho certeza. Alguém saberia me indicar o caminho das pedras?

Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
Type a Wikipedia search term: Jesus Christ

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Jesus , also referred to as Jesus of Nazareth and Jesu
s Christ, was a first-century Jewish preacher and religious leader."
> [text-robot] Keywords: Jesus Christ, Jesus of Nazareth, religious leader, firs
t-century Jewish preacher

> [text-robot] Sentence: "He is the central figure of Christianity, and is widel
y described as the most influential person in history."
> [text-robot] Keywords: central figure of Christianity, influential person, his
tory

> [text-robot] Sentence: "Most Christians believe he is the incarnation of God t
he Son and the awaited Messiah prophesied in the Old Testament"
> [text-robot] Keywords: incarnation of God, Old Testament, Christians, Son, Mes
siah

> [text-robot] Sentence: "Virtually all modern scholars of antiquity agree that
Jesus existed historically, although the quest for the historical Jesus has prod
uced little agreement on the historical reliability of the Gospels and on how cl
osely the Jesus portrayed in the Bible reflects the historical Jesus."
> [text-robot] Keywords: historical Jesus, modern scholars of antiquity, little
agreement, Jesus, historical reliability of the Gospels, quest, Bible

> [text-robot] Sentence: "Jesus was a Galilean Jew who was baptized by John the
Baptist and began his own ministry."
> [text-robot] Keywords: Galilean Jew, Jesus, John, Baptist, own ministry

> [text-robot] Sentence: "He preached orally and was often referred to as "rabbi
"."
> [text-robot] Keywords: rabbi

> [text-robot] Sentence: "Jesus debated with fellow Jews on how to best follow G
od, engaged in healings, taught in parables and gathered followers."
> [text-robot] Keywords: fellow Jews, Jesus, healings, parables, followers, God

> [image-robot] Starting...
> [image-robot] Querying Google Images with: "Jesus Christ"
(node:5032) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'm
ap' of undefined
    at fetchGoogleAndReturnImagesLinks (C:\Users\Abraao\Videos\VIDEO MAKER\video
-maker\robots\image.js:43:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:5032) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>
C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>

**Comment by hebertlima** [comment]
acessa o [Google CSE](https://cse.google.com/cse/all) habilita a opção **Pesquisa de imagens** e **Pesquisar em toda a Web**, confirma se em *Sites a pesquisar* esta usando **google.com**

**Comment by Abraaozuza** [comment]
> acessa o [Google CSE](https://cse.google.com/cse/all) habilita a opção **Pesquisa de imagens** e **Pesquisar em toda a Web**, confirma se em _Sites a pesquisar_ esta usando **google.com**

Muito obrigado, de coração.
Agora sim o robô tá começando a andar, mas ainda assim surgiu outro erro, estou postando abaixo. Você sabe como resolver? Eu acredito que seja algo relacionado com o After Effects. Eu não tinha esse programa instalado em meu notebook, então eu o instalei hoje, mas não o utilizei. Só instalei mesmo caso fosse precisar pra este projeto.

Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>node index.js
Type a Wikipedia search term: Jesus Christ

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Jesus , also referred to as Jesus of Nazareth and Jesu
s Christ, was a first-century Jewish preacher and religious leader."
> [text-robot] Keywords: Jesus Christ, Jesus of Nazareth, religious leader, firs
t-century Jewish preacher

> [text-robot] Sentence: "He is the central figure of Christianity, and is widel
y described as the most influential person in history."
> [text-robot] Keywords: central figure of Christianity, influential person, his
tory

> [text-robot] Sentence: "Most Christians believe he is the incarnation of God t
he Son and the awaited Messiah prophesied in the Old Testament"
> [text-robot] Keywords: incarnation of God, Old Testament, Christians, Son, Mes
siah

> [text-robot] Sentence: "Virtually all modern scholars of antiquity agree that
Jesus existed historically, although the quest for the historical Jesus has prod
uced little agreement on the historical reliability of the Gospels and on how cl
osely the Jesus portrayed in the Bible reflects the historical Jesus."
> [text-robot] Keywords: historical Jesus, modern scholars of antiquity, little
agreement, Jesus, historical reliability of the Gospels, quest, Bible

> [text-robot] Sentence: "Jesus was a Galilean Jew who was baptized by John the
Baptist and began his own ministry."
> [text-robot] Keywords: Galilean Jew, Jesus, John, Baptist, own ministry

> [text-robot] Sentence: "He preached orally and was often referred to as "rabbi
"."
> [text-robot] Keywords: rabbi

> [text-robot] Sentence: "Jesus debated with fellow Jews on how to best follow G
od, engaged in healings, taught in parables and gathered followers."
> [text-robot] Keywords: fellow Jews, Jesus, healings, parables, followers, God

> [image-robot] Starting...
> [image-robot] Querying Google Images with: "Jesus Christ"
> [image-robot] Querying Google Images with: "Jesus Christ central figure of Chr
istianity"
> [image-robot] Querying Google Images with: "Jesus Christ incarnation of God"
> [image-robot] Querying Google Images with: "Jesus Christ historical Jesus"
> [image-robot] Querying Google Images with: "Jesus Christ Galilean Jew"
> [image-robot] Querying Google Images with: "Jesus Christ rabbi"
> [image-robot] Querying Google Images with: "Jesus Christ fellow Jews"
> [image-robot] [0][0] Image successfully downloaded: https://www.ldsart.shop/wp
-content/uploads/jesus-christ-painting-resurrection-and-the-life-by-brent-borup-
white-background.jpg
> [image-robot] [1][0] Image successfully downloaded: https://media.gettyimages.
com/photos/jesus-christ-central-figure-of-christianity-picture-id498743244
> [image-robot] [2][0] Image successfully downloaded: https://i.ytimg.com/vi/DwF
N5naa8Jg/maxresdefault.jpg
> [image-robot] [3][0] Image successfully downloaded: https://i.ytimg.com/vi/e32
f-Ntg1Us/hqdefault.jpg
> [image-robot] [4][0] Image successfully downloaded: https://www-images.christi
anitytoday.com/images/68798.jpg?w=700
> [image-robot] [5][0] Image successfully downloaded: https://i.ytimg.com/vi/tWY
99B_O5fE/maxresdefault.jpg
> [image-robot] [6][0] Image successfully downloaded: http://www.ifcj.org/assets
/images/social-sharing-images/ifcj-logo-fbhome.jpg
> [video-robot] Starting...
> [video-robot] Image converted: ./content/0-converted.png
> [video-robot] Image converted: ./content/1-converted.png
> [video-robot] Image converted: ./content/2-converted.png
> [video-robot] Image converted: ./content/3-converted.png
> [video-robot] Image converted: ./content/4-converted.png
> [video-robot] Image converted: ./content/5-converted.png
> [video-robot] Image converted: ./content/6-converted.png
> [video-robot] Sentence created: ./content/0-sentence.png
> [video-robot] Sentence created: ./content/1-sentence.png
> [video-robot] Sentence created: ./content/2-sentence.png
> [video-robot] Sentence created: ./content/3-sentence.png
> [video-robot] Sentence created: ./content/4-sentence.png
> [video-robot] Sentence created: ./content/5-sentence.png
> [video-robot] Sentence created: ./content/6-sentence.png
> [video-robot] YouTube thumbnail created
> [video-robot] Starting After Effects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>

**Comment by Abraaozuza** [comment]
Eu alterei o código do arquivo video.js de acordo com a issue #121, e na hora de testar o erro que saiu foi este (estou colocando só a parte do erro pra não ficar muito grande):

(node:2164) UnhandledPromiseRejectionWarning: TypeError: robots.video is not a f
unction
    at start (C:\Users\Abraao\Videos\VIDEO MAKER\video-maker\index.js:14:16)
(node:2164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:2164) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

C:\Users\Abraao\Videos\VIDEO MAKER\video-maker>

Não sei se estou vendo errado, mas este erro se refere ao arquivo index.js? lá tem uma função chamada robots.video, que de acordo com este erro não é reconhecida como uma função. Estou perdido.

**Comment by Abraaozuza** [comment]
Pessoal, eu li e reli tudo a respeito desse erro que reportei quase uma hora atrás e consegui resolvê-lo. Quando alterei o código a partir da issue que eu falei, acabei apagando a última linha de código e, sem ela, o node não estava reconhecendo aquele bloco como um robô. Só que, como a vida é feita de emoções, rodei novamente e, desta vez surgiu este erro. Estou postando um print da tela porque não consegui copiar. Se trata de algum problema com a API do youtube? Alguém pode me dar uma luz?
![ERRO2](https://user-images.githubusercontent.com/22822088/57204482-82ae2200-6f8e-11e9-8bdf-749e0100f217.jpg)

**Comment by hebertlima** [comment]
vc precisa corrigir 2 coisas:
path de onde estar o reader.exe do after effects 2019:
no arquivo **videos.ts** dentro da função **renderVideoWithAfterEffects** variavel: **aerenderFilePath** : 
`C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe` (no seu caso pode não ser exatamente esse caminho, mas o final **/aerender.exe** precisa ser)

2º alteração dentro da pasta **templates/1/template.aep** você vai procurar a composição: **tittle-animation** vai dar dois clicks:
![image](https://user-images.githubusercontent.com/34013325/57243039-73b98500-700b-11e9-9067-67ffdb2390e8.png)

vai navegar até o **Expression Source Text**:
![image](https://user-images.githubusercontent.com/34013325/57243091-9ba8e880-700b-11e9-97dd-cc48ece20739.png)

e vai alterar esse path: `$.evalFile('D:/Documentos/workstation/video-maker/content/after-effects-script.js')` tem que apontar para o seu diretório **video-maker/content/after-effects-script.js**
![image](https://user-images.githubusercontent.com/34013325/57243137-b8452080-700b-11e9-819e-da8f38e0acbd.png)

por ultimo no site do [Adobe](https://helpx.adobe.com/download-install/kb/creative-cloud-apps-download.html) vc vai baixar o **Extendscript Toolkit CC**

obs: após abrir o **template.aep** salve ele novamente o proprio after effects vai corrigir alguns parametros para adequa-lo ao windows porque ele foi criado com o mac e as configurações são diferentes

**Comment by Abraaozuza** [comment]
@hebertlima 
Muito obrigado pela sua ajuda. Segui tudo o que você orientou e percebi que o robô está indo um pouco mais adiante (eu acho!), contudo, ainda apareceu este erro, que parece ser bem semelhante, e não consegui entender ainda ao quê está relacionado. 
![ERRO3](https://user-images.githubusercontent.com/22822088/57255579-93ac7100-702a-11e9-8d70-7430808a4cbc.jpg)

**Comment by Abraaozuza** [comment]
@hebertlima 
Baseado no erro acima, eu imaginei que o erro poderia estar no arquivo youtube.js, então eu fui lá e, onde está destacado, tinha apenas ...credentials/google-youtube.json', então eu fui lá e coloquei o caminho, conforme pode-se ver na imagem abaixo, mas continua apontado exatamente o mesmo erro acima. Você tem ideia do que poderia ser?
![ERRO4](https://user-images.githubusercontent.com/22822088/57256824-1256dd80-702e-11e9-8137-5d0a9e6c433c.jpg)

**Comment by Abraaozuza** [comment]
@hebertlima @filipedeschamps @danielschmitz 
Eu só tenho a agradecer a vocês, é a primeira vez que eu sigo algo relacionado a programação até o fim.
Até o presente, consegue resolver o problema acima. (foi só um detalhe de um hífen que eu usei no nome do aplicativo na hora de criar as APIs e esqueci de colocar no OAuth do youtube).
Eu acredito que esteja faltando pouco pra eu conseguir rodar o projeto, sinto que preciso disso pra aí sim começar a pensar em formas de modificá-lo. O que aconteceu foi que, na hora de autorizar o aplicativo no youtube, me apareceu este erro abaixo. Não vou ler a respeito agora porque tenho prova de cálculo amanhã, depois da prova eu vejo. Se até lá alguém conseguir me dar uma luz, agradecerei do fundo do coração!
![ERRO6](https://user-images.githubusercontent.com/22822088/57267181-91134100-7055-11e9-9aff-ad62ce616d8b.jpg)

**Comment by hebertlima** [comment]
é assim mesmo o navegador não abre sozinho, sobre o erro basicamente ele não achou o arquivo **output.mov** dentro da pasta **content/**, da uma olha nessa pasta e veja se existe o arquivo **output.mov** se existir, verifica se o robô **youtube.js** esta chamando o vídeo no **path** correto

**Comment by Abraaozuza** [comment]
Ih, caramba, esse arquivo não existe

**Comment by Abraaozuza** [comment]
Eu realmente me perdi aqui. Pensei que, ou o After Effects não está salvando o video como output.mov ou então em algum arquivo eu preciso indicar este caminho. Acredito que seja o primeiro caso, pois não encontrei o output.mov em lugar algum. Também não estou encontrando o caminho para alterar a pasta de saída

**Comment by Abraaozuza** [comment]
Encontrei o caminho para mudar a saída no After Effects, só que mesmo assim o arquivo não está aparecendo na pasta content

**Comment by hebertlima** [comment]
parece que seu problema começa com o arquivo video.js porque ele é responsável por criar o video, da uma olhada nele

**Comment by Abraaozuza** [comment]
@hebertlima 
Acabei de alterar os locais onde salvar o arquivo, e etc, e onde ele pode ser encontrado, tanto no video.js quanto no youtube.js, mas ainda está com esse erro. To enviando os arquivos também, com certeza fiz algo muito errado.
![ERRO 7](https://user-images.githubusercontent.com/22822088/57346163-e28a0180-7123-11e9-9179-f4f940d7a25a.jpg)



[video.txt](https://github.com/filipedeschamps/video-maker/files/3155278/video.txt)
[youtube.txt](https://github.com/filipedeschamps/video-maker/files/3155279/youtube.txt)

**Comment by hebertlima** [comment]
seus paths estão errados, coloque todos os caminhos relativos ao diretório atual, por exemplo se vc tem essa estrutura de pastas assim:
``` diff
movie-maker/
   ├── content/  
+  │   └── output.mov
   ├── credentials/  
+  │   └── google-youtube.json
   ├── robots/         
   │   ├── video.js
+  │   ├── youtube.js
   │   └── image.js
   └── templates/
          └── 1/
```

e você esta esta dentro do arquivo `youtube.js` e quer acessar as credênciais `google-youtube.json`, você precisa voltar **1 diretório**, nesse caso caso vc utiliza o ponto `.` para indicar um **nivel acima**  seguido por uma barra `/` que indica de forma simples, o começo de onde deve-se procurar o arquivo, ficaria algo assim `./`.

nesse momento vc esta indicando que busca algo dentro da pasta `movie-maker/` não mais em `movie-maker/robots/`, apartir disso você indicar o caminho para o arquivo `google-youtube.json`, que ficaria assim: `./credentials/google-youtube.json`, ou seja a sua variavel `const credentials = require('...')` ;
ficaria assim:
```js
const credentials = require('./credentials/google-youtube.json')
```

use esse conceito para corrigir todos os paths (caminhos) dos arquivos que você está acessando, provavelmente o erro esta justamente ai, alguns recurso não fazem a busca da path absoluto como você esta indicando e acredito que por isso ele não esta achando os arquivos e/ou salvando nos lugares certos, outra coisa, quando usar a barra dentro de uma string cercada por aspas simples você precisa usar duas barras `\\` porque, 1 barra indica "escape", 
```js
const errado = 'C:\foo\bar\teste'
const correto = 'C:\\foo\\bar\\teste'
```

para saber mais sobre strings da uma olhada aqui: [How To Work with Strings in JavaScript](https://www.digitalocean.com/community/tutorials/how-to-work-with-strings-in-javascript)

**Comment by Abraaozuza** [comment]
@hebertlima 
Muitíssimo obrigado pelas dicas, estou lendo agora e corrigindo conforme a sua orientação!

**Comment by hebertlima** [comment]
@Abraaozuza magina cara! estamos ai pra ajudar 😃

**Comment by C-Miriane** [comment]
Oi @hebertlima,

Agora acho que estou com o mesmo erro dele, só que sou iniciante e não entendi sua explicação. A única mudança que fiz foi alterar o caminho do After adicionando a versão que tenho e no final colocar.exe. Deu certo a principio e passei para essa etapa, agora parou de novo. Abriu uma tela pedindo autorização quando estava rodando o código e parou. Oq posso fazer para corrigir? tem algum código que preciso mudar?

> [youtube-robot] Starting...
> [youtube-robot] Listening on http://localhost:5000
(node:2812) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cred
entials/google-youtube.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at createOAuthClient (C:\Users\HP\Desktop\GIT\video-maker - Cópia (2)\robots
\youtube.js:42:27)
    at authenticateWithOAuth (C:\Users\HP\Desktop\GIT\video-maker - Cópia (2)\ro
bots\youtube.js:18:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:2812) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
Olá @C-Miriane, no seu erro parece que ele não está encontrando o arquivo **google-youtube.json**, dentro da past **credentials/**, verifica se esse arquivo está lá dentro 🤓

**Comment by C-Miriane** [comment]
Oi @hebertlima,
 Então, esta lá dentro sim e refiz novamente para ver se havia algum erro, mas nada de dar certo. Aí lendo sua resposta aqui fiquei pensando se o meu problema não seria parecido ao do @Abraaozuza  pois mudei a versão e caminho do After (a principio deu certo pq andou mais um pouco). Será que é necessário baixar o Extendscript Toolkit CC também? Ou será que essa etapa já foi solucionada e o problema é só com a credencial?
https://github.com/filipedeschamps/video-maker/issues/158#issuecomment-489708147

> [video-robot] Starting After Effects
aerender version 9.0x346
> [video-robot] After Effects closed
> [youtube-robot] Starting...
> [youtube-robot] Listening on http://localhost:5000
(node:3140) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cred
entials/google-youtube.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at createOAuthClient (C:\Users\HP\Desktop\GIT\video-maker\robots\youtube.js:
42:27)
    at authenticateWithOAuth (C:\Users\HP\Desktop\GIT\video-maker\robots\youtube
.js:18:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:3140) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by C-Miriane** [comment]
Oi @hebertlima , nossa finalmente consegui resolver essa etapa. Eu fiquei tão focada no passo a passo das credenciais que o detalhe do nome passou batido.
No passo a passo está escrito 
"renomeio o arquivo para youtube.json e salve dentro da pasta video-maker/credentials "
 
E só agora lendo seu comentário percebi que faltou o "Google na frente, pois o correto é "google-youtube.json".

Se tivesse como, era bom mudar lá no passo a passo....mas vc mesmo que me ajudou :)

**Comment by C-Miriane** [comment]
@hebertlima aí quando acho que enfim deu certo, copio a URL, autorizo acesso a minha conta, mas não da certo...
![Erro ao permitir acesso a conta](https://user-images.githubusercontent.com/49778340/57528337-7ae0db80-7308-11e9-9a9b-8044902dd4c7.png)

Sabe dizer pq isso aconteceu e como posso resolver?

**Comment by hebertlima** [comment]
@C-Miriane esse ai é la no google cloud, lembra onde você colocou a url para solicitar as credenciais http://localhost:5000? então, tira o **https://**, o correto é **http://localhost:5000** nos dois campos!

**Comment by C-Miriane** [comment]
@hebertlima era isso mesmo, a página ficou em branco escrito obrigado em inglês. o código rodou mais um pouco, porém agora apareceu isso:

 [youtube-robot] Please give your consent: https://accounts.google.com/o/oauth2
/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyou
tube&response_type=code&client_id=328116377253-92umuumggr6s8c3pu2h41vt4bj8eksgf.
apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Foauth2ca
llback
> [youtube-robot] Waiting for user consent...
> [youtube-robot] Consent given: 4/RgHfncfjaa5m0G56bOxJ7J7zwCvqPXDsQ6YmjpfgkF8V4
L-LpuDrEygbfWY-A5m9-ZN0BdudRkTC10wVS_v84fs
> [youtube-robot] Access tokens received!
(node:3252) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, stat './content/output.mov'
    at Object.statSync (fs.js:850:3)
    at uploadVideo (C:\Users\HP\Desktop\GIT\video-maker\robots\youtube.js:108:30
)
    at Object.robot [as youtube] (C:\Users\HP\Desktop\GIT\video-maker\robots\you
tube.js:13:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:3252) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by Abraaozuza** [comment]
@hebertlima @C-Miriane 
eu continuo sem conseguir gerar o arquivo output.mov e então, quando tentei redefinir o caminho de saida novamente, no after effects, me deparei com o seguinte: 

![ERRO AFTER EFFECTS](https://user-images.githubusercontent.com/22822088/57576455-70246480-7436-11e9-8f46-dc16585a5df6.png)

Será que é por isso que não está gerando o arquivo? Se for, vocês sabem qual caminho para solucionar?
