### ISSUE TITLE
Criar Código de Conduta no projeto & no README.md

### ISSUE THREAD

**Issue by glaucia86** [filipedeschamps/video-maker#16]
@filipedeschamps em grandes projetos open source é uma boa prática criar um arquivo  `.md` de código de conduta.

Vou ver se crio um PR para deixar o seu `README.md` para facilitar a documentação e execução do seu projeto e incluir o código de conduta.

Há inúmeros modelos. Mas, vou deixar aqui alguns exemplos em português (que uso nos meus repositórios) e inglês:

* [Português](https://github.com/glaucia86/todo-list-vuejs-2/blob/master/CODE-OF-CONDUCT.md)
* [Inglês](https://gist.github.com/Integralist/4e84af31c483d0f5a182)

Se você curtir a ideia, posso abrir uma PR e como consequencia, assim que for para a master do seu projeto, fecho essa Issue aqui. 

O que você acha?

**Comment by matheuschimelli** [comment]
Não seria interessante adicionar um Issue template também?

**Comment by brunooomelo** [comment]
já cria os templates e mostra para ele e assim agiliza tudo.

**Comment by glaucia86** [comment]
> já cria os templates e mostra para ele e assim agiliza tudo.

farei nesse final de semana. Pois tenho ajudado na finalização das traduções da documentação do React. 
Mas, com certeza nesse fds farei um PR.

**Comment by danielschmitz** [comment]
Olá @glaucia86 sua ajuda será muito bem vinda! Dê uma olhada em #77  para saber mais detalhes.
