### ISSUE TITLE
Erro ao procurar imagens

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#162]
Olá, estou com o seguinte erro (print abaixo) após procurar pelas imagens, após ele pegar o texto do Wikipedia, ele vai para pegar as imagens, e nessa hora dá erro, se alguém puder me ajudar!

![image](https://user-images.githubusercontent.com/48515934/57259632-94e39b00-7036-11e9-8471-457f912ae4b8.png)

**Comment by dionesrosa** [comment]
Verifica antes se a busca de imagens está retornando algum resultado. Da um console.log(response.data.items);

**Comment by VinyciusC** [comment]
@dionesrosa tem algum lugar específico que devo colocar?

**Comment by VinyciusC** [comment]
Ví que há possuí uma issue com este mesmo problema, e já consegui resolver, era só fazer a mesma coisa que nessa issue, obrigado mesmo assim! 

Issue da qual estou me referindo: https://github.com/filipedeschamps/video-maker/issues/158

**Comment by Abraaozuza** [comment]
@VinyciusC que bom que conseguiu, parabéns

**Comment by VinyciusC** [comment]
Se alguém puder me ajudar em relação ao ImageMagick, abri a issue #164 para isso, não entendi muito bem como funciona, e nem como instala ele.
