### ISSUE TITLE
Erro oAuth2/Localhost

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#165]
Estou com um problema de autenticação, após aceitar tudo como na print:
![image](https://user-images.githubusercontent.com/48515934/57372321-ac707000-716b-11e9-8be1-ede8ea2281a7.png)
Ele acontece isso:
![image](https://user-images.githubusercontent.com/48515934/57372341-be521300-716b-11e9-8b53-801bd33883c2.png)

Já configurei certinho:
![image](https://user-images.githubusercontent.com/48515934/57372357-cc079880-716b-11e9-8655-c1ff7a8cce87.png)

Alguém pode me ajudar?

**Comment by hebertlima** [comment]
pode ser duas coisas: 
1º seu código não esta subindo o servidor `http://localhost:5000` no momento de pedir a autenticação
2º você esta subindo o localhost em outra porta, exemplo se a porta 5000 estiver ocupada ele vai abrir em outra ex: `http://localhost:4200`

**Comment by VinyciusC** [comment]
@hebertlima tentei alterar para `https://localhost:4200` e `https://localhost:4200/oauth2callback` e não funcionou, o código eu peguei direto já pronto do Filipe, sabe se tem alguma outra coisa que eu possa tá tentando?

**Comment by W3CMS** [comment]
@hebertlima o SSL do seu localhost tá configurado certinho?

**Comment by VinyciusC** [comment]
@hebertlima agora deu certo, eu tirei o `s` do `https` de tudo e funcionou, porém estou com um outro problema agora:
![image](https://user-images.githubusercontent.com/48515934/57420023-b467f880-71db-11e9-82c1-c081fa393729.png)

**Comment by C-Miriane** [comment]
Oi @VinyciusC vc tirou o "s" que estava cadastrado lá no Google Cloud? estou com o mesmo problema. Até aparece para autorizar, mas após fazer isso, ocorre esse erro. Se puder me auxiliar.

**Comment by VinyciusC** [comment]
Olá @C-Miriane ,

Para arrumar esse problema, é bem simples, você deve remover o `s` do `https://` dos seguintes locais:
- Google Cloud
- google-youtube.json
- youtube.json

Caso apareça outro erro, provavelmente é a porta que já está sendo utilizada, para resolver, altere  o `5000` para por exemplo `5001`, ou qualquer outro número, lembrando que você deve alterar nos mesmos locais citados acima.

**Comment by C-Miriane** [comment]
Obrigada @VinyciusC , fiz essa alteração agora pouco e apareceu um tela só de agradecimento em inglês e o código mudou para:

 [youtube-robot] Listening on http://localhost:5000
> [youtube-robot] Please give your consent: https://accounts.google.com/o/oauth2
/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyou
tube&response_type=code&client_id=328116377253-92umuumggr6s8c3pu2h41vt4bj8eksgf.
apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Foauth2ca
llback
> [youtube-robot] Waiting for user consent...
> [youtube-robot] Consent given: 4/RgHfncfjaa5m0G56bOxJ7J7zwCvqPXDsQ6YmjpfgkF8V4
L-LpuDrEygbfWY-A5m9-ZN0BdudRkTC10wVS_v84fs
> [youtube-robot] Access tokens received!
(node:3252) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, stat './content/output.mov'
    at Object.statSync (fs.js:850:3)
    at uploadVideo (C:\Users\HP\Desktop\GIT\video-maker\robots\youtube.js:108:30
)
    at Object.robot [as youtube] (C:\Users\HP\Desktop\GIT\video-maker\robots\you
tube.js:13:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:3252) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

Pq será isso?

**Comment by hebertlima** [comment]
@C-Miriane no erro dis: **no such file or directory, stat './content/output.mov'** não encontrou o arquivo **output.mov** dentro da pasta **content**

**Comment by VinyciusC** [comment]
@C-Miriane ele fez e renderizou o vídeo?
Você configurou no After Effects?

**Comment by C-Miriane** [comment]
@hebertlima esse arquivo  "output.mov" não tem na pasta Content mesmo, como faço para colocar?

**Comment by C-Miriane** [comment]
@VinyciusC  a principio sim, mas vou dar uma olhada aqui.

**Comment by VinyciusC** [comment]
O arquivo `output.mov` é criado após o vídeo ser feito e depois da renderização, e ele fica na pasta até ser upado no YouTube, após o processo terminar ele é excluído automaticamente, se não foi configurado no After Effects, ele não irá criar esse arquivo, o que abará resultando em erro, já que o robô do YouTube não irá encontrar o vídeo para upar.

**Comment by hebertlima** [comment]
@C-Miriane exatamente como o @VinyciusC explicou, se não houver um arquivo **output.mov** dentro da pasta **content/**, tem algo de errado com o seu robô **video.ts**, possivelmente com a local onde você pede para ele salver o video

**Comment by C-Miriane** [comment]
@VinyciusC  entendi, mas como foi avançando achei que tinha dado certo. Na pasta content consta o arquivo After Effects, mas não consta o output.mov. Estou usando o After de outra versão, porém alterei o nome, ..caminho e coloquei .exe no final lá para continuar rodando e deu certo (acho) pq seguiu...
Nem sei usar o After na verdade pois prefiro outro. No caso preciso mudar o local de salvar os aquivos? pq no momento tinha deixado para salvar na área de trabalho mesmo...por não usar. 
Não entendi qual a mudança que preciso fazer nele.

**Comment by hebertlima** [comment]
@C-Miriane no seu robô **video.ts** dentro da função **renderVideoWithAfterEffects** precisa ficar assim:
```js
const aerenderFilePath = 'C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'
const templateFilePath = `${rootPath}/templates/1/template.aep`
const destinationFilePath = `${rootPath}/content/output.mov`
```

você só vai precisar corrigir o path do **aerender.exe** que deve seguir para a pasta que você fez a instalação, você tbm irá precisar baixar o **Extendscript Toolkit CC** você acha ele aqui [Adobe](https://forums.adobe.com/thread/1081523)

**Comment by C-Miriane** [comment]
@hebertlima eu cheguei a fazer a mudança depois que li uma resposta sua para outra pessoa aqui. Aí chegou até a continuar o processo, só não sabia se tinha dado certo de fato...pelo jeito não então. Vou baixar o Extendscript Toolkit CC e ver se da certo com minha versão. No caso posso salvar onde quiser?

**Comment by C-Miriane** [comment]
@hebertlima como foi adicionado ".exe" após "aerender", será que na expressão que se repte precisa colocar também? 
const aerender = spawn(aerenderFilePath, [
        '-comp', 'main',
        '-project', templateFilePath,
        '-output', destinationFilePath

**Comment by hebertlima** [comment]
> 
> 
> @hebertlima eu cheguei a fazer a mudança depois que li uma resposta sua para outra pessoa aqui. Aí chegou até a continuar o processo, só não sabia se tinha dado certo de fato...pelo jeito não então. Vou baixar o Extendscript Toolkit CC e ver se da certo com minha versão. No caso posso salvar onde quiser?

sim, pode salver o arquivo que baixar e instalar em qualquer lugar



> 
> 
> @hebertlima como foi adicionado ".exe" após "aerender", será que na expressão que se repte precisa colocar também?
> const aerender = spawn(aerenderFilePath, [
> '-comp', 'main',
> '-project', templateFilePath,
> '-output', destinationFilePath

acho que você não entendeu o que é esse **aerender.exe**, o que esta acontecendo aqui é o sguinte, você esta dizendo para o seu robô (video.ts) que ele precisa usar esse um programa chamado **aerender.exe** na hora que ele for executar a função **renderVideoWithAfterEffects**, por esse motivo você coloca o **aerender.exe** com a extensão **.exe** (que é um executavel) seria o mesmo de quando você executa qualquer programa no seu pc dando os dois cliques, e nesse caso não precisa mudar nada nessas linhas seguintes `const aerender = spawn(aerenderFilePath, [...`

**Comment by C-Miriane** [comment]
@hebertlima Obrigada, é isso mesmo, o problema é que entendo apenas algumas partes do que estou fazendo, aí complica demais. Estou começando...e vou procurar me aprofundar mais, ao contrário não adianta de nada. Só queria finalizar ele, mas ta complicado. A impressão que tenho é que da o start no After e já fecha em seguida, aí nem cria aquele arquivo lá. Já simulei um caminho errado só para ver se mesmo assim prossegue, já que dando "certo" não funciona....aí noto que não vai mesmo...ou seja o problema não é no código e já mexi tanto que nem sei mais oq fazer....
Ah...tem hora que autentica e e outras vezes aparece a página de erro...mas claro que isso é o de menos..pq nem o vídeo está "pronto" na pasta lá.

 Starting After Effects
aerender version 9.0x346
> [video-robot] After Effects closed
> [youtube-robot] Starting...
> [youtube-robot] Listening on http://localhost:5000
> [youtube-robot] Please give your consent: https://accounts.google.com/o/oauth2
/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyou
tube&response_type=code&client_id=328116377253-92umuumggr6s8c3pu2h41vt4bj8eksgf.
apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Foauth2ca
llback
> [youtube-robot] Waiting for user consent...
> [youtube-robot] Consent given: 4/RgFQUE170EgjIi_3eQ09Zs3WqS4HfT7qabPk6O8RqjBQN
HFVdl2W6YIiEhtpKBG_3DWNM5tlvm6irlV0_WD7szQ
> [youtube-robot] Access tokens received!
(node:4360) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or dir
ectory, stat './content/output.mov'
    at Object.statSync (fs.js:850:3)
    at uploadVideo (C:\Users\HP\Desktop\GIT\video-maker\robots\youtube.js:108:30
)
    at Object.robot [as youtube] (C:\Users\HP\Desktop\GIT\video-maker\robots\you
tube.js:13:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:4360) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
@C-Miriane entendi, não desanima não, essa é a graça de programar precisa dar muito errado antes de dar certo 🤣, ainda parece ser um problema no robô **video.ts** 🤔, por acaso dentro da pasta **content/** ele esta baixando as imagens?

**Comment by hebertlima** [comment]
> 
> 
> @C-Miriane ele fez e renderizou o vídeo?
> Você configurou no After Effects?
> 
> Se o After Effects não estiver configurado, abra ele e altere o local de salvamento após a renderização do vídeo:
> ![image](https://user-images.githubusercontent.com/48515934/57534626-d914bb00-7316-11e9-82b5-c2230a8a097d.png)

você checou isso?

**Comment by C-Miriane** [comment]
@hebertlima abri o After e coloquei para salvar na pasta content, era isso? só que o meu não consta nada, ou seja, acho que nem esta "processando". 
Na pasta content consta as imagens que vão sendo baixadas, um arquivo chamado after-effects-script e outro youtube-thumbnail.

**Comment by hebertlima** [comment]
> 
> 
> @hebertlima abri o After e coloquei para salvar na pasta content, era isso? só que o meu não consta nada, ou seja, acho que nem esta "processando".
> Na pasta content consta as imagens que vão sendo baixadas, um arquivo chamado after-effects-script e outro youtube-thumbnail.

no after effects você precisa fazer apenas uma coisa, alterar o caminho do **title-animation** e apontar para **after-effects-script.js**, 

```js
$.evalFile('alterar/aqui/after-effects-script.js');
```
porque o caminho pra salvar ja esta configurado no proprio template para **content/**

**Comment by C-Miriane** [comment]
@hebertlima é bem isso que estou confusa. Até consigo criar um projeto lá no After e apontar para after-effects-script.js,, porém vc disse que precisa ser alterado o caminho do "title-animation"....como faço isso? no vídeo do Felipe ele abre aquele primeiro vídeo que ele criou e aí sim aparece essa opção "title-animation". Mas no meu caso não aparece pq não sei como funciona. Cheguei a abrir o template.asp pelo After, mas acho que não tem nada a ver né....
Como que faço nesse caso?

**Comment by hebertlima** [comment]
@C-Miriane sim você precisa editar o template.asp mesmo, da uma olhada [aqui](https://github.com/filipedeschamps/video-maker/issues/158#issuecomment-489708147)

**Comment by C-Miriane** [comment]
@hebertlima Obrigada, havia lido já e por isso entendi melhor. Só que quando abro esse arquivo no AF da um erro dizendo que a versão que ele foi feito é superior ao que tenho que é CS4. Aí queria ver com você como que faço para converter esse arquivo para abrir com o AF inferior ou se é possível abrir com outro tipo de programa, aí só mudo no código.

**Comment by hebertlima** [comment]
@C-Miriane pelo que procurei, (no site da adobe)[https://forums.adobe.com/thread/1409267] só é possível uma conversão do cs6 para o cs5 via próprio after effects ou através de plugins, nesse vc tem algumas alternativas, baixar o AF6 ou AF 2019 (cc), usar o ffmpeg (tem uma pr dessa implementação aqui no git) ou avconv

**Comment by C-Miriane** [comment]
Obrigada @hebertlima , vou tentar baixar o AF6 primeiro e substituir o Template por esse outro (https://github.com/filipedeschamps/video-maker/issues/133#issuecomment-485456742) vc acha que da certo daí ou precisa instalar mais alguma coisas?

**Comment by hebertlima** [comment]
@C-Miriane sim, fica mais se você usar a mesma versão que o filipe indica, acredito que o seu único problema é justamente configurar o AF, resolvendo isso vai conseguir rodar o projeto

**Comment by C-Miriane** [comment]
@hebertlima Agradeço pela ajuda, mas tentei diversas formas só que a máquina que estou usando é 32 bits e não consigo instalar o AF6. Acabei baixando o ffmeg (conforme indicou) mas ao clicar no aplicativo, só aparece uma tela preta e fecha no mesmo momento...talvez até é normal isso. Vou tentar assistir uns vídeos no Youtube para ver como ele funciona e como tenho que configurar. Quanto a essa implementação com ele aqui no GIT, é só copiar e alterar né?

**Comment by hebertlima** [comment]
@C-Miriane dauma olhada nessa #152 acho que vai te ajudar

**Comment by C-Miriane** [comment]
Obrigada @hebertlima estou tentando ver se consigo usar essa opção pq agora esta dando erro de Token ou algo do tipo. Aí escrevi lá para ver se sabem dizer que erro é esse.

**Comment by 8uch3ch4** [comment]
> > @C-Miriane ele fez e renderizou o vídeo?
> > Você configurou no After Effects?
> > Se o After Effects não estiver configurado, abra ele e altere o local de salvamento após a renderização do vídeo:
> > ![image](https://user-images.githubusercontent.com/48515934/57534626-d914bb00-7316-11e9-82b5-c2230a8a097d.png)
> 
> você checou isso?

@hebertlima 

bom dia amigo, não estou conseguindo achar isso. 
![erro1](https://user-images.githubusercontent.com/50780009/58100675-7b089300-7bb4-11e9-9b21-96aaf5d04454.png)


estou com esse erro, acredito que seja o caminho tbm.
