### ISSUE TITLE
t> > > Estou com esse erro, alguém pode ajudar?

### ISSUE THREAD

**Issue by C-Miriane** [filipedeschamps/video-maker#169]
> > > Estou com esse erro, alguém pode ajudar?
> > > PS C:\Users\HP\desktop\testes\video-maker> node index.js
> > > internal/modules/cjs/loader.js:584
> > > throw err;
> > > ^
> > > Error: Cannot find module '../credentials/algorithmia.json'
> > > at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
> > > at Function.Module._load (internal/modules/cjs/loader.js:508:25)
> > > at Module.require (internal/modules/cjs/loader.js:637:17)
> > > at require (internal/modules/cjs/helpers.js:22:18)
> > > at Object. (C:\Users\HP\desktop\testes\video-maker\robots\text.js:2:27)
> > > at Module._compile (internal/modules/cjs/loader.js:701:30)
> > > at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> > > at Module.load (internal/modules/cjs/loader.js:600:32)
> > > at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> > > at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> > 
> > 
> > Bom dia, @C-Miriane ,
> > Acredito que você esteja tentando rodar o projeto pronto, nesse caso é necessário criar uma conta no Algorithmia e criar esse arquivo "algorithmia.json" com a ApiKey da sua conta.
> > Tem esse passo a passo explicando tudo #89 , (parabéns ao @hebertlima criador desse material).
> > qualquer coisa, sigo à disposição.
> 
> Obrigada pela atenção em responder fernandadagostin. Infelizmente já segui o passo a passo e refiz tudo novamente quando apareceu o erro na primeira vez, mas o problema persiste.

Oi, consegui replicar seu erro aqui. 
Verifica os itens abaixo:
- Nome da pasta "credentials"
- Nome do arquivo "algorithmia.json"
- No arquivo robot/text.js, const algorithmiaApiKey = require('../**credentials/algorithmia.json**') essa informação precisa ser extamente o nome do arquivo na pasta. 

Obs.: Acredito que tenha algum erro de sintaxe em algum desses pontos, dessa forma o programa não acha o arquivo, ocasionando o erro. 

qualquer coisa, sigo à disposição. =D

_Originally posted by @fernandadagostin in https://github.com/filipedeschamps/video-maker/issues/87#issuecomment-490547519_

**Comment by 8uch3ch4** [comment]
bom dia, estou com o mesmo erro. 

pode me esclarecer melhor a resposta Fernanda

**Comment by hebertlima** [comment]
> 
> 
> bom dia, estou com o mesmo erro.
> 
> pode me esclarecer melhor a resposta Fernanda

ola @8uch3ch4 fica mais facil te ajudar se você colocar a mensagem de erro que apareceu pra você, mas caso seja a mesma basta seguir esses passos:

- Nome da pasta "credentials"
-  Nome do arquivo "algorithmia.json"
- No arquivo robot/text.js, const algorithmiaApiKey = require('../credentials/algorithmia.json') essa informação precisa ser extamente o nome do arquivo na pasta.

**Comment by 8uch3ch4** [comment]
Olá @hebertlima 

 segue o erro, mas tentei fazer os passos, mas como sou novo na programação, 
não compreendi os passo que a fernanda passou,  


S C:\Users\Usuario\video-maker> node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Usuario\video-maker\robots\text.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PS C:\Users\Usuario\video-maker>



const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey

const algorithmiaApiKey = require('../devo alterar o nome todo?').apiKey

**Comment by fernandadagostin** [comment]
Bom dia @8uch3ch4, 

Tranquilo. 

Quando indicamos um caminho como nessa linha:
**const algorithmiaApiKey = require('../credentials/algorithmia.json')**

estamos dizendo que, dentro da pasta do programa, existe uma pasta chamada **credentials** e que dentro desta pasta existe o arquivo **algorithmia.json**, porém, se ao criar o arquivo tivermos um erro de digitação e o arquivo for criado com o nome **algorthmia.json** (sem o i depois do r, ou seja, diferente do indicado no programa) ao executar o programa o sistema não encontrará o arquivo **algorithmia.json** (com o i) pois o arquivo existente possui nome diferente.

Simplificando, se o arquivo .json criado na pasta não tiver exatamente o mesmo nome indicado no programa, o sistema não tem como encontra-lo. É como enviar uma correspondência para o endereço errado, a correspondência não irá chegar.

Nesse cenário o sistema vai gerar o Erro: 
**Cannot find module '../credentials/algorithmia.json'** (que pode ser traduzido para Não foi possivel encontrar o módulo '../credentials/algorithmia.json')

Para resolver, verrfique os itens abaixo:
- Nome da pasta "credentials"
- Nome do arquivo "algorithmia.json"
- No arquivo robot/text.js, const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey essa informação precisa ser extamente o nome do arquivo na pasta.
- No arquivo "algorithmia.json" a palavra **apiKey** precisa estar igual ao indicado no arquivo robot/text.js, const algorithmiaApiKey = require('../credentials/algorithmia.json').**apiKey **

Espero ter ajudado e se ainda tiver alguma dúvida, pode mandar.

**Comment by 8uch3ch4** [comment]
@fernandadagostin 

peço mil perdoes, mas ainda não conseguir compreender,

1° nome das pasta estão Iguais, 
2° nome do arquivos estão iguais. 

3° ai que mora o não entendimento. me desculpe novamente, (sou muito iniciante)

Robot/teste : const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')

Pasta: credentials/algorithmia.json
{
  " .apiKey ": "simb9MOkrB6ddUOepecel+eRjLX1"
}

MUITO OBRIGADO PELA ATENÇÃO

**Comment by fernandadagostin** [comment]
@8uch3ch4 

acredito que é o **.**  na frente do apiKey
{
" apiKey ": "sua key aqui"
}

Obs.: Edita o comentário e apaga sua Key.

**Comment by 8uch3ch4** [comment]
@fernandadagostin 
   ainda está com o mesmo erro 

PS C:\Users\Usuario\video-maker> node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Usuario\video-maker\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PS C:\Users\Usuario\video-maker>

sera que não e o caminho ainda minha pasta está localizada

C:\Users\Usuario\video-maker\credentials

**Comment by hebertlima** [comment]
> 
> 
> @fernandadagostin
> ainda está com o mesmo erro
> 
> PS C:\Users\Usuario\video-maker> node index.js
> internal/modules/cjs/loader.js:584
> throw err;
> ^
> 
> Error: Cannot find module '../credentials/algorithmia.json'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
> at Function.Module._load (internal/modules/cjs/loader.js:508:25)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (C:\Users\Usuario\video-maker\robots\text.js:2:27)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> PS C:\Users\Usuario\video-maker>
> 
> sera que não e o caminho ainda minha pasta está localizada
> 
> C:\Users\Usuario\video-maker\credentials

sua **algorithmia.json** deve se parecer com isso:
```js
{
   "apiKey" : "chave_aqui"
}
```
Ps. sem espaços entre a palavra apiKey e as aspas `"apiKey"`

**Comment by 8uch3ch4** [comment]
@hebertlima @fernandadagostin 
![erro1](https://user-images.githubusercontent.com/50780009/58037522-fc541d00-7b03-11e9-9c41-0fdeb84bc0d1.png)
![erro2](https://user-images.githubusercontent.com/50780009/58037523-fc541d00-7b03-11e9-8b1d-264ae15e3876.png)
![erro3](https://user-images.githubusercontent.com/50780009/58037524-fc541d00-7b03-11e9-8676-17a51593d53d.png)




acho que vou ter que começar tudo de novo. 
ainda esta com erro.

**Comment by fernandadagostin** [comment]
Não vamos desistir! rs @8uch3ch4 

lembra se foi executado o comando:
`npm i algorithmia`
esse comando faz a instalação da biblioteca do algorithmia
Não achei problema na sintaxe.

**Comment by 8uch3ch4** [comment]
não tinha estalado, acabei de executar

PS C:\Users\Usuario\video-maker> npm i algorithmia
+ algorithmia@0.3.10
updated 1 package and audited 581 packages in 4.375s
found 0 vulnerabilities

Mesmo Erro

**Comment by fernandadagostin** [comment]
@8uch3ch4 
Vê se o erro agora não é em outro arquivo?
Acho que vai dar na biblioteca do watson agora, pois também é necessário instalar a biblioteca.

**Comment by 8uch3ch4** [comment]
PS C:\Users\Usuario\video-maker> npm i algorithmia
+ algorithmia@0.3.10
updated 1 package and audited 581 packages in 4.375s
found 0 vulnerabilities

PS C:\Users\Usuario\video-maker> node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Usuario\video-maker\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by fernandadagostin** [comment]
@8uch3ch4 
vou começar a rezar rs
me manda email nanda.dagostin@gmail.com

**Comment by 8uch3ch4** [comment]
kkkkkk tbm acho. enviado

**Comment by luisfn** [comment]
Me parece problema com o caminho do seu arquivo. Infelizmente, nao sei como caminhos relativos se comportam no windows (esse ../), mas tente fazer isso:

Altere de 

`const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey`

para

`const algorithmiaApiKey = require('C:\Users\Usuario\video-maker\credentials\algorithmia.json').apiKey`

ou se quiser apenas passar desse erro por enquanto, use sua chave diretamente (nao recomendado)

`const algorithmiaApiKey = 'minhachaveaqui'`

**Comment by hebertlima** [comment]
> 
> 
> @fernandadagostin
> 
> não tinha estalado, acabei de executar
> 
> PS C:\Users\Usuario\video-maker> npm i algorithmia
> 
>     * algorithmia@0.3.10
>       updated 1 package and audited 581 packages in 4.375s
>       found 0 vulnerabilities
> 
> 
> Mesmo Erro
> 
> Instalado Visual Studio Code

se vc precisou dar `npm i algorithmia`, certifique-se que vc esta com todos os modulos instalado, execute `npm install` porque na verdade quando clonou o projeto todos os pacotes já deveriam estar instalados

**Comment by hebertlima** [comment]
> 
> 
> Me parece problema com o caminho do seu arquivo. Infelizmente, nao sei como caminhos relativos se comportam no windows (esse ../), mas tente fazer isso:
> 
> Altere de
> 
> `const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey`
> 
> para
> 
> `const algorithmiaApiKey = require('C:\Users\Usuario\video-maker\credentials\algorithmia.json').apiKey`
> 
> ou se quiser apenas passar desse erro por enquanto, use sua chave diretamente (nao recomendado)
> 
> `const algorithmiaApiKey = 'minhachaveaqui'`

não recomendaria ele fazer isso não, a forma como ele esta chamando os arquivos no windows `../` esta correta, acredito que o problema seja mesmo o módulo que não estava instalado

**Comment by 8uch3ch4** [comment]
Boa tarde Galera, 

@fernandadagostin  conseguir me ajudar, os Tipos dos Arquivos estavam com a extensão erradas. como não estava usando os programas certos para ver os arquivos, ficou todos como .txt 

não estavam sendo lidos corretamente.

**Comment by luisfn** [comment]
Se o erro continua sendo `Error: Cannot find module '../credentials/algorithmia.json'` com certeza nao esta encontrando o arquivo com as credenciais por alguma razao. A mensagem em si nao se refere a outros modulos (instalados ou nao)

Eu consigo simular exatamente a mesma mensagem quando o caminho esta de alguma forma incorreto (no caso meu arquivo nao existe):

`Error: Cannot find module '../credentials/algorithmia.json'
Require stack:
/Users/luis/Projects/node/video-maker/robots/text.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)`

**Comment by fernandadagostin** [comment]
@hebertlima, @luisfn, @8uch3ch4 
Conseguimos descobrir o problema, era pegadinha do Windows.

Os arquivos da pasta credencials foram criado usando o notepad.exe e mesmo salvando os arquivos com a extensão .json o notepad estava adicionando a extensão .txt, daí a pegadinha, como por padrão a configuração de pastas do windows esconde extensões conhecidas o arquivo na pasta era demonstrado como "algorithmia.json" porém na realidade o arquivo era "algorithmia.json.txt". (Estavamos a ponto de chamar o padre Quevedo, lol)
Ao tirarmos o ".txt" funcionou! 

Segue o conselho de usar o Visual Studio Code, foi com esse programa que percebi o que estava acontecendo.

**Comment by hebertlima** [comment]
@fernandadagostin eu já estava duvidando da minha pouca capacidade de programar 😂😅
