### ISSUE TITLE
De fato temos alguma solução para a língua portuguesa?

### ISSUE THREAD

**Issue by tassomuniz** [filipedeschamps/video-maker#172]
Fala galera tudo bom?
De fato alguém conseguiu resolver e deixar estável a questão de fazer os videos em português?

**Comment by FelippeChemello** [comment]
Sim, basta alterar o input do algorithmia.
Exemplo: 
https://www.youtube.com/watch?v=soR5nbGWLsU
só efetuar a alteração a baixo:
`async function fetchContentFromWikipedia(content) {
    console.log('> [text-robot] Fetching content from Wikipedia')
    var input = {
      "articleName": content.searchTerm,
      "lang": "pt"
    };`

**Comment by tassomuniz** [comment]
Sou novato, você consegue me explicar melhor? onde essa função está sendo declarada? não encontrei no input.js

**Comment by VinyciusC** [comment]
@felipemarchi você diz no arquivo `text.js` nessa parte?
`async function fetchContentFromWikipedia(content) {`

**Comment by tassomuniz** [comment]
Consegui!!!! Vlw

**Comment by VinyciusC** [comment]
@tassomuniz é ali onde eu falei mesmo? É necessário remover parte do código ou só coloco o que o @FelippeChemello disse?

**Comment by VinyciusC** [comment]
Pra quem vier aqui e quiser arrumar, como ambos de cima não apresentaram o código anterior, esterei mostrando a seguir:

Em `text.js` altere a linha: 
`const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)`

Para:
`const wikipediaResponse = await wikipediaAlgorithm.pipe({`

Abaixo disso coloque o seguinte código:
`"articleName": content.searchTerm,`

E abaixo desse anterior coloque esse outro:
`"lang" : "pt"`

Ai basta fechar utilizando:
`})`

Certifique-se que ficou desse modo:
![image](https://user-images.githubusercontent.com/48515934/57540920-3cf1b080-7324-11e9-867d-16dd3d6d5313.png)

E é só rodar o projeto com `index.js`
