### ISSUE TITLE
Alteração do formato de vídeo para mp4

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#173]
Olá, gostaria de saber se é possível alterar o formato, ao invés de `.mov` para por exemplo `.mp4`...

**Comment by hebertlima** [comment]
Ola @VinyciusC o after effects têm poucos codec disponíveis, mp4 não é um deles, é necessário usar outra ferramenta no caso o adobe media encoder, mas tem uma implementação que disponibilizaram aqui no git que utiliza outra ferramenta para renderizar

**Comment by willianbs** [comment]
@VinyciusC Mandei aqui um PR para converter pra MP4 e reduzir o tamanho usando handbrake.js:
https://github.com/filipedeschamps/video-maker/pull/161

**Comment by VinyciusC** [comment]
Obrigado pessoal :)
