### ISSUE TITLE
Problema com vídeo no youtube

### ISSUE THREAD

**Issue by caufom** [filipedeschamps/video-maker#176]
Em todo vídeo que o robô envia para o youtube, o youtube apaga o vídeo e aparece: "Este vídeo é cópia de outro vídeo do youtube.". Alguém sabe como resolver?

**Comment by VinyciusC** [comment]
Já tentou alterar o template do vídeo?

**Comment by caufom** [comment]
Não. Será que não é pq todos os vídeos tem a mesma duração de 1:16 ?

**Comment by luisfn** [comment]
Com certeza nao é a duracao do video, se nao ninguem no youtube poderia ter video com 1:16. Como o script segue o mesmo passo para todos (nada e randomico), as chances de gerar um arquivo identico sao altas, logo vc deve estar criando o mesmo conteudo que outros ja fizeram. Eu recem fiz todo o processo funcionar, fiz um video "what is lego", fez o upload e funcionou normalmente.
