### ISSUE TITLE
Google Trends em Python

### ISSUE THREAD

**Issue by bvrpythondev** [filipedeschamps/video-maker#18]
@filipedeschamps 
Queria somente deixar aqui a minha solução de como pegar a trending do google em python,pois a pouco documentação sobre em português e também mostrar que esse projeto pode ser feito em outras linguagens como python.

```
import codecs
import os
import urllib.request
from xml.etree import ElementTree

url = 'https://trends.google.com/trends/trendingsearches/daily/rss?geo=BR'
keywords_filename = './keywords.txt'
tmp_filename = './keywords_tmp.xml'
urllib.request.urlretrieve(url, tmp_filename)
if os.path.isfile(keywords_filename):
    with open(keywords_filename, 'r') as f:
        old_list = f.read().splitlines()
else:
    old_list = []
tree = ElementTree.parse(tmp_filename)
root = tree.getroot()
fresh_list = [title.text.lower()
              for title in root.iter('title')]
try:
    fresh_list.remove('daily search trends')
except ValueError:
    pass
output = '\n'.join(a for a in list(set(old_list + fresh_list)))
with codecs.open('./keywords.txt', 'w+', "utf-8") as f:
    f.write(output)
os.remove(tmp_filename)

```
Muito Obrigado e Parabéns Filipe por essa iniciativa de criar o projeto
Have fun and Code Forever

**Comment by Fguedes90** [comment]
@bvrpythondev como diria o @filipedeschamps Sensacional! Muito bom encontrar mais pessoas implementando em python.
Também criei uma função para buscar os trend topics do google, segue a baixo a versão que fiz.

```
import feedparser

def searchGoogleTrendTopics(geo = 'BR',period = 'daily'):
    # Return a array with with google's trend topics titles
    searchUrl = 'https://trends.google.com/trends/trendingsearches/'+period+'/rss?geo='+geo
    googleTrendsTitles=[]
    feed = feedparser.parse(searchUrl)
    googleTrendsTitles.append([feed.entries[i].title for i in range(len(feed.entries))])
    return googleTrendsTitles
```

**Comment by bvrpythondev** [comment]
Realmente é muito bacana ver pessoas implementando em python.Que ótimo que está compartilhando sua função ficou realmente boa parabéns. Have fun and code forever meu amigo

**Comment by lucianopf** [comment]
Boa tarde @bvrpythondev, blz?
Topa criar um PR que chama um script em python? 🤔 

No node a gnt consegue dar spawn em outros processos e com isso da pra fazer interop de langs 😬 

Mesmo sendo um overhead acho que uma implementaçãozinha dessa iria no mínimo abrir a cabeça de uma boa parte da galera aqui! 

cc: @filipedeschamps

**Comment by bvrpythondev** [comment]
Boa noite @lucianopf tudo bem e com vc?

Acredito que seria uma boa ideia, como diria o @filipedeschamps Sensacional 👏👍

Realmente iria abir a mente de muitas pessoas concordo 100% lets go implementar

**Comment by eliaskill** [comment]
esse video-maker em python seria muito legal!

**Comment by danielschmitz** [comment]
Conforme já estamos agitando em #77, no readme do projeto futuro, iremos inserir o link dos repos do video-maker em outras linguagens.
