### ISSUE TITLE
Erro ao renderizar

### ISSUE THREAD

**Issue by Cyberx9901** [filipedeschamps/video-maker#183]
> [video-robot] YouTube thumbnail created
> [video-robot] Starting After Effects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hebertlima** [comment]
@Cyberx9901 você tem o **After Effects** Instalado? se sim, no seu arquivo **videos.ts** procure a variavel **aerenderFilePath** vai estar assim:
```js
aerenderFilePath = '/Applications/Adobe After Effects CC 2019/aerender'
```
você precisa mudar e apontar a instalação do seu **aerender.exe** dentro da pasta que esta instlado o After Effects, o meu ficou assim ex:
```js
aerenderFilePath = 'C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'
```
se você usa windows e esta usando o After Effects CC e fez a instalação padrão, talves seja um caminho parecido, caso não basta apontar onde esta o **aerender.exe**

**Comment by Cyberx9901** [comment]
Uso Ubuntu, tem alguma maneira de não usar o After Effects para isso? ou uma maneira de instalar o mesmo no Ubuntu?

**Comment by hebertlima** [comment]
você pode tentar usar o [ffmeg](https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/) tem uma implementação aqui #152 eu particularmente nunca usei, mas acredito que nessa mesma pr a gelera pode te ajudar

**Comment by als260502** [comment]
Peguei o template do felipe pq nao entendo nada de AE, quando rodo o node com ele vai renderizando e no final da um erro pq ele ta tentando procurar os arquivos que estao configurados no template do felipe
ai da erro, alguem me ajuda conte eu mudo isso
PROGRESS:  19/07/2019 21:36:42: composi��o conclu�da main.
PROGRESS:  Tempo total decorrido: 1 min, 10 s
WARNING:Aviso do After Effects: registrado um erro  "Erro do After Effects: N�o � poss�vel r**enderizar: arquivo /Users/filipedeschamps/video-maker/content/0-sentence.png n�o localizado"**
LoadLibrary "n" failed!
LoadLibrary "n" failed!
After effectsc closed

**Comment by hebertlima** [comment]
@als260502  você esta apontando para o diretório errado ** /Users/filipedeschamps/video-maker/content/0-sentence.png**

**Comment by jeronimojbarbosa** [comment]
@hebertlima vc teve problema com o template? Por ele ter sido salvo exclusivamente para MACOS, estou com problemas pra uso no Windows.

**Comment by MatheusRV** [comment]
Resolvido com #167
