### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by CirosBlack** [filipedeschamps/video-maker#184]
olá amigos sou bem iniciante, segui o passo a passo inicial e instalei o "Git" e o "Node"
e segui os seguintes comandos

git clone https://github.com/filipedeschamps/video-maker.git
cd video-maker
npm install

porem segue o erro:

> websocket@1.0.28 install C:\Users\CirosBlack\Desktop\YoutubeMaker\video-maker\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\CirosBlack\Desktop\YoutubeMaker\video-maker\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

poderiam me explicar oque houve?

**Comment by VictorCampelo** [comment]
npm install -g node-gyp

Execute antes do npm install.

**Comment by MatheusRV** [comment]
@CirosBlack Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando por inatividade, reabra em caso de mais informações.
