### ISSUE TITLE
Erro Robo de Video

### ISSUE THREAD

**Issue by felipealfah** [filipedeschamps/video-maker#188]
Pessoal ao rodar o robo no meu pc ele apresenta o seguintes erros!!
O erro aqui acredito que é no Robo de videos, ele consegue baixar as imagens, porém ao dar o start no robo do vídeo ele tras os seguintes erros.

[video-robot] Starting...
(node:2812) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

    at ChildProcess.onExit (C:\Users\Felipe\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (C:\Users\Felipe\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:2812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
Olá, reinstala o imagemagick e marca essa opção:
[!image](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSvn_kDV1aTYz87cXxN517GgomU76GiX8f3dKocIpM5eHFSTKLl)

**Comment by felipealfah** [comment]
Refiz a instalação do jeito que vc me falou e mesmo assim não funcionou, continua o mesmo erro!!

**Comment by felipealfah** [comment]
@hebertlima Na verdade não tinha instalado o ImageMagick, dai depois que vc me falou eu fiz a instalação no pc de acordo com o que me passou na imagem anterior, não funcionou, dai eu dei o seguinte comando "npm install imagemagick", por talvez faltar alguma instancia, mas também não funcionou, continua no mesmo erro!

**Comment by hebertlima** [comment]
> 
> 
> @hebertlima Na verdade não tinha instalado o ImageMagick, dai depois que vc me falou eu fiz a instalação no pc de acordo com o que me passou na imagem anterior, não funcionou, dai eu dei o seguinte comando "npm install imagemagick", por talvez faltar alguma instância, mas também não funcionou, continua no mesmo erro!

tem que verificar qual é a nova msg de erro, essa msg aqui: `(node:2812) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
` é causado porque no Windows existe uma lib com o comando `convert` e da conflito com o `convert` do ImageMagick, quando você habilita a instalação Legacy o instalador corrige o path de chamada do `convert` para evitar o conflito, se você habilitou a opção durante a instalação, abre seu cmd e digita:
```bash
convert -version
```
tem que aparecer algo que começa assim:
`Version: ImageMagick 7.0.8-43 Q16 x64 2019-05-02 http://www.imagemagick.org`

se aparecer assim, o erro foi corrigido, precisa ver qual é o novo erro 😃

**Comment by felipealfah** [comment]
@hebertlima deu certo!!!! Fiz as outras Alterações e só precisava dar um reset no CMD, para funcionar já rodei!! Valeu!!!

**Comment by hebertlima** [comment]
show!! agora só fecha a issue e boa sorte!

**Comment by ryangalvaogp** [comment]
Olá, tudo bem? Eu estou com o mesmo problema só que eu fiz tudo que o herbet fez, porém não deu certo.
O que você fez Felipe? me explica por favor?

**Comment by fparmezani** [comment]
Oi Amigos,   vi os comentários acima e acinda continuo com este problema
a mensagem de erro é 
(node:16308) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido

Instalei como informado acima,  "e.g. convert"

Quando digito a opção   convert -version  recebo a mensagem

Especificação de unidade inválida.

Alguma ajuda?

**Comment by hebertlima** [comment]
> Oi Amigos, vi os comentários acima e ainda continuo com este problema
> a mensagem de erro é
> 
> (node:16308) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido
> 
> Instalei como informado acima, "e.g. convert"
> 
> Quando digito a opção convert -version recebo a mensagem
> 
> Especificação de unidade inválida.
> 
> Alguma ajuda?

Olá,
Se ao digitar `convert -version` no console você resta recebendo uma mensagem diferente da que citei no post, certamente a instalação foi feita errada, tenta refazer a instalação do imagemagick marcando as opções como na imagem, feche o `CMD` e reinicie a maquina, e tente executar o comando `convert -version`, o output preicsa ser exatamente esse:

```cmd
Version: ImageMagick 7.0.8-43 Q16 x64 2019-05-02 http://www.imagemagick.org
```
se não esta saindo esse output, sua instalação continua errada, será necessário revisar a instalação do ImageMagick.
