### ISSUE TITLE
Erro: IBM Watson Credentials

### ISSUE THREAD

**Issue by alangodoi** [filipedeschamps/video-maker#189]
Iniciei ontem e estou seguindo os vídeos dos robôs.

Na parte de integrar com o IBM Watson está ocorrendo um erro e não estou conseguindo resolver.

## Erro
```
/home/alan/projetos/robot/node_modules/ibm-cloud-sdk-core/lib/base_service.js:244
                throw new Error(errorMessage);
                ^

Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password and iam_access_token.
    at NaturalLanguageUnderstandingV1.BaseService.initCredentials (/home/alan/projetos/robot/node_modules/ibm-cloud-sdk-core/lib/base_service.js:244:23)
    at NaturalLanguageUnderstandingV1.BaseService (/home/alan/projetos/robot/node_modules/ibm-cloud-sdk-core/lib/base_service.js:95:29)
    at new NaturalLanguageUnderstandingV1 (/home/alan/projetos/robot/node_modules/ibm-watson/natural-language-understanding/v1.js:57:28)
    at Object.<anonymous> (/home/alan/projetos/robot/robots/text.js:18:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

Já vi e revi os vídeos, fiz e refiz o código e inclusive copiei o código daqui, sempre com o mesmo erro.

## watson-nlu.json
```json
{
  "apikey": "API KEY",
  "iam_apikey_description": "Auto-generated for key b69636f6-f598-43a9-9030-5923af533d6d",
  "iam_apikey_name": "Auto-generated service credentials",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ba7b9a30726d44ad8d474a897b3e1f13::serviceid:ServiceId-0416378c-06d2-4a0f-bff5-d6963228bef3",
  "url": "https://gateway-wdc.watsonplatform.net/natural-language-understanding/api"
}
```

## text.js
```js
const watsonCredentials = require('../credentials/watson-nlu.json')
const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1.js')

const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonCredentials.apiKey,
  version: '2018-04-05',
  url: "https://gateway.watsonplatform.net/natural-language-understanding/api"
})
```

Também tentei assim (pegando a url do `watson-nlu.json`)
```js
const watsonCredentials = require('../credentials/watson-nlu.json')
const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1.js')

const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonCredentials.apiKey,
  version: '2018-11-16',
  url: watsonCredentials.url
})
```

Preciso de uma ajudinha :)

**Comment by danielschmitz** [comment]
"apikey": "API KEY",

vc configurou sua api cnoforme https://github.com/filipedeschamps/video-maker#api-watson

**Comment by alangodoi** [comment]
@danielschmitz Sim, fiz igualzinho. A única diferença com os vídeos, é que na hora de de instalar o **Watson**, foi necessário usar a versão 

> ibm-watson

 ao invés de 

> watson-developer-cloud

Pq já está em uma versão mais atual, porém acredito que não faria diferença. Também clonei o repositório e executei o `npm install`, mesmo erro.

**Comment by hebertlima** [comment]
muda 
``` diff
- const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1.js')
+ const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js')
```

**Comment by alangodoi** [comment]
@hebertlima Já fiz isso e não funciona. Como expliquei, na versão mais nova o nome é diferente. Também clonei o projeto e não funciona.

**Comment by vaso991** [comment]
change url in text.js to: https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2018-11-16

**Comment by alangodoi** [comment]
@vaso991 Same thing. Invalid Credentials.

**Comment by vaso991** [comment]
@alangodoi did you changed url in watson-nlu.json too?

**Comment by alangodoi** [comment]
@vaso991 Yes, Invalid Credentials. I've also generated a new api key and the same error occurs.

**Comment by alangodoi** [comment]
Finally, I did it.

From @vaso991 tip. 

Go to IBM Cloud and generate a new api key (London server in my case), copy to `watson-nlu.json`
```json
{
  "apikey": "API KEY",
  "iam_apikey_description": "Auto-generated for key b5b1b2d7-6bec-4b5f-974d-dab3c17b66bb",
  "iam_apikey_name": "Service credentials-1",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ba7b9a30726d44ad8d474a897b3e1f13::serviceid:ServiceId-fd55df16-8334-404d-83cb-b84679bb5c5d",
  "url": "https://gateway-lon.watsonplatform.net/natural-language-understanding/api"
}
```

> `watson-nlu.json` url and `text.js` url are different


### text.js

```js
const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: "API KEY",
  version: '2018-11-16',
  url: "https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?"
})
```

This URL didn't worked for me. 

> [https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2018-11-16](https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2018-11-16)

The `version` is needed to be passed as parameter and removed from `url
> [https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?](https://gateway-lon.watsonplatform.net/natural-language-understanding/api/v1/analyze?)

Working. Thank you!

**Comment by erickkaiquesilva** [comment]
@alangodoi , cara voce conseguiu ja resolver este problema, estou com o mesmo, e ainda não encontrei uma solução.

**Comment by joaogabrielpancheski** [comment]
@erickkaiquesilva como está o seu text.js?

**Comment by alangodoi** [comment]
@erickkaiquesilva para mim o problema era a URL no text.js, a URL utilizada nos vídeos não funcionava. Detalhei o que fiz aí em cima.

**Comment by tambosi** [comment]
@erickkaiquesilva tive o mesmo problema e no meu caso foi a linha abaixo:
const watsonApiKey = require('../credentials/watson-nlu.json').apikey;

a palavra apikey no video do Filipe está com a letra k maiuscula e copiando da ibm o k está minúsculo. Deixe o k minúsculo que deve funcionar.

**Comment by AlvaroJr10** [comment]
Time exatamente o mesmo problema com o `K` e o `k`, tudo certo agora!

**Comment by renansjs** [comment]
Boa noite galera, também travei nesse erro, o problema é realmente na URL, você tem usar a URL da sua autenticação, a URL que vem no exemplo do github não funciona.

**Comment by Lorhan7** [comment]
a URL mudou se eu não me engano, agora é essa " https://gateway.watsonplatform.net/natural-language-understanding/api/ " 
mas qualquer coisa visita o site do npm [aqui](https://www.npmjs.com/package/ibm-watson) e pesquisa sobre o **Natural Language Understanding**;

mas adiantando deve ficar mais ou menos assim:

```js
const watsonApiKey = require('../credentials/watson-nlu.json').apikey;


const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');

const nlu = new NaturalLanguageUnderstandingV1({
  authenticator: new IamAuthenticator({ apikey: watsonApiKey }),
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

```

**Comment by ralmeidax** [comment]
Também estava com problema. Um deles era o "k" de apikey, que no meu caso estava errado, com o "K" maiúsculo.

No meu caso funcionando ficou assim: 

```
const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js')

const nlu = new NaturalLanguageUnderstandingV1({
    username: 'myusername@example.com',
    password: 'mypassword',
    iam_apikey: watsonApiKey,
    version: '2020-04-04',
    url: "https://api.eu-gb.natural-language-understanding.watson.cloud.ibm.com/instances/430e9757-f4d0-40b0-b8fd-f665a274c6c9",
  })
```

Desta forma, funcionou! Gostaria de agradecer a todos acima, e em especial a Filipe Deschamps

**Comment by fabriciocunhauk** [comment]
Também estava tendo o mesmo erro troquei o K do apiKey para k apikei e nada, mas quando troquei o k do iam_apikey: watsonApiKey, dai deu certo.
