### ISSUE TITLE
(node:20848) UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by 8uch3ch4** [filipedeschamps/video-maker#190]
Bom dia Galera, Não conseguir achar esse erro aqui na comunidade, alguém consegue me dar uma força. 

Está rodando tudo perfeito até essa parte, o script já consegue criar o arquivo .mov completo. 
Mas chega nessa parta acontece isso.
![erro1](https://user-images.githubusercontent.com/50780009/58098662-73df8600-7bb0-11e9-80aa-b896c7834f42.png)

o que pode ser?

**Comment by luisfn** [comment]
Vc criou o arquivo `credentials/google-youtube.json`?

Se criou, qual o conteudo dele?

**Comment by 8uch3ch4** [comment]
{"web":{"client_id":"152252111029-m36424fs63f1uljah6faomkjnbn31f0g.apps.googleusercontent.com","project_id":"metal-sky-241202","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"knGVNv3a8zQJKaO-GrHD1beU"}}

**Comment by hebertlima** [comment]
essa key não é do youtube essa ai é do **google-search.json** a do youtube você baixa depois de configurar no google cloud platform, da uma olhada aqui #89 procura por **Api YouTube**

**Comment by 8uch3ch4** [comment]
{"web":{"client_id":"825086505233-nqfprhh4qaft3rneiut950n0kbqlsc3p.apps.googleusercontent.com","project_id":"meu-futuro-241203","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"7iuYGBhvO4VN9jcLbRWKJk3H","redirect_uris":["http://localhost:5000/oauth2callback"],"javascript_origins":["http://localhost:5000"]}}

**Comment by 8uch3ch4** [comment]
{"web":{"client_id":"825086505233-nqfprhh4qaft3rneiut950n0kbqlsc3p.apps.googleusercontent.com","project_id":"video-maker-youtube-241203","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"7iuYGBhvO4VN9jcLbRWKJk3H","redirect_uris":["http://localhost:5000/oauth2callback"],"javascript_origins":["http://localhost:5000"]}}

**Comment by hebertlima** [comment]
> 
> 
> bom dia @hebertlima
> 
> segui os passo do #89, criei tudo certinho lá, fiz os passo da #174 tbm mas ainda o erro continua.
> 
> {"web":{"client_id":"825086505233-nqfprhh4qaft3rneiut950n0kbqlsc3p.apps.googleusercontent.com","project_id":"video-maker-youtube-241203","auth_uri":"[https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"7iuYGBhvO4VN9jcLbRWKJk3H","redirect_uris":["http://localhost:5000/oauth2callback"],"javascript_origins":["http://localhost:5000"]}}](https://accounts.google.com/o/oauth2/auth%22,%22token_uri%22:%22https://oauth2.googleapis.com/token%22,%22auth_provider_x509_cert_url%22:%22https://www.googleapis.com/oauth2/v1/certs%22,%22client_secret%22:%227iuYGBhvO4VN9jcLbRWKJk3H%22,%22redirect_uris%22:%5B%22http://localhost:5000/oauth2callback%22%5D,%22javascript_origins%22:%5B%22http://localhost:5000%22%5D%7D%7D)

o nome esta correto? **google-youtube.json** verifica se a real extenção do arquivo é **.json** e não **.json.txt** e coloca  a nova msg de erro pra vermos o que aconteceu 😃

**Comment by 8uch3ch4** [comment]
Boa tarde @hebertlima 

Obrigado pela ajuda, mas era erro de . e virgulas, agora estou tentando deixar ele com tradução. 

Obrigado a ajuda de todos envolvidos.
