### ISSUE TITLE
Problemas, não estou conseguindo importar os resultados para as KeyWords Sempre aparece um erro ao tentar preencher as funções da Key em cada sentença

### ISSUE THREAD

**Issue by yurimedeiros** [filipedeschamps/video-maker#191]
Olá estou com problemas, não estou conseguindo importar os resultados para as KeyWords
Sempre aparece um erro ao tentar preencher as funções da Key em cada sentença, Help-me

Codigo text.js

"""

const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')

const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js')
 
var nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
})

async function robot(content) {
	await fetchContentFromWikipedia(content)
	sanitizeContent(content)
	breakContentIntoSentences(content)
	limitMaximumSentences(content)
	await fetchkeywordsOfAllSentences(content)

	async function fetchContentFromWikipedia(content) {
		const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
		const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
		const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
		const wikipediaContent = wikipediaResponse.get()
		
		content.sourceContentOriginal = wikipediaContent.content	
	}

	function sanitizeContent(content) {
		const withoutBlankLinesAndMarkdown = removeBlankLinesAndMarkdown(content.sourceContentOriginal)
		const withoutDatesInParentheses = removeDatesInParentheses(withoutBlankLinesAndMarkdown)

		content.sourceContentSanitized = withoutDatesInParentheses

		function removeBlankLinesAndMarkdown(text) {
			const allLines = text.split('\n')
			
			const withoutBlankLinesAndMarkdown = allLines.filter((line) => {
				if (line.trim().length === 0 || line.trim().startsWith('=')) {
					return false
				}

				return true
				})
			
			return withoutBlankLinesAndMarkdown.join(' ')
		}
	}

	function removeDatesInParentheses(text) {
			return text.replace(/\((?:\([^()]*\)|[^()])*\)/gm, '').replace(/  /g,' ')
		}
	function breakContentIntoSentences(content) {
		content.sentences = []

		const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
		sentences.forEach((sentence) => {
			content.sentences.push({
				text: sentence,
				keywords: [],
				images: []
			})
		})

	}

	function limitMaximumSentences(content) {
		content.sentences = content.sentences.slice(0, content.maximumSentences)
	}

	async function fetchkeywordsOfAllSentences(content) {
			for (const sentence of content.sentences) {
				sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)
			}
		}

	async function fetchWatsonAndReturnKeywords(sentence) {
		return new Promise((resolve, reject) => {
			nlu.analyze({
			text: sentence,
			features: {
			  keywords: {}
		  }
	  	}, (error, response) => {
	  	if (error) {
	  		throw error
	  	}

	  	const keywords = response.keywords.map((keywords) => {
	  	return keyword.text
	  	})

		resolve(keywords)
		})
	})
}

}
module.exports = robot

""""

Nesta parte pude perceber que quando tiro o async/await ele funciona, mas não execulta a função de gerar as keyswords.

'''
async function fetchkeywordsOfAllSentences(content) {
			for (const sentence of content.sentences) {
				sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)
''

Este é o ERROR que acontece, quando execulta o codigo de modo normal como esta na tela.

""

$ node index.js
Digite um termo de pesquisa da Wikipedia: bacon

[1] Quem e
[2] O que e
[3] A historia
[0] CANCEL

Escolha um seguimento de busca [1, 2, 3, 0]: 3
(node:24460) UnhandledPromiseRejectionWarning: Error: keyword is not defined
    at formatError (C:\Users\YuriM\Desktop\Video maker 2\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:111:17)
    at C:\Users\YuriM\Desktop\Video maker 2\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:259:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:24460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). (rejection id: 1)
(node:24460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.

""

**Comment by gmonteeeiro** [comment]
acredito que tu tenha um erro nesse trecho aqui:
```
const keywords = response.keywords.map((keywords) => {
    return keyword.text
})
```

A função anônima tem o parâmetro `keywords`, porém tu tenta usar `keyword`. Tente fazer assim:
```
const keywords = response.keywords.map((keyword) => {
    return keyword.text
})
```

**Comment by MatheusRV** [comment]
Seems related to #225

**Comment by yurimedeiros** [comment]
pessoal muito obrigado, eu consegi finalizar o projeto, conclui todas as etapas, e devo isso a voces por terem me ajudado, neste projeto que para mim parecia uma agulha no oceano, obrigado ao felipe e a toda equipe aqui.

**Comment by leodutra** [comment]
@yurimedeiros show. Se quiser ajudar, temos enhancements a fazer.
Ficaria feliz de poder ajudar e evoluir revisando as colaborações.
