### ISSUE TITLE
Erro no robo de video

### ISSUE THREAD

**Issue by denismarden** [filipedeschamps/video-maker#195]
> [image-robot] [5][0] Image successfully downloaded: http://www.zonu.com/imapa/americas/small/Mapa_Ciudades_Brasil.jpg
> [image-robot] [6][0] Image successfully downloaded: http://www.worldatlas.com/webimage/countrys/samerica/brsa.gif
> [video-robot] Starting...
(node:7548) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

    at ChildProcess.onExit (C:\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (C:\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:7548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Alguem poderia me ajudar não consigo sair daqui estou seguindo o tutorial

**Comment by denismarden** [comment]
Consegui resolver ao reinstalar o imagemagick mas agora deu outro erro...

> [video-robot] YouTube thumbnail created
> [video-robot] Starting After Effects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by luisfn** [comment]
Opa

Que bom que resolveste o primeiro erro. Errors "ENOENT" ocorrem quando o caminho de algum arquivo está errado, no caso, o caminho do Adobe After effects.

O Path para o "AE" está definido no código, e não em uma config, então pode ser que o seu esteja em outro caminho.

1. Verifique se vc já tem o after effects instalado
2. Verifique se o caminho está correto

**Comment by chmenegatti** [comment]
> Consegui resolver ao reinstalar o imagemagick mas agora deu outro erro...
> 
> > [video-robot] YouTube thumbnail created
> > [video-robot] Starting After Effects
> > events.js:174
> > throw er; // Unhandled 'error' event
> > ^
> 
> Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
> at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> at onErrorNT (internal/child_process.js:415:16)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> Emitted 'error' event at:
> at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
> at onErrorNT (internal/child_process.js:415:16)
> at process._tickCallback (internal/process/next_tick.js:63:19)

O Fillipe está usando um MAC para os vídeos.
Quem usa Windows, no meu caso, e está dando erro acima, precisa ajustar a configuração do caminho do aerender. Ex: const aerenderFilePath = '/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'

e tem que especificar o nome do executável, aerender.exe no caso.

**Comment by p3ss1n** [comment]
> > [image-robot] [5][0] Image successfully downloaded: http://www.zonu.com/imapa/americas/small/Mapa_Ciudades_Brasil.jpg
> > [image-robot] [6][0] Image successfully downloaded: http://www.worldatlas.com/webimage/countrys/samerica/brsa.gif
> > [video-robot] Starting...
> > (node:7548) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
> 
> ```
> at ChildProcess.onExit (C:\video-maker\node_modules\gm\lib\command.js:301:17)
> at ChildProcess.emit (events.js:198:13)
> at ChildProcess.cp.emit (C:\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
> at maybeClose (internal/child_process.js:982:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> ```
> 
> (node:7548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:7548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Alguem poderia me ajudar não consigo sair daqui estou seguindo o tutorial

Estou com o mesmo problema. Ja reinstalei o ImageMagick mas não adiantou.

[video-robot] Starting...
(node:5864) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

    at ChildProcess.onExit (vdeo-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

Alguém pode me ajudar? travei nessa parte

**Comment by AlvaroJr10** [comment]
To com o mesmo problema, conseguiu resolver isso? 
O diretorio que passei foi exatamente o mesmo.

**Comment by marceloazh** [comment]
> > [image-robot] [5][0] Image successfully downloaded: http://www.zonu.com/imapa/americas/small/Mapa_Ciudades_Brasil.jpg
> > [image-robot] [6][0] Image successfully downloaded: http://www.worldatlas.com/webimage/countrys/samerica/brsa.gif
> > [video-robot] Starting...
> > (node:7548) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
> 
> ```
> at ChildProcess.onExit (C:\video-maker\node_modules\gm\lib\command.js:301:17)
> at ChildProcess.emit (events.js:198:13)
> at ChildProcess.cp.emit (C:\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
> at maybeClose (internal/child_process.js:982:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> ```
> 
> (node:7548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:7548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Alguem poderia me ajudar não consigo sair daqui estou seguindo o tutorial

Boa noite! Infelizmente

> > Consegui resolver ao reinstalar o imagemagick mas agora deu outro erro...
> > > [video-robot] YouTube thumbnail created
> > > [video-robot] Starting After Effects
> > > events.js:174
> > > throw er; // Unhandled 'error' event
> > > ^
> > 
> > 
> > Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> > at onErrorNT (internal/child_process.js:415:16)
> > at process._tickCallback (internal/process/next_tick.js:63:19)
> > Emitted 'error' event at:
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
> > at onErrorNT (internal/child_process.js:415:16)
> > at process._tickCallback (internal/process/next_tick.js:63:19)
> 
> O Fillipe está usando um MAC para os vídeos.
> Quem usa Windows, no meu caso, e está dando erro acima, precisa ajustar a configuração do caminho do aerender. Ex: const aerenderFilePath = '/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'
> 
> e tem que especificar o nome do executável, aerender.exe no caso.

Boa noite pessoal!
Infelizmente eu não consegui resolver reinstalando o ImageMagick...

Estou recebendo este retorno:

(node:14148) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

    at ChildProcess.onExit (C:\git\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:209:13)
    at ChildProcess.cp.emit (C:\git\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

Alguém poderia me dar uma luz?
Obrigado!!!!

**Comment by marceloazh** [comment]
> > > [image-robot] [5][0] Image successfully downloaded: http://www.zonu.com/imapa/americas/small/Mapa_Ciudades_Brasil.jpg
> > > [image-robot] [6][0] Image successfully downloaded: http://www.worldatlas.com/webimage/countrys/samerica/brsa.gif
> > > [video-robot] Starting...
> > > (node:7548) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
> > 
> > 
> > ```
> > at ChildProcess.onExit (C:\video-maker\node_modules\gm\lib\command.js:301:17)
> > at ChildProcess.emit (events.js:198:13)
> > at ChildProcess.cp.emit (C:\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
> > at maybeClose (internal/child_process.js:982:16)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> > ```
> > 
> > 
> > (node:7548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> > (node:7548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > Alguem poderia me ajudar não consigo sair daqui estou seguindo o tutorial
> 
> > > Consegui resolver ao reinstalar o imagemagick mas agora deu outro erro...
> > > > [video-robot] YouTube thumbnail created
> > > > [video-robot] Starting After Effects
> > > > events.js:174
> > > > throw er; // Unhandled 'error' event
> > > > ^
> > > 
> > > 
> > > Error: spawn /Applications/Adobe After Effects CC 2019/aerender ENOENT
> > > at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
> > > at onErrorNT (internal/child_process.js:415:16)
> > > at process._tickCallback (internal/process/next_tick.js:63:19)
> > > Emitted 'error' event at:
> > > at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
> > > at onErrorNT (internal/child_process.js:415:16)
> > > at process._tickCallback (internal/process/next_tick.js:63:19)
> > 
> > 
> > O Fillipe está usando um MAC para os vídeos.
> > Quem usa Windows, no meu caso, e está dando erro acima, precisa ajustar a configuração do caminho do aerender. Ex: const aerenderFilePath = '/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'
> > e tem que especificar o nome do executável, aerender.exe no caso.
> 
> Boa noite pessoal!
> Infelizmente eu não consegui resolver reinstalando o ImageMagick...
> 
> Estou recebendo este retorno:
> 
> (node:14148) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
> 
> ```
> at ChildProcess.onExit (C:\git\video-maker\node_modules\gm\lib\command.js:301:17)
> at ChildProcess.emit (events.js:209:13)
> at ChildProcess.cp.emit (C:\git\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> ```
> 
> Alguém poderia me dar uma luz?
> Obrigado!!!!

Pessoal, consegui fazer funcionar da mesma forma com que nosso amigo acima conseguiu: reinstalando ImageMagick, GM e tudo relacionado, além de um fusca-in, fusca-out, rs. Tentei novamente hoje, depois de um boot, e... deu certo!

Desculpem a repetição! Abraço!

**Comment by acaciomartins** [comment]
Vocês sabem de alguma alternativa de **Adobe After Effects CC 2019** para Ubuntu?

**Comment by MatheusRV** [comment]
Definitivamente o Natron é a melhor solução ao AE.

**Comment by aitorserra** [comment]
> O Fillipe está usando um MAC para os vídeos.
> Quem usa Windows, no meu caso, e está dando erro acima, precisa ajustar a configuração do caminho do aerender. Ex: const aerenderFilePath = '/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe'
> 
> e tem que especificar o nome do executável, aerender.exe no caso.

It doesn't work for me with:

      }else if (systemPlatform=='win32'){
        const aerenderFilePath = '/Program Files/Adobe/Adobe After Effects 2020/Support Files/aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('./templates/1/template.aep')
      const destinationFilePath = fromRoot('./content/output.mov')
