### ISSUE TITLE
Async Await

### ISSUE THREAD

**Issue by Luanftg** [filipedeschamps/video-maker#197]
Ola, estou com problemas ao utilizar o async await (eu acho).
Estou escrevendo(tentando) o código , do zer, assistindo os videos. Ainda estou no robo de texto. Ja consegui faze-lo me mostrar o searchTerm e o prefix , depois do sourceContentOriginal (uma vez!rs) Mas depois de inserir a parte de limpar o texto , insiro todo o código , mas não tem efeito nenhum para limpar e os itens voltaram a serem mostrados no inicio..por isso pensei em algo relacionado ao async await.
Talvez aqui não seja o melhor lugar para perguntar. Me desculpa se atrapalho.

**Comment by gmonteeeiro** [comment]
Poste teu trecho de código, vai nos facilitar a te ajudar

**Comment by DanielFelizardoDev** [comment]
Mostra a função que está com dificuldade. Fica melhor mostrar pra gente poder te ajudar, onde pode ter acontecido o problema.

**Comment by MatheusRV** [comment]
@Luanftg Friendly Ping

**Comment by leodutra** [comment]
Dúvidas podem ser tiradas no [Discord](https://discord.gg/wawRMu).
Os problemas do GitHub são para problemas e sugestões.

Se encontrou sugestão e ela não está documentada, colabore com o documento README.
Fechando por inatividade.
