### ISSUE TITLE
erro de autorização 

### ISSUE THREAD

**Issue by tiagomoi** [filipedeschamps/video-maker#198]
node index.js
Type a Wikipedia search term: Tiago

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:8528) UnhandledPromiseRejectionWarning: authorization required
(node:8528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
da uma lida no readme do projeto, você precisa criar as credenciais do algorithmia, ibm, youtube etc

**Comment by MatheusRV** [comment]
@tiagomoi Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Dúvidas podem ser tiradas no [Discord](https://discord.gg/wawRMu).
Os problemas do GitHub são para problemas e sugestões.

Se encontrou sugestão e ela não está documentada, colabore com o documento README.
Fechando.
