### ISSUE TITLE
Como criar um pull request?

### ISSUE THREAD

**Issue by Pacheco95** [filipedeschamps/video-maker#20]
Fiz a implementação de automaticamente encontrar os termos usando a API do Google Trends, mas eu não sei utilizar muito bem o git.
Eu criei uma nova branch no repositório clonado e tentei fazer um push dela mas aparece a seguinte mensagem:

```
$ git push origin auto-term-search 
Username for 'https://github.com': Pacheco95
Password for 'https://Pacheco95@github.com': 
remote: Permission to filipedeschamps/video-maker.git denied to Pacheco95.
fatal: unable to access 'https://github.com/filipedeschamps/video-maker.git/': The requested URL returned error: 403

```

Desculpem a minha ignorância quando se trata de utilizar o git de forma colaborativa.

**Comment by pedrosobral** [comment]
Basicamente você não tem acesso ao repositório.

Primeiro você deve fazer um fork deste projeto, clonar o seu fork na sua máquina, fazer as modificações no seu repositório, os commits da vida, etc. Com o seu repositório com as modificações, aí sim você consegue abrir um pull request.

Olha esse tutorial aqui que explica tudo detalhado com imagens:

https://www.digitalocean.com/community/tutorials/como-criar-um-pull-request-no-github-pt

ou do próprio github em inglês: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

Abraço.

**Comment by Pacheco95** [comment]
Deu certinho! Já fiz o pull request! Obrigado!!!

**Comment by glaucia86** [comment]
> Fiz a implementação de automaticamente encontrar os termos usando a API do Google Trends, mas eu não sei utilizar muito bem o git.
> Eu criei uma nova branch no repositório clonado e tentei fazer um push dela mas aparece a seguinte mensagem:
> 
> ```
> $ git push origin auto-term-search 
> Username for 'https://github.com': Pacheco95
> Password for 'https://Pacheco95@github.com': 
> remote: Permission to filipedeschamps/video-maker.git denied to Pacheco95.
> fatal: unable to access 'https://github.com/filipedeschamps/video-maker.git/': The requested URL returned error: 403
> ```
> Desculpem a minha ignorância quando se trata de utilizar o git de forma colaborativa.

Sem problemas. Todos aqui somos eternos aprendizes. Tem um post do @fdaciuk que explica de uma maneira belíssima, como criar um PR e como atualizar o seu PR com da master

* [Git e Github - Do clone ao pull request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)

* [Manter repositório do Github forkado sincronizado com o original](https://blog.da2k.com.br/2014/01/19/manter-repositorio-github-forkado-sincronizado-com-o-original/)

**Comment by glaucia86** [comment]
@Pacheco95 caso o seu problema já foi resolvido, podemos fechar essa issue?

**Comment by Pacheco95** [comment]
@glaucia86 Obrigado pelos links. Pode sim!
