### ISSUE TITLE
Dificuldade com apikey algorithmia

### ISSUE THREAD

**Issue by EvansLopes** [filipedeschamps/video-maker#200]
Boa noite, pessoal!

Estou enfrentando dificuldades em utilizar a api do Algorithmia, muito provavelmente pelo pouco tempo e conhecimento que tenho em json e JS.
Poderiam me ajudar?

Passos que executei:
  - [x] Copiar minha própria apiKey;
  - [x] Tentar remover a apiKey e rodar o projeto;
  - [x] Criar uma nova apiKey customizada no portal da Algorithmia.

Pelo que pude perceber, há algum parâmetro que eu não estou passando e não consegui identificar qual é!

Abaixo está a mensagem:

Choose one option [1, 2, 3, 0]: 1
_http_outgoing.js:595
    throw new ERR_INVALID_ARG_TYPE('first argument',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
    at write_ (_http_outgoing.js:595:11)
    at ClientRequest.write (_http_outgoing.js:567:10)
    at AlgorithmiaClient.req (C:\Users\Lopes\Video_automation\node_modules\algorithmia\lib\algorithmia.js:117:19)
    at Algorithm.pipe (C:\Users\Lopes\Video_automation\node_modules\algorithmia\lib\algorithm.js:27:28)
    at fetchContentFromWikipedia (C:\Users\Lopes\Video_automation\robots\text.js:11:50)
    at Object.robot [as text] (C:\Users\Lopes\Video_automation\robots\text.js:4:5)
    at start (C:\Users\Lopes\Video_automation\index.js:12:9)
    at Object.<anonymous> (C:\Users\Lopes\Video_automation\index.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

**Comment by brunorafaeI** [comment]
Pelo o que estou vendo o erro se refere ao tipo passado como primeiro argumento, ele deveria ser do tipo string, mas talvez nada esta sendo passado 'undefined' (indefinido).

**Comment by EvansLopes** [comment]
Rafael, obrigado pela ajuda!

Seria então, talvez, minha busca que está enviando o tipo errado de dados ou a própria API que montei?

**Comment by acristh** [comment]
Bom dia. Tenta pegar a variável do robô de texto com um `console.log(variave)`, aparentemente está na linha 11 do seu arquivo `texto.js` do robô.

**Comment by arlindopaulo** [comment]
tenho o mesmo problema e nao acho solução
eis o codigo


const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
async function robot(content){
    //console.log('Recebi com sucesso o content: ${content.search}')
    await fetchContentFromWikipedia(content)
    //sanitizeContent(content)
    //breakContentIntoSentences(content)

    

    async function fetchContentFromWikipedia(content){
        json : true
        //console.log(content)
        
        const algorithmiaAuthenticated = algorithmia (algorithmiaApiKey)
        const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
        const wikipediaResponde = await wikipediaAlgorithm.pipe(content.seachTerm)
        const wikipediaContent = wikipediaResponde.get()
        console.log(wikipediaContent)
        


    }
}
module.exports = robot

**Comment by AlvesUeliton** [comment]
É possível usar isso em Bash?

**Comment by leodutra** [comment]
Testei o projeto e não há problemas com a key do algorithmia.
Verifique a configuração correta no README.
Agradecemos a colaboração.
