### ISSUE TITLE
Não localiza as API

### ISSUE THREAD

**Issue by Ociamo** [filipedeschamps/video-maker#201]
Eu estou começando a aprender.
Entrei no Github, segui todos os procedimentos, mas aparece mensagem de erro.
Não acha nenhuma API.
Se alguém puder ajudar eu agradeço.
A mensagem é a seguinte:

C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório\video-maker>node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório\video-maker\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório\video-maker>

**Comment by gmonteeeiro** [comment]
Acredito que ele não esteja localizando as credenciais e não a API em si.

Dá uma olhada no [passo da instalação](https://github.com/filipedeschamps/video-maker#api-algorithmia) referente às credenciais do algorithmia

**Comment by Ociamo** [comment]
Como eu faço para desinstalar e tentar de novo do zero?

**Comment by gmonteeeiro** [comment]
Cara, acho que tu nem precisa tentar tudo de novo, basta criar uma conta no [Algorithmia](https://algorithmia.com/) e criar o arquivo `credentials/algorithmia.json`.

O Filipe mostra isso a partir [nesse ponto do vídeo](https://youtu.be/8XgbjUP-Gxo?t=575). Dá uma olhada

**Comment by Ociamo** [comment]
Esse é o problema. Eu criei a conta e o arquivo também. Só que não funcionou.

**Comment by gmonteeeiro** [comment]
e tendo o arquivo, qual o erro?

**Comment by Ociamo** [comment]
O erro é o informado no posto principal.
Error: Cannot find module '../credentials/algorithmia.json'

Só se eu, por alguma inexperiência, estou fazendo algo errado. Mas eu criei a conta no algorithmia, depois criei o arquivo algorithmia.json e coloquei la dentro a chave. Assim:
{
  "apiKey": "xxxxxxxxxxxxxxxx"
}

A chave eu coloquei no local onde está o "x"

**Comment by apreczewski** [comment]
Boa tarde, Ociamo... verifica se o import do arquivo está correto. Você pode ter posto "." a mais ou menos.
exemplo: const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey

Posta seu código para olharmos... abraço meu querido!

**Comment by Ociamo** [comment]
apreczewski, o código que eu coloquei no arquivo algorithmia.json foi só:
{
"apiKey": "xxxxxxxxxxxxxxxx"
}

A chave do algorithmia eu coloquei no local onde está o "xxxx"

Deveria ter colocado mais algum código?
Ou se vc está falando de algum código que já está lá, me diz onde eu retiro ele para colocar aqui para vc ver. Como não sou dá área de programação, posso ter entendido errado.
É código dentro do Algorithmia.json ?

**Comment by joaogabrielpancheski** [comment]
@Ociamo posta o código do text.js onde você faz a importação do algorithmia.json

**Comment by Ociamo** [comment]
Ok. Agora entendi. O código é esse:

const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')

const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js')
 
const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
})

const state = require('./state.js')

async function robot() {
  console.log('> [text-robot] Starting...')
  const content = state.load()

  await fetchContentFromWikipedia(content)
  sanitizeContent(content)
  breakContentIntoSentences(content)
  limitMaximumSentences(content)
  await fetchKeywordsOfAllSentences(content)

  state.save(content)

  async function fetchContentFromWikipedia(content) {
    console.log('> [text-robot] Fetching content from Wikipedia')
    const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
    const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
    const wikipediaContent = wikipediaResponse.get()

    content.sourceContentOriginal = wikipediaContent.content
    console.log('> [text-robot] Fetching done!')
  }

  function sanitizeContent(content) {
    const withoutBlankLinesAndMarkdown = removeBlankLinesAndMarkdown(content.sourceContentOriginal)
    const withoutDatesInParentheses = removeDatesInParentheses(withoutBlankLinesAndMarkdown)

    content.sourceContentSanitized = withoutDatesInParentheses

    function removeBlankLinesAndMarkdown(text) {
      const allLines = text.split('\n')

      const withoutBlankLinesAndMarkdown = allLines.filter((line) => {
        if (line.trim().length === 0 || line.trim().startsWith('=')) {
          return false
        }

        return true
      })

      return withoutBlankLinesAndMarkdown.join(' ')
    }
  }

  function removeDatesInParentheses(text) {
    return text.replace(/\((?:\([^()]*\)|[^()])*\)/gm, '').replace(/  /g,' ')
  }

  function breakContentIntoSentences(content) {
    content.sentences = []

    const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
    sentences.forEach((sentence) => {
      content.sentences.push({
        text: sentence,
        keywords: [],
        images: []
      })
    })
  }

  function limitMaximumSentences(content) {
    content.sentences = content.sentences.slice(0, content.maximumSentences)
  }

  async function fetchKeywordsOfAllSentences(content) {
    console.log('> [text-robot] Starting to fetch keywords from Watson')

    for (const sentence of content.sentences) {
      console.log(`> [text-robot] Sentence: "${sentence.text}"`)

      sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)

      console.log(`> [text-robot] Keywords: ${sentence.keywords.join(', ')}\n`)
    }
  }

  async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
      nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
      }, (error, response) => {
        if (error) {
          reject(error)
          return
        }

        const keywords = response.keywords.map((keyword) => {
          return keyword.text
        })

        resolve(keywords)
      })
    })
  }

}

module.exports = robot



Agradeço muito a atenção e paciência de vocês!

**Comment by joaogabrielpancheski** [comment]
Aparentemente, a importação está correta.
Verifica se não há nenhum erro em relação ao caminho especificado e nome do arquivo, se isso está correto: '../credentials/algorithmia.json'

**Comment by Ociamo** [comment]
joão, o caminho é o seguinte:
C:\Users\Ociamo\Desktop\Projeto Deschamps\Cópia do repositório\video-maker\credentials

E dentro da pasta credentials está o arquivo algorithmia.json

**Comment by joaogabrielpancheski** [comment]
Posta um print da sua estrutura de arquivos

**Comment by Ociamo** [comment]
![image](https://user-images.githubusercontent.com/52223705/61015665-f2f86b80-a362-11e9-8e25-1f085ee2b902.png)

**Comment by Ociamo** [comment]
![image](https://user-images.githubusercontent.com/52223705/61015683-07d4ff00-a363-11e9-942e-4dc38628c5f0.png)

**Comment by joaogabrielpancheski** [comment]
@Ociamo tu consegue subir seu projeto em um repositório, aí consigo analisar melhor e posso tentar te ajudar, porque olhando superficialmente não estou encontrando onde está o erro.

**Comment by apreczewski** [comment]
@Ociamo tudo bem?

Tem como você tirar um print da tela quando estiver com o projeto aberto no seu editor? qualquer coisa me avisa, que podemos fazer um hangout! abraço meu querido!

**Comment by apreczewski** [comment]
@Ociamo tudo bem?
Dúvida você instalou o algorithmia? **npm i algorithmia** 
Verifica se o **sbd** tbm está instalado

**Comment by Ociamo** [comment]
Epa...
Não lembro de instalar algorithmia. Eu fiz a clonagem do repositório. No tutorial não fala que tem que instalar, só fala para criar conta no algorithmia. Tinha que instalar algorithmia?

**Comment by joaogabrielpancheski** [comment]
Precisa @Ociamo 
Segue o que o @apreczewski disse, roda o "npm i algorithmia" e o "npm i sbd"

**Comment by Ociamo** [comment]
João, como eu faço para rodar "npm i algorithmia" e o "npm i sbd" ?

**Comment by joaogabrielpancheski** [comment]
Vai no cmd ou powershell, ou o console que você preferir, navegue até a pasta do projeto, e execute os comandos

**Comment by Ociamo** [comment]
João, fui na pasta e na pasta video-maker e abri o CMD.
No CMD digitei npm i algorithmia e o resultado foi esse:

C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório>npm i algorithmia
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Maico\Desktop\Projeto Deschamps\Cópia do repositório\package.json'
npm WARN Cópia do repositório No description
npm WARN Cópia do repositório No repository field.
npm WARN Cópia do repositório No README data
npm WARN Cópia do repositório No license field.

+ algorithmia@0.3.10
added 1 package and audited 1 package in 1.704s
found 0 vulnerabilities

**Comment by joaogabrielpancheski** [comment]
@Ociamo se você clonou o repositório, pra evitar outros problemas nesse mesmo sentido, roda o comando "npm install", que vai instalar todas as dependências que constam no package.json

**Comment by Ociamo** [comment]
Desculpe, ignore esse meu ultimo comentário pois abri o CMD no lugar errado.

**Comment by Ociamo** [comment]
O algorithmia foi instalado com sucesso, mas na pasta video-maker.

**Comment by joaogabrielpancheski** [comment]
Você utilizou o "npm install"?

**Comment by Ociamo** [comment]
O npm i sbd também instalei agora com sucesso.
Não cheguei a utilizar o npm install novamente.
Vou tentar rodar o programa e ver se vai.

**Comment by joaogabrielpancheski** [comment]
Roda o "npm intall", pois ele vai instalar todas as dependências necessárias, isso evitará erros deste mesmo caso em outras partes do sistema.

**Comment by Ociamo** [comment]
Rodei o npm install e depois testei rodando o node index.js , mas ainda não funcionou.

**Comment by joaogabrielpancheski** [comment]
Continua aquele mesmo erro do início?

**Comment by Ociamo** [comment]
Sim. Conferi. É o mesmo erro.

**Comment by Ociamo** [comment]
Boa noite,
será que desinstalando e instalando novamente eu consigo ? Se sim, como faço para desinstalar ?

**Comment by MatheusRV** [comment]
@Ociamo Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by Ociamo** [comment]
Boa tarde MatheusRV,
apesar das ajudas acima não consegui resolver e o programa não funcionou.
Verifiquei nas dicas acima que aparentemente haviam passos que não constavam do tutorial. Eventualmente possa existir algum outro passo que não consta no tutorial e não foi mencionado aqui.
O fato é que não funcionou e acabei tendo que desistir de fazer funcionar devido a falta de alternativas.

**Comment by leodutra** [comment]
Por favor, baixe novamente o projeto, siga os passos do README e abra 
quando se tiver mais informações do seu bug. Realizei um teste e está tudo funcionando após uso do Algorithmia.
