### ISSUE TITLE
Alguem pode fazer um tutorial atualizado da parte da API do Google?

### ISSUE THREAD

**Issue by ArthurBottcher** [filipedeschamps/video-maker#203]

**Comment by ArthurBottcher** [comment]
Necessito de ajuda pois mudou os sites e tenho duvidas

**Comment by britotiagos** [comment]
Tambem estou com problemas nesta parte 

**Erro**
```
[image-robot] Querying Google Images with: "Michael Jackson"
(node:45281) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at fetchGoogleAndReturnImagesLinks (/Users/tiagobrito/Repos/Study/video-maker/video-maker/robots/image.js:49:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:45281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45281) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Meu Codigo**

```
async function fetchGoogleAndReturnImagesLinks(query) {
    const response = await customSearch.cse.list({
      auth: googleSearchCredentials.apiKey,
      cx: googleSearchCredentials.searchEngineId,
      q: query,
      searchType: "image",
      num: 2
    });
    const imagesUrl = response.data.items.map(item => {
      return item.link;
    });
    return imagesUrl;
  }
```

Deveria fazer um `map` dos **items** mas retorna **undefined**, fiz um console log da `const response` e volta fazia mesmo. Acredito que tenha mudado algo na API, alguem tem alguam info sobre isso?

**Comment by apreczewski** [comment]
Boa tarde, pelo que notei tem algo que mudou na parte de autenticação, não tenho certeza, mas acho que o custom search está exigindo oauth como autenticação. Acabei pulando algumas etapas e fiz a parte de oauth2 do youtube, para saber como me autenticar, testei os robots custom search e o do youtube, e bingo! funcionou. A dica é criar a oauth separado, assim é possível utilizar no robots custom search e youtube (passando o scope quando necessário :D)... feito! abraço meus queridos!!!

**Comment by apreczewski** [comment]
Boa tarde, havia comentado sobre a possível autenticação oauth para o custom search, mas olhando com mais calma não era esse o problema, acabei apagando o post. 
Bom, o que funcionou no meu caso, foi editar o search cse (https://cse.google.com/cse/all), selecionei o **Mecanismos de pesquisa** > **Configurações Básicas** > **Pesquisar em toda a Web** habilitei esse campo, e com isso consegui utilizar normamente o custom search. Não tenho certeza se essa é a melhor maneira de corrigir o problema, no entanto, é um palhativo para continuarmos os estudos. Caso alguém tenha algo mais relevante, por favor, informar... feito! abraços meus queridos!

**Comment by britotiagos** [comment]
Perfeito @apreczewski funcionou direitinho, valeu pela ajuda.

Vou fechar ess Issue, se nao esta funcionando pra alguem ainda, abre ela de novo. 

Abraço

**Comment by dajoso** [comment]
Fiz isso e o erro ainda continua

**Comment by vlaskz** [comment]
E se fizéssemos uso do Selenium Webdriver e parássemos de usar o Google API? seria interessante. Aliás, eu mesmo vou tentar fazer dessa forma, pois não tenho mais conta gratuita no Google (faz tempo que uso a GCP). No mais, pelo que eu testei,

APENAS ALTERE PARA PESQUISAR TODA A WEB

nos parâmetros do GCSE.

**Comment by jlenon7** [comment]
muito obrigado!!!! @apreczewski
