### ISSUE TITLE
(node:14052) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by wfrsilva** [filipedeschamps/video-maker#206]
E:\robovideoyoutube\video-maker>node index.js
Type a Wikipedia search term: Docker

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Docker is a set of coupled software-as-a-service and platform-as-a-service products that use operating-system-level virtualization to develop and deliver software in packages called containers."
(node:14052) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (E:\robovideoyoutube\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (E:\robovideoyoutube\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (E:\robovideoyoutube\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (E:\robovideoyoutube\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:14052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

E:\robovideoyoutube\video-maker>

**Comment by wfrsilva** [comment]
Gerei as credenciais de novo no watson:


E:\robovideoyoutube\video-maker>node index.js
Type a Wikipedia search term: docker

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Docker is a set of coupled software-as-a-service and platform-as-a-service products that use operating-system-level virtualization to develop and deliver software in packages called containers."
(node:3280) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (E:\robovideoyoutube\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (E:\robovideoyoutube\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (E:\robovideoyoutube\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (E:\robovideoyoutube\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

E:\robovideoyoutube\video-maker>

**Comment by wfrsilva** [comment]
Deletei e criei as Credenciais do Watson novamente ... 
Atualizei o watson-nlu.json e rodei novamente.
funcionou \o/

**Comment by mariogomesbarbosa** [comment]
Eu estou tendo o mesmo erro. Fiz o procedimento acima, apaguei as credenciais, gerei uma nova, mas continua dando o mesmo erro. Notei que quando fui fazer o tutorial o 'watson-developer-cloud' estava depreciado, então instalei o que foi orientado pelo próprio IBM, o 'ibm-watson'.
 

## File: `watson-nlu.json`
``` json
{
  "apikey": "0j8XELLQw5OBn1x8OOIGelzgQ5Da-N4v5E5WNG4jWdpb",
  "iam_apikey_description": "Auto-generated for key 69c6db70-9681-4e01-a2de-b2b3ddbb45a3",
  "iam_apikey_name": "CredencialNOVA",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/c779117c8be246fa9b4e1132c124803e::serviceid:ServiceId-a11bf66c-4ee2-4b00-a212-5b47769372e9",
  "url": "https://gateway-syd.watsonplatform.net/natural-language-understanding/api"
}
  ```
## File: `text.js`

``` javascript
const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd')

const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1.js');

var nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});


nlu.analyze(
    {
      text: `Hi i'm Michael Jaskcon an I like doing the moonwalk every night.`,
      features: {
        keywords: {}
      }
    })
    .then(result => {
      console.log(JSON.stringify(result, null, 4));
    })
    .catch(err => {
      console.log('error:', err);
    });

async function robot(content) {
    await fetchContentFromWikipedia(content)
    sanitizeContent(content)
    breakContentIntoSentences(content)

    async function fetchContentFromWikipedia(content) {
        const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
        const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
        const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm)
        const wikipediaContent = wikipediaResponse.get()

        content.sourceContentOriginal = wikipediaContent.content
    }

    function sanitizeContent(content) {
        const withoutBlankLines = removeBlankLines(content.sourceContentOriginal)
        const withoutMarkDown = removeMarkDown(withoutBlankLines)

        content.sourceContentSanitized = withoutMarkDown

        function removeBlankLines(text) {
            const allLines = text.split('\n')

            const withoutBlankLines = allLines.filter((line) => {
                if(line.trim().length === 0) {
                    return false
                }
                return true
            })
            return withoutBlankLines
        }

        function removeMarkDown(lines) {
            const withoutMarkDown = lines.filter((line) => {
                if (line.trim().startsWith('=')) {
                    return false
                }
                return true
            })
            return withoutMarkDown.join(' ')
        }
    }

    function breakContentIntoSentences(content){
        content.sentences = []

        const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
        sentences.forEach((sentence) => {
            content.sentences.push({
                text: sentence,
                keywords: [],
                images: []
            })
        });
    }
}

module.exports = robot
```

## Console Error

``` console
error: { Unauthorized: Access is denied due to invalid credentials.
    at RequestWrapper.formatError (C:\Mário Barbosa\Video Maker Bot\video-maker-bot\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:200:21)
    at C:\Mário Barbosa\Video Maker Bot\video-maker-bot\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:188:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Unauthorized',
  code: 401,
  message: 'Access is denied due to invalid credentials.',
  body: '{"code":401,"error":"Unauthorized"}',
  headers:
   { 'x-backside-transport': 'FAIL FAIL',
     'content-type': 'application/json',
     'x-dp-transit-id': 'gateway01-1094085007',
     'x-global-transaction-id': '7ecac92c5d8a3fee4136698f',
     'strict-transport-security': 'max-age=31536000;',
     'x-dp-watson-tran-id': 'gateway01-1094085007',
     'x-edgeconnect-midmile-rtt': '127',
     'x-edgeconnect-origin-mex-latency': '72',
     date: 'Tue, 24 Sep 2019 16:10:22 GMT',
     connection: 'close' } }
```

**Comment by mariogomesbarbosa** [comment]
Descobri o meu erro, a url dada no trecho da documentação do Natural Language Understanding:
``` javascript
var nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: '<apikey>',
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});
```
Estava diferente da gerada nas credenciais do IBM Cloud:

``` javascript
"url": "https://gateway-syd.watsonplatform.net/natural-language-understanding/api"
```
