### ISSUE TITLE
Lista de Linguagens > Olá. Você poderia me explicar como inserir o camp lang no algorithmia.json?

### ISSUE THREAD

**Issue by wfrsilva** [filipedeschamps/video-maker#208]
Onde consigo a lista de linguagens possíveis?

Poderia ser mais uma pergunta do robo:

Select language:
[1]Eng
[2] Spa
[3] Ptg
[4] Fra

> Olá. Você poderia me explicar como inserir o camp lang no algorithmia.json?

Basta fazer assim:
{
  "apiKey": "sua chave",
  "lang": "idioma desejado"
}

_Originally posted by @marcosmachado81 in https://github.com/filipedeschamps/video-maker/pull/168#issuecomment-500755038_

**Comment by wfrsilva** [comment]
Listas de idiomas possíveis?

**Comment by Giancarl021** [comment]
Pelo que eu entendi esse código do algorithmia coloca a linguagem no primeiro campo da url pra
pesquisar

lang: 'pt' &rarr; pt.wikipedia.org/
lang: 'en' &rarr; en.wikipedia.org/

Se for assim, os idiomas disponíveis estão nesta lista [aqui](https://en.wikipedia.org/wiki/List_of_Wikipedias).
