### ISSUE TITLE
Erro no robot de vídeo

### ISSUE THREAD

**Issue by alessandrodesign** [filipedeschamps/video-maker#211]
[video-robot] Starting...
(node:15472) UnhandledPromiseRejectionWarning: Error: Command failed: Parâmetro Inválido - /content

    at ChildProcess.onExit (D:\wamp64\www\youtube-maker\video-maker-youtube\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (D:\wamp64\www\youtube-maker\video-maker-youtube\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:15472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JuniorPetrini** [comment]
o meu estava dando o mesmo problema

**Comment by thiagocavalcanti** [comment]
O meu também

**Comment by p3ss1n** [comment]
> o meu estava dando o mesmo problema

conseguiu corrigir?

**Comment by yurimedeiros** [comment]
o  meu tbm

**Comment by ramonrota** [comment]
alguém conseguiu resolver? tenho o mesmo problema...

**Comment by hebertlima** [comment]
Pessoal desistalem o ImageMagick e reinstala marcando essa opção:
[img](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRaBkTc5jbTSNGWTyelzKJi48acalWUuN94_2whETGIeYlPuvv4)
