### ISSUE TITLE
Não consigo Criar imagem em miniatura do Youtube (THUMBNAIL)

### ISSUE THREAD

**Issue by yurimedeiros** [filipedeschamps/video-maker#212]

**Comment by yurimedeiros** [comment]
Desculpa Galera mas quero motivar um pouco, este post foi editado 3 vezes, tentei de varias formas e consegui resolver o problema quero agradeçer ao felipe e toda comunidade. 
meu robo esta ficando pronto e estou feliz comigo pois sempre fiquei pausando projeto.
conheci o canal em março depois de muitas tentativas e muitos erros, consegui.
NUNCA DESISTA! CONTINUE..NAO PARE...

**Comment by yurimedeiros** [comment]
(node:15764) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at createYouTubeThumbnail (C:\Users\YuriM\Desktop\Video maker 2\robots\image.js:193:3)
    at Object.robot [as image] (C:\Users\YuriM\Desktop\Video maker 2\robots\image.js:15:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). (rejection id: 2)
(node:15764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.

**Comment by MatheusRV** [comment]
Você precisa de uma permissão do Youtube para conseguir realizar isso, em alguma issue (que não consigo encontrar agora) vi essa solução para seu problema.

**Comment by leodutra** [comment]
Alguma função assíncrona está dando `throw` em erro, ou usando uma API que está dando `throw` e não está sendo tratado. 

Provavelmente no ponto citado pelo @MatheusRV 

Você pode iniciar o Node em modo debug, e fazer uso de breakpoints e watchers ou tentar esta alternativa anêmica:
```js
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  // application specific logging, throwing an error, or other logic here
});
```

**Comment by leodutra** [comment]
Fechando, por favor reabra se persistir.
