### ISSUE TITLE
me ajude

### ISSUE THREAD

**Issue by jean-1** [filipedeschamps/video-maker#214]
Felipe me ajuda

**Comment by danilosales** [comment]
Coloca a sua dúvida aí que a comunidade pode te ajudar.

**Comment by jean-1** [comment]
estou tentando clonar o repositório para uma pasta e da erro sabe me dizer o porque

**Comment by hebertlima** [comment]
@jean-1 da uma lida no readme do projeto: https://github.com/filipedeschamps/video-maker vc precisa instalar o nodejs e o git no seu pc e configurar depois rodar o comando abaixo:
```bash
git clone https://github.com/filipedeschamps/video-maker.git
```

**Comment by MatheusRV** [comment]
@jean-1 Conseguiu? Posso te recomendar vídeos no Youtube para aprender como instalar o git e clonar um projeto.
