### ISSUE TITLE
Error: Bad Request

### ISSUE THREAD

**Issue by s4muc4** [filipedeschamps/video-maker#216]
**Estou tendo alguns problemas na hora de implementar esta parte do codigo no robo de imagens:**
---

const response = await customSearch.cse.list({
        auth: googleSearchCredentials.apiKey,
        cx: googleSearchCredentials.searchEngineId,
        q: 'Michael Jackson',
        num: 2
    })
    console.dir(response, { depth: null })
    process.exit(0) 

---

Antes de escrever essa parte, o index.js roda certinho, porém quanto acrecentada essa parte do código, ele me da esse erro: 

---

(node:13544) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Gaxios.request (C:\Users\samuc\desktop\video-maker\node_modules\gaxios\build\src\gaxios.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:13544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). (rejection id: 1)
(node:13544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.

---

O que faço para resolve-lo?

**Comment by hebertlima** [comment]
Configura o GSC para pesquisar em **Toda Web** e Habilita **buscar por imagens**

**Comment by s4muc4** [comment]
> Configura o GSC para pesquisar em **Toda Web** e Habilita **buscar por imagens**

Opa mano, obrigado pela dica! Estão habilitadas as duas opções, porém o erro ainda continua o mesmo... Empaquei no projeto e não consigo mais avançar. Tem mais alguma sugestão?

**Comment by hebertlima** [comment]
escreve um bloco `try catch` em volta 
```js
async function fetchGoogleAndReturnImagesLinks(query) { 
    const response = await customSearch.cse.list({
      auth: googleSearchCredentials.apiKey,
      cx: googleSearchCredentials.searchEngineId,
      q: query,
      searchType: 'image',
      num: 2
    })

    const imagesUrl = response.data.items.map((item) => {
      return item.link
    })

    return imagesUrl
}
```
algo assim:
```js
async function fetchGoogleAndReturnImagesLinks(query) { 
    try {
      const response = await customSearch.cse.list({
        auth: googleSearchCredentials.apiKey,
        cx: googleSearchCredentials.searchEngineId,
        q: query,
        searchType: 'image',
        num: 2
      })
  
      const imagesUrl = response.data.items.map((item) => {
        return item.link
      })
  
      return imagesUrl  
    } catch (error) {
      console.log(error);
    }    
}
```

**Comment by s4muc4** [comment]
Muito Obrigado pela ajuda! Tentei fazer tudo isso que você orientou, porém nada, revendo os vídeos do Felipe, ví que peguei a apiKey errada. Não era nem erro de código, e sim da interação com a api kkkkkkk. Obrigado
