### ISSUE TITLE
Error: Unauthorized: Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by m3g4mInD** [filipedeschamps/video-maker#217]
Ola, apos baixar testar a uns tempos atras decidi voltar a fazer git pull e  ver o que existe de novo, contudo verifico um erro onde ja algums usuarios tambem tiveram.
Error: Unauthorized: Access is denied due to invalid credentials.
Crei nova conta atè para descartar alguem erro.
Gerei mais de 5 credenciais de novo no watson: e o erro continua, 
verifiquei api key a url da api e esta tudo correcto aqui.

` node index.js 
Type a Wikipedia search term: paper

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Paper is a thin material produced by pressing together moist fibres of cellulose pulp derived from wood, rags or grasses, and drying them into flexible sheets."
(node:4812) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (F:\YOUTUBE\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (F:\YOUTUBE\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (F:\YOUTUBE\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (F:\YOUTUBE\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:4812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
Agradeço a ajuda

**Comment by hebertlima** [comment]
Qual a *url da api* do Watson você está fazendo requisição?

**Comment by m3g4mInD** [comment]
"url": "https://gateway-lon.watsonplatform.net/natural-language-understanding/api" @hebertlima

**Comment by hebertlima** [comment]
a api correta é: `https://gateway.watsonplatform.net/natural-language-understanding/api/`

**Comment by m3g4mInD** [comment]
mas entao pk la no site ele da esse url? mt estranho mesmo, 
criei uma nova e me da assim `{
  "apikey": "xxxxxxxxxxxxxxxxxxxxxxxxx",
  "iam_apikey_description": "Auto-generated for key xxxxxxxxxx",
  "iam_apikey_name": "Auto-generated service credentials",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/xxxxxxxxxxxxxxa::serviceid:ServiceId-6xxxxxxxxxx",
  "url": "https://gateway-lon.watsonplatform.net/natural-language-understanding/api"
}` mt estranho

**Comment by m3g4mInD** [comment]
bem, consegui resolver para ja esse erro, tive a verificar o file text.js e troquei o url para o ulr correcto e esta funcionando ja. obg

**Comment by hebertlima** [comment]
ah, então era o parâmetro escrito errado rs, mas se resolveu pode fechar a issue

**Comment by Guilherme774** [comment]
estou tendo esse erro após a seleção do prefixo

(node:6512) UnhandledPromiseRejectionWarning: Forbidden: Access is denied due to invalid credentials.
    at formatError (C:\Users\guilherme\Desktop\video-robots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:111:17)
    at C:\Users\guilherme\Desktop\video-robots\node_modules\watson-developer-cloud\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:259:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

alguém poderia me ajuda porfavor

**Comment by Lorhan7** [comment]
Creio que voce esteja usando o modulo Antigo do Watson verifique se é o mesmo desse site: https://www.npmjs.com/package/ibm-watson
