### ISSUE TITLE
 Estou com este erro, logo apois tranferir os dados do Robo de imagem para o robo de video. estou estou um passo antes do after effects.

### ISSUE THREAD

**Issue by yurimedeiros** [filipedeschamps/video-maker#218]
Olá Galera tudo bem ? Boa noite, Estou com este erro, logo apois tranferir os dados do Robo de imagem para o robo de video. estou estou um passo antes do after effects.

![image](https://user-images.githubusercontent.com/47609034/62988869-3b9cbc00-be1c-11e9-9674-8e2ece5b8b72.png)

" (node:16992) UnhandledPromiseRejectionWarning: ReferenceError: state is not defined
    at Object.robot [as image] (C:\Users\YuriM\Desktop\Video maker 2\robots\image.js:8:18)
    at start (C:\Users\YuriM\Desktop\Video maker 2\index.js:12:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promis
e which was not handled with .catch(). (rejection id: 2)
(node:16992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zer
o exit code.
"

+++++ MEU CODIGO +++

const imageDownloader = require('image-downloader')
const google = require('googleapis').google
const customSearch = google.customsearch('v1')

const googleSearchCredentials = require('../credentials/google-search.json')
 
 async function robot() {
	const content = state.load()

	await fetchImagesOfAllSentences(content)
	await downloadAllImages(content)

	state.save(content)

	async function fetchImagesOfAllSentences(content) {
		for (const sentence of content.sentences) {
			const query = `${content.searchTerm} ${sentence.keywords[0]}`
			sentence.images = await fetchGoogleAndReturnImagesLinks(query)
			
			sentence.googleSearchQuery = query
		}
	}

	async function fetchGoogleAndReturnImagesLinks(query){
		const response = await customSearch.cse.list({
		auth: googleSearchCredentials.apiKey,
		cx: googleSearchCredentials.searchEngineId,
		q: query,
		searchType: 'image',
		num: 2
		})

		const imagesUrl = response.data.items.map((item) => {
			return item.link
		})

		return imagesUrl
	}
	
	async function downloadAllImages(content) {
		content.downloadedImages = []

		for (let sentenceIndex = 0; sentenceIndex < content.sentences.length; sentenceIndex++) {
			const images = content.sentences[sentenceIndex].images

			for (let imageIndex = 0; imageIndex < images.length; imageIndex++) {
				const imageUrl = images[imageIndex]

				try {
					if (content.downloadedImages.includes(imageUrl)) {
						throw new Error('Imagem Ja foi Baixada')
					}
					
					await downloadAndSave(imageUrl, `${sentenceIndex}-original.png`)
					content.downloadedImages.push(imageUrl)
					console.log(` > [${sentenceIndex}] [${imageIndex}] Imagem Ja foi Baixada com sucesso: ${imageUrl}`)
					break
					} catch(error) {
					console.log(` > [${sentenceIndex}] [${imageIndex}] Imagem duplicada pular (${imageUrl}): ${error}`)
					}
				}
			}
		}
	}

	async function downloadAndSave(url, fileName) {
		return imageDownloader.image({
			url, url,
			dest: `./content/${fileName}`
		})
	}

module.exports = robot

**Comment by hebertlima** [comment]
vc não esta importando state pra dentro do seu image.js
```js
const state = require('./state.js')
```

**Comment by MatheusRV** [comment]
@yurimedeiros Conseguiu resolver? Caso necessário posso abrir novamente.
