### ISSUE TITLE
Problema com robô do youtube

### ISSUE THREAD

**Issue by s4muc4** [filipedeschamps/video-maker#219]
O código estava rodando normalmente, estava dando tudo certo

Porém hoje quando fui rodar o código, o processamento do vídeo no youtube não aparecia... ia direto pros 100%.

---

> [youtube-robot] Starting to upload the video to YouTube
> [youtube-robot] 100% completed
> [youtube-robot] Video available at: https://youtu.be/53SgcP475Aw
> [youtube-robot] Thumbnail uploaded
> [video-robot] Encoding finished successfully

---

O robô finalizava, porém no link que o robô dá pra visualizar o vídeo caia numa pagina do youtube dizendo "Vídeo indisponível"

Aí no Studio do youtube, o vídeo estava la, porém com erro, e com apenas uma opção.. a de excluir...

Fiquei tentando resolver, porém estourei minha cota no dia de hoje...

Alguém pode me ajuda?? Desde já agradeço!

**Comment by hebertlima** [comment]
tenta gerar um novo video, e apaga todas as imagens e o video que fica na pasta

**Comment by MatheusRV** [comment]
@s4muc4 Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando, se não resolveu reabra novamente.
