### ISSUE TITLE
Olá Devs!

### ISSUE THREAD

**Issue by Alenario-Rafael** [filipedeschamps/video-maker#220]
[nodemon] starting `node src/server.js`
(node:1716) UnhandledPromiseRejectionWarning: ValidationError: Dev validation failed: Avatar: Path `Avatar` is required.
    at new ValidationError (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\error\validation.js:30:11)
    at model.Document.invalidate (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\document.js:2317:32)
    at p.doValidate.skipSchemaValidators (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\document.js:2166:17)
    at C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\schematype.js:1037:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Alguém pode me ajudar com este erro que está dando no vs code?

**Comment by hebertlima** [comment]
@alenario-rafael nesse repositório nos discutimos problemas relacionados ao projeto dos Robos que criam videos para o Youtube, a dúvida que você postou é sobre a semana oministack, que já se encerrou, dito isso, vou te dar uma dica do que pode ser, esta faltando o campo `avatar`, ou ele esta vazio, ou ele não esta sendo enviado

**Comment by vlaskz** [comment]
> 
> 
> [nodemon] starting `node src/server.js`
> (node:1716) UnhandledPromiseRejectionWarning: ValidationError: Dev validation failed: Avatar: Path `Avatar` is required.
> at new ValidationError (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\error\validation.js:30:11)
> at model.Document.invalidate (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\document.js:2317:32)
> at p.doValidate.skipSchemaValidators (C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\document.js:2166:17)
> at C:\Users\RAFAEL\Desktop\www\semanaomnistack08\aulas\backend\node_modules\mongoose\lib\schematype.js:1037:9
> at processTicksAndRejections (internal/process/task_queues.js:75:11)
> (node:1716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:1716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Alguém pode me ajudar com este erro que está dando no vs code?

Esse Issue poderia ser movido/ encerrado imediatamente.

**Comment by MatheusRV** [comment]
Duplicado de https://github.com/filipedeschamps/video-maker/issues/225, por favor feche o issue.
