### ISSUE TITLE
Templates do mac para windowns

### ISSUE THREAD

**Issue by yurimedeiros** [filipedeschamps/video-maker#221]
Olá galera tudo bem? 
Estou com um problema, não sei usar o after effects para criar um tamplates.
porem baixei o do felipe, que foi criado no MAC, eu uso o Win e o after é CS6.

Alguem tem o template do felipe, usado no windowns?

**Comment by hebertlima** [comment]
@yurimedeiros você consegue usar o mesmo template normal, pois é um componente criado pelo after effects independente da plataforma win ou mac, quando você abrir o template no AF automaticamente ele vai mudar o preset para win, você só vai precisar alterar algumas configuração, e baixar o extendscript toolkit

**Comment by yurimedeiros** [comment]
Olá @hebertlima  Obrigado por tentar me ajudar, porem como sou iniciante no mundo da programação nao sei fazer essas configurações que tu me disse.
tenho ja no meu computador o extendscript toolkit,
revi o video varias vezes, eu publiquei abaixo o erro.
quando importo ele para dentro do AF ele não abre.
Gostaria de sabe quais e onde devo fazer essas configurações.

> erro no depois de toda execução do robo _
![err](https://user-images.githubusercontent.com/47609034/63555741-7daeb780-c518-11e9-9bdc-535c042ba56c.PNG)
error ao importar no AF o Projeto.
_
![err2](https://user-images.githubusercontent.com/47609034/63555765-9c14b300-c518-11e9-9c1f-6cd278129c46.PNG)

**Comment by vlaskz** [comment]
O erro é de versão, não de OS. Procure baixar a versão indicada no Erro (16.0.1) e provavelmente funcionará.

**Comment by yurimedeiros** [comment]
> O erro é de versão, não de OS. Procure baixar a versão indicada no Erro (16.0.1) e provavelmente funcionará.

Obrigado cara :D Funciono perfeitamente, como nao tenho nenhuma pratica com programação, to indo passo a passao.
 o video foi criado com sucesso.
 agora esta aparecendo um erro do oauth vou ver oque pode ser...
Obrigado !!!
![image](https://user-images.githubusercontent.com/47609034/63694212-4c6e0a00-c7ec-11e9-955b-2de76c076615.png)

**Comment by yurimedeiros** [comment]
galera quero agradeçer a todos voces por estar me ajudando, pois essa é a unica comunidade de programação que utilizo e conheco, graças ao felipe tamo junto....


tenho uma duvida sobre o codigo...
O que esta selecionado em azul, por ter as barras // o link esta bloqueado ?

![image](https://user-images.githubusercontent.com/47609034/63695353-e636b680-c7ee-11e9-9ce8-e78ba222e7f7.png)

**Comment by leodutra** [comment]
Resolvido?

**Comment by leodutra** [comment]
Possível bug, investigar.

**Comment by yurimedeiros** [comment]
Muito obrigado a todos que teve paciencia comigo, eu consegui finalizar
este projeto, devo a voces e ao felipe este feito, obrigado, no inicio
parecia uma agulha no palheiro e hoje estou feliz por ter todos voces,
juntos nesta familia. obg

Em qui, 31 de out de 2019 às 16:36, Leonardo Dutra <notifications@github.com>
escreveu:
