### ISSUE TITLE
ERRO AUTORIZAÇÃO

### ISSUE THREAD

**Issue by Marcim00** [filipedeschamps/video-maker#222]
![image](https://user-images.githubusercontent.com/54808064/64118590-52c13080-cd6e-11e9-9bdb-9a69861e48c3.png)
como resolver?

**Comment by LewisFreitas** [comment]
Encontrei isto agora também. 

O url hardcoded em `robots/text.js` deveria ser lido do objeto em `watson.js`, uma vez que pode corresponder a diferentes áreas geográficas.

Vá a `robots/text.js` e altere o url. Ou então altere o código para ler do `watson.js`

```
const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'ALTERE_URL_AQUI'
})
```

**Comment by MatheusRV** [comment]
Ainda está com o erro? Caso não por favor feche o issue.

**Comment by MatheusRV** [comment]
@Marcim00 Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
Fechando, reabra caso ainda persista.
