### ISSUE TITLE
Robot de imagens com bug do custom search

### ISSUE THREAD

**Issue by marcelo09714** [filipedeschamps/video-maker#224]
Fiz tudo direito, mas quando pesquisa ele acrescente "Google Custom Search" ao titulo quando passo a variável no parâmetro "q: query". Se nesse parâmetro eu colocar "q: 'Michael Jackson'" manualmente, ele funciona. Só buga quando passa a variável. Alguém consegue ajudar?

![image](https://user-images.githubusercontent.com/33968232/65188189-bd0feb80-da65-11e9-9211-8737537c8534.png)

![image](https://user-images.githubusercontent.com/33968232/65188376-33ace900-da66-11e9-981c-5dcdcb0020ce.png)

**Comment by L3onix** [comment]
Estou com o mesmo problema, procurei a documentação do Google mas até agora não deu em nada.

**Comment by marcelo09714** [comment]
É estranho, porque se escrever manualmente ele procura direito, mas quando se passa a variável pela função ele acrescenta "Google Custom Search" ao titulo e não encontrei nada nem documentação a falar deste problema.

**Comment by L3onix** [comment]
No link abaixo, tem a documentação do dessa função em específico, e da pra testar as requisições nela. Com os testes que fiz aqui, eu acredito que o problema esteja na configuração do CSE.
[Google Search API cse.list](https://developers.google.com/custom-search/v1/cse/list)

**Comment by L3onix** [comment]
Acho que encontrei a solução (mas não da pra eu testar agora XD). Na página de configuração do [CSE Google](https://www.google.com/cse/manage/all) ative a opção "**Pesquisar em toda a Web**". Fiz o teste usando a ferramenta de testes do Google que mencionei no comentário acima, e funcionou.

**Comment by marcelo09714** [comment]
Funcionou, já gravou os links e já pesquisou direito. Obrigado.

**Comment by MatheusRV** [comment]
Ainda está com o erro? Caso não por favor feche o issue.
