### ISSUE TITLE
(node:10456) UnhandledPromiseRejectionWarning: Error: Bad Request

### ISSUE THREAD

**Issue by ramonrota** [filipedeschamps/video-maker#225]
Dá o seguinte erro quando o bot termina a pesquisa no Wikipédia e começa a busca no google imagens. Alguém tem ideia do que seja?

> [image-robot] Starting...
> [image-robot] Querying Google Images with: "google"
(node:10456) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Gaxios.<anonymous> (G:\temporário\teste\video-maker\node_modules\gaxios\build\src\gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (G:\temporário\teste\video-maker\node_modules\gaxios\build\src\gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without
a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termi
nate the Node.js process with a non-zero exit code.

**Comment by hebertlima** [comment]
esse erro é problema nas configurações do google CSE, habilita pesquisar imagens e “pesquisar em toda a web”

**Comment by ramonrota** [comment]
Minha opção "pesquisar em toda a web" estava desabilitada, mas mesmo habilitando o erro continua. Minha configuração:

![image](https://user-images.githubusercontent.com/55772603/65736538-b1e63c80-e0b1-11e9-95ca-9c7d40b525d0.png)

![image](https://user-images.githubusercontent.com/55772603/65736585-db9f6380-e0b1-11e9-92bd-88004c70effe.png)

**Comment by MatheusRV** [comment]
> Se possível manda o seu código do text.js, verifica se você importou a credencial do algorithmia corretamente no seu arquivo text.js:
> `const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey `

Segundo o miguelarcjr pode ter relação com a key do algorithmia, ninguém consegue enviar esse arquivo?

**Comment by leodutra** [comment]
Não, a key do algorithmia é pessoal. Tem instruções na página inicial sobre.

Alguma função assíncrona está dando `throw` em erro, ou usando uma API que está dando `throw` e não está sendo tratado. 

Você pode iniciar o Node em modo debug, e fazer uso de breakpoints e watchers ou tentar esta alternativa anêmica:
```js
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  // application specific logging, throwing an error, or other logic here
});
```

**Comment by leodutra** [comment]
Fechando, reabra caso ainda ocorra o mesmo erro.
