### ISSUE TITLE
Erro text-robot

### ISSUE THREAD

**Issue by Gyron77** [filipedeschamps/video-maker#226]
Olá Pessoal!
Estou com o seguinte erro. Alguém poderia me ajudar?

Type a Wikipedia search term: Edwards

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:13076) UnhandledPromiseRejectionWarning: authorization required
(node:13076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MatheusRV** [comment]
Dup of https://github.com/filipedeschamps/video-maker/issues/225

**Comment by miguelarcjr** [comment]
Se possível manda o seu código do text.js, verifica se você importou a credencial do algorithmia corretamente no seu arquivo text.js:
`const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
`

**Comment by MatheusRV** [comment]
Fechando em favor de #225.

**Comment by PedroWagnerBomfim** [comment]
> Se possível manda o seu código do text.js, verifica se você importou a credencial do algorithmia corretamente no seu arquivo text.js:
> `const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey `

Eurealizei a exportação da credencial corretamente,  mas o erro que ocorreu foi parecido

(node:8229) UnhandledPromiseRejectionWarning: authorization required
(node:8229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
