### ISSUE TITLE
(node:3688) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by vini-rossi** [filipedeschamps/video-maker#227]
Olá pessoal

Estou tendo problemas na parte de imagens
acontece o seguinte erro:
![image](https://user-images.githubusercontent.com/56283285/66711484-45329980-ed63-11e9-8975-6d005d8b9543.png)

Vocês podem me ajudar!

**Comment by eduardo-120** [comment]
tambem estou tendo esse erro conseguiu resolver?

**Comment by guilhermelionzo** [comment]
Eduardo, o erro ocorre durante a pesquisa das imagens. Verifique se em sua **Custom Search Engine** a opção _Image Search_ está habilitada.

**Comment by nishantsethi** [comment]
Hi, I faced the same issue. Found the solution, In the Custom Search Engine, go to the Setup. You will find an option of **Search the entire web**, enable it.

**Comment by Jonntz** [comment]
Olá, estou com o mesmo problema, o meu Custom Search Engine está com a opção Image search e a opção Pequisar em toda a web habilitada, mas o problema persiste. Alguém conseguiu resolver?
