### ISSUE TITLE
Alguém poderia dispor um template para Windows e MACOS...

### ISSUE THREAD

**Issue by jeronimojbarbosa** [filipedeschamps/video-maker#228]
Preciso de um template do Adobe After Effects usado no projeto, para Windows e como já verifiquei que algumas pessoas estão precisando de outras versões mesmo pra MACOS, por favor quem puder ajudar?

**Comment by miguelarcjr** [comment]
Olá jeronimo, eu tenho para windows, precisei fazer algumas modificações, a intro ainda está com alguns bugs, eu editei usando o after effects 2019 cc. Você pode encontrar  no meu repositório: https://github.com/miguelarcjr/video-maker/tree/master/templates/1

Obs: Não esqueça de alterar no AE o destino de está o seu 'after-effects-script.js' na composição que serve para exibir o termo que você usou para criar o vídeo.

**Comment by jeronimojbarbosa** [comment]
@miguelarcjr Cara muito obrigado, vou verificar se dá certo, más mesmo assim muito obrigado por sua ajuda!

**Comment by jeronimojbarbosa** [comment]
@miguelarcjr consegui, obrigado, tive que atualizar meu AE, porém ainda tenho um erro e é com as fonts usadas, por incrível que pareça, não aparece quais as fonts usadas. Por favor vc pode me ajudar, com passando as fontes do projeto?

**Comment by MatheusRV** [comment]
Fechando, visto que já foi solucionado.
