### ISSUE TITLE
Error: (node:7130) [DEP0018]

### ISSUE THREAD

**Issue by acaciomartins** [filipedeschamps/video-maker#231]
Quando rodo o `node index.js` ele começa fazer as pesquisas, porém, termina com o seguinte erro:

Retrograde pyelogram
Ribosome
Random glucose test
Rebound (basketball)
All pages with titles beginning with RPG
All pages with titles containing RPG
(node:7130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7130) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Já procurei nas Issues e nada de achar uma solução!!!**

**Comment by miguelarcjr** [comment]
Cara se puder manda um print da mensagem de erro e código do seu arquivo text.js ;)

**Comment by MatheusRV** [comment]
@acaciomartins Conseguiu resolver? Posso fechar a issue?
Em 15 dias sem resposta do autor irei fechar, caso necessário posso abrir novamente.

**Comment by leodutra** [comment]
@acaciomartins alguma função assíncrona está dando `throw` em erro, ou usando uma API que está dando `throw` e não está sendo tratado. 

Você pode iniciar o Node em modo debug, e fazer uso de breakpoints e watchers ou tentar esta alternativa anêmica:
```js
process.on('unhandledRejection', (reason, p) => {
  console.log('Unhandled Rejection at: Promise', p, 'reason:', reason);
  // application specific logging, throwing an error, or other logic here
});
```

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem e quais já foram resolvidos, caso necessário posso abrir novamente.
