### ISSUE TITLE
Problema no Robô de Vídeo ( Template )

### ISSUE THREAD

**Issue by julio9246** [filipedeschamps/video-maker#232]
Galera !!! Dei uma travada quanto a template no meu ( como eu não tinha modelo ) eu criei um do zero e salvei lá, mas ele ignorou e deixou o vídeo sem nenhuma relação com o robô de vídeo.

 
Até baixei a sua do GIT mas como os caminhos estão diferentes , nome de usuário etc...tem alguma dica que possa me dar pra eu concluir esses robôs ( To empolgadão e ta faltando muito pouco )

**Comment by leodutra** [comment]
Substitui os caminhos e nomes de usuário e tente novamente.
Perguntas devem ser feitas no Discord.
https://discord.gg/wawRMu

Fechando. Reabra se tiver certeza que for um bug e tiver o log.
