### ISSUE TITLE
Alguém Pode Me Ajudar Com Esse Erro?

### ISSUE THREAD

**Issue by VH-loop** [filipedeschamps/video-maker#233]
PS C:\Users\Kv\Documents\Projeto\robo\video-maker> node index.js
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
Require stack:
- C:\Users\Kv\Documents\Projeto\robo\video-maker\robots\text.js
- C:\Users\Kv\Documents\Projeto\robo\video-maker\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:849:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\Kv\Documents\Projeto\robo\video-maker\robots\text.js:2:27)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:812:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:849:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\Kv\\Documents\\Projeto\\robo\\video-maker\\robots\\text.js'[39m,
    [32m'C:\\Users\\Kv\\Documents\\Projeto\\robo\\video-maker\\index.js'[39m
  ]
}

**Comment by julio9246** [comment]
Já confirmou se dentro da pasta Credentials está criado esse arquivo? com essa estrutura : 
{
    "apiKey":"xxx"
}

?

**Comment by VH-loop** [comment]
@julio9246 Verificado e está tudo correto.

**Comment by MatheusRV** [comment]
@VH-loop por favor, dps de ter o erro solucionado não edite removendo o texto. Outras pessoas podem ter um erro semelhante. Sucesso.
