### ISSUE TITLE
Erro Auth2 Consentimento

### ISSUE THREAD

**Issue by julio9246** [filipedeschamps/video-maker#234]
Boa tarde....alguém sabe o que pode ser isso:

 Please give your consent: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube&response_type=code&client_id=290881676931-4vohnvif344hdqbn8stkta67o5egbti1.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth

Já procurei formas de dar consentimento...mas não to achando! Alguém pode me ajudar?

**Comment by leodutra** [comment]
É uma pergunta ou um bug? Parece uma pergunta.
Perguntas devem ser feitas no Discord.
https://discord.gg/wawRMu

Fechando. Reabra se tiver certeza que for um bug e tiver o log.

**Comment by iamgoncalo** [comment]
> É uma pergunta ou um bug? Parece uma pergunta.
> Perguntas devem ser feitas no Discord.
> https://discord.gg/wawRMu
> 
> Fechando. Reabra se tiver certeza que for um bug e tiver o log.

Esse link não é mais válido? Obrigado!
