### ISSUE TITLE
Procedimento mudou (ApiKey google imagens)

### ISSUE THREAD

**Issue by MatheusDeAquino** [filipedeschamps/video-maker#236]
Em 5:37 mudou a forma como pede a ApiKey. Hoje ele pede mais duas alternativas: De onde vc chamará a API? e Que dados vc acessará? 
- O que devo fazer? Não sei qual opção é a correta  em relação ao projeto.
Perceba nas imagens abaixo que ao selecionar uma resposta uma outra alternativa aparece.
:)
![matt apikey 1](https://user-images.githubusercontent.com/43558548/68814696-3720b300-0658-11ea-91de-575812717ab9.JPG)
![matt apikey 2](https://user-images.githubusercontent.com/43558548/68814698-3720b300-0658-11ea-82db-7dc3e9c16122.JPG)
![matt apikey 3](https://user-images.githubusercontent.com/43558548/68814699-37b94980-0658-11ea-93d3-9922f31e9442.JPG)

**Comment by leandro-santiago** [comment]
Oi @MatheusDeAquino, eu fiz ontem o tutorial e passei por esse mesmo problema. Quando aparecer essa tela, ao invés de preencher o formulário clica em Cancelar. Dessa forma você irá para a página que tem um botão para Criar Credencial com uma seta para baixo do lado. Você clica no botão e seleciona a opção API Key, que a sua API key será gerada sem precisar preencher esse formulário.

Pelo que entendi, o preenchimento dess formulário cria outro tipo de autenticação.
Espero ter ajudado!
Abraço!

**Comment by MatheusDeAquino** [comment]
> Oi @MatheusDeAquino, eu fiz ontem o tutorial e passei por esse mesmo problema. Quando aparecer essa tela, ao invés de preencher o formulário clica em Cancelar. Dessa forma você irá para a página que tem um botão para Criar Credencial com uma seta para baixo do lado. Você clica no botão e seleciona a opção API Key, que a sua API key será gerada sem precisar preencher esse formulário.
> 
> Pelo que entendi, o preenchimento desse formulário cria outro tipo de autenticação.
> Espero ter ajudado!
> Abraço!

Interessante, eu prossegui com essa marcação das imagens e acabei conseguindo. Será que é possível haver problema futuro?

**Comment by leodutra** [comment]
Parece que tanto faz. O que deve seguir é apenas uma tela com instruções para o SDK ideal, para cada caso.

Parece resolvido. Fechando então.
