### ISSUE TITLE
Ajuda? (node:8164) UnhandledPromiseRejectionWarning: TypeError: content.sentences is not iterable

### ISSUE THREAD

**Issue by MatheusDeAquino** [filipedeschamps/video-maker#237]
**Não detectei nenhuma diferença com o do Filipe. O erro
Aparece assim:**
"
(node:14748) UnhandledPromiseRejectionWarning: TypeError: content.sentences is n
ot iterable
    at fetchImagesOfAllSentences (D:\Matheus\Programação 2018.19\auto-video-proj
ect\auto-videos\robots\image.js:18:40)
    at Object.robot [as image] (D:\Matheus\Programação 2018.19\auto-video-projec
t\auto-videos\robots\image.js:12:11)
    at start (D:\Matheus\Programação 2018.19\auto-video-project\auto-videos\inde
x.js:10:15)
    at Object.<anonymous> (D:\Matheus\Programação 2018.19\auto-video-project\aut
o-videos\index.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
(node:14748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 2)
(node:14748) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
"
**Meu code abaixo:**

```
const imageDownloader = require('image-downloader')
const google = require('googleapis').google
const customSearch = google.customsearch('v1')
const state = require('./state.js')

const googleSearchCredentials = require('../credentials/google-search.json')

async function robot() {
    
    const content = state.load()

    await fetchImagesOfAllSentences(content)
    await downloadAllImages(content)

    state.save(content)

    async function fetchImagesOfAllSentences(content) {
        for (const sentence of content.sentences) {
            const query = '${content.searchTerm} ${sentence.keywords[0]}'
            sentence.images = await fetchGoogleAndReturnImagesLinks(query)

            sentence.googleSearchQuery = query
        }
    }

    async function fetchGoogleAndReturnImagesLinks(query) {
        const response = await customSearch.cse.list({
            auth: googleSearchCredentials.apiKey,
            cx: googleSearchCredentials.searchEngineId,
            q: query,
            searchType: 'image',
            num: 2
        })

        const imagesUrl = response.data.items.map((item) => {
            return item.link
        })

        return imagesUrl
    }

    async function downloadAllImages(content) {
        content.downloadedImages = []

        for (let sentenceIndex = 0; sentenceIndex < content.sentences.length; sentenceIndex++) {
            const images = content.sentences[sentenceIndex].images

            for (let imageIndex = 0; imageIndex < images.length; imageIndex++) {
                const imageUrl = images[imageIndex]

                try {
                    if (content.downloadedImages.includes(imageUrl)) {
                        throw new Error('Imagem já foi baixada')
                    }

                    await downloadAndSave(imageUrl, '${sentenceIndex}-original.png')
                    content.downloadedImages.push(imageUrl)
                    console.log('> [${sentenceIndex}][${imageIndex}] Baixou imagem com sucesso: ${imageUrl}')
                    break
                } catch (error) {
                    console.log('> [${sentenceIndex}][${imageIndex}] Erro ao baixar (${imageUrl}): ${error}')
                }
            }
        }
    }

    async function downloadAndSave(url, fileName) {
        return imageDownloader.image({
            url, url,
            dest: './content/${fileName}'
        })
    }
}

module.exports = robot
```

**Comment by leodutra** [comment]
Resolveu?
