### ISSUE TITLE
ApiKey baixa a mesma imagem (e com erro) !

### ISSUE THREAD

**Issue by MatheusDeAquino** [filipedeschamps/video-maker#238]
O programa está baixando as mesmas imagens porém com dominio esquisito.
![tela erro](https://user-images.githubusercontent.com/43558548/69015962-52e9c900-0978-11ea-9372-1446dfe9925f.JPG)

**Comment by leodutra** [comment]
É um bug conhecido. Por enquanto, coloca as repetições em um array de blacklist e busca outra imagem.
