### ISSUE TITLE
Erro [video-rebot] starting..

### ISSUE THREAD

**Issue by alportblu** [filipedeschamps/video-maker#241]
![image](https://user-images.githubusercontent.com/59105422/71302172-face2a00-235c-11ea-9cff-6bda161d9ad3.png)

Alguem consegue me ajudar?

**Comment by rafaeldepaulalura** [comment]
Estou com o mesmo problema @MatheusRV

**Comment by brunobozz** [comment]
Vocês já instalaram o ImageMagick?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
