### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by renan407** [filipedeschamps/video-maker#242]
Ola, bom dia! se alguém puder me ajudar ficarei grato, depois de adicionar essa function abaixo

 async function fetchKeywordsOfAllSentences(content){
    for (const sentence of content.sentences) {
      sentence.keywords = await fetchWatsonAndReturnKeywords(sentence.text)
    }
  }

O meu console aponta o seguinte erro: 

C:\Windows\System32\video-maker>node index.js
Type a Wikipedia search term: michael jackson

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
(node:6852) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at C:\Windows\System32\video-maker\robots\text.js:91:44
    at C:\Windows\System32\video-maker\node_modules\ibm-watson\natural-language-understanding\v1.js:164:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:6852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.

----------------------------------------------------------------------------------------------------------
segue código Abaixo

const algorithmia = require('algorithmia')
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
const sentenceBoundaryDetection = require('sbd') //observar.. caso nao funcione

const fs = require('fs');
const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('ibm-watson/natural-language-understanding/v1');
const { IamAuthenticator } = require('ibm-watson/auth');
 
const nlu = new NaturalLanguageUnderstandingV1({
  authenticator: new IamAuthenticator({ apikey: watsonApiKey}),
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

async function robot (content){// async esperar a execusao do codigo

  await fetchContentFromWikipedia(content);
  sanitizeContent(content);
  breakContentIntoSentences(content);//observar.. caso nao funcione
  limitMaximumSentences(content);
  await fetchKeywordsOfAllSentences(content)

  async function fetchContentFromWikipedia(content){
    const algorithmiaAuthenticated = algorithmia(algorithmiaApiKey)
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')
    const wikipediaResponse = await wikipediaAlgorithm.pipe(content.searchTerm); //retorna uma promise 'pipe'
    const wikipediaContent = wikipediaResponse.get()

     content.sourceContentOriginal = wikipediaContent.content
  }

  function sanitizeContent(content) {
    const withoutBlankLinesAndMarkdown = removeBlankLinesAndMarkdown(content.sourceContentOriginal)
    const withoutDatesInParentheses = removeDatesInParentheses(withoutBlankLinesAndMarkdown)

    content.sourceContentSanitized = withoutDatesInParentheses

    function removeBlankLinesAndMarkdown(text) {
      const allLines = text.split('\n')

      const withoutBlankLinesAndMarkdown = allLines.filter((line) => {
        if (line.trim().length === 0 || line.trim().startsWith('=')) {
          return false
        }

        return true
      })

      return withoutBlankLinesAndMarkdown.join(' ')
    }
  }

  function removeDatesInParentheses(text) {
    return text.replace(/\((?:\([^()]*\)|[^()])*\)/gm, '').replace(/  /g,' ') //espaços
  }

 async function breakContentIntoSentences(content) {
    content.sentences = []

    const sentences = sentenceBoundaryDetection.sentences(content.sourceContentSanitized)
    sentences.forEach((sentence) => {
      content.sentences.push({
        text: sentence,
        keywords: [],
        images: []
      })
    })
  }

   function limitMaximumSentences(content){
      content.sentences = content.sentences.slice(0, content.maximumSentences)
  }

  async function fetchKeywordsOfAllSentences(content) {
      for (const sentence of content.sentences) {
        sentence.keywords =  await fetchWatsonAndReturnKeywords(sentence.text);
    }
  }

  async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
     nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
      }, (error, response) => {
        if (error) {
          reject(error)
          throw error
        }
         const keywords = response.keywords.map((keyword) => {
          return keyword.text
        })
        resolve(keywords)
      })
    })
  }

  
}
module.exports = robot

**Comment by geleador** [comment]
ESTOU COM O MESMO PROBLEMA E NÃO ACHO NADA E NÃO CONSIGO RESOLVER.

**Comment by geleador** [comment]
Estava com o mesmo problemas achei uma Issues falando sobre esse problema e consegui resolver.
[SEGUE  O LINK](https://github.com/filipedeschamps/video-maker/issues/203)

**Comment by Lorhan7** [comment]
mano
eu estava com esse erro ate agora. a Response da  IBM mudou agora as **Keywords** ficam dentro de uma propriedade chamada **result**

Então na função 

```js

async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
      nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
      }, (error, response) => {
        if (error) {
          reject(error)
          return
        }

        const keywords = response.keywords.map((keyword) => {
          return keyword.text
        })

        resolve(keywords)
      })
    })
  }


```

voce troca o 

>  response.keywords.map((keyword)

Para

response.result.keywords.map((keyword)

**Comment by MatheusRV** [comment]
Obrigado @Lorhan7. Pela solução.

**Comment by brunobozz** [comment]
Hoje me deu esse erro. E agora tive que tirar o RESULT! Que droga isso né?

**Comment by Lorhan7** [comment]
Eu não tenho ideia, o meu tava dando esse erro lá de cima ai eu fui no site do [npm](https://www.npmjs.com/package/ibm-watson)
 e lá esta assim: 
![image](https://user-images.githubusercontent.com/53243389/78300748-fd1c5480-7505-11ea-945e-69280307f0b5.png)

**Comment by marcosCorreia** [comment]
Obrigado @Lorhan7 por me audar a resolver o meu problema

**Comment by fernandossp20** [comment]
Pessoal que compartilhar que tive o mesmo problema. Eu tirei o result e funcionou. Hoje 07/05/2020.
