### ISSUE TITLE
Não roda

### ISSUE THREAD

**Issue by valdney** [filipedeschamps/video-maker#243]
Error: Cannot find module 'C:\Windows\System32\video-maker\indes.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

alguem te ideia da onde esta o erra?

**Comment by MatheusRV** [comment]
você conseguiu rodar o `yarn` ou `npm install`

**Comment by Lorhan7** [comment]
Creio que o erro esteja em;
Error: Cannot find module 'C:\Windows\System32\video-maker\ **indes.js** <=
Deveria ser "index.js" não "indes.js"

**Comment by MatheusRV** [comment]
@Lorhan7 perfeito, isso irá resolver.
