### ISSUE TITLE
[bug] aerenderFilePath is not defined

### ISSUE THREAD

**Issue by renanrox** [filipedeschamps/video-maker#244]
estou tendo esse erro a 3 dias e ainda não consegui resolver.
OBS: Ja pesquisei as diversas formas de prováveis correções e já copiei alguns códigos dos colegas aqui, dentre os quais

 " const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects CC 2019\\Support Files\\aerender.exe'" (utilizando as duas barras)

"  const aerenderFilePath = 'C:/Program Files/Adobe/Adobe After Effects CC 2019/Support Files/aerender.exe' "  (com a barra tradicional)

 const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects CC 2019//Support Files//aerender.exe'  (dupla barra tradicional)

então eu imagino q estou algo grande deixando passar, ou tem alguma configuração q eu possa nao ter feito (mesmo eu acreditando que ja tenha feito tudo)

**Comment by renanrox** [comment]
no mesmo tempo que eu estava realizando o pedido de ajuda, eu fui testando as diversas maneira de preencher, e acabei encontrando a solução

const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects CC 2019//Support Files//aerender.exe' 

 com 2 barras "normais" - não sei se vale a pena deixar a pergunta e a respostas publicadas, mas  gostaria de deixar aqui minha minuscula contribuição para aqueles que tb tenha problemas com essa situação tao boba.

 deixarei a critério dos adms

**Comment by aitorserra** [comment]
Hello,

I have the same error and doesn't work with:

}else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'

or

}else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'

**Comment by aitorserra** [comment]
It doesn't work either with:

        const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('C://video-maker/templates//1//template.aep')
      const destinationFilePath = fromRoot('C://video-maker//content//output.mov')
