### ISSUE TITLE
Problemas [video-robot] !! 

### ISSUE THREAD

**Issue by alportblu** [filipedeschamps/video-maker#247]
![image](https://user-images.githubusercontent.com/59105422/73010020-65dca780-3dc6-11ea-9e75-3dbcebba5e0f.png)

Se alguem conseguir me ajudar, agradeço!
Tenho que instalar o After Effects?

**Comment by giovanikoenig** [comment]
tbm deu esse erro no meu queri saber com resolve

**Comment by ZCErik** [comment]
Eu também tenho o mesmo problema ... Percebi que o robô que gera o inputFile, usa a seguinte URL:

`const inputFile = fromRoot(`./content/${sentenceIndex}-original.png[0]`)`

Estou tentando entender por que a string com o valor de [0] está fixa no final ... Parece que é por isso que o robô não encontra a imagem. Mas tentei removê-lo e nada ... Ainda estou procurando a resposta ... Alguém com alguma sugestão?

**Comment by clovisj** [comment]
o [0] ao final serve para caso a imagem seja um gif, assim pega o primeiro frame

**Comment by ZCErik** [comment]
> o [0] ao final serve para caso a imagem seja um gif, assim pega o primeiro frame

Boaaaa! Vlw

**Comment by brunobozz** [comment]
Eu tive esse erro tbm! Vou contar como contornei.

Pelo que eu entendi o erro estava dando porque eu não tinha o imageMagick instalado. Ele serve para converter as imagens originais nas novas que o video vai usar. A princípio era só isso. Mas no windows não consegui rodar mesmo instalando ele. Resolvi fazer no iMac e ai sim tudo correu bem. 

O filipe não fala disso nos videos. Ele diz que já tem o imageMagick instalado e toca ficha. Ajudaria muito se mostrasse como fazer no windows.

**Comment by fparmezani** [comment]
Olá, 

Encontrei este link que fala sobre o ImageMagic no Windows, 

Link:
http://www.imagemagick.org/script/download.php#windows

Vou tentar esta solução!  Se alguém conseguiu contornar de outra forma, adoraria saber..

Grato

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
