### ISSUE TITLE
Adicionar orientação a comunidade

### ISSUE THREAD

**Issue by matheuschimelli** [filipedeschamps/video-maker#25]
Olá devs. O projeto é muito legal em si próprio, e está possibilitando que muitas pessoas aprendam a programar ou aprendam novas skills. Entretanto, suponho que uma grande parte das pessoas aqui não estão utilizando o espaço de Issues corretamente. Eu vi usuários fazendo a divulgação da comunidade do Discord em Issues abertos até mesmo a criação de Issues somente para divulgar forks em outra linguagem (o que mesmo sendo ótimo, acredito que a sessão Issues não seja o lugar para a divulgação). Assim sendo, proponho que seja adicionado uma sessão de orientação a comunidade (já tem um Issue aberto com a ideia de adicionar um código de conduta, porém acho que esse não abrange orientação de como usar corretamente as seções do Github. Talves orientação até mesmo a utilização do StackOverflow para perguntas e resolução de bugs.

**Comment by glaucia86** [comment]
@matheuschimelli podemos seguir os mesmos passos dos repositórios do Reactjs.org e do Nodejs.org (ambos estou ajudando e colaborando nas traduções)

* [ReactJs.org](https://github.com/reactjs/pt-BR.reactjs.org)
* [Nodejs - pt](https://github.com/nodejs/nodejs-pt)

**Comment by danielschmitz** [comment]
É necessário criar Labels e gerenciá-las. Assim fica mais tql de ver o que a issue representa

**Comment by matheuschimelli** [comment]
Concordo @danielschmitz

**Comment by danielschmitz** [comment]
Conversei com o Filipe, vou ajudá-lo na questão das issues.

**Comment by MatheusRV** [comment]
Estou ajudando nisso, vamos criar mais labels o que acham?
