### ISSUE TITLE
Olha so isso, loucura!

### ISSUE THREAD

**Issue by rafaeldepaulalura** [filipedeschamps/video-maker#251]
Não sai dessa tela, começa e para ai.
O que pode ser?
![we](https://user-images.githubusercontent.com/61248386/76046811-b441a200-5f3f-11ea-8a74-3c5dc819312b.jpg)

**Comment by Lorhan7** [comment]
Mostra o seu código

**Comment by rafaeldepaulalura** [comment]
Eu não mexi nada no código, apenas segui o passo a passo certinho, quando fui testar parou ai, e só fica carregando. @Lorhan7

**Comment by Lorhan7** [comment]
voce consegue digitar qualquer numero
