### ISSUE TITLE
Problemas no Video Robo After Effects

### ISSUE THREAD

**Issue by rafaeldepaulalura** [filipedeschamps/video-maker#253]
**Esse e o Erro que esta dando**

[video-robot] Starting After Effects
(node:14456) UnhandledPromiseRejectionWarning: ReferenceError: aerenderFilePath is not defined
    at C:\Users\User\video-maker\robots\video.js:163:30
    at new Promise (<anonymous>)
    at renderVideoWithAfterEffects (C:\Users\User\video-maker\robots\video.js:147:12)
    at Object.robot [as video] (C:\Users\User\video-maker\robots\video.js:18:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (C:\Users\User\video-maker\index.js:14:3)
(node:14456) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14456) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Aqui esta o código! Peguei ele direto da pasta!**

if (systemPlatform== 'darwin'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }

**Alguém pode dar uma ajuda i?**

**Comment by ZCErik** [comment]
Também estou tentando resolver esse problema ... No começo, pensei que era meu caminho que continha espaços, mas não é ...

**Comment by silvioramalho** [comment]
@rafaeldepaulalura tente declarar aerenderFilePath antes(fora) das condicionais.
Exemplo:

```
let aerenderFilePath = ''
if (systemPlatform== 'darwin'){
aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
}else if (systemPlatform=='win32'){
aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
}else{
return reject(new Error('System not Supported'))
}
```

**Comment by rafaeldepaulalura** [comment]
@silvioramalho Agora apareceu isso.

[video-robot] Starting After Effects
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:Program FilesAdobeAdobe After Effects 2020Support Filesaerender.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:Program FilesAdobeAdobe After Effects 2020Support Filesaerender.exe',
  path: 'C:Program FilesAdobeAdobe After Effects 2020Support Filesaerender.exe',
  spawnargs: [
    '-comp',
    'main',
    '-project',
    'C:\\Users\\User\\video-maker\\templates\\1\\template.aep',
    '-output',
    'C:\\Users\\User\\video-maker\\content\\output.mov'
  ]
}

**Comment by silvioramalho** [comment]
@rafaeldepaulalura verifica se o path para o aerender.exe está correto, e teste se é necessário informar o escape character  `\` antes de `\`, exemplo:

```
aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe'
```

`OBS: No exemplo anterior, se tiver rodando no windows, utilize dentro da condicional referente a plataforma win32.`

**Comment by rafaeldepaulalura** [comment]
@silvioramalho  Top mano, funcionou!!!!!!!!!!!!
Valeu mesmo.....

**Comment by aitorserra** [comment]
Hello,

I have the same error and can't get the program working with:

        const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('./templates/1/template.aep')
      const destinationFilePath = fromRoot('./content/output.mov')


either with

        const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('.\\templates\\1\\template.aep')
      const destinationFilePath = fromRoot('.\\content\\output.mov')

**Comment by aitorserra** [comment]
Either with:

      if (systemPlatform== 'darwin'){
        const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('C:\\video-maker\\templates\\1\\template.aep')
      const destinationFilePath = fromRoot('C:\\video-maker\\content\\output.mov')

**Comment by aitorserra** [comment]
Another variation that doesn't work. I think it have to be anything else:

      if (systemPlatform== 'darwin'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('C:\video-maker\templates\1\template.aep')
      const destinationFilePath = fromRoot('C:\video-maker\content\output.mov')

**Comment by faustoct** [comment]
@aitorserra is a local scope variable. You must try something like

````
...
let aerenderFilePath = null
  if (systemPlatform== 'darwin'){
    aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
  }else if (systemPlatform=='win32'){
    aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
  }else{
    return reject(new Error('System not Supported'))
  }
...
````

**Comment by aitorserra** [comment]
Thank you for your help but it doesn't work:

(node:1920) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:411:3)
    at spawn (child_process.js:547:16)
    at C:\video-maker\robots\video.js:164:24
    at new Promise (<anonymous>)
    at renderVideoWithAfterEffects (C:\video-maker\robots\video.js:147:12)
    at Object.robot [as video] (C:\video-maker\robots\video.js:18:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (C:\video-maker\index.js:14:3)


I have this:

let aerenderFilePath = null
	  
      if (systemPlatform== 'darwin'){
        const aerenderFilePath = '/Applications/Adobe After Effects 2020/aerender'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('C:\video-maker\templates\1\template.aep')
      const destinationFilePath = fromRoot('C:\video-maker\content\output.mov')

**Comment by aitorserra** [comment]
I tried again with:

const aerenderFilePath = '%programfiles%\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'

But same error:

[ERR_INVALID_ARG_TYPE]:

**Comment by faustoct** [comment]
@aitorserra 
1. You may be declaring variable twice like `const aerenderFilePath` and `let aerenderFilePath`. 
2. Your path may be wrong, try to set hardcoded to make sure it's right.
3. The template does have filipe's home path set hardcoded you have to open the template in AfterEffects and change it by yourself.

**Comment by aitorserra** [comment]
Thank you for your help. Anything worked.

I opened the template and relinked all the files. Then, I ran it with:

      if (systemPlatform== 'darwin'){
        const aerenderFilePath = '/Applications/Adobe After Effects 2020/aerender'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = '%programfiles%\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('C:\video-maker\templates\1\template.aep')
      const destinationFilePath = fromRoot('C:\video-maker\content\output.mov')

It didn't work. I tried too with:

      }else if (systemPlatform=='win32'){
        const aerenderFilePath = 'C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\aerender.exe'

And:

const aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'

Any other idea? Thank you.

**Comment by faustoct** [comment]
@aitorserra Try to remove 'const' before aerenderFilePath

**Comment by aitorserra** [comment]
Without the const it worked, thank you.

    if (systemPlatform== 'darwin'){
        const aerenderFilePath = '/Applications/Adobe After Effects 2020/aerender'
      }else if (systemPlatform=='win32'){
        aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'

**Comment by creuza** [comment]
**_Obrigado amigos, esta solução também funcionou para mim!_**

if (systemPlatform== 'darwin'){
    const aerenderFilePath = '/Applications/Adobe After Effects 2020/aerender'
  }else if (systemPlatform=='win32'){
    aerenderFilePath = 'C://Program Files//Adobe//Adobe After Effects 2020//Support Files//aerender.exe'
