### ISSUE TITLE
Erro "node:7887"

### ISSUE THREAD

**Issue by richardqcarvalho** [filipedeschamps/video-maker#258]
![Captura de tela de 2020-04-02 19-02-46](https://user-images.githubusercontent.com/55627630/78304256-b124dc00-7514-11ea-9972-cb4defcea11a.png)

Como resolver?

P.S.: Eu tô no sexto vídeo da playlist, cujo título é "Deep Learning, Web Scraping e Processamento de Linguagem Natural (API grátis)"

**Comment by richardqcarvalho** [comment]
P.S.: Eu tô no sexto vídeo da playlist, cujo título é "Deep Learning, Web Scraping e Processamento de Linguagem Natural (API grátis)"

**Comment by 1010l1010n** [comment]
Estou com mesmo problema! alguém dar um help aqui.

**Comment by bcgs** [comment]
Talvez vocês estejam passando o JSON pro _Algorithmia_ ao invés da **chave** `apikey`.

Sugiro dar uma olhada no import e verificar se tá assim:

`const algorithmiaApiKey = require('../credentials/algorithmia.json').apikey;`

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
