### ISSUE TITLE
(node:20273) &  [DEP0018] 

### ISSUE THREAD

**Issue by silviobonilha** [filipedeschamps/video-maker#261]
Olá pessoal!
Será que algum de vocês poderiam dar uma ajuda com esse erro?
"
(node:20273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

"
(node:20273) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

Obrigado

**Comment by fernandossp20** [comment]
Estou com o mesmo problema que você.

**Comment by fernandossp20** [comment]
Cara eu comentei o If e funcionou aqui, converteu as imagens. O problema era na biblioteca command.js

Minha versao do node é a 12

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
