### ISSUE TITLE
Access is denied due to invalid credentials.

### ISSUE THREAD

**Issue by Amir258** [filipedeschamps/video-maker#265]
# Opa, estou com esse problema, já vi todas as issues nenhuma me resolveu.
Eu criei as credentials tudo certinho, estou acompanhando a série do youtube, ja tentei 2 vezes.
Não sei porque continua dando o mesmo erro.

Está assim:

```js
const watsonApiKey = require('../credentials/watson-nlu.json').apikey
const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
 
var nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,                
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

nlu.analyze({
    text: `Hi I'm Michael Jackson and I like doing the moonwalk dance move.`,
    features: {
        keywords: {}
    }
}, (error, response) => {
    if(error) {
        throw error
    };
    console.log(JSON.stringify(response, null, 4))
    process.exit(0)
});
```

**Comment by Amir258** [comment]
Já dei um `console.log` ele ta me retornando a key certa.

**Comment by Lorhan7** [comment]
Verificou se é `apikey `ou `apiKey`?

**Comment by Amir258** [comment]
> 
> 
> Verificou se é `apikey `ou `apiKey`?

Ele ta retornando a api normal, dei um console.log, ou está falando ali da `iam_apikey`?

**Comment by Amir258** [comment]
> 
> 
> Verificou se é `apikey `ou `apiKey`?

Vou mudar as credentials para ver se funciona

**Comment by Amir258** [comment]
Continua o mesmo erro

**Comment by Amir258** [comment]
# Ih ala, eu fui tentar excluir o serviço e criar outro.

## Bugou, agora aparece que só posso criar se excluir o que já tenho, mas eu já exclui

**Comment by Amir258** [comment]
# Eu já exclui o serviço e criei denovo mesmo assim não consigo, continua o erro.
 ### Se alguem aí souber como resolver me avisa aí

**Comment by Lorhan7** [comment]
Tenta ve se encontra o seu problema nas issues #189 #155

**Comment by Amir258** [comment]
> 
> 
> Tenta ve se voce encontra o seu problema nas issues #189 e na #155

Ué, eu instalo qual modulo? o que ele instalou no vídeo ou o ibm-watson?

**Comment by Amir258** [comment]
> 
> 
> Tenta ve se voce encontra o seu problema nas issues #189 e na #155

Ja tentei fazer tudo, exclui e criar um novo serviço, tentar a conexão q tava na outra issue nada funciona.

**Comment by Amir258** [comment]
> 
> 
> Tenta ve se voce encontra o seu problema nas issues #189 e na #155

Eu acho que talvez seja o url, o meu ta assim `https://gateway.watsonplatform.net/natural-language-understanding/api/`

**Comment by Amir258** [comment]
Ja consegui resolver, quem estiver com o mesmo problema, não esquece de puxar a url do json.
```js
var nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watson.apikey,                
  version: '2018-04-05',
  url: watson.url
});```

Ali em url

**Comment by fabriciocunhauk** [comment]
Também estava tendo o mesmo erro troquei o K do apiKey para k apikei e nada, mas quando troquei o k do iam_apikey: watsonApiKey, dai deu certo.

**Comment by PedroWagnerBomfim** [comment]
@fabriciocunhauk o meu deu certo,  mas agora o erro que gerou foi no Node.

(node:8229) UnhandledPromiseRejectionWarning: authorization required
(node:8229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wendellunny** [comment]
@Amir258 Oh mano, ajudou muito, deu certo aqui. Vlww dms
