### ISSUE TITLE
Problema com after effects

### ISSUE THREAD

**Issue by evertoncarlos** [filipedeschamps/video-maker#267]
Por gentileza alguém pode me ajudar.
![erro](https://user-images.githubusercontent.com/11351590/79630081-e04a6880-8124-11ea-937c-3d98db0b6b3a.PNG)

**Comment by apfjunior** [comment]
Puts, eu optei em outra ferramenta, o FFmpeg no lugar do AE. Tô quebrando a cabeça ainda pra substituir. Sobre o seu erro, acho que tem que dar uma olhada na sua variável `aerenderFilePath`. Uma dica, sempre coloque teu código e o erro pra facilitar a galera te ajudar. Sobre o trecho do teu código, lá onde fica essa variável, está dessa forma? 

```js
async function renderVideoWithAfterEffects() {
    return new Promise((resolve, reject) => {
      const aerenderFilePath =
        "/Applications/Adobe After Effects CC 2019/aerender";
      const templateFilePath = `${rootPath}/templates/1/template.aep`;
      const destinationFilePath = `${rootPath}/content/output.mov`;

      console.log('> [video-robot] Starting After Effects')

      const aerender = spawn(aerenderFilePath, [
        "-comp",
        "main",
        "-project",
        templateFilePath,
        "-output",
        destinationFilePath
      ]);

      aerender.stdout.on("data", data => {
        process.stdout.write(data);
      });

      aerender.on("close", () => {
        console.log("> After Effects closed");
        resolve();
      });
    });
  }
```
Não esquece de apontar: 
```js 
const aerenderFilePath =  local_do_seu_after_effects_instalado_windows```

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
