### ISSUE TITLE
"Request contains an invalid argument"

### ISSUE THREAD

**Issue by iamgoncalo** [filipedeschamps/video-maker#271]
Olá Pessoal, 

Vocês podem-me ajudar?
O que deve ser o argumento inválido?

```

> [text-robot] Sentence: "Beyoncé continued her acting career with starring roles in The Pink Panther , Dreamgirls , and Obsessed ."
> [text-robot] Keywords: acting career, Pink Panther, Beyoncé, roles, Dreamgirls

> [image-robot] Starting...
> [image-robot] Querying Google Images with: "Beyonce"
(node:24986) UnhandledPromiseRejectionWarning: Error: Request contains an invalid argument.
    at Gaxios.<anonymous> (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:24986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Muito obrigado!

**Comment by apfjunior** [comment]
> Olá Pessoal,
> 
> Vocês podem-me ajudar?
> O que deve ser o argumento inválido?
> 
> ```
> 
> > [text-robot] Sentence: "Beyoncé continued her acting career with starring roles in The Pink Panther , Dreamgirls , and Obsessed ."
> > [text-robot] Keywords: acting career, Pink Panther, Beyoncé, roles, Dreamgirls
> 
> > [image-robot] Starting...
> > [image-robot] Querying Google Images with: "Beyonce"
> (node:24986) UnhandledPromiseRejectionWarning: Error: Request contains an invalid argument.
>     at Gaxios.<anonymous> (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:73:27)
>     at Generator.next (<anonymous>)
>     at fulfilled (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:16:58)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:24986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:24986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> Muito obrigado!

Joga o seu código do text-robot aqui pra vermos.

**Comment by iamgoncalo** [comment]
> > Olá Pessoal,
> > Vocês podem-me ajudar?
> > O que deve ser o argumento inválido?
> > ```
> > 
> > > [text-robot] Sentence: "Beyoncé continued her acting career with starring roles in The Pink Panther , Dreamgirls , and Obsessed ."
> > > [text-robot] Keywords: acting career, Pink Panther, Beyoncé, roles, Dreamgirls
> > 
> > > [image-robot] Starting...
> > > [image-robot] Querying Google Images with: "Beyonce"
> > (node:24986) UnhandledPromiseRejectionWarning: Error: Request contains an invalid argument.
> >     at Gaxios.<anonymous> (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:73:27)
> >     at Generator.next (<anonymous>)
> >     at fulfilled (/Users/goncalo/Desktop/Robot/video-maker/node_modules/gaxios/build/src/gaxios.js:16:58)
> >     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > (node:24986) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > (node:24986) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ```
> > 
> > 
> > Muito obrigado!
> 
> Joga o seu código do text-robot aqui pra vermos.

Muito obrigado. Já pus na outra issue!

**Comment by apfjunior** [comment]
> UnhandledPromiseRejectionWarning

@iamgoncalo vi seu código, tá tudo certo. Tentei simular seu erro aqui comigo e consegui repetí-lo  errando os nomes das variáveis do arquivo /credentials/google-search.json. Verifica se está exatamente igual:

```json
{
  "apiKey": "api_here",
  "searchEngineId": "api_here"
}
```

**Comment by iamgoncalo** [comment]
bem, eu não sei o que se passou, mas deveria ter algum erro, porque agora está a dar certo! MUITISSIMO OBRIGADO.

Agora está a falhar em 
```
Starting After Effects
(node:68282) UnhandledPromiseRejectionWarning: ReferenceError: aerenderFilePath is not defined
    at /Users/goncalo/Desktop/Robot/video-maker/robots/video.js:163:30
    at new Promise (<anonymous>)
    at renderVideoWithAfterEffects (/Users/goncalo/Desktop/Robot/video-maker/robots/video.js:147:12)
    at Object.robot [as video] (/Users/goncalo/Desktop/Robot/video-maker/robots/video.js:18:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (/Users/goncalo/Desktop/Robot/video-maker/index.js:14:3)
```

Sabes o que pode ser?
Forte abraço!

**Comment by iamgoncalo** [comment]
Ok consegui! Muito obrigado!!!

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
