### ISSUE TITLE
Video demasiado pesado

### ISSUE THREAD

**Issue by iamgoncalo** [filipedeschamps/video-maker#273]
Graças a vocês consegui que tudo funcionasse muito obrigado!
Como faço para reduzir o tempo, e a tamanhos dos videos? Posso reduzir a qualidade do video?

Muito obrigado e tudo de bom,
Gonçalo

**Comment by agnoldo** [comment]
Oi Gonçalo, sugiro o Handbrake (open source). Muito tranquilo de usar e gera vídeos bem pequenos, se usadas as configurações corretas...

**Comment by faustoct** [comment]
Converti os vídeos para MP4. O vídeo reduziu para 5MB.

**Comment by matbrgz** [comment]
Já existe um tópico relacionado ao tamanho dos arquivos, o Issue https://github.com/filipedeschamps/video-maker/issues/148 seria mais correto para tal assunto. Vou fechar esse issue por se tratar de um assunto duplicado (dup).
