### ISSUE TITLE
Autenticar automaticamente

### ISSUE THREAD

**Issue by iamgoncalo** [filipedeschamps/video-maker#274]
Olá pessoal,

Já estou a conseguir fazer tudo, como posso fazer para que "autentique" automaticamente? Ele pede-me sempre permissão do Youtube.

Abraço e tudo de bom,
Gonçalo

**Comment by apfjunior** [comment]
> Olá pessoal,
> 
> Já estou a conseguir fazer tudo, como posso fazer para que "autentique" automaticamente? Ele pede-me sempre permissão do Youtube.
> 
> Abraço e tudo de bom,
> Gonçalo

Quando você permite uma vez para acessar o youtube, sempre vai direto na aba "Thank you", pelo meno pra mim. O que vc pode fazer pra ficar melhor, sem ficar copiando e colando a url, é passar o parâmetro utilizando o "open". No terminal dentro do projeto, baixe o pacote open:

`npm install open`

Altere o código `youtube-robot.js`, importando o `open`  e adicione na função `requestUserConsent()` a linha para abrir a URL gerada no navegador padrão do sistema.

``` js
const open = require('open');

function requestUserConsent(OAuthClient) {
      const consentUrl = OAuthClient.generateAuthUrl({
        access_type: 'offline',
        scope: ['https://www.googleapis.com/auth/youtube']
      });

      open(consentUrl); //open url browser
    }
``` 
Meu código completo: https://github.com/apfjunior/video-maker/blob/master/robots/youtube.js

**Comment by iamgoncalo** [comment]
Uau, perfeito! Fantástico.
Consegui! Só queria chamar à atenção que o teu vídeo chama-e video-maker.mp4 e não output.mov, mas está ótimo.

Obrigado gigante pela ajuda!

**Comment by apfjunior** [comment]
> Uau, perfeito! Fantástico.
> Consegui! Só queria chamar à atenção que o teu vídeo chama-e video-maker.mp4 e não output.mov, mas está ótimo.
> 
> Obrigado gigante pela ajuda!

Não usei o after effects @iamgoncalo , optei por ferramentas open sources: `vídeoshow` para aplicar efeitos e `FFmpeg` para conversão para .mp4, por isso que está diferente do seu código. 

Bom saber que te ajudou! 😁

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
