### ISSUE TITLE
Erro no imageMagick

### ISSUE THREAD

**Issue by roperes98** [filipedeschamps/video-maker#275]
(node:36007) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: convert "-size" "1920x400" "-gravity" "center" "-background" "transparent" "-fill" "white" "-kerning" "-1" "caption:Natsu "Salamander" Dragneel is a fictional character and protagonist of the Fairy Tail manga series created by Hiro Mashima." "./content/0-sentence.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/Rodrigo/Estudos/video-maker/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:36007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by apfjunior** [comment]
> (node:36007) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: convert "-size" "1920x400" "-gravity" "center" "-background" "transparent" "-fill" "white" "-kerning" "-1" "caption:Natsu "Salamander" Dragneel is a fictional character and protagonist of the Fairy Tail manga series created by Hiro Mashima." "./content/0-sentence.png" this most likely means the gm/convert binaries can't be found
> at ChildProcess. (/Users/Rodrigo/Estudos/video-maker/node_modules/gm/lib/command.js:232:12)
> at ChildProcess.emit (events.js:315:20)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
> at onErrorNT (internal/child_process.js:467:16)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> (node:36007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:36007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

@roperes98 coloca teu código `video-robot.js`, facilita a galera ajudar. Provavelmente seja algum parâmetro setado errado pra renderizar. Na resolução, tenta full hd (1920x1080).
