### ISSUE TITLE
Onde baixar o Extend Script do After Effects?

### ISSUE THREAD

**Issue by roperes98** [filipedeschamps/video-maker#277]
Eu não encontrei o extend script em nenhum lugar para baixar e rodar no after effects... Algm pd me dar alguma dica?

**Comment by Jeffersontee** [comment]
Boa Tarde segue o link 
https://console.adobe.io/downloads/ae
Se não estiver conseguindo aqui esta o instalador 
Windows 32 bits : http://prdl-download.adobe.com/ExtendScriptToolkit/85C17E5FC8B34A7B8483796F0367F97C/1509443329438/Ad...

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
