### ISSUE TITLE
O q é isso? Não encontrei ninguém com esse erro

### ISSUE THREAD

**Issue by Gizati** [filipedeschamps/video-maker#278]
O meu ta dando esse bug e não sei como resolver

Microsoft Windows [versão 6.3.9600]
(c) 2013 Microsoft Corporation. Todos os direitos reservados.

C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>node index.j
s
internal/modules/cjs/loader.js:1222
    throw err;
    ^

SyntaxError: C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker
\credentials\google-search.json: Unexpected string in JSON at position 62
    at parse (<anonymous>)
←[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1219
:22)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:923:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1074:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\alfre_000\Desktop\Alfredo\copia do reposotór
io\video-maker\robots\image.js:6:33)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1185:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:1
0)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m

C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>

**Comment by Fredbeta** [comment]
Tb deu isso para mim

C:\Users\alfre_000\Desktop\Robo\video-maker>npm audit fix
up to date in 1.662s

1 package is looking for funding
  run `npm fund` for details

fixed 0 of 0 vulnerabilities in 576 scanned packages

C:\Users\alfre_000\Desktop\Robo\video-maker>npm fund
video-maker@1.0.0
`-- https://github.com/sponsors/ljharb
  `-- qs@6.9.3

**Comment by apfjunior** [comment]
> O meu ta dando esse bug e não sei como resolver
> 
> Microsoft Windows [versão 6.3.9600]
> (c) 2013 Microsoft Corporation. Todos os direitos reservados.
> 
> C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>node index.j
> s
> internal/modules/cjs/loader.js:1222
> throw err;
> ^
> 
> SyntaxError: C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker
> \credentials\google-search.json: Unexpected string in JSON at position 62
> at parse ()
> ←[90m at Object.Module._extensions..json (internal/modules/cjs/loader.js:1219
> :22)←[39m
> ←[90m at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m
> ←[90m at Function.Module._load (internal/modules/cjs/loader.js:923:14)←[39m
> ←[90m at Module.require (internal/modules/cjs/loader.js:1074:19)←[39m
> ←[90m at require (internal/modules/cjs/helpers.js:72:18)←[39m
> at Object. (C:\Users\alfre_000\Desktop\Alfredo\copia do reposotór
> io\video-maker\robots\image.js:6:33)
> ←[90m at Module._compile (internal/modules/cjs/loader.js:1185:30)←[39m
> ←[90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:1
> 0)←[39m
> ←[90m at Module.load (internal/modules/cjs/loader.js:1034:32)←[39m
> 
> C:\Users\alfre_000\Desktop\Alfredo\copia do reposotório\video-maker>

@Gizati esse erro é de sintaxe. Verifica teu arquivo `google-search.json` se as variáveis estão corretas. Talvez o erro na Issue #271 seja simular.
