### ISSUE TITLE
Erro ao tentar executar o index.js

### ISSUE THREAD

**Issue by ninjaoboladao** [filipedeschamps/video-maker#28]
$ node index.js
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'algorithmia'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\calie\Desktop\video-maker-master\robots\text.js:1:83)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

**Comment by naurojunior** [comment]
Tenta executar antes o 
```` 
npm install
````

Ele instala as dependências (do package.json)

**Comment by ninjaoboladao** [comment]
fiz isso e deu o mesmo erro

**Comment by naurojunior** [comment]
Ele não deu nenhum erro ao executar o npm install? Clonasse o repo com package.json atualizado?

Confere se no teu package.json nas dependências tem o "algorithmia", executa o npm install e posta o resultado aqui

**Comment by Beaast-exe** [comment]
> fiz isso e deu o mesmo erro

tenta esse comando

`npm i algorithmia`

**Comment by danielschmitz** [comment]
Você criou o arquivo `algorithmia.json` com a sua api key ?

**Comment by Pacheco95** [comment]
@danielschmitz por favor explique melhor o que vc quis dizer

**Comment by danielschmitz** [comment]
Você tem que ir no site algorithmia.com, criar uma conta, logar. Aí vc vai aqui:

![image](https://user-images.githubusercontent.com/1509692/53961843-62660200-40c8-11e9-813c-910c3286bfc4.png)

e cria uma chave:

![image](https://user-images.githubusercontent.com/1509692/53961897-845f8480-40c8-11e9-8966-fc8212f573e4.png)

De posse dessa chave, crie um arquivo `algorithmia.json` no diretório `credentials` com ela:

![image](https://user-images.githubusercontent.com/1509692/53962010-c5f02f80-40c8-11e9-9520-087603629335.png)

assim será possível rodar o algorithmiapara que ele traga termos baseados em suas palavras.

**Comment by naurojunior** [comment]
@danielschmitz Correto, mas no caso do erro do guri ali, o node não tá encontrando nem o módulo pra iniciar

**Comment by danielschmitz** [comment]
Ahh tá rs. É que fiz o pull rodei e deu um erro parecido

No caso dele é fazer `npm install` ou "npm install algorithmia`

se mesmo assim nao funcionar, tenta remover a pasta node_modules e executar o `npm install`novamente.

**Comment by brunosereu** [comment]
Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.

Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.

**Comment by brunosereu** [comment]
> Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> 
> Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.

Idealizei este robo do Wikipedia apenas para que não tenhamos o trabalho de pagar o Algorithmia/utilizar os creditos no mesmo, tendo a API da Wikipedia aberta por ela mesmo

**Comment by luizgabriellf** [comment]
> Ahh tá rs. É que fiz o pull rodei e deu um erro parecido
> 
> No caso dele é fazer `npm install` ou `npm install algorithmia`
> 
> se mesmo assim nao funcionar, tenta remover a pasta node_modules e executar o `npm install`novamente.

Pode tentar fazer um `npm cache clean && npm install `

**Comment by brunosereu** [comment]
> > Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> > Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.
> 
> Idealizei este robo do Wikipedia apenas para que não tenhamos o trabalho de pagar o Algorithmia/utilizar os creditos no mesmo, tendo a API da Wikipedia aberta por ela mesmo

Este é o modelo de como esta atualmente:
![screen-recording-_3-7-2019-3-50-35-pm_](https://user-images.githubusercontent.com/19417162/53981270-f3e96a00-40f0-11e9-9309-b9fa22929568.gif)

**Comment by juloko** [comment]
> > > Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> > > Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.
> > 
> > 
> > Idealizei este robo do Wikipedia apenas para que não tenhamos o trabalho de pagar o Algorithmia/utilizar os creditos no mesmo, tendo a API da Wikipedia aberta por ela mesmo
> 
> Este é o modelo de como esta atualmente:
> ![screen-recording-3-7-2019-3-50-35-pm](https://user-images.githubusercontent.com/19417162/53981270-f3e96a00-40f0-11e9-9309-b9fa22929568.gif)

Não sei qual é o pensamento de nosso mestre, mas isso de pagar não coisa que combina com a gente. Já submeteu? Submeta e deixe o mestre analisar, se ele não usar eu uso. =DDD

**Comment by leokbs** [comment]
Juloko, se possível, disponibilize aí pra gente. Realmente, é melhor utilizar a API da própria Wikipedia. Vlw

**Comment by leokbs** [comment]
> > > > Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> > > > Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.
> > > 
> > > 
> > > Idealizei este robo do Wikipedia apenas para que não tenhamos o trabalho de pagar o Algorithmia/utilizar os creditos no mesmo, tendo a API da Wikipedia aberta por ela mesmo
> > 
> > 
> > Este é o modelo de como esta atualmente:
> > ![screen-recording-3-7-2019-3-50-35-pm](https://user-images.githubusercontent.com/19417162/53981270-f3e96a00-40f0-11e9-9309-b9fa22929568.gif)
> 
> Não sei qual é o pensamento de nosso mestre, mas isso de pagar não coisa que combina com a gente. Já submeteu? Submeta e deixe o mestre analisar, se ele não usar eu uso. =DDD

Juloko, se possível, disponibilize aí pra gente. Realmente, é melhor utilizar a API da própria Wikipedia. Vlw

**Comment by leokbs** [comment]
> Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> 
> Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.

Se possível, disponibilize aí pra gente. Realmente, é melhor utilizar a API da própria Wikipedia. Vlw

**Comment by ninjaoboladao** [comment]
**consegui arrumar!** ive que criar manualmente o arquivo 
algorithmia.json e colocar dentro esse codigo `{
  "apiKey": "suachaveaqui"
}` e logo funcionou! eu notei que o arquivo readme.md tinha esse codigo `# Credentials format

## Algorithmia

File: `algorithmia.json`

```
{
  "apiKey": "suachaveaqui"
}
```
 ` mas nao entendi pra que ele serve ja que tive q criar o arquivo manualmente

obrigado @danielschmitz

**Comment by danielschmitz** [comment]
> **consegui arrumar!** Tive que criar manualmente o arquivo
> algorithmia.json e colocar dentro esse codigo `{ "apiKey": "suachaveaqui" }` e logo funcionou! eu notei que o arquivo readme.md tinha esse codigo
> 
> > # Credentials format
> > ## Algorithmia
> > File: `algorithmia.json`
> > ```
> > {
> >   "apiKey": "suachaveaqui"
> > }
> > ```
> 
> ```
> 
>  mas nao entendi pra que ele serve ja que tive q criar o arquivo manualmente
> 
> obrigado @danielschmitz 
> ```

ele precisa da api pra saber que é você que está usando o produto dele, Assim se vc comecar a usar a API dele, tipo, 50 vezes por segundo 24horas por dia, ele vai te bloquear e cobrar. Enquanto estiver usando pouquinho, ele deixa de graça

**Comment by brunosereu** [comment]
> ue combina com a gente. Já submeteu? Submeta e deixe o mestre analisar, se ele não usar eu uso. =DDD

Realizei o Pull Request caso queira visualizar o mesmo/analisar: https://github.com/filipedeschamps/video-maker/pull/34

**Comment by Patricia7sp** [comment]
Pessoal bom dia!

Como estão? 

Eu também estou com problema para executar  index.js ,  só que meu erro e diferente do citado anteriormente.



(node:10065) UnhandledPromiseRejectionWarning: authorization required
(node:10065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

 
conseguem me ajudar?

**Comment by naurojunior** [comment]
@Patricia7sp Isso aí é porque falta o arquivo do Algorithmia nos credentials

Cria um cadastro no Algorithmia (como o Deschamps cita nesse vídeo) https://www.youtube.com/watch?v=8XgbjUP-Gxo

Depois cria na pasta "credentials" um arquivo chamado algorithmia.json com o conteúdo:
````
{
  "apiKey": "sim8As72h56j3mBYqEOSHfLE4k81"
}
````

Só que com a Api Key que o site do Algorithmia te deu.

Boa sorte =)

**Comment by Patricia7sp** [comment]
@naurojunior  Muito obrigada pela atencao.

Eu fiz tudo isso ja,  criei minha conta, peguei meu key,  pasta e arquivo, mas o erro parmanece.

https://github.com/Patricia7sp/rob-s-maker/tree/master/credentials

**Comment by Walicen** [comment]
Colocar a "apiKey" com k maiúsculo e testa novamente.

**Comment by Patricia7sp** [comment]
@Walicen - muito bom em, deu certo, uma coisinha tao besta, e eu não tinha observado que estava em letra minuscula.

**Comment by Patricia7sp** [comment]
@Walicen muito obrigada pela ajuda!!!

**Comment by MatheusDeAquino** [comment]
Meu erro é muito parecido e não consigo resolver!
Criei meu 'algorithmia' manualmente, não usei terminal.
Instalei ele no terminal usando npm install algorithmia

$ node index.js
D:\Matheus\Programação 2018.19\auto-video-project\auto-videos\index.js:4
        text: require('./robots/text.js')
        ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by danielschmitz** [comment]
@MatheusDeAquino veja o #87

**Comment by wsj1983** [comment]
> Meu erro é muito parecido e não consigo resolver!
> Criei meu 'algorithmia' manualmente, não usei terminal.
> Instalei ele no terminal usando npm install algorithmia
> 
> $ node index.js
> D:\Matheus\Programação 2018.19\auto-video-project\auto-videos\index.js:4
> text: require('./robots/text.js')
> ^^^^
> 
> SyntaxError: Unexpected identifier
> at new Script (vm.js:80:7)
> at createScript (vm.js:274:10)
> at Object.runInThisContext (vm.js:326:10)
> at Module._compile (internal/modules/cjs/loader.js:664:28)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
> at startup (internal/bootstrap/node.js:283:19)

Tô travando exatamente nesse problema aí. Todo o rolê das credentials do #87 tá certinho.

**Comment by wsj1983** [comment]
@MatheusDeAquino fiquei travando um tempo com esse problema também.
Não clonei o projeto do Filipe e fui refazendo aqui acompanhando pelos vídeos.
Acontece que qdo ele digita no **index.js**:
`  userInput: require('./robots/user-input.js'),`
`  text: require('./robots/text.js'),`
ele não coloca vírgula no final dessas linhas.
Colocando a vírgula resolve (pelo menos esse problema aí).

> Meu erro é muito parecido e não consigo resolver!
> Criei meu 'algorithmia' manualmente, não usei terminal.
> Instalei ele no terminal usando npm install algorithmia
> 
> $ node index.js
> D:\Matheus\Programação 2018.19\auto-video-project\auto-videos\index.js:4
> text: require('./robots/text.js')
> ^^^^
> 
> SyntaxError: Unexpected identifier
> at new Script (vm.js:80:7)
> at createScript (vm.js:274:10)
> at Object.runInThisContext (vm.js:326:10)
> at Module._compile (internal/modules/cjs/loader.js:664:28)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
> at startup (internal/bootstrap/node.js:283:19)

**Comment by yurimedeiros** [comment]
> @Walicen - muito bom em, deu certo, uma coisinha tao besta, e eu não tinha observado que estava em letra minuscula.

Sua duvida me ajudou, Obrigado @Walicen  a nos ajudar, realmente uma coisa de nada e tudo vai de agua a baixo

**Comment by gilialdo** [comment]
Sou novo usando o node, e tentei executar o index.js, porem deu o erro:

C:\Projetos\node\video-maker>node index.js
module.js:675
    throw err;
    ^

SyntaxError: C:\Projetos\node\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:672:27)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Projetos\node\video-maker\robots\image.js:6:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)

esse erro no arquivo image.js, até onde entendi, tem essa linha:

const googleSearchCredentials = require('../credentials/google-search.json')

na pasta credentials, existe os arquivos algorithmia.json, google-search.json, watson-nlu.json, youtube.json.

meu arquivo google-search.json

{
  "apiKey": "chave gerada pela api do googlesearch"
  "searchEngineId": "chave gerada pela api do youtube"
}

Eles foram criado conforme os passos dados aqui no github, ou seja, todos tem as suas keys.

Alguém sabe informar o motivo do porque desse erro?

**Comment by hebertlima** [comment]
@gilialdo vc criou às credenciais em cada plataforma? e esta faltando uma vírgula no seu google-search.json

```js
{
key: “valor”, //<— essa vírgula
key: ”valor”
}
```

**Comment by julio-byte** [comment]
tenho um erro na hora de usar no postman, quando uso git bash pra rodar o node index.js 

ReferenceError: getUsers is not defined
    at C:\Users\fabio\node.js\Routers\UserRouters.js:30:27
    at Layer.handle [as handle_request] (C:\Users\fabio\node.js\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:137:13)
    at next (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:131:14)
    at Route.dispatch (C:\Users\fabio\node.js\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\fabio\node.js\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\fabio\node.js\node_modules\express\lib\router\index.js:410:3)

**Comment by megavapor** [comment]
> > Algo que notei é que para poder usar o Algorithmia você teria que ter um cadastro, para poder gerar sua key, e poder utilizar a api da Wikipedia, porem para isso é consumido seus creditos da algothmia, e no momento que o mesmo acabar, seria nescessario comprar outros.
> > Em tese não seria nescessario pois a Wikipedia tem sua propria API publica para consumo, e não sendo nescessario utilizar o Algorithmia como intermediador neste caso, desenvolvi um robo do wikipedia apenas para isso, caso queiram eu disponibilizo ele por aqui, por meio de um pull request.
> 
> Idealizei este robo do Wikipedia apenas para que não tenhamos o trabalho de pagar o Algorithmia/utilizar os creditos no mesmo, tendo a API da Wikipedia aberta por ela mesmo

to me batendo pra conseguir rodar, voce ta com ele ai liso? tem fork com essas alterações? valeu
