### ISSUE TITLE
Ajuda no tutorial do README.md do diretório raiz

### ISSUE THREAD

**Issue by rodrigoslayertech** [filipedeschamps/video-maker#282]
Estou na parte de gerar as credenciais lá no Custom Search API e parece que a parte lá foi atualizada pelo o Google e não tem mais somente a pergunta "Qual API você usa?" e pronto.

No tutorial aqui no README.md diz: 
"Procure por Custom Search API no dropdown e clique em "Preciso de quais credenciais?""
"Após isso irá aparecer sua Api Key"
mas não aparece a API Key:

Agora eu preciso responder mais 2 perguntas:

![image](https://user-images.githubusercontent.com/9668277/81466351-56337400-91a7-11ea-8407-be7c3d950cee.png)

"De onde você chamará a API?"

O que eu escolho das opções abaixo?
![image](https://user-images.githubusercontent.com/9668277/81466374-8d098a00-91a7-11ea-960b-2852dd66a8e3.png)

"Que dados você acessará?"
O que eu escolho?

**Comment by alhadef** [comment]
conseguiu resolver? to com o mesmo problema

**Comment by slowaways** [comment]
> conseguiu resolver? to com o mesmo problema

Consegui não, estou esperando a resposta do Felipe

**Comment by leodutra** [comment]
Pessoal, o projeto é executado em Node.js.
Então presumo que seja a segunda opção: "Servidor da Web".

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
