### ISSUE TITLE
(node:9633) [DEP0018]

### ISSUE THREAD

**Issue by AlanPrates** [filipedeschamps/video-maker#285]
Alguém pode me ajudar nesse erros

Choose one option [1, 2, 3, 0]: 3
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:9633) UnhandledPromiseRejectionWarning: authorization required
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9633) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9633) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by roperes98** [comment]
Alan, coloca o seu código aqui pro pessoal ver se pd ter algum erro no código.. o ideal é fazer um repositório aqui no github pra facilitar a visualização

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
