### ISSUE TITLE
Não estou conseguindo chamar função seguinte

### ISSUE THREAD

**Issue by maickom88** [filipedeschamps/video-maker#286]
Estou na aula "

16:47 / 25:07
Deep Learning, Web Scraping e Processamento de Linguagem Natural (API grátis)"
"

e nao consigo executar a proxima funcao que é limpar os espaços . alguem sabe o porque fiz um commit com "error ao chamar function"

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
