### ISSUE TITLE
(node:44306) UnhandledPromiseRejectionWarning: Error: Request contains an invalid argument.

### ISSUE THREAD

**Issue by nixoletas** [filipedeschamps/video-maker#294]
> [image-robot] Starting...
> [image-robot] Querying Google Images with: "michael jackson"
(node:44306) UnhandledPromiseRejectionWarning: Error: Request contains an invalid argument.
    at Gaxios._request (/home/nicholas/video-maker/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bcgs** [comment]
Conseguiu gerar a API key no Google Cloud Platform e configurar o Search Engine?

**Comment by andutra** [comment]
No fim como corrigia o problema? Eu to com o mesmo problema, já tentei regerar a api mas não rolou
