### ISSUE TITLE
Erro no Video-Robot

### ISSUE THREAD

**Issue by iNorox** [filipedeschamps/video-maker#295]
Fala pessoal, todos tranquilos?

Pois então, estava acompanhando os vídeos do Felipe e, além de me encantar com esse Video Maker, fiquei curioso e com vontade de aprender como funcionam esses Bots. Mas depois de implementar todos os códigos, criar e implementar todas as Keys, eu comecei a ter um erro na execução do meu projeto que eu ainda não consegui entender o motivo.

Pelo o que pude acompanhar o erro acontece assim que o Video-Robot é iniciado, mas o que me deixou mais confuso é o fato de que toda vez que eu executo o programa o código de erro é outro.

![image](https://user-images.githubusercontent.com/67293506/85346254-4e1b6380-b4cb-11ea-9fbe-66ab704005a8.png)

![image](https://user-images.githubusercontent.com/67293506/85346275-61c6ca00-b4cb-11ea-946e-f3421a4bb326.png)

![image](https://user-images.githubusercontent.com/67293506/85346324-7acf7b00-b4cb-11ea-9636-072021206f9e.png)

Será que alguém pode me dar uma luz? Me explicar o que está acontecendo, o motivo desse erro e o que eu estou errando?

Desde já agradeço!!
;)

**Comment by bcgs** [comment]
iNorox, dá uma olhada nessa issue #126

**Comment by iNorox** [comment]
Hmmm... Acho que entendi, o problema era rodar o projeto no Windows?? Foi isso??

Bom, depois de fazer o que foi falado ali na issue eu ainda tive um errinho, mas aí foi um pequeno descuido meu... Kkkk

```
events.js:292
Error: spawn C:\Program Files\ImageMagick-7.0.8-Q16\convert.exe ENOENT
```

Como eu baixei uma versão mais recente do ImageMagick eu só precisei alterar o nome da pasta na etapa:

```
Substitua a linha exports.convert.path = 'convert'; por exports.convert.path = "C:\\Program Files\\ImageMagick-7.0.8-Q16\\convert.exe";
```

Agora é só sucesso (literalmente, kkkk)
![image](https://user-images.githubusercontent.com/67293506/85779339-e008b380-b6f9-11ea-90ed-ccb8d75fc7c9.png)

Obrigado @bcgs !!
Tmj

**Comment by bcgs** [comment]
Show!

De fato essa parada do PATH às vezes atrapalha usuários de Windows.
Já que deu tudo certo já pode fechar essa issue. 😄🚀
