### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido -

### ISSUE THREAD

**Issue by rmarangoni** [filipedeschamps/video-maker#301]
![image](https://user-images.githubusercontent.com/49693497/88091586-a5adfd00-cb65-11ea-8f4d-a27f64a822b6.png)
> [video-robot] Starting...
(node:8148) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - (

    at ChildProcess.onExit (C:\Users\rmara\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.cp.emit (C:\Users\rmara\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlanWehrliLC** [comment]
Se ainda estiver tendo problema essa Issue pode resolver...
https://github.com/filipedeschamps/video-maker/issues/110#issuecomment-480595553

Mas resumindo é só reinstalar o ImageMagick e ativar essa opção na instalação "Install legacy utilities (e.g. convert)"
![Install legacy utilities (e g  convert)0](https://user-images.githubusercontent.com/64156830/93352532-51e02d00-f811-11ea-819c-c02afa07ea7b.jpg)
abra o cmd (se estiver aberto, fecha e abre novamente)
digite: magick identify --version

Se aparecer a versão dele, então deu certo
obs.: caso esteja usando o terminal via vs code, reinicie o vs code

**Comment by igorfastronicorrea** [comment]
Estou com o mesmo problema. instalei o ImageMagick conforme o AlanWehrliLC falou, quando eu digito o magick identify --version aparece a versão, mas mesmo assim ainda ta com dando o mesmo erro

**Comment by 1Marcuth** [comment]
> 

Também...

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
