### ISSUE TITLE
erro node:7752 preciso de uma ajuda nao sei mais o que fazer :(

### ISSUE THREAD

**Issue by megavapor** [filipedeschamps/video-maker#304]
ja testei varios forks, o unico que deixou pesquisar a palavra e andou um pouco ate agora foi o do Heber , nao sei mais o que fazer, no do felipe e mais uns 2 que testei da erro antes de colocar a palavra ali, o do heber passou um pouco, da uma luz ai por favor, ja fiz de tudo, conferi as api id key etc tudo certo, vcs sabe se tem alguem que conseguiu monetizar esses videos? youtube nao ta dando block em automatização?

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/youtube-video-maker (master)
$ node index.js
Type a Wikipedia search term: ferrari

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 3
(node:7752) UnhandledPromiseRejectionWarning: Forbidden: Access is denied due to
invalid credentials.
at formatError (E:\videomaker\youtube-video-maker\node_modules\ibm-cloud-sdk
-core\lib\requestwrapper.js:111:17)
at E:\videomaker\youtube-video-maker\node_modules\ibm-cloud-sdk-core\lib\req
uestwrapper.js:259:19
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag --unhandle d-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:7752) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.

**Comment by jhonatanecardoficial** [comment]
Olá, seu problema esta na suas credenciais.

Veja os videos do @filipedeschamps e foca nas partes que ele explica sobre as credenciais (ou keys de acesso.).
https://youtu.be/kjhu1LEmRpY

Provavelmente voce apenas clonou, dessa forma apenas não vai conseguir.

**Comment by PedroWagnerBomfim** [comment]
@megavapor  foca na criação da sua apikey do algorithimia e NLU watson, sem  esquecer de charmas e declarar corretamente no text.js

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
