### ISSUE TITLE
api do google mudou

### ISSUE THREAD

**Issue by alhadef** [filipedeschamps/video-maker#306]
na hora de criar as credenciais do custom search api, me pergunta de onde eu vou chamar ela:
![image](https://user-images.githubusercontent.com/32226684/89703374-6da60880-d920-11ea-90af-fc69bf62b77f.png)

e que dados eu vou acessar:
![image](https://user-images.githubusercontent.com/32226684/89703394-9201e500-d920-11ea-8ad8-eb815ab44408.png)

se eu marcar dados do aplicativo:
![image](https://user-images.githubusercontent.com/32226684/89703406-aa71ff80-d920-11ea-8d96-01053f73ebe0.png)

preciso de ajuda.

**Comment by PedroWagnerBomfim** [comment]
Estou passando por essa situação, o modo de configuração da API do Google mudou e estou meio desnorteado para realizar essa configuração.

- Ao criar credenciais a Google Cloud Plataform solicita:
   - Adicionar credenciais ao seu projeto
       - Qual API você usa?
       - De onde você chamará a API?
       - Que dados você acessará?
  - Crie um ID do cliente OAuth 2.0
      -  Restrições:
          - Origens JavaScript autorizadas?
          - URIs de redirecionamento autorizados?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
