### ISSUE TITLE
(node:3188) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro no v�lido

### ISSUE THREAD

**Issue by aitorserra** [filipedeschamps/video-maker#313]
Hello,

This is the error I'm getting. I installed Imagemagick with the legacy check and graphicmagick too:

> [video-robot] Starting...
(node:3188) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro no v�lido: (

    at ChildProcess.onExit (C:\Users\aitor\Documents\videomaker\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.cp.emit (C:\Users\aitor\Documents\videomaker\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:3188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aitorserra** [comment]
I installed the Adobe After Effects trial and now, the error is:

> [video-robot] Starting After Effects
(node:6308) UnhandledPromiseRejectionWarning: ReferenceError: aerenderFilePath is not defined
    at C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:163:30
    at new Promise (<anonymous>)
    at renderVideoWithAfterEffects (C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:147:12)
    at Object.robot [as video] (C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:18:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async start (C:\Users\aitor\Documents\videomaker\video-maker\index.js:14:3)
(node:6308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by faustoct** [comment]
Veja #253

**Comment by kriacoesmobile** [comment]
> I installed the Adobe After Effects trial and now, the error is:
> 
> > [video-robot] Starting After Effects
> > (node:6308) UnhandledPromiseRejectionWarning: ReferenceError: aerenderFilePath is not defined
> > at C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:163:30
> > at new Promise ()
> > at renderVideoWithAfterEffects (C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:147:12)
> > at Object.robot [as video] (C:\Users\aitor\Documents\videomaker\video-maker\robots\video.js:18:9)
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > at async start (C:\Users\aitor\Documents\videomaker\video-maker\index.js:14:3)
> > (node:6308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> > (node:6308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Were you able to solve this problem?**

**Comment by matbrgz** [comment]
Is this solved? I hope you got it.
I am closing error-related issues to understand which errors still exist, which have already been resolved, and if necessary I can open them again.
