### ISSUE TITLE
Every video uploaded to Youtube it is blocked by default

### ISSUE THREAD

**Issue by aitorserra** [filipedeschamps/video-maker#314]
Hello,

It looks Youtube doesn't like the videos from this program, it blocks every video it uploads automatically:

Términos y políticas
YouTube ha configurado este vídeo como privado. 

Are you having the same problem?

Thank you.

**Comment by faustoct** [comment]
**It is not a video-maker issue**. You should close this issue.

This is a message that comes from YouTube api. If YouTube thinks somehow the api has been misused, or the api usage is not complying with YouTube policies or terms, all they videos uploaded are locked in _private_ mode. 

You should contact them and submit [this form](https://support.google.com/youtube/contact/yt_api_form?hl=en) explain what you are trying to do.

**Comment by matbrgz** [comment]
Closing this cause seems not related to video-maker.
