### ISSUE TITLE
Erro Robô Imagem: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by oberdan-oliveira** [filipedeschamps/video-maker#315]
Por favor, alguém poderia me ajudar com esse erro? Quando executo 
o bot image-robot gera a seguinte crítica: "UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined_". 

_> [image-robot] Starting...
(node:3780) ExperimentalWarning: The http2 module is an experimental API.
(node:3780) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at fetchImagesOfAllSentences (C:\Users\engob\Documents\GitHub\video-maker\robots\image.js:18:67)
    at Object.robot [as image] (C:\Users\engob\Documents\GitHub\video-maker\robots\image.js:12:9)
    at start (C:\Users\engob\Documents\GitHub\video-maker\index.js:15:16)
    at Object.<anonymous> (C:\Users\engob\Documents\GitHub\video-maker\index.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
(node:3780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

O proplema está na propriedade Length, porém não conseguir solucionar. Fico grato se alguém puder me ajudar.

![Erro image-robot](https://user-images.githubusercontent.com/53917512/97122640-1b49dc00-1706-11eb-94a4-59464832599f.PNG)

Segue abaixo o código que está com o erro:
https://github.com/filipedeschamps/video-maker/blob/master/robots/image.js

**Comment by LeonardoDalessandro** [comment]
Oi oberdan-oliveira vc fez algumas mudanças no seu codigo? Talvez o robô de texto nao està funcionando. Verifica que no arquivo content.json tem todas as frases no formato de array.

**Comment by oberdan-oliveira** [comment]
> Oi oberdan-oliveira vc fez algumas mudanças no seu codigo? Talvez o robô de texto nao está funcionando. Verifique se no arquivo content.json tem todas as frases no formato de array.

Na realidade, eu não tenho esse arquivo content.json... A pasta Content está vazia :(

**Comment by LeonardoDalessandro** [comment]
Provavelmente é sò isso. Tenta criar o arquivo "content.json", dentro a pasta "content" e roda o node. Esse arquivo vai ser o seu DB.

**Comment by oberdan-oliveira** [comment]
Leonardo, por favor, poderia me enviar a estrutura desse json!? 😎 Vai me ajudar d+++

**Comment by LeonardoDalessandro** [comment]
no arquivo "content.json", na linha 1, coloca sò:
{}

depois roda o node de novo

**Comment by oberdan-oliveira** [comment]
> no arquivo "content.json", na linha 1, coloca sò:
> 
> ```
> {}
> ```
> 
> depois roda o node de novo

Muitíssimo obrigado pelo apoio, Leonardo! 
Porém, gerou o mesmo erro com a propriedade length :(

![image](https://user-images.githubusercontent.com/53917512/97243615-7ac2ed00-17d5-11eb-9952-f30397936dd9.png)

**Comment by LeonardoDalessandro** [comment]
De nada meu amigo. Olha, pelo o que vc colocou aqui, tem algum problema antes.
O text-robot nao està trazendo os conteudos de wikipedia para o seu projeto.
Olha diretinho como està trabalhando essa parte.

Tenta isolar o problema assim:
```
const robots = {
  /*input: require('./robots/input.js'),*/

  text: require('./robots/text.js'),
  state: require('./robots/state.js'),

  /*
  image: require('./robots/image.js'),
  video: require('./robots/video.js'),
  youtube: require('./robots/youtube.js')
  */
}

async function start() {
  /*robots.input()*/

  await robots.text()

  /*
  await robots.image()
  await robots.video()
  await robots.youtube()
  */
}

start()
```

Assim pode fazer um debug melhor do text-robot.
Coloca um console.log() pra cada input e cada output pra ver se o fluxo de dados està saido como esperado o nao.

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
