### ISSUE TITLE
Sera que corre em PHP?

### ISSUE THREAD

**Issue by ldobreira** [filipedeschamps/video-maker#318]
Sera que é possivel fazer este mesmo projecto em PHP?

**Comment by programadoramauri** [comment]
Observando as dependências do projeto, apenas não encontrei um alternativo para o SDB. O express pode ser substituido pelo "php -S" ou usar o swoole e todas as outras dependências você tem uma versão em PHP.

**Comment by ldobreira** [comment]
Obrigado @programadoramauri
