### ISSUE TITLE
google.customSearch is not a function

### ISSUE THREAD

**Issue by PedroWagnerBomfim** [filipedeschamps/video-maker#322]
Prezados,

Ao tentar executar o sistema, estou recebendo o seguinte reporte.

<pre>/home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/image.js:2
const customSearch = google.customSearch(&apos;v1&apos;);
                            ^

TypeError: google.customSearch is not a function
    at Object.&lt;anonymous&gt; (/home/pedro/Documentos/projetos/Sistema-Video-Maker/robots/image.js:2:29)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:1063:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)</font>
<font color="#555753">    at Module.load (internal/modules/cjs/loader.js:928:32)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:769:14)</font>
<font color="#555753">    at Module.require (internal/modules/cjs/loader.js:952:19)</font>
<font color="#555753">    at require (internal/modules/cjs/helpers.js:88:18)</font>
    at Object.&lt;anonymous&gt; (/home/pedro/Documentos/projetos/Sistema-Video-Maker/index.js:5:10)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:1063:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)</font>
</pre>

Não estou conseguindo identificar onde esta o erro ou bug.

**Comment by LeonardoDalessandro** [comment]
Oi Pedro tudo bem?

Antes, de entrar no detalhes do erro, lembra que não é recomendado um nome de pasta desse tipo "nome-da-pasta".
Tenta sempre usar essa forma:
"nome_da_pasta"
ou
"NomeDaPasta".

Isso porque pode gerar problemas de interpretaçao do caráter: "-"

Sobre o erro, eu queria entender melhor o contexto.
Vc editou algumas linhas de codigo ou vc està rodando o script da mesma forma que podemos encontrar nesse repositorio?

Caso vc editou, pode escriver aqui essas linhas por favor?

Abraços

**Comment by PedroWagnerBomfim** [comment]
Prezado @LeonardoDalessandro ,

Estou seguindo o tutorial conforme os videos do Felipe.

No momento o meu arquivo 'index.js' está da seguinte forma:

`const robots = {
  input: require("./robots/input.js"),
  text: require("./robots/text.js"),
  state: require("./robots/state.js"),
  image: require("./robots/image.js"),
};

async function start() {
  robots.input();
  await robots.text();
  await robots.image();

  const content = robots.state.load();
  console.dir(content, { depth: null });
}

start();
`

O arquivo recém criado é o image.js:

`const google = require("googleapis").google;
const customSearch = google.customSearch("v1");
const state = require("./state.js");

const googleSearchCredentials = require("../credentials/google-search.json");

async function robot() {
  const content = state.load();

  await fetchImagesOfAllSenternces(content);

  state.save(content);

  async function fetchImagesOfAllSenternces(content) {
    for (const sentence of content.sentences) {
      const query = "${content.searchTerm} ${sentence.keywords[0]}";
      sentence.images = await fetchGoogleAndReturnImagesLinks(query);

      sentence.googleSearchQuery = query;
    }
  }

  async function fetchGoogleAndReturnImagesLinks(query) {
    const response = await customSearch.cse.list({
      auth: googleSearchCredentials.apikey,
      cx: googleSearchCredentials.searchEngineId,
      q: query,
      searchType: "image",
      imgSize: "huge",
      num: 2,
    });

    const imagesUrl = response.data.items.map((item) => {
      return item.link;
    });

    return imagesUrl;
  }
}

module.exports = robot;
`

Acabei de finalizar o vídeo https://www.youtube.com/watch?v=LzPuCVhdUew&list=PLMdYygf53DP4YTVeu0JxVnWq01uXrLwHi&index=9 e estou iniciando o https://www.youtube.com/watch?v=qwLH112DM54&list=PLMdYygf53DP4YTVeu0JxVnWq01uXrLwHi&index=10&t=6s.

**Comment by LeonardoDalessandro** [comment]
Oi Pedro! Beleza, vamos tentar resolver para exclusão.

Vc encontra no seu package.json essa linha?

```
"googleapis": "^38.0.0",
```

Se sim otimo, se nao roda no seu terminal:

```
npm i googleapis
```

**Comment by PedroWagnerBomfim** [comment]
Prezado @LeonardoDalessandro,


No meu arquivo  package.json consta o seguinte versão:

`{
  "name": "sistema-video-maker",
  "version": "1.0.0",
  "description": "Projeto open soucer para a criação de videos automatizados",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/PedroWagnerBomfim/Sistema-Video-Maker.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/PedroWagnerBomfim/Sistema-Video-Maker/issues"
  },
  "homepage": "https://github.com/PedroWagnerBomfim/Sistema-Video-Maker#readme",
  "dependencies": {
    "algorithmia": "^0.3.10",
    "googleapis": "^66.0.0",
    "readline-sync": "^1.4.9",
    "sbd": "^1.0.18",
    "watson-developer-cloud": "^4.0.1"
  }
}
`

**Comment by LeonardoDalessandro** [comment]
Bom dia.
Otimo, era pra ter certeza que todas as dependencias estao presente.

Agora, percebi o seguinte erro:

```
const query = "${content.searchTerm} ${sentence.keywords[0]}";
```

A interpolaçao nao pode ser feita dessa forma em javascript.
Como vc escriveu a const **_query_** vai retornar erro.

Tenta da seguente forma:

```
const query = `${content.searchTerm} ${sentence.keywords[0]}`;
```
ou se vc prefere:
```
const query = content.searchTerm + ' ' + sentence.keywords[0];
```

O parametro **_query_**, nesse caso, è muito importante porque è o input que vc manda para a api do google.
Por favor, olha pra mim se resolvendo esse pequeno erro vai dar tudo certo. Pode ser?

Abraços

**Comment by PedroWagnerBomfim** [comment]
@LeonardoDalessandro , 


Realizei a alteração sugerida por você, porem ao executar o comendo 'node index.js' o sistema reporta:


<pre>node index.js
/home/pedro/Documentos/projetos/sistema_video_maker/robots/image.js:2
const customSearch = google.customSearch(&quot;v1&quot;);
                            ^

TypeError: google.customSearch is not a function
    at Object.&lt;anonymous&gt; (/home/pedro/Documentos/projetos/sistema_video_maker/robots/image.js:2:29)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:1063:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)</font>
<font color="#555753">    at Module.load (internal/modules/cjs/loader.js:928:32)</font>
<font color="#555753">    at Function.Module._load (internal/modules/cjs/loader.js:769:14)</font>
<font color="#555753">    at Module.require (internal/modules/cjs/loader.js:952:19)</font>
<font color="#555753">    at require (internal/modules/cjs/helpers.js:88:18)</font>
    at Object.&lt;anonymous&gt; (/home/pedro/Documentos/projetos/sistema_video_maker/index.js:5:10)
<font color="#555753">    at Module._compile (internal/modules/cjs/loader.js:1063:30)</font>
<font color="#555753">    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)</font></pre>

**Comment by LeonardoDalessandro** [comment]
Boa noite.
Eu acho que achei qual é o problema.

Vc colocou assim:
```
const customSearch = google.customSearch("v1");
```
**customSearch()** nao existe na api do Google, vc tem que mudar para **customsearch()**, com todos os caracteres minúsculos :
```
const customSearch = google.customsearch("v1");
```

Tenta mudar dessa forma e me fale se resolveu.

Abraços

**Comment by PedroWagnerBomfim** [comment]
@LeonardoDalessandro  sua observação foi precisa, a situação foi resolvida... Só que agora o sistema retorna o seguinte:

<pre>Type a Wikipedia search term: nba

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 3
&gt; [text-robot] Starting...
&gt; [text-robot] Fetching content from Wikipedia
&gt; [text-robot] Fetching done!
&gt; [text-robot] Starting to fetch keywords from Watson
&gt; [text-robot] Sentence: &quot;The National Basketball Association is an American men&apos;s professional basketball league.&quot;
&gt; [text-robot] Keywords: National Basketball Association, American men&apos;s professional basketball league

&gt; [text-robot] Sentence: &quot;It is composed of 30 teams and is one of the four major professional sports leagues in the United States and Canada.&quot;
&gt; [text-robot] Keywords: major professional sports leagues, United States, teams, Canada

&gt; [text-robot] Sentence: &quot;It is the premier men&apos;s professional basketball league in the world&quot;
&gt; [text-robot] Keywords: premier men&apos;s professional basketball league, world

&gt; [text-robot] Sentence: &quot;The league was founded in New York City on June 6, 1946, as the Basketball Association of America .&quot;
&gt; [text-robot] Keywords: New York City, league, June, Basketball Association of America

&gt; [text-robot] Sentence: &quot;It changed its name to the National Basketball Association on August 3, 1949, after merging with the competing National Basketball League .&quot;
&gt; [text-robot] Keywords: National Basketball Association, competing National Basketball League, name, August

(node:5898) UnhandledPromiseRejectionWarning: TypeError: Cannot read property &apos;map&apos; of undefined
    at fetchGoogleAndReturnImagesLinks (/home/pedro/Documentos/projetos/sistema_video_maker/robots/image.js:33:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async fetchImagesOfAllSenternces (/home/pedro/Documentos/projetos/sistema_video_maker/robots/image.js:17:25)
    at async Object.robot [as image] (/home/pedro/Documentos/projetos/sistema_video_maker/robots/image.js:10:3)
    at async start (/home/pedro/Documentos/projetos/sistema_video_maker/index.js:11:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5898) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5898) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</pre>

**Comment by PedroWagnerBomfim** [comment]
@LeonardoDalessandro  O sistema informa que a propriedade 'map' está indefinida.

Mas na linha abaixo

`const imagesUrl = response.data.items.map((item) => {
      return item.link
    })`

A const imagesUrl  o response, as propriedades data e items, o método map e o parâmetro item, no final eu retor o resultado para o parâmetro adicionando a propriedade link... Ao meu ver está tudo correto.

Mas em outras issues, eu verifiquei que   "o erro ocorre durante a pesquisa das imagens. Verifique se em sua Custom Search Engine a opção Image Search está habilitada."

Onde encontro essa opção?

**Comment by PedroWagnerBomfim** [comment]
Na conta api search engine eu definitivamente não consegui encontrar, mas nas configurações básicas do 'searc engine' , já consta ativo.

-  https://cse.google.com
![image](https://user-images.githubusercontent.com/17617563/102946191-a7764680-449e-11eb-88d6-c011e7778c38.png)
![image](https://user-images.githubusercontent.com/17617563/102946223-c248bb00-449e-11eb-8319-b45ae271735e.png)

**Comment by LeonardoDalessandro** [comment]
@PedroWagnerBomfim olà. 
Por favor, lembra sempre de crear um issue especifico para cada problema que vc quer resolver.
Isso porque vai ajudar bastante todas as pessoas que tiver a sua mesma dificuldade.
Tenta sempre coloca sempre um titolo bem especifico e que resume o conteudo.
Quando for posivel, coloca um label tambem.

**Comment by LeonardoDalessandro** [comment]
@PedroWagnerBomfim 

> @LeonardoDalessandro O sistema informa que a propriedade 'map' está indefinida.
> 
> Mas na linha abaixo
> 
> `const imagesUrl = response.data.items.map((item) => { return item.link })`
> 
> Na const imagesUrl recebe o response, as propriedades data e items, o método map e o parâmetro item, no final eu retor o resultado para o parâmetro adicionando a propriedade link... Ao meu ver está tudo correto.
> 
> Mas em outras issues, eu verifiquei que "o erro ocorre durante a pesquisa das imagens. Verifique se em sua Custom Search Engine a opção Image Search está habilitada."
> 
> Onde encontro essa opção?

Esse erro que vc mostrou nao està falando que **.map()** è _undefined_.
O .map() è um "metodo do javascript" è ele nao pode ser undefined ([https://www.w3schools.com/jsref/jsref_map.asp](https://www.w3schools.com/jsref/jsref_map.asp)).

O que è resulta _undefined_ è sempre o que fica antes do metodo, que nesse caso deveria ser o seu array.
Tenta o seguinte, para entender a qual nivel tem o erro:
```
console.log(response)
console.log(response.data)
console.log(response.data.items)
```

Abraços
