### ISSUE TITLE
Ta dando esse erro aí quando executo o "node index.js" no Cmder, ja andei editando as credentials para ver se resolve mas sempre da um erro. Preciso que alguém me ajude a resolver isso, que quero executar o projeto e ver se da pra ajudar deixar ele ainda melhor. Desde ja agradeço quem puder me ajudar.

### ISSUE THREAD

**Issue by guiflor** [filipedeschamps/video-maker#323]
λ node index.js
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Users\Administrador\Desktop\Cmder\video_maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at parse (<anonymous>)

Veja aqui a imagem do erro no terminal:
https://imgur.com/a/WLisNjs

**Comment by kriacoesmobile** [comment]
Pela imagem parece que o problema está no arquivo json mal formatado, você conseguiu resolver?

**Comment by wfserafim** [comment]
@kriacoesmobile e @guiflor estou com o mesmo problema e também não consegui resolver. Consegue dar um apoio ?

**Comment by aronrodrigues** [comment]
Nem sei como explicar: Vocês leram a mensagem de erro?
```
"SyntaxError: C:\Users\Administrador\Desktop\Cmder\video_maker\credentials\google-search.json: Unexpected string in JSON at position 60".
```
Caso não entendam inglês, segue mensagem traduzida pelo Google Tradutor:
```
SyntaxError: C: \ Users \ Administrador \ Desktop \ Cmder \ video_maker \ credentials \ google-search.json: string inesperada em JSON na posição 60
```

Conseguiram resolver?

**Comment by hucas520** [comment]
Estou com o mesmo problema

**Comment by aronrodrigues** [comment]
Um puxão de orelhas. O Deschamps fez tudo do zero e vocês não conseguem se
virar pra resolver um problema?

**Comment by danilojm** [comment]
Olá @guiflor, tudo bom?
Se você abrir o seu arquivo google-search.json, vai ver que estará faltando a virgula no final da linha "apiKey"
{
  "apiKey": "API_KEY_AQUI" , **<--**
  "searchEngineId": "ID_MECANISMO_DE_BUSCA"
}

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
