### ISSUE TITLE
Erro na hora de executar o node index js

### ISSUE THREAD

**Issue by guiflor** [filipedeschamps/video-maker#324]
λ node index.js
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Users\Administrador\Desktop\Cmder\video_maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at parse (<anonymous>)

at Object.<anonymous> (C:\Users\Administrador\Desktop\Cmder\video_maker\robots\image.js:6:33)

Veja qui a imagem do erro: 
https://imgur.com/a/WLisNjs

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
