### ISSUE TITLE
UnhandledPromiseRejectionWarning: invalid_request

### ISSUE THREAD

**Issue by KriacoesMobile** [filipedeschamps/video-maker#327]
Galera estou tentando fazer upload do vídeo mas sempre retorna esse erro mesmo após permitir e retornar o token onde deveria iniciar o upload ele da erro e fecha. Alguém já passou por isso e pode ajudar?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
