### ISSUE TITLE
 Convert: improper image header () ImageMagic

### ISSUE THREAD

**Issue by KriacoesMobile** [filipedeschamps/video-maker#328]
Alguém está enfrentando esse problema? Ao tentar converter uma imagem ele retorna erro, mas é porque o cabeçalho do png está incorreto, são imagens normalmente do facebook que apresenta esse erro, estava tentando validar as imagens antes de fazer o download para evitar esse erro mas não consegui validar a url. Minha ideia seria um if tipo:

      	 if(imageUrl === ".png|.jpg" ){
      	 	const imageUrl = images[imageIndex]
      	 }

Alguém poderia dar uma força não sou tão familiarizado com Node.js.

Como um paliativo após a função terminar de fazer o download das imagens antes da conversão eu pauso o script para verificar se todas as imagens são boas.

Segue parte do texto (robots/video.js) pois pode ajudar alguém.

await askToContinue()

async function askToContinue() {
    const continuar = ['Continuar']
    const selectedContinuarIndex = readline.keyInSelect(continuar, 'Verifique na pasta content se todas as imagens originais sao visiveis, antes continuar...')
    const selectedContinuarText = continuar[selectedContinuarIndex]
  }

PS: Sou curioso se tiver uma forma melhor de fazer essa funçaõ por favor corrijam o código.

**Comment by richarddiogo** [comment]
Arrumou com?
 if(imageUrl === ".png|.jpg" ){
  	const imageUrl = images[imageIndex]
  }
Pelo oque vi aqui tem bastante código que precisa de if pra tratar alguns erros


mas o meu da outro erro,
[video-robot] Starting...
(node:15813) UnhandledPromiseRejectionWarning: Error: Could not execute GraphicsMagick/ImageMagick: convert "/Desktop/videomaker/video-maker-master/content/0-original.png[0]" "(" "-clone" "0" "-background" "white" "-blur" "0x9" "-resize" "1920x1080^" ")" "(" "-clone" "0" "-background" "white" "-resize" "1920x1080" ")" "-delete" "0" "-gravity" "center" "-compose" "over" "-composite" "-extent" "1920x1080" "/Desktop/videomaker/video-maker-master/content/0-converted.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Desktop/videomaker/video-maker-master/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:15813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15813) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kriacoesmobile** [comment]
Olá meu amigo, não consegui verificar a url, mas acabei utilizando uma nova abordagem parando a conversão de imagens antes dela iniciar., logo após o download assim consigo verificar se todas as imagens são visíveis e de acordo com o contexto. Você pode verificar um video gerado com o sistema, é claro depois de inúmeras personalizações de estrutura e template. https://youtu.be/tC9fyIzdraA?list=PLKkjpqTAZG16FJbgAAElPipxtxdGPWADY

**Comment by richarddiogo** [comment]
FICOU muito bom! compartilha com a gente se possivel

o meu problema resolvi atualizando algumas coisas  e baixando 
`sudo add-apt-repository ppa:dhor/myway
sudo apt-get update
sudo apt-get install graphicsmagick
sudo apt-get install imagemagick`

**Comment by rzfzr** [comment]
@kriacoesmobile o teu template ficou muito massa! mas nao esta disponivel no teu fork ne?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
