### ISSUE TITLE
aerenderFilePath is not defined

### ISSUE THREAD

**Issue by NiinjaFeroz** [filipedeschamps/video-maker#332]
> [video-robot] Starting After Effects
(node:4812) UnhandledPromiseRejectionWarning: ReferenceError: aerenderFilePath is not defined
    at Promise (C:\Users\Lucas\Documents\Projeto\Video-Maker\robots\video.js:163:30)
    at new Promise (<anonymous>)
    at renderVideoWithAfterEffects (C:\Users\Lucas\Documents\Projeto\Video-Maker\robots\video.js:147:12)
    at Object.robot [as video] (C:\Users\Lucas\Documents\Projeto\Video-Maker\robots\video.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

o código:  async function renderVideoWithAfterEffects() {
    return new Promise((resolve, reject) => {
      const systemPlatform=os.platform
	  	 
      if (systemPlatform== 'darwin'){
        const aerenderFilePath = '%programfiles%\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe'
      }else if (systemPlatform=='win32'){
        const aerenderFilePath = '%programfiles%\Adobe\Adobe After Effects CC 2019\Support Files\aerender.exe'
      }else{
        return reject(new Error('System not Supported'))
      }
      
      const templateFilePath = fromRoot('${rootPath}/templates/1/template.aep')
      const destinationFilePath = fromRoot('${rootPath}/content/output.mov')

      console.log('> [video-robot] Starting After Effects')

      const aerender = spawn(aerenderFilePath, [
        '-comp', 
		'main',
        '-project', 
		templateFilePath,
        '-output', 
		destinationFilePath
      ])

      aerender.stdout.on('data', (data) => {
        process.stdout.write(data)
      })

      aerender.on('close', () => {
        console.log('> [video-robot] After Effects closed')
        resolve()
      })
    })
  }

}

module.exports = robot

**Comment by rzfzr** [comment]
Acho que ele n esta detectando o sistema nesse primeiro if else, tenta colocar o caminho dele diretamente no spawn, assim:
```
      const aerender = spawn('C:\\Program Files\\Adobe\\Adobe After Effects 2020\\Support Files\\aerender.exe', [
        '-comp', 'main',
```

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
