### ISSUE TITLE
Problema ao upar quaisquer vídeos

### ISSUE THREAD

**Issue by Pedro-Estevao** [filipedeschamps/video-maker#334]
Ao terminar o projeto e testar, percebo que na parte do robô do youtube, ao upar o vídeo, o mesmo fica com a visibilidade como: Privado (bloqueado)[Primeiro] sendo impossível mudar. Isso só ocorre quando o vídeo é enviado pelo projeto, porém quando envio manualmente(colocando mesmo título, mesma descrição, tags, thumbnail, etc)[segundo] a visibilidade poder ser alterada sem nenhum problema. Alguém poderia me dizer como resolver? ?
![Screenshot_18](https://user-images.githubusercontent.com/61397405/105888754-23a70100-5fec-11eb-9efc-91925a8e5311.jpg)

**Comment by richarddiogo** [comment]
Ta com a ultima versão do projeto?

**Comment by Wizard-Anorak** [comment]
Sim, eu fui seguindo a playlist e realizando as atualizações necessárias.
Porém mesmo assim, não vai.

**Comment by rodmessias** [comment]
O YouTube mudou as diretrizes de upload e vc precisa autorizar seu app https://support.google.com/youtube/contact/yt_api_form enviando este formulário, eu segui os passos e recebi a aprovação do meu, mas ainda assim o meu upload é bloqueado, acredito que possa ser algo com a validação do domínio autorizado no developer console, que agora só permite dominios válidos e não mais localhost

**Comment by reinaldomml** [comment]
@rodmessias Fala cara, teve alguma atualização sobre esse problema, utilizando uma URL válida? O vídeo entrou como público?

> só permite dominios válidos e não mais localhost

**Comment by rodmessias** [comment]
@reinaldomml eu entrei em contato com o youtube eles me responderam que estavam avaliando o ocorrido, encaminhei todas as evidencias e ate o momento não obtive resposta.

**Comment by matbrgz** [comment]
Esse erro não é relacionada ao sistema video-maker, mas sim ao YouTube. Vou fechar esse issue qualquer coisa podemos reabrir.
