### ISSUE TITLE
Estou com problemas

### ISSUE THREAD

**Issue by AndradeYamaoka** [filipedeschamps/video-maker#337]
Não estou conseguindo resolver.
Me ajudem, desde já, muito obrigado.fica dando esse erro, do print,
![Screenshot 2021-03-03 194027](https://user-images.githubusercontent.com/68540415/109882659-fe478b80-7c58-11eb-96ba-2194b63fd589.png)

**Comment by ellioenay21** [comment]
Gente pra quem está com dificuldades de executar o comando 'converte 0-original.png -resize 50% 0-converted.png
' ou quando aparece 'Parâmetro invalido' faz o seguinte:
1-  no site do ImageMagick clique em Download, após isso procure por Windows, e baixe o arquivo .exe http. Após isso instale ele no computador.


2- No terminal executem o comando npm install gm.


3 -  Ao invés de usar o comando 'convert 'use o comando 'magick' que no final ficara: 'magick 0-original.png -resize 50% 0-converted.png'


Pronto após isso funcionara perfeitamente

**Comment by weslleyfaria** [comment]
Estou com problema parecido com o do colega @AndradeYamaoka,

Depois de executar o `npm i gm`, não consigo atribuir os comandos como no vídeo onde o @filipedeschamps ensina.

Tentei realmente instalar o ImageMagick, versão com dll, mais preciso esta: "ImageMagick-7.0.11-13-Q16-HDRI-x64-dll.exe"

Sem êxito.

Se eu entendi alguma coisa:

1º Instalar o ImageMagick;
2º Executar o `npm i gm`;
3º Executar algum comando via prompt `convert <nome imagem> <comando ex: -resize 50%> <nome arquivo saída + extensão png, jpg etc.>`

Preciso de ajuda...

**Comment by weslleyfaria** [comment]
**Parece que aconteceu algum progresso**

![image](https://user-images.githubusercontent.com/51805270/119064811-97618500-b9b2-11eb-8d05-e3670e0c8e5b.png)
![image](https://user-images.githubusercontent.com/51805270/119064842-a21c1a00-b9b2-11eb-9672-7499cc36cb5e.png)

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
