### ISSUE TITLE
Pessoal estou passando por um problema com o gm e imagemagick

### ISSUE THREAD

**Issue by gogaoliveira** [filipedeschamps/video-maker#338]
estou acompanhando a video aula e na parte que que começa a tratar as imagens, estou tendo erros, como por exemplo:

$ node index.js
> [image-robot] Starting...
(node:5064) UnhandledPromiseRejectionWarning: ReferenceError: fromRoot is not defined
    at C:\Users\6110173\videomaker\robots\image.js:78:29
    at new Promise (<anonymous>)
    at convertImage (C:\Users\6110173\videomaker\robots\image.js:77:16)
    at convertAllImages (C:\Users\6110173\videomaker\robots\image.js:72:19)
    at Object.robot [as image] (C:\Users\6110173\videomaker\robots\image.js:15:11)
    at start (C:\Users\6110173\videomaker\index.js:11:15)
    at Object.<anonymous> (C:\Users\6110173\videomaker\index.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rej
ecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https:
//nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
 with a non-zero exit code.

**Comment by rzfzr** [comment]
Instalou e adicionou o imagemagick ao path?
Se abrir um cmd e digitar `magick -version`, ele te retorna algo?

**Comment by gogaoliveira** [comment]
retorna isso 

C:\Users\6110173>magick -version
Version: ImageMagick 7.0.11-2 Q16 x64 2021-02-28 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192829337
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib
