### ISSUE TITLE
erro Choose one option [1, 2, 3, 0]: 3

### ISSUE THREAD

**Issue by HEITORHOG1** [filipedeschamps/video-maker#345]
ola pessoal sabem dizer que erro pode ser este 

> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:23776) UnhandledPromiseRejectionWarning: Page id "garden undata" does not match any pages. Try another id!
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by 1Marcuth** [comment]
Cadê o código?

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
