### ISSUE TITLE
Robô que cria vídeos no Youtube

### ISSUE THREAD

**Issue by Diana0912** [filipedeschamps/video-maker#347]
Gente, eu fiz o procedimento do robô que cria vídeos no youtube todo passo a passo corretamente,mas, quando vou abrir o robô no cmd fica dando esse erro: Error: Cannot find module 'C:\Users\diana\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

O que devo fazer?

**Comment by killabomb** [comment]
Também estou com a mesma issue

**Comment by juniorbotelho** [comment]
Vocês tem que direcionar o CMD de vocês pra dentro da pasta onde o projeto se encontra, por exemplo:
```
cd "C:\Users\diana\video-maker"
```

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Estou fechando os issues relacionados a erro para entender quais erros ainda existem, quais já foram resolvidos, caso necessário posso abrir novamente.
