### ISSUE TITLE
Não estou conseguindo colocar para rodar

### ISSUE THREAD

**Issue by lucasmoroo** [filipedeschamps/video-maker#348]
Bom dia, alguém poderia me ajudar a atualizar e deixar rodando o robô, estou tentando aqui porém não tenho muita familiaridade com JavaScript e GitHub se alguém tiver interesse em me ajudar/ensinar... tenho conhecimento em Python porém achei bem diferente isso... Vou tentando aqui mas se alguém puder me ajudar a atualizar ele agradeço, ps não precisa ser de graça vlw

**Comment by lucasmoroo** [comment]
mano os arquivos que estão aqui estão bem diferentes do vídeo, pra quem não tem muita experiência tá f***

**Comment by rzfzr** [comment]
Continuando a conversa do outro issue, vc disse que ele para no meio, cola aqui o erro de quando isso acontece

**Comment by lucasmoroo** [comment]
@rzfzr beleza, obrigado. coloquei para rodar selecionei o termos ai apareceu no caso para digitar 1 para who is etc... após isso deu essa mensagem

> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "A beacon is an intentionally conspicuous device designed to attract attention to a specific location."
(node:18200) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lucasmoroo** [comment]
diz eu as credencias estão inválidas, porém fiz os arquivos certinhos...

**Comment by rzfzr** [comment]
Realmente, o que esta empacando são as credenciais do watson em especifico, vou tentar rodar o projeto original aqui e ja te digo

**Comment by lucasmoroo** [comment]
no meu tem isso aqui

const nlu = new NaturalLanguageUnderstandingV1({
  iam_apikey: watsonApiKey,
  version: '2018-04-05',
  url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
})

esse link não leva alugar algum, não sei se seria isso que está errado...

**Comment by rzfzr** [comment]
vc n tem o arquivo watson-nlu.json com essa info? isso ta descrito no readme dentro do credentials, esse print eh do meu, eu tirei do file e coloquei direto no code
![image](https://user-images.githubusercontent.com/13456224/130635454-57eb868f-3af0-4e56-b3b7-93eb750be41a.png)

**Comment by rzfzr** [comment]
Esse bloco que tu mostrou ta batendo com o meu, o url n bater nada no navegador n quer dizer nada, ele foi feito pra ser um endpoint pra api ne.
Meu projeto foi muito editado, to tentando entender aqui

**Comment by lucasmoroo** [comment]
entendi, vou rever essa parte aqui

**Comment by lucasmoroo** [comment]
conferi aqui e está correto, tenho sim todos os arquivos dentro do Credentials, mas nesse arquivo do watson-nlu.json eu só alterei a ''ApiKey'', se tiver que alterar outra coisa eu não mexi....

**Comment by rzfzr** [comment]
seguindo o readme ele diz que vc teria todos esses itens
   {
  "apikey" : "...",
  "iam_apikey_description" : "...",
  "iam_apikey_name": "...",
  "iam_role_crn": "...",
  "iam_serviceid_crn": "...",
  "url": "..."

clicando nele na nova página vai aparecer um botão "criar" no final da página, uma vez que o serviço for criado, você será redirecionado para a página de gerenciamento do serviço que você acabou de criar, no menu lateral esquerdo procure por **Credenciais de Serviços** e depois clique em **Auto-generated service credentials** destacado abaixo, então copie as *Credenciais*:

**Comment by lucasmoroo** [comment]
entendi refiz aqui e está correto, porém quando fui rodar

> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "A beacon is an intentionally conspicuous device designed to attract attention to a specific location."
(node:13220) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

essa parte agora está correto

**Comment by lucasmoroo** [comment]
![image](https://user-images.githubusercontent.com/89079139/130644214-f374d272-03ed-4c85-90cc-243faa6eef89.png)

**Comment by lucasmoroo** [comment]
não se interfere em alguma coisa mas observei que nesse código ali em cima no const algorithma está com esses pontinho em baixo do require

**Comment by rzfzr** [comment]
Esse pontinho seria somente alguma sugestão do editor, se deixar o mouse em cima ele vai te dar mais detalhes, 
parece que continua com algum problema de permissões, talvez a info no .json esteja correta mas o setup no site n esta habilitando o uso do watson

**Comment by lucasmoroo** [comment]
beleza obrigado, vou rever aqui essa parte do Watson e ver se deixei passar alguma coisa, desde já lhe agradeço

**Comment by lucasmoroo** [comment]
eu fiz aqui e instalei npm i watson-developer-cloud

realizei um teste Type a Wikipedia search term: bacon

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "A beacon is an intentionally conspicuous device designed to attract attention to a specific location."
(node:26252) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\Users\lucas\OneDrive\Documentos\LUCAS\Python\Projetos\RoboYoutube\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

e outro com um outro termo

Type a Wikipedia search term: michael jackson

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
(node:24596) UnhandledPromiseRejectionWarning: Page id "michael jacks" does not match any pages. Try another id!
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

é na plataforma da IBM eu não ativei nada de Watson, somente o NaturalLanguageUnderstanding está correto? lá está ativo aqui eu cadastrei as credenciais... essas partes eu já fiz por acaso não tem outra que eu devo atualizar?

**Comment by lucasmoroo** [comment]
este primeiro erro as credenciais que tá dando erro não é aquela que está dentro da pasta Credentiais está errando em outra

**Comment by mayrinkdotcom** [comment]
Olá @lucasmoroo , você conseguiu resolver o problema do `Page id "..." does not match any pages. Try another id!` ? Estou passando pelo mesmo perrengue aqui, se puder compartilhar a solução ficarei grato!

**Comment by matbrgz** [comment]
Estou fechando esse issue devido inatividade e aparamente o autor já resolveu o erro, @mayrinkdotcom se ainda estiver com erro abre um novo issue por favor.
