### ISSUE TITLE
Boa noite Devs! Alguem pode me ajudar com essa issue? ja quebrei minha cabeça e não consigo, meu Deus!

### ISSUE THREAD

**Issue by alaindaniel** [filipedeschamps/video-maker#349]
> [text-robot] Fetching content from Wikipedia
(node:9140) UnhandledPromiseRejectionWarning: algorithm did not complete within 420.0 seconds
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by juniorbotelho** [comment]
Isso é um problema na API do ```Algorithmia```, pelo que parece à cada 1 hora o servidor é definido para uso de baixo recurso, o que acaba causando esse problema de instabilidade. Nesse caso é só esperar uns 30-60min que tudo deve voltar ao normal.

Obs:
```
UnhandledPromiseRejectionWarning: algorithm did not complete within 420.0 seconds
```

É possível alterar esse tempo de **timeout**, alterando o seguinte bloco para setar um timeout menor, por exemplo, eu defino para que haja uma exceção após somente 30 segundos sem resposta do servidor:

```ts
const article = await ctx.algorithmia
  .algo('web/WikipediaParser/0.1.2?timeout=30')
  .pipe({
    articleName: content.searchTerm,
    lang: 'en',
  })
```

Espero ter ajudado 😊

**Comment by alaindaniel** [comment]
Obrigado irmão! me ajudou muito! agora estou parado em outra issue rsrs. (node:1092) UnhandledPromiseRejectionWarning: Error: Unauthorized: Access is denied due to invalid credentials.
    at Request._callback (C:\video-maker\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:102:21)
    at Request.self.callback (C:\video-maker\node_modules\request\request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (C:\video-maker\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (C:\video-maker\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by juniorbotelho** [comment]
Esse outro problema é referente às tuas credenciais de autenticação da IBM, dá uma olhada se tu fez tudo certinho com a apiKey da IBM Cloud.

**Comment by alaindaniel** [comment]
ah sim entendi, imaginei. vou dar uma revisada, obrigado mais uma vez!!

**Comment by matbrgz** [comment]
Entendendo que já existem diversos tópicos sobre esse assunto, estou fechando esse issue. Qualquer coisa só chamar.
