### ISSUE TITLE
Como mergear minha branch com uma branch de outro colaborador?

### ISSUE THREAD

**Issue by Pacheco95** [filipedeschamps/video-maker#35]
Fiz um pull request [#21](https://github.com/filipedeschamps/video-maker/pull/21) e gostaria de fazer um merge dele com outro pull request [#28](https://github.com/filipedeschamps/video-maker/pull/29).

Alguém pode me explicar como faço isso? Achei a ideia do @RodolfoSilva muito bacana e gostaria de utilizá-la.

**Comment by RodolfoSilva** [comment]
Acho que você só precisa fazer merge eu meu branch, mas acredito que ficaria grande para avaliar o seu PR. Acredito que o melhor seria se o @filipedeschamps fizesse o merge do PR #28 antes. Mas temos que ver quais são os planos dele primeiro rsrsrsrsrs....

**Comment by danielschmitz** [comment]
2 situações aqui:
1 - o filipe "junta" no master dele, vc pega faz o pull escreve seu código e manda o PR
2- você adiciona um novo remote no seu repo:

```
git remote add rodolfo https://github.com/RodolfoSilva/video-maker.git
```

então você faz um merge do repo do rodolfo no seu

```
git merge rodolfo/master
```

então você resolve os conflitos e pode fazer o PR para o filipe


Eu prefiro o método 1

**Comment by Pacheco95** [comment]
Muito obrigado!
A solução 2 parece mais fácil :)

**Comment by Pacheco95** [comment]
```console
$ git remote add video-maker-rodolfo https://github.com/RodolfoSilva/video-maker.git
$ git status
On branch auto-search-trends
Your branch is up to date with 'origin/auto-search-trends'.

nothing to commit, working tree clean

$ git checkout -b change-form
Switched to a new branch 'change-form'

$ git merge video-maker-rodolfo/change-form
merge: video-maker-rodolfo/change-form - not something we can merge

$ git remote -v
origin	git@github.com:Pacheco95/video-maker.git (fetch)
origin	git@github.com:Pacheco95/video-maker.git (push)
video-maker-rodolfo	https://github.com/RodolfoSilva/video-maker.git (fetch)
video-maker-rodolfo	https://github.com/RodolfoSilva/video-maker.git (push)
```

**Comment by Pacheco95** [comment]
Descobri o erro. O comando correto é:
`$ git merge video-maker-rodolfo change-form`
e não
`$ git merge video-maker-rodolfo/change-form`

**Comment by leodutra** [comment]
A outra opção é fazer o mesmo utilizando o GitKraken.
Aumenta bem a produtividade.

Mas se não conhece bem o Git no terminal, finja que eu não disse nada e pratique.
