### ISSUE TITLE
Algorithmia parou

### ISSUE THREAD

**Issue by juhlio** [filipedeschamps/video-maker#350]
Gente,

Estou desenvolvendo esse projeto agora para estudar e de um dia para o outro o Algorithmia parou, alguém tem alguma alternativa para essa funcionalidade?

**Comment by juniorbotelho** [comment]
Pode substituir pela versão oficial da API da Wikipedia conforme foi mostrado na PR: https://github.com/filipedeschamps/video-maker/pull/34

Eu também uso a própria API do Wikipedia, é bem melhor que o Algortihmia: https://github.com/juniorbotelho/videomaker-core/blob/main/utilities/Wikipedia.ts

**Comment by juhlio** [comment]
Valeuuuu Junior

Vou ver essa API... mto obrigado mesmo.. salvou!!
