### ISSUE TITLE
Wikipedia Parser morreu

### ISSUE THREAD

**Issue by douglasdnn** [filipedeschamps/video-maker#351]
Para quem não está conseguindo rodar, sem retorno do parser do robô de texto, isso acontece porque o serviço Wikipedia Parser do Algorithmia aparentemente morreu para sempre.

Ou trocamos de parser (o que descaracterizaria bastante o projeto - não seria um problema normalmente, se não fosse criar um distanciamento do vídeo, para quem está acompanhando a playlist pode ficar estranho) - ou este projeto fica apenas na memória de quem acompanhou lá atrás.

**Comment by juhlio** [comment]
Douglas 

Da uma olhada aqui: #350

**Comment by matbrgz** [comment]
Entendendo que já existem diversos tópicos sobre esse assunto, estou fechando esse issue. Qualquer coisa só chamar.

**Comment by matbrgz** [comment]
@filipedeschamps acredito ser valido as considerações desse vídeo? Quem sabe um vídeo atualização desse repositório? Sinta-se a vontade para reabrir esse issue se fizer sentido.
