### ISSUE TITLE
ALGUEM PODE ME AJUDAR? 

### ISSUE THREAD

**Issue by Thiagopereira10** [filipedeschamps/video-maker#352]
**### Encontrei um codigo para gerar NFTs, e não entendo muito de programação, o "npm instal" e o "npm install truffle -p" deu certo, mas na hora de usar o "node index.js" da erro... No caso não está gerando as NFTs...**

`PS C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1> node index.js
(node:4536) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181
    const image = await loadImage(`${_layer.selectedElement.path}`);
                                                            ^

TypeError: Cannot read properties of undefined (reading 'path')
    at C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:181:61
    at new Promise (<anonymous>)
    at loadLayerImg (C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:180:10)
    at C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:361:31
    at Array.forEach (<anonymous>)
    at startCreating (C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\src\main.js:360:17)
    at C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\index.js:6:3
    at Object.<anonymous> (C:\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)`

**Comment by LuisFernandoPeretti** [comment]
amigo, deixe-me perguntar: você conseguiu substituir a API do algorithmia pela do wikipedia?

**Comment by anilsonlopes** [comment]
O problema tem relação com o projeto?

**Comment by an-dutra** [comment]
Cara você não podia ir perguntar isso, num lugar mais errado.... kkkkk

**Comment by matbrgz** [comment]
Acredito que essa dúvida não é relacionada a esse projeto, se estiver erado me avise. Estou fechando essa issue.

O erro é do projeto hashlips_art_engine que é relacionado a um gerador de NFT.
