### ISSUE TITLE
Alguém pode me ajudar, sobre Vue.js

### ISSUE THREAD

**Issue by cristiancastano852** [filipedeschamps/video-maker#354]
Preciso fazer o mesmo mas com o vue.js, já tentei, mas não funciona, preciso da dica de alguém, por favor

**Comment by matbrgz** [comment]
Acredito que seja melhor procurar ajuda em um fórum especializado, o issue não é para esse intuito. Explica o que você quer fazer no [TabNews](https://www.tabnews.com.br/) e tenho certeza que vai conseguir ajuda.
