### ISSUE TITLE
Qual o discord desse repositório?

### ISSUE THREAD

**Issue by GustavoFabrino** [filipedeschamps/video-maker#356]
Pessoal vi em um comentário que tem um discord para tirar duvidas e tudo mais porem o convite esta expirado
sabem se ainda existe esse discord e se puder mandar o convite novamente agradeço 😃

**Comment by josehfnascimento** [comment]
Gustavo me chama no whats que te ajudo, rodei o projeto recente 18 981114238

**Comment by oliveiraresgate** [comment]
Bom dia Srs.
Estou chegando agora e tentando rodar também, posso fazer parte deste papo???
No meu deu erro de falta de arquivo mas já reinstalei tudo e reescrevi mas não sei onde errei...

**Comment by matbrgz** [comment]
Essa dúvida não é relacionada ao conteúdo desse repositório, rapidamente procurei e não encontrei nenhum servidor de Discord relacionado ao Deschmaps. Estou fechando essa issue, qualquer coisa só chamar.
