### ISSUE TITLE
Error promise 279 err unhandled rejection

### ISSUE THREAD

**Issue by ishaanbatra005** [filipedeschamps/video-maker#357]
i am being shown this error when try to run the program

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "authorization required".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by matbrgz** [comment]
Is this solved? I hope you got it.
I am closing error-related issues to understand which errors still exist, which have already been resolved, and if necessary I can open them again.
