### ISSUE TITLE
Alguém pode me Ajudar?

### ISSUE THREAD

**Issue by pciautocom** [filipedeschamps/video-maker#359]
![image](https://user-images.githubusercontent.com/68808224/189250714-f512d410-53d2-4250-a314-53a6f802d258.png)

**Comment by pciautocom** [comment]
Fiz todas as apis corretamente, mas creio que deva ter algo errado porque logo apos escolher a pesquisa e o tipo na wikipedia, 
da esse erro de falta de autorização.

**Comment by LKSFerreira** [comment]
Acredito que projeto tenha sido descontinuado, uma vez que também tentei ter acesso ao modelos de linguagem sem sucesso.

**Comment by matbrgz** [comment]
Conseguiu resolver? Espero que tenha conseguido.
Irei fechar o issue, caso necessário posso abrir novamente.
