### ISSUE TITLE
Ideia para gerenciar os PRs da galera sem atrapalhar os videos do filipe

### ISSUE THREAD

**Issue by danielschmitz** [filipedeschamps/video-maker#36]
@filipedeschamps 

Seria interessante começar a aceitar os PRs da galera, acho que ainda vão vir muitos !! 

Tive uma ideia que pode funcionar. Crie aí um novo branch, vamos chamá=lo de **community**. Aí o pessoal vai fazer os PRs nesse branch, que vai ser meio que uma versão PRO do video maker que vc está ensinando.

**Comment by nandumoura** [comment]
Gostei da idéia

**Comment by glaucia86** [comment]
Eu particularmente só vou começar a criar PR's quando ele começar aprovar as demais. Para não haver retrabalho. Já tinha algo que eu iria fazer. Mas já fizeram. Até para não atrapalhar as coisas.

**Comment by taranttini** [comment]
Eu acredito que os PR's acabariam afetando a didática proposta por ele nos vídeos, e quem estiver apenas com a intensão de ver o progresso do vídeo iria se deparar com uma gama de instruções que surgiram de uma hora para outra, e ai sairia do passo a passo proposto por ele nos vídeos, mas essa opção de ter o segundo branch, essa pode ser a sacada para ter uma versão com tantas melhorias propostas pela comunidade.

**Comment by danielschmitz** [comment]
fechando essa issue e caminhando para #77
