### ISSUE TITLE
oque fazer quando Api: Algorithmia nao esta desponivel em seu pais?

### ISSUE THREAD

**Issue by chapisnd** [filipedeschamps/video-maker#366]
eu vivo na Suiça ja agora props au Filipe por teres chegado tao longe com os teus videos e sim.
Eu gostava de conseguir instalar o datarobot que nao esta disponivel no meu pais, se alguem conseguir ajudar mandem a dica <3 (grande community) descubri a pouco e aprendi tanto...

**Comment by 1Marcuth** [comment]
Você não precisa dele para pegar conteúdo do wikipédia, eu fiz um código alternativo que retorna as mesmas informações da api do Algorithmia:  https://gist.github.com/1Marcuth/f5d4db7da743582f957f00596daea78e

**Comment by matbrgz** [comment]
Entendendo que já existem diversos tópicos sobre esse assunto, estou fechando esse issue. Qualquer coisa só chamar.
