### ISSUE TITLE
A API do Algorithmia  é paga agora, existe alguma opção ?

### ISSUE THREAD

**Issue by wferreiracosta** [filipedeschamps/video-maker#367]
Uma empresa DataRobot comprou o Algorithmia e agora a API é paga, gostaria de saber se existe alguma substituição.

**Comment by byhebsoares** [comment]
https://github.com/filipedeschamps/video-maker/issues/366#issuecomment-1546248299

**Comment by matbrgz** [comment]
Entendendo que já existem diversos tópicos sobre esse assunto, estou fechando esse issue. Qualquer coisa só chamar.
