### ISSUE TITLE
Ideia pro Audio Robot

### ISSUE THREAD

**Issue by Braayy** [filipedeschamps/video-maker#37]
Eu fui acessar o canal **Know The World**, e reparei uma coisa meio chata. **A musica é sempre a mesma.** Logo pensei em, no lugar de sempre usar a mesma música, ter uma playlist, não muito grande, para dar uma variada e não ficar repetitivo.

**Comment by maykbrito** [comment]
@Braayy acredito que ele irá usar um template semi pronto. Por isso é a mesma música.
Caso seja esse o cenário, a opção seria duplicar os templates, modificando os audios em cada um dos templates. Teria a "playlist" de templates rsrs

**Comment by Braayy** [comment]
> @Braayy acredito que ele irá usar um template semi pronto. Por isso é a mesma música.
> Caso seja esse o cenário, a opção seria duplicar os templates, modificando os audios em cada um dos templates. Teria a "playlist" de templates rsrs

Desde que não fique repetitivo ta ótimo kk

**Comment by rrfaria** [comment]
se ele já vai fazer um update no content do vídeo, acho que da pra fazer isso com áudio também, pra não precisa ficar duplicando template.

**Comment by thiagohenriquerossato** [comment]
daria pra ter uma playlist de musicas e o robo adicionaria um aleatoriamente no tamplate, assim como faz com o texto e imagens
