### ISSUE TITLE
Problema com instalação do sdb

### ISSUE THREAD

**Issue by thiagohenriquerossato** [filipedeschamps/video-maker#40]
Eu estava tentando fazer a instalação do pacote sdb mas nao consegui, o codigo de erro é o ELIFECYCLE, tem esse log: [2019-03-12T05_07_56_954Z-debug.log](https://github.com/filipedeschamps/video-maker/files/2955231/2019-03-12T05_07_56_954Z-debug.log)

sdb@0.2.1 install C:\Users\N202\Documents\****\***\video_maker\node_modules\sdb
> node-gyp rebuild

C:\Users\N202\Documents\***\***\video_maker\node_modules\sdb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\N202\Documents\***\***\video_maker\node_modules\sdb
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sdb@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sdb@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Kraysh** [comment]
Para usar conseguir usar o node-gyp é preciso ter o Visual Studio e o Python 2.
Se quiser instalar tudo automaticamente:
https://www.npmjs.com/package/windows-build-tools

**Comment by thiagohenriquerossato** [comment]
fiz a instalação do vs e python. aparece isso agora

> sdb@0.2.1 install C:\Windows\system32\node_modules\sdb
> node-gyp rebuild


C:\Windows\system32\node_modules\sdb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
MSBUILD : error MSB1009: Arquivo de projeto não existe.
Opção: build/binding.sln
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\sdb
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\system32\package.json'
npm WARN system32 No description
npm WARN system32 No repository field.
npm WARN system32 No README data
npm WARN system32 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sdb@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sdb@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\N202\AppData\Roaming\npm-cache\_logs\2019-03-13T23_22_26_923Z-debug.log

**Comment by vsalbuq** [comment]
@thiagohenriquerossato, conseguiu fazer rodar?

Se não, roda um `npm audit` e posta o resultado aqui.
