### ISSUE TITLE
Erro  node index.js

### ISSUE THREAD

**Issue by Patricia7sp** [filipedeschamps/video-maker#42]
Boa tarde!

Felipe e  todos membros do grupo,  como estao?

Estou tendo um problema quando  digito o comando node index.js -  não esta funcionando e esta voltado este  erro

module.js:549
    throw err;
    ^

Error: Cannot find module 'sbd'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/patricia/rob-s-maker/robots/text.js:3:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Conseguem me ajudar?  

Tentei buscar uma solução e não consegui.

**Comment by nadoneves** [comment]
Instalou o modulo com o npm?

**Comment by Jrfidellis** [comment]
Oi :) 

Você já rodou o comando `npm install`?

**Comment by Patricia7sp** [comment]
Quando tento instalar com npm esta dando erro

 npm WARN enoent ENOENT: no such file or directory, open '/home/patricia/package.json'
npm WARN patricia No description
npm WARN patricia No repository field.
npm WARN patricia No README data
npm WARN patricia No license field.
patricia@patricia-UX330UAK:~$

**Comment by Jrfidellis** [comment]
Você tem que rodar o comando `npm install` na pasta do projeto (a pasta que você clonou)

**Comment by Patricia7sp** [comment]
falha minha

**Comment by Patricia7sp** [comment]
estava tentando instalar a versao recente do node , mas nao vai, continua na minha antiga que e v8.10 . eu uso linux

**Comment by Jrfidellis** [comment]
funcionou agora?

**Comment by Patricia7sp** [comment]
nao funcionou nao

**Comment by Patricia7sp** [comment]
o erro persiste

**Comment by Jrfidellis** [comment]
Acredito que a versão do Node não seja o problema, tenta rodar o `npm install` na pasta do projeto e manda aqui o erro que aparecer no console

**Comment by Patricia7sp** [comment]
sudo npm install nodejs
rob-s-maker@1.0.0 /home/patricia/rob-s-maker


patricia@patricia-UX330UAK:~/rob-s-maker$ sudo npm install nodejs
rob-s-maker@1.0.0 /home/patricia/rob-s-maker
├── algorithmia@0.3.10  extraneous
├── nodejs@0.0.0  extraneous
├── package.json@2.0.1 
└── readline-sync@1.4.9  extraneous

**Comment by Patricia7sp** [comment]
e fiz a instalacao desta forma tambem

patricia@patricia-UX330UAK:~/rob-s-maker$ sudo apt install nodejs npm
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
npm is already the newest version (3.5.2-0ubuntu4).
nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 46 não atualizados.

**Comment by Jrfidellis** [comment]
Pelo que vi na mensagem a versão do node já está atualizada.

Como eu disse, acho que a versão do Node não é o problema, você tem que rodar o comando `npm install` (sem mais nada) na pasta do projeto, esse comando vai instalar as dependências do projeto e colocá-las na pasta `node_modules` (que ele mesmo vai criar).

https://docs.npmjs.com/cli/install

**Comment by viniciusafx** [comment]
Patricia não sei se você consegui resolver, mas se não conseguiu ou alguma outra pessoa esta com a mesma duvida execute esses seguintes comandos:
// Verificar se o node e o npm está instalado na máquina:
node -v
npm -v
// Clonar o repositorio:
git clone https://github.com/filipedeschamps/video-maker.git
// Entrar na pasta:
cd video-maker
// Instalar as dependências do projeto:
npm install
// Iniciar o node:
node index.js

O meu sistema é Windows, mas acho que esses comandos funcionarão também no linux.

Imagem com os comandos usados:
![commands](https://user-images.githubusercontent.com/22448818/54237758-7610ce80-44f5-11e9-9107-30c5002fe720.png)

**Comment by Patricia7sp** [comment]
@Jrfidellis deu certo, agora, eu baixei o sbd.   Muito obrigada pela ajuda

**Comment by Patricia7sp** [comment]
@viniciusafx  Muito obrigada pela sua ajuda, eu consegui resolver agora, eu instalei o sbd.

**Comment by Patricia7sp** [comment]
Quero agradecer a todos pela ajuda, eu estou novata ainda neste meio e fico perdida as vezes.

**Comment by Jrfidellis** [comment]
Ótimo! Qualquer coisa só abrir outra issue que aparece alguém pra ajudar. E como essa foi resolvida vc já pode fechá-la. Valeu!

**Comment by Patricia7sp** [comment]
Pessoal ia fechar a issue , mas agora esta dando um erro de autorizacao - promise


(node:7685) UnhandledPromiseRejectionWarning: authorization required
(node:7685) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7685) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
patricia@patricia-UX330UAK:~/rob-s-maker$
