### ISSUE TITLE
Erro - Autorizacao requerida para executar  index.js

### ISSUE THREAD

**Issue by Patricia7sp** [filipedeschamps/video-maker#44]
Pessoal bom dia!Como estão?

Eu estou com um  outro erro para executar index.js 

(node:10065) UnhandledPromiseRejectionWarning: authorization required(node:10065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)(node:10065) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

conseguem me ajudar?

**Comment by lucianopf** [comment]
@Patricia7sp pela descrição do seu erro parece que faltou vc criar as credenciais de configuração dos serviços usados no projeto e isso está dando throw num erro na sua aplicação.

Vc chegou a criar o arquivo de credenciais do algorithimia? [ref](https://github.com/filipedeschamps/video-maker/tree/master/credentials)

**Comment by Patricia7sp** [comment]
sim crie

**Comment by rrfaria** [comment]
o problema é esse ai mesmo K é maiusculo 
`/robots/text.js`
veja segunda linha do arquivo

**Comment by Patricia7sp** [comment]
@Walicen  Muito obrigada pela ajuda, deu tudo certo!! Erro besta que acabamos nao percebendo

**Comment by Patricia7sp** [comment]
@rrfaria  Muito obrigada pela atencao!!
