### ISSUE TITLE
Erro depois de escolher uma das opções "[1] Who is [2] What is [3] The history of" ele dá um erro e não aparece a pesquisa.

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#46]
Alguém sabe como arrumar isso?
![image](https://user-images.githubusercontent.com/48515934/54301942-b6785700-459e-11e9-88f4-16e539e74444.png)

**Comment by naurojunior** [comment]
É o problema do #44 , falta as credentials (algorithmia.json), com a "apiKey" =)

**Comment by VinyciusC** [comment]
> É o problema do #44 , falta as credentials (algorithmia.json), com a "apiKey" =)

Eu coloquei a "apiKey", descobri o problema, é que no vídeo que o Filipe mostra a parte do API, está sem as barras como na print, e eu removi essas barras, por isso estava dando o erro, agora coloquei novamente a API só que com as barras e funcionou certinho, muito obrigado! :D

![image](https://user-images.githubusercontent.com/48515934/54305245-a748d780-45a5-11e9-8a0d-52ca8e757b4e.png)

![image](https://user-images.githubusercontent.com/48515934/54305306-c9daf080-45a5-11e9-8c72-c46d99db1a99.png)
