### ISSUE TITLE
Remover as opções "['Who is', 'What is', 'The history of']" e colocar que podemos digitar ao invés de escolher uma das opções

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#50]
Olá, estava vendo aqui e pensei em remover as opções, no caso:

```
function askAndReturnPrefix() {
    return readline.question('Prefix: ')
    const prefixes = ['Who is', 'What is', 'The history of']
    const selectedPrefixIndex = readline.keyInSelect(prefixes, 'Choose one option: ')
    const selectedPrefixText = prefixes[selectedPrefixIndex]

    return selectedPrefixText
  }
```
E alterar para que possamos digitar ao invés de escolher uma opção, pensei em fazer dessa maneira, e ele alterou o prefixo, porém não sei se irá dar algum problema depois, não tenho um conhecimento profundo igual a maioria, então se possível, poderiam ver se aconteceria algum problema:

```
function askAndReturnPrefix() {
    return readline.question('Prefix: ')

    return selectedPrefixText
  }
```

Ao executar o `node index.js` aconteceu tudo corretamente a principio:
![image](https://user-images.githubusercontent.com/48515934/54358598-8765f200-463f-11e9-83e7-3a7f0e827fda.png)

**Comment by VinyciusC** [comment]
**ADICIONEI OUTRO APENAS COM O CÓDIGO EDITADO:**

https://github.com/filipedeschamps/video-maker/issues/54

**Comment by Fernandingo7** [comment]
Ola VinyciusC! Tudo bem? Eu estou fazendo o projeto, mas tive um problema. O Visual Studio Code está falando que o comando:
`function askAndReturnPrefix() `
O que eu faço?
