### ISSUE TITLE
Problemas com acentuação

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#52]
É possível corrigir os erros de acentuação?

![image](https://user-images.githubusercontent.com/48515934/54378465-29003a00-4666-11e9-90e4-340f08a22996.png)

No caso fazer tipo um tratamento para corrigir isso, desculpem ficar abrindo issue por coisas que provavelmente pra vocês é algo bobo, não sou nem um profissional em JS, cai de paraquedas nisso, mais enfim, se alguém puder me ajudar a arrumar isso, ficarei muito agradecido :)

**Comment by viniciusafx** [comment]
O editor de texto que você esta utilizando está configurado para salvar o arquivo em UTF-8?

**Comment by genesluna** [comment]
Esse é um problema que acontece no windows. Você precisa mudar a codificação da página para utf-8. Para resolver digite `chcp 65001` no powershell antes de rodar o index.js. 

O problema é que você vai ter que fazer isso todas as vezes que abrir o powershell.

Para resolver para sempre, faça o seguinte:

1. Abra sua 'profile' usando o notepad pelo powershell 

`notepad $profile`

Se você ainda não tiver um arquivo de profile, o notepad vai pedir para criar um.

2. Uma vez que o notepad esteja aberto, adicione a seguinte linha e salve.

`chcp 65001`

Pronto. Toda ver que você abrir o Powershell, ele já vai estar configurado com a codificação correta de página.

**Comment by VinyciusC** [comment]
@genesluna onde salvo o arquivo? E ele não abriu com o notepad (Tenho ele instalado) abriu com o bloco de notas.

**Comment by genesluna** [comment]
> @genesluna onde salvo o arquivo? E ele não abriu com o notepad (Tenho ele instalado) abriu com o bloco de notas.

O notepad é o bloco de notas. Agora você precisa abrir o bloco de notas pelo powershell usando o comando `notepad $profile` Não precisa escolher onde salvar, é adicionar a linha e apertar Ctrl+S.

**Comment by foliveira15** [comment]
> @genesluna onde salvo o arquivo? E ele não abriu com o notepad (Tenho ele instalado) abriu com o bloco de notas.

Se você não tem o arquivo criado ainda, grave com o nome Microsoft.PowerShell_profile.ps1 dentro da pasta "Documentos\WindowsPowerShell"

Ex:

`C:\Usuários\seu_usuário_aqui\Documentos\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

**Comment by VinyciusC** [comment]
Funcionou, obrigado @genesluna e @foliveira15 !

**Comment by Adenilson365** [comment]
@FernandoFalcone-dev 

Tive o mesmo problema, criei o arquivo com o nome: "Microsoft.PowerShell_profile.ps1" indicado pelo @foliveira15 e usei o abrir local do arquivo em cima do powershell até chegar na pasta raiz e colei lá.
