### ISSUE TITLE
Remover as opções "['Who is', 'What is', 'The history of']" e colocar que podemos digitar ao invés de escolher uma das opções

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#54]
**Código anterior:**

```
unction askAndReturnPrefix() {
    const prefixes = ['Who is', 'What is', 'The history of']
    const selectedPrefixIndex = readline.keyInSelect(prefixes, 'Choose one option: ')
    const selectedPrefixText = prefixes[selectedPrefixIndex]

    return selectedPrefixText
  }
```

**Código com as opções removidas:**
```
function askAndReturnPrefix() {
    return readline.question('Prefix: ')

    return selectedPrefixText
  }
```

**OBSERVAÇÃO:** Como não foi testado na parte do YouTube, não sei se funcionará corretamente.

**Comment by gabrielrufino** [comment]
Acho que podiamos continuar com algumas opções pré setadas (Isso que foi já foi implementado) e acrescentar, também, a possibilidade de digitar um novo prefixo. Dar mais de uma opção ao usuário de fazer uma coisa é muito bom! UX em alto nível :D

**Comment by danielschmitz** [comment]
Vamos discutindo esse tema em #77
