### ISSUE TITLE
Erro ao executar o index.js

### ISSUE THREAD

**Issue by VinyciusC** [filipedeschamps/video-maker#59]
Fui colocar a parte do Watson e quando vou executar o index.js (`node index.js`) ele dá o problema da imagem abaixo:

![image](https://user-images.githubusercontent.com/48515934/54551512-05eac880-498d-11e9-818b-984ae87e66fb.png)

**Comment by AcNeidert** [comment]
Você Instalou o watson no node?
```
npm install watson-developer-cloud
```

**Comment by VinyciusC** [comment]
Quando instalo o Watson acontece isso:
![image](https://user-images.githubusercontent.com/48515934/54552086-0f286500-498e-11e9-8d19-5f31eed00d44.png)

**Comment by AcNeidert** [comment]
Tente remover o arqivo package-lock.json  e tente novamente

**Comment by VinyciusC** [comment]
@AcNeidert não funcionou também:
![image](https://user-images.githubusercontent.com/48515934/54553118-44ce4d80-4990-11e9-89a7-3dec6f7ee919.png)

**Comment by willianrssi** [comment]
@VinyciusC verifique se após remover o arquivo package-lock.json como o @AcNeidert sugeriu você usou o: 
```
npm install watson-developer-cloud
```

porque na segunda imagem que você mandou parece ter usado `node` no lugar de `npm`

**Comment by VinyciusC** [comment]
Ah sim, não tinha visto, agora funcionou, coloco o package-lock.json novamente para a pasta?

**Comment by willianrssi** [comment]
@VinyciusC acredito ao executar a instalação com: `npm install watson-developer-cloud` já deva ter sido criado uma nova versão do package-lock.json automaticamente.

Para que você entenda um pouco mais o que possa ter acontecido, sugiro que leia este artigo:

[Tudo que você queria saber sobre o package-lock.json](https://medium.com/trainingcenter/tudo-que-voc%C3%AA-queria-saber-sobre-o-package-lock-json-mas-estava-com-vergonha-de-perguntar-e70589f2855f)

**Comment by VinyciusC** [comment]
@willianrssi agora o problema é que não passa disso:
![image](https://user-images.githubusercontent.com/48515934/54556128-f7a1aa00-4996-11e9-8018-92ceeb8cbcec.png)

Só fica assim :/

**Comment by willianrssi** [comment]
@VinyciusC se puder criar um repositório e botar seu código lá e depois disponibilizar aqui, facilita bastante a comunidade te ajudar

**Comment by guilhermeadsf** [comment]
Estou com esse erro : https://imgur.com/O5yh56r , alguem tem conhecimento sobre oque é ? minha credencial eu criei como gerente

**Comment by vsalbuq** [comment]
@guilhermeadsf , tive o mesmo problema aqui ontem.

Resolvi alterando o trecho do version da requisição para `version: '2018-11-16'`.

Encontrei isso na documentação do site da IBM.

Meu código talvez esteja um pouco diferente porque achei que o robô de texto começou a ficar muito embolado, com muita coisa junta, então refatorei separando as coisas, mas segue o código completo abaixo:

```js
const watsonApiKey = require('../../credentials/watson-nlu.json').apikey

const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
 
const nlu = new NaturalLanguageUnderstandingV1({
    iam_apikey: watsonApiKey,
    version: '2018-11-16',
    url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
});

async function robot(sentence){
    const keywords = await fetchWatsonAndReturnKeywords(sentence)

    return keywords
    
    async function fetchWatsonAndReturnKeywords (sentence) {
        return new Promise((resolve, reject) => {
            nlu.analyze({
                text: sentence,
                features: {
                    keywords: {}
                }
            }, (error, response) => {
                if(error) {
                    throw error
                }
                
                const keywords = response.keywords
                    .map(keyword => keyword.text)

                resolve(keywords)
            })
        })
    }
}

module.exports = robot
```
Coloquei ele dentro da pasta robots (`robots/text/watson-nlu.js`) e fiz o require dele no `text.js`.

**Comment by yagoernandes** [comment]
> Estou com esse erro : https://imgur.com/O5yh56r , alguem tem conhecimento sobre oque é ? minha credencial eu criei como gerente

Descrevi esse erro em uma nova issue, a #68

**Comment by yagoernandes** [comment]
> @guilhermeadsf , tive o mesmo problema aqui ontem.
> 
> Resolvi alterando o trecho do version da requisição para `version: '2018-11-16'`.
> 
> Encontrei isso na documentação do site da IBM.
> 
> Meu código talvez esteja um pouco diferente porque achei que o robô de texto começou a ficar muito embolado, com muita coisa junta, então refatorei separando as coisas, mas segue o código completo abaixo:
> 
> ```js
> const watsonApiKey = require('../../credentials/watson-nlu.json').apikey
> 
> const NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
>  
> const nlu = new NaturalLanguageUnderstandingV1({
>     iam_apikey: watsonApiKey,
>     version: '2018-11-16',
>     url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
> });
> 
> async function robot(sentence){
>     const keywords = await fetchWatsonAndReturnKeywords(sentence)
> 
>     return keywords
>     
>     async function fetchWatsonAndReturnKeywords (sentence) {
>         return new Promise((resolve, reject) => {
>             nlu.analyze({
>                 text: sentence,
>                 features: {
>                     keywords: {}
>                 }
>             }, (error, response) => {
>                 if(error) {
>                     throw error
>                 }
>                 
>                 const keywords = response.keywords
>                     .map(keyword => keyword.text)
> 
>                 resolve(keywords)
>             })
>         })
>     }
> }
> 
> module.exports = robot
> ```
> 
> Coloquei ele dentro da pasta robots (`robots/text/watson-nlu.js`) e fiz o require dele no `text.js`.

@vsalbuq Eu fiz o que você sugeriu e o erro continuou, olha a issue que eu abri... #68

**Comment by VinyciusC** [comment]
**Parte do erro já consegui resolver, quem está com o erro de busca no Wikipedia, por favor, prossiga para essa issue:** https://github.com/filipedeschamps/video-maker/issues/70
