### ISSUE TITLE
Watson - Access denied

### ISSUE THREAD

**Issue by gustavocardoso** [filipedeschamps/video-maker#67]
Estou tendo um erro quando o programa tenta se autenticar no Watson. Fiz exatamente como está no vídeo, mas recebo esta mensagem:

Error: Unauthorized: Access is denied due to invalid credentials.

Alguém teve o mesmo problema?

**Comment by gustavocardoso** [comment]
Resolvi. Fiz a parte de autorização completa. Precisei criar um grupo, adicionar o user no grupo.

**Comment by yagoernandes** [comment]
Eu obtive um erro diferente, quando faço do mesmo jeito do vídeo tenho o seguinte erro: 

> Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.

Mas aí eu alterei a importação das credenciais no robô de texto pra ficar assim:

```javascript
const watsonCredentials = require('../credentials/watson-nlu.json')
```
E na utilização assim:
```javascript
var nlu = new naturalLanguageUnderstandingV1({
   ...watsonCredentials
})
```

Mas mesmo com essas alterações eu obtive o erro:

> Error: Unauthorized: Access is denied due to invalid credentials.

Como você resolveu @gustavocardoso ?

**Comment by gustavocardoso** [comment]
Fala, @yagoernandes. Blz?

Cara, eu fui na area de settings do IAM: https://cloud.ibm.com/iam#/settings

Ali, eu criei um Access Group, depois associei nele o Service ID e coloquei meu user dentro desse grupo. Foi isso que fiz e acabou dando certo. hehehehehehe

:)

**Comment by yagoernandes** [comment]
Valeu cara! Funcionou aqui!

**Comment by Beaast-exe** [comment]
como resolve ?

**Comment by gustavocardoso** [comment]
@Beaast-exe, dá uma olhada no meu comentário acima. Foi como deu certo pra mim!

**Comment by Beaast-exe** [comment]
> @Beaast-exe, dá uma olhada no meu comentário acima. Foi como deu certo pra mim!

para mim nao funcionou :( acho que tou fazendo algo errado

**Comment by Beaast-exe** [comment]
@gustavocardoso
