### ISSUE TITLE
Watson - Access denied

### ISSUE THREAD

**Issue by yagoernandes** [filipedeschamps/video-maker#68]
Fiz tudo igual ao vídeo, substituindo as credenciais, mas ao executar o index.js eu recebo este erro: 

> Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.

Mas aí eu alterei a importação das credenciais no robô de texto pra ficar assim:

```javascript
const watsonCredentials = require('../credentials/watson-nlu.json')
```
E na utilização assim:
```javascript
var nlu = new naturalLanguageUnderstandingV1({
   version: '2018-11-16',
   ...watsonCredentials
})
```

Mas mesmo com essas alterações eu obtive o erro:

> Error: Unauthorized: Access is denied due to invalid credentials.

Alguém sabe resolver?

**Comment by yagoernandes** [comment]
Consegui! O erro dava porque quando eu passava os atributos pelo spread operator ele passava a API Key com o nome "apikey" e o Native Language Understanding requeria como "iam_apikey" 🙄

**Comment by Beaast-exe** [comment]
como conseguiu resolver ? eu tou com o mesmo erro

**Comment by gfernandes410** [comment]
@Beaast-exe tentou está solução?

Solução no issue #67 

> Fala, @yagoernandes. Blz?
> 
> Cara, eu fui na area de settings do IAM: https://cloud.ibm.com/iam#/settings
> 
> Ali, eu criei um Access Group, depois associei nele o Service ID e coloquei meu user dentro desse grupo. Foi isso que fiz e acabou dando certo. hehehehehehe
> 
> :)

**Comment by Beaast-exe** [comment]
@gfernandes410 sim, acho que tou fazendo algo errado
