### ISSUE TITLE
Error: unable to get local issuer certificate na nlu do Watson

### ISSUE THREAD

**Issue by sgalmeid** [filipedeschamps/video-maker#69]
Boa tarde pessoal.
Estou tendo problemas para acessar a API do Watson pelo robo.

Estou rodando em uma rede com proxy, porem se tento acessar a api do watson pelo curl vai sem problema algum.

Quando rodo o nodejs tenho o erro abaixo.

> video-maker/robots/text.js:87
>           throw error
>           ^
> 
> Error: unable to get local issuer certificate
>     at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
>     at TLSSocket.emit (events.js:182:13)
>     at TLSSocket._finishInit (_tls_wrap.js:631:8)

```
async function fetchWatsonAndReturnKeywords(sentence) {
    return new Promise((resolve, reject) => {
      nlu.analyze({
        text: sentence,
        features: {
          keywords: {}
        }
      }, (error, response) => {
        if (error) {
          throw error //linha 87
        }
        const keywords = response.keywords.map((keyword) => {
          return keyword.text
        })
        resolve(keywords)
      })
    })
  }
```

**Comment by rico2290** [comment]
Nao teria como vc desabilitar proxy?. Esse mesmo problema aconteceu comigo num projeto pessoal que estou fazendo acessando Watson NLU com python. So depois de desabilitar proxy eu tive sucesso na requisição

**Comment by sgalmeid** [comment]
@rico2290 Obrigado pela resposta. Porem não tem como, estou dentro da empresa e nem tenho acesso a isso.

**Comment by rico2290** [comment]
use este comando no executar: inetcpl.cpl ,4
depois clica no "Configurações da LAN" e por fim, desabilitar a caixa "Servidor proxy"

**Comment by GuibaGold** [comment]
Boa tarde pessoal estou tendo problemas para acessar a API também, mas é um problema referente a apiKey
![image](https://user-images.githubusercontent.com/31520760/54868942-cb0fd880-4d70-11e9-87fd-d6da09b6e79e.png)

inclusive não consigo puxar a apiKey do arquivo watson-nlu.json da forma que o Filipe faz. Estou atribuindo o valor da apiKey da mesma forma que se é atribuído o valor da url, diretamente.
![image](https://user-images.githubusercontent.com/31520760/54868962-fbf00d80-4d70-11e9-99d8-65e1a1ecc4b3.png)
fazendo desta forma eu recebo o erro no console(primeira imagem)

Me ajudem!!

**Comment by sgalmeid** [comment]
> use este comando no executar: inetcpl.cpl ,4
> depois clica no "Configurações da LAN" e por fim, desabilitar a caixa "Servidor proxy"

Por eu estar em uma rede corporativa, se eu desligar o proxy perco o acesso a internet.

Tentei algumas formas de fazer o node autenticar no proxy. Porem sem resultado algum.

**Comment by danielschmitz** [comment]
#87
