### ISSUE TITLE
Erro ao buscar no wikipedia

### ISSUE THREAD

**Issue by MatheusDeAquino** [filipedeschamps/video-maker#70]
O erro acontece no momento em que o @filipedeschamps consegue fazer a busca no wikipedia e as letras ficam verdes.
Meu caso, da esse erro!
O que devo fazer?
:::
![erro ao pesquisar](https://user-images.githubusercontent.com/43558548/54730957-6420d280-4b6a-11e9-9b20-d59d9747daa6.jpg)
:::

**Comment by hugocalheira** [comment]
Chegou a gerar sua apiKey lá no algorithmia?

**Comment by hugocalheira** [comment]
Consegui reproduzir seu erro aqui. Tem relação com o uso do **async await**.
Você está tentando trabalhar dados que ainda não chegaram do servidor.

```
async function robot(content) {
    await fetchContentFromWikipedia(content)
    ...
```

**Comment by VinyciusC** [comment]
@MatheusDeAquino também estou com esse problema, @hugocalheira sabe como resolver?

**Comment by MatheusDeAquino** [comment]
> Consegui reproduzir seu erro aqui. Tem relação com o uso do **async await**.
> Você está tentando trabalhar dados que ainda não chegaram do servidor.
> 
> ```
> async function robot(content) {
>     await fetchContentFromWikipedia(content)
>     ...
>     async function fetchContentFromWikipedia(content) {
>     ...
> ```
Eu tentei mexer no async/await de varias formas e o erro persiste.
Neste momento do code o @filipedeschamps conseguiu baixar do wikipedia com letra verde e tal. Meu caso fica esse erro :(

Meu "text.js" está assim:
```
const algorithmia = require('algorithmia') //importando o modulo deles pro bot
const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey

async function robot(content){
    await BuscaWikipedia(content)
    //LimparConteudo(content)
    //QuebrarSentencas(content)

    async function BuscaWikipedia(content) {
        const algorithmiaAutenticada = algorithmia(algorithmiaApiKey)
        const wikipediaAlgorithm = algorithmiaAutenticada.algo('web/WikipediaParser/0.1.2') //link no site deles. Aba node JS
        const wikipediaResponde = await wikipediaAlgorithm.pipe(content.serarchTerm)
        const wikipediaContent = wikipediaResponde.get()   
        console.log(wikipediaContent)
    }
}
module.exports = robot
```
:::
Meu "index.js" está assim:
```
const readline = require('readline-sync')
const robots = {
	text: require('./robots/text.js')
}

function start() {
	const content = {}

	content.searchTerm = askAndReturnSearchTerm()
	content.prefix = askAndReturnPrefix()

	robots.text(content)

	function askAndReturnSearchTerm() {
		return readline.question('Digite um termo de pesquisa da Wikipedia: ')
	}
	function askAndReturnPrefix() {
		const prefixes = ['Quem e', 'O que e', 'A historia de']
		const selectedPrefixIndex = readline.keyInSelect(prefixes, 'Escolha uma alternativa: ')
		const selectedPrefixText = prefixes[selectedPrefixIndex]

		return selectedPrefixText
	}

	console.log(content)
}
start()
```
:::

**Comment by MatheusDeAquino** [comment]
> > Consegui reproduzir seu erro aqui. Tem relação com o uso do **async await**.
> > Você está tentando trabalhar dados que ainda não chegaram do servidor.
> > ```
> > async function robot(content) {
> >     await fetchContentFromWikipedia(content)
> >     ...
> >     async function fetchContentFromWikipedia(content) {
> >     ...
> > ```
> 
> Eu tentei mexer no async/await de varias formas e o erro persiste.
> Neste momento do code o @filipedeschamps conseguiu baixar do wikipedia com letra verde e tal. Meu caso fica esse erro :(
> 
> Meu "text.js" está assim:
> 
> ```
> const algorithmia = require('algorithmia') //importando o modulo deles pro bot
> const algorithmiaApiKey = require('../credentials/algorithmia.json').apiKey
> 
> async function robot(content){
>     await BuscaWikipedia(content)
>     //LimparConteudo(content)
>     //QuebrarSentencas(content)
> 
>     async function BuscaWikipedia(content) {
>         const algorithmiaAutenticada = algorithmia(algorithmiaApiKey)
>         const wikipediaAlgorithm = algorithmiaAutenticada.algo('web/WikipediaParser/0.1.2') //link no site deles. Aba node JS
>         const wikipediaResponde = await wikipediaAlgorithm.pipe(content.serarchTerm)
>         const wikipediaContent = wikipediaResponde.get()   
>         console.log(wikipediaContent)
>     }
> }
> module.exports = robot
> ```
> :::
> Meu "index.js" está assim:
> 
> ```
> const readline = require('readline-sync')
> const robots = {
> 	text: require('./robots/text.js')
> }
> 
> function start() {
> 	const content = {}
> 
> 	content.searchTerm = askAndReturnSearchTerm()
> 	content.prefix = askAndReturnPrefix()
> 
> 	robots.text(content)
> 
> 	function askAndReturnSearchTerm() {
> 		return readline.question('Digite um termo de pesquisa da Wikipedia: ')
> 	}
> 	function askAndReturnPrefix() {
> 		const prefixes = ['Quem e', 'O que e', 'A historia de']
> 		const selectedPrefixIndex = readline.keyInSelect(prefixes, 'Escolha uma alternativa: ')
> 		const selectedPrefixText = prefixes[selectedPrefixIndex]
> 
> 		return selectedPrefixText
> 	}
> 
> 	console.log(content)
> }
> start()
> ```
> :::

CONSEGUI!

o ERRO ERA QUE EU ESCREVI "searchTerm" errado na linha  de comando.
"const wikipediaResponde = await wikipediaAlgorithm.pipe(content.**serarchTerm**)"

Isso que da programar sem parar. Não queria dormir com erro no code mas agora de manhã ja acordei revendo isso.
Obrigado pelo ajuda a todos aí!

**Comment by danielschmitz** [comment]
Erro resolvido, fechando a issue.
