### ISSUE TITLE
Escolher o template e música do vídeo a ser gerado

### ISSUE THREAD

**Issue by ninjaoboladao** [filipedeschamps/video-maker#71]
Galera vocês não acham interessante se houvesse uma opção do usuário escolher o template e a música antes de cada vídeo ser gerado? Alguem teria ideia de como automatizar isso?

**Comment by ninjaoboladao** [comment]
por exemplo um usuario leigo quer fazer um vídeo de culinaria e outro sobre futebol, logo o video ficaria estranho se nao houvesse forma de ele escolher o template

**Comment by faustoct** [comment]
1. Nao seria uma boa experienca pro usuario. 
2. O foco é ele iria consumir a info
3. A ideia eh legal mas vejo como uma melhoria futura
4. Isso deve ser feito por tras, nao pelo user.

**Comment by leodutra** [comment]
Interessante, mas acho que deveria ter um esquema de mudar a música em menos de 30 segundos ou de licença aberta comercialmente.
