### ISSUE TITLE
Expor robo via api (servico rest)

### ISSUE THREAD

**Issue by faustoct** [filipedeschamps/video-maker#73]
Expor o robo como servico via api rest

Objetivo / Vantagens
- Componentizar e isolar responsabilidades
- Reutilizar web / app
- pontos de extensão
- fácil manter e testar

Sugestões de endpoint
- Home
`GET /user/home`
````
Response
[{
  youtube-video-url:"https://www.youtube.com/watch?v=5J4J1K595vs",
  youtube-video-id: "5J4J1K595vs",
  title:"Who is Steve Jobs",
},
{
...
}
]
````

- Procurar por termo
`GET /search/{term}`
````
Response
{
  youtube-video-url:"https://www.youtube.com/watch?v=5J4J1K595vs",
  youtube-video-id: "5J4J1K595vs",
  title:"Who is Steve Jobs",
  searchterm: "Steve Jobs"
}
````

**Comment by nandumoura** [comment]
Top essa idéia

**Comment by MatheusRV** [comment]
@danielschmitz Porque fechou? Algum motivo em particular?

Voto até para usar uma tecnologia mais hype como GraphQL.
