### ISSUE TITLE
Desenvolver app / interface

### ISSUE THREAD

**Issue by faustoct** [filipedeschamps/video-maker#74]
Podemos expor td isso com uma interface bem amigável. O user final pode ter uma experiência bem agradável. Pensei numa interface tipo tinder. Simples, intuitiva e fácil de usar. Acho q fica legal.. precisa de uns ajustes mas é um start.. tá no [github](https://github.com/faustoct/4linked-app).

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/3135444/54669527-5c145480-4ad0-11e9-8bde-9fa6c61278a1.gif)

**Comment by ninjaoboladao** [comment]
Essa interface seria para o usuário final criar seus vídeos? Não entendi amigo

**Comment by faustoct** [comment]
@ninjaoboladao a ideia é criar um app. Esse app seria consumido por usuarios. Eu poderia ir na google play ou apple store e baixar. Isso é uma sugestão de mvp. O mvp deve ser criado para um proposito. Qual? Esse é o desafio..

Algumas ideias
- Aprenda qq tema em 1min.
- Aprenda algo novo todo dia.
- Curiosidades para vc.
- Seila oq :)

Pode ser educacional. Pode ser pra passar tempo. Pode ser pra aprender. Isso é algo q precisa ser discutido. Se tiver uma ideia compartilha :) Ainda poderia usar a api para terceiros.. num formato tipo algorithmia :D 

Minha sugestão é
- Idealizar MVP
- Codar MVP
- Definir business model
- Usar esse business model para pagar galera q ta no projeto :) (acho isso legal)
- Doar uma fatia dessa receita. As instituições poderiam se cadastrar e solicitar por isso. 

Como disse, esse projeto parece bem on going.

**Comment by faustoct** [comment]
@ninjaoboladao tô com tempo curto mas vou codar alguma coisa pra melhorar esse app. Ele tá num repositório público caso queira rodar na sua máquina :) abc

**Comment by faustoct** [comment]
@ninjaoboladao O q ficaria legal..
1. Video recomendados para o usuario. ele teria uma lista de videos antigos e novos.
2. um buscador tipo google q alimenta isso em tempo real. só q, isso eh dificil rs... 

Ainda mais importante q isso
1. Qual a utilidade disso pro usuário final?
2. É curiosidade? é educacional? é entretenimento? ..
