### ISSUE TITLE
Erro Watson

### ISSUE THREAD

**Issue by MatheusDeAquino** [filipedeschamps/video-maker#75]
Esse erro aparece quando executo o "index.js"
Insufficient credentials provided in constructor argument. Refer to the document for the required parameters. Common examples are username/password, api_key, and iam_access_token.
Parece que preciso botar meu user e senha que cadastrei no watson mas o @filipedeschamps fez com outro comando.

```
var nlu = new NaturalLanguageUnderstandingV1({
    iam_apikey: watsonApiKey,
    version: '2018-04-05',
    url: 'https://gateway.watsonplatform.net/natural-language-understanding/api/'
})
```

![error](https://user-images.githubusercontent.com/43558548/54786163-e5c63e00-4c06-11e9-9b14-57459c054463.JPG)

**Comment by faustoct** [comment]
Oi @MatheusDeAquino cara fiz o setup do projeto blz aqui. Pfv 
- Criou sua conta no Watson
- Verificar sua conta no Watson
- Setup dos arquivos de conf do watson
- Veja o arquivo `credentials/README.md ` ali tem as infos de setup do algorithima, watson, etc

abc eh noix

**Comment by faustoct** [comment]
Complementando. A msg diz q falta parametros. Comparando a forma como tá fazendo e da documentacao. Esses sao os parametros
File: `watson-nlu.json`

```
{
  "apikey": "Qynm-JBOd9m7JqEAFSvSt4feydYO4Pt0xYvAfaNEY2LW",
  "iam_apikey_description": "Auto generated apikey during resource-key operation for Instance - crn:v1:bluemix:public:natural-language-understanding:us-south:a/ffcb2c250e19bc335de2e9f1533711c8:4423b565-1e77-4d4c-a56e-656b3af7ac0d::",
  "iam_apikey_name": "auto-generated-apikey-27b6655f-6a69-40ba-a46a-60ae25b6d10a",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ffcb2c250e19bc335de2e9f1533711c8::serviceid:ServiceId-3b990ca3-62e6-4445-b303-84239f956d01",
  "url": "https://gateway.watsonplatform.net/natural-language-understanding/api"
}
````

**Comment by MatheusDeAquino** [comment]
Fiz isso.
Dentro do readme.md tem a credencial que peguei no watson e também fiz o arquivo "watson-nlu.json"

**Comment by MatheusDeAquino** [comment]
Até usando a "watson-nlu.json" da erro

**Comment by MatheusDeAquino** [comment]
> Complementando. A msg diz q falta parametros. Comparando a forma como tá fazendo e da documentacao. Esses sao os parametros
> File: `watson-nlu.json`
> 
> ```
> {
>   "apikey": "Qynm-JBOd9m7JqEAFSvSt4feydYO4Pt0xYvAfaNEY2LW",
>   "iam_apikey_description": "Auto generated apikey during resource-key operation for Instance - crn:v1:bluemix:public:natural-language-understanding:us-south:a/ffcb2c250e19bc335de2e9f1533711c8:4423b565-1e77-4d4c-a56e-656b3af7ac0d::",
>   "iam_apikey_name": "auto-generated-apikey-27b6655f-6a69-40ba-a46a-60ae25b6d10a",
>   "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Manager",
>   "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/ffcb2c250e19bc335de2e9f1533711c8::serviceid:ServiceId-3b990ca3-62e6-4445-b303-84239f956d01",
>   "url": "https://gateway.watsonplatform.net/natural-language-understanding/api"
> }
> ```
> VEja> https://github.com/filipedeschamps/video-maker/blob/master/credentials/README.md

Fiz isso.
Dentro do readme.md tem a credencial que peguei no watson e também fiz o arquivo "watson-nlu.json"
Até usando o "watson-nlu.json" dele está dando erro.

**Comment by faustoct** [comment]
@MatheusDeAquino 
![xxx](https://user-images.githubusercontent.com/3135444/54791361-4d38b980-4c18-11e9-9dca-78b9eb5461a8.png)
Minha pasta. Dentro do meu `watson-nlu.json`. Colei as credentials do watson natural language understading.

**Comment by faustoct** [comment]
Vc tá com as credentials que o Filipe publicou no README. Honestamente nao sei esses credenciais tao validas. 
- Fui no https://cloud.ibm.com/ e criei uma conta
- Fui no watson natural language understading.
- Criei uma crendencial
- Copiei colei no watson-nlu.json

**Comment by faustoct** [comment]
Usei essa sua chave
````
MacBook-Pro:4linked-api fausto$ node index.js 
Type a Wikipedia search term: Facebook

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
/Users/fausto/Projects/coding/4linked-api/robots/text.js:93
          throw error
          ^

Error: {"context":{"requestId":"a031cff83424420aa8b892e1b6e02204","requestType":"incoming.Identity_Token","userAgent":"NotSet","clientIp":"191.37.151.66","url":"https://iam.bluemix.net","instanceId":"iamid-3.8-5308-74c4c6dcbf-6fw7b","threadId":"135c163","host":"iamid-3.8-5308-74c4c6dcbf-6fw7b","startTime":"21.03.2019 23:41:28:355 UTC","endTime":"21.03.2019 23:41:28:419 UTC","elapsedTime":"64","locale":"en_US","clusterName":"iam-id-predal13-5E53"},"errorCode":"BXNIM0415E","errorMessage":"Provided API key could not be found"}
    at Request._callback (/Users/fausto/Projects/coding/4linked-api/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:113:21)
    at Request.self.callback (/Users/fausto/Projects/coding/4linked-api/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (/Users/fausto/Projects/coding/4linked-api/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:197:13)
    at IncomingMessage.<anonymous> (/Users/fausto/Projects/coding/4linked-api/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
````

**Comment by MatheusDeAquino** [comment]
Obrigado, man!
Encontrei o erro, eu não fiz o comando no "index.js" e por isso não rodava correto.
Tive que refazer meus passos pra poder entender onde estaria faltando alguma coisa.

**Comment by faustoct** [comment]
show, eh noix tmj :)
obs: aqui, fiz nda rs. Só setup do algorithmia / watson . Rodei `node index.js` e deu certo
abc
