### ISSUE TITLE
Escopo e tarefas

### ISSUE THREAD

**Issue by JuniorBaka** [filipedeschamps/video-maker#8]
- [x] Especificar tarefas e escopo

---

- [ ] ***Orquestrador***
 - [ ] Perguntar pelo termo de busca
 - [ ] Perguntar pelo prefixo
 - [ ] Iniciar robo de texto
 - [ ] Iniciar robo do video
 - [ ] Iniciar robo do YouTube

---

- [ ] ***Robo de texto***
 - [ ] Estrutura de dados
 - [ ] Pegar conteudo no Wikipedia
 - [ ] Limpar o conteudo
 - [ ] Quebrar em sentenças
 - [ ] Pegar a interpretaçao do Watson
 - [ ] Adicionar tags
 - [ ] Salvar estrutura de dados

---

- [ ] ***Robo de imagem***
 - [ ] Carregar a estrutura de dados
 - [ ] Buscar as imagens no Google Image
 - [ ] Baixar as imagens
 - [ ] Salvar a estrutura de dados

---

- [ ] ***Robo de video***
 - [ ] Preparar/ redimensionar as imagens
 - [ ] Criar as sentenças com imagens
 - [ ] Criar a thumbnail para o video
 - [ ] Renderizar o video com After Effects

---

- [ ] ***Robo do YouTube***
 - [ ] Autenticar o OAuth
 - [ ] Upload do video
 - [ ] Upload da thumbnail

**Comment by Kaypira** [comment]
Pessoal criei um servidor do discord para nós inscritos do Filipe, caso tenham interesse em entrar, segue o link abaixo:

https://discord.gg/Q73zZ6J (Filipe, desculpa usar o seu nome, mas como comentei e você apoiou, decidi adiantar a ideia para facilitar a comunicação entre nós em projetos, ideias novas para o canal e etc)

**Comment by fer2ap** [comment]
Acho que não é aqui que essa issue deveria estar hahaha

**Comment by filipedeschamps** [comment]
@JuniorBaka você deveria criar esta issue no seu repositório. Estou fechando essa, combinado? 👍

**Comment by helioaandrade** [comment]
A consulta de termos no Wikipedia poderia retornar o resultado na lingua portuguesa ou só funciona em Ingles?
Exemplo da chamada:
    const wikipediaAlgorithm = algorithmiaAuthenticated.algo('web/WikipediaParser/0.1.2')

**Comment by abdenirio** [comment]
> * [x]  Especificar tarefas e escopo
> 
> * [ ]  _**Orquestrador**_
> * [ ]  Perguntar pelo termo de busca
> * [ ]  Perguntar pelo prefixo
> * [ ]  Iniciar robo de texto
> * [ ]  Iniciar robo do video
> * [ ]  Iniciar robo do YouTube
> 
> * [ ]  _**Robo de texto**_
> * [ ]  Estrutura de dados
> * [ ]  Pegar conteudo no Wikipedia
> * [ ]  Limpar o conteudo
> * [ ]  Quebrar em sentenças
> * [ ]  Pegar a interpretaçao do Watson
> * [ ]  Adicionar tags
> * [ ]  Salvar estrutura de dados
> 
> * [ ]  _**Robo de imagem**_
> * [ ]  Carregar a estrutura de dados
> * [ ]  Buscar as imagens no Google Image
> * [ ]  Baixar as imagens
> * [ ]  Salvar a estrutura de dados
> 
> * [ ]  _**Robo de video**_
> * [ ]  Preparar/ redimensionar as imagens
> * [ ]  Criar as sentenças com imagens
> * [ ]  Criar a thumbnail para o video
> * [ ]  Renderizar o video com After Effects
> 
> * [ ]  _**Robo do YouTube**_
> * [ ]  Autenticar o OAuth
> * [ ]  Upload do video
> * [ ]  Upload da thumbnail

Vou começar o projeto acompanhando os videos  do canal, mas não quero criar um novo repositorio, então acho que vou responder mesm aqui!
