### ISSUE TITLE
Upload do conteúdo gerado pelo robo nas redes sociais

### ISSUE THREAD

**Issue by faustoct** [filipedeschamps/video-maker#80]
Isso é uma sugestão de estratégia de mkt digital. Seguintes plataformas podem ser alimentadas via api, com o conteúdo gerado pelo robo.
- Medium
- Facebook
- Twitter
- Instagram

**Objetivo:** Usar o conteúdo gerado pelo robo para alimentar as mídias sociais do mvp/projeto.

**Vantages**
- Trabalho automatizado de marketing digital
- Conteúdo está curado e excelente SEO
- Gerar leads para uso do serviço/mvp
- Uso de tags aumenta o discoverability
- Aumentar presença digital
- Bom alcance organico em redes sociais q priorizam videos (Facebook / Instagram)
- Branding

**Comment by leodutra** [comment]
Excelente ideia

**Comment by ninjaoboladao** [comment]
Boa ideia, porém acho que seria melhor o backend separado para q nos possamos criar um serviço com esses robôs e por a venda

**Comment by leodutra** [comment]
Fazendo como módulo e CLI fica fácil de criar um endpoint rest

**Comment by danielschmitz** [comment]
Bem legal ,vamos centralizar essa ideia em #77
