### ISSUE TITLE
Error: "errorMessage":"Provided API key could not be found" 

### ISSUE THREAD

**Issue by GuibaGold** [filipedeschamps/video-maker#81]
Estou com dificuldade para acessar a API da forma que o Filipe faz, atribuindo o valor da apiKey pelo arquivo watson-nlu.json, sendo assim atribuí o valor diretamente como uma string, mas aí recebo o erro depois de processar a user-input 
![image](https://user-images.githubusercontent.com/31520760/54869019-a831f400-4d71-11e9-8464-ca1d42b3e3dc.png)

Help me!

**Comment by hugocalheira** [comment]
@GuibaGold , se puder, cola aí o seu arquivo `text.js`.
Obs: lembre de mascarar a sua api key.

**Comment by GuibaGold** [comment]
![image](https://user-images.githubusercontent.com/31520760/54872992-08458c00-4dac-11e9-9a7e-849ada5a7f49.png)

![image](https://user-images.githubusercontent.com/31520760/54872993-1a272f00-4dac-11e9-8ec3-10b7d1c54275.png)

![image](https://user-images.githubusercontent.com/31520760/54872995-227f6a00-4dac-11e9-9184-11e84386656e.png)


dessa forma está funcionando

**Comment by GuibaGold** [comment]
> Estou com dificuldade para acessar a API da forma que o Filipe faz, atribuindo o valor da apiKey pelo arquivo watson-nlu.json, sendo assim atribuí o valor diretamente como uma string, mas aí recebo o erro depois de processar a user-input
> ![image](https://user-images.githubusercontent.com/31520760/54869019-a831f400-4d71-11e9-8464-ca1d42b3e3dc.png)
> 
> Help me!

Resolvi Galera! Infelizmente não consegui mascarar a apiKey

**Comment by thiagobutignon** [comment]
@GuibaGold 
cara verifica se você não importou errado:

```js
const watsonApiKey = require("../credentials/watson-nlu.json").apikey;
```

O meu estava com o mesmo erro que o seu, eu escrevi apiKey e é apikey. Com minúscula, não é camel case!

**Comment by danielschmitz** [comment]
#87 vai te ajudar nessa questão
