### ISSUE TITLE
Duvida?! Video Robot!

### ISSUE THREAD

**Issue by bvrpythondev** [filipedeschamps/video-maker#83]
@filipedeschamps 
@danielschmitz 
Bom dia a todos.Estou tentando criar o video apartir das imagens ou seja renderiza las.Entrentanto não consegui achar nenhuma api que faça ou alguma documentação sobre.Procurei sobre o adobe after effects e como usar e n encontrei.

Alguem sabe qual api o Filipe o usou ou alguma ideia sobre?

Seria de grande ajuda.

Ate agora somente consegui isso com o ffmpeg mesmo assim o video n fica bem redimensionado como o do Deschamps e sem a intro do after effects

```
import os

class VideoRobot():

    def __init__(self, project_directory):
        self.images_directory = project_directory
        self.subtitles_template =  NOTE:TEMPLATE DE SUBTITILES RETIRADO DEVIDO AS ASPAS!
    def make_video(self):
        command = "cat {0}/*.jpg | ffmpeg -y -framerate 0.08 -f image2pipe -i - {0}/output_imgs.mp4".format(self.images_directory)


        os.system(command)

    def add_subtitles(self, sentences):
        self.subtitles_template = self.subtitles_template.format(sentences[0],
            sentences[1], sentences[2], sentences[3],
            sentences[4], sentences[5], sentences[6])

        with open("{0}/subtitles.srt".format(self.images_directory), "w") as subtitles_file:
            subtitles_file.write(self.subtitles_template)

        os.system("ffmpeg -y -i {0}/output_imgs.mp4 -vf subtitles={0}/subtitles.srt{0}/output_text.mp4".format(self.images_directory))

    def add_music(self):
        os.system("ffmpeg -y -i {0}/output_text.mp4 -i music.ogg -c copy -map 0:v:0 -map 1:a:0 {0}/final_video.mp4".format(self.images_directory))
```

```

   def convert_to_jpg_and_Resize(self, files):
        print(files)
        for f in files:
            imagem = Image.open(f)
            altura_desejada = 720
            largura_desejada = 1280
            largura_imagem = imagem.size[0]
            altura_imagem = imagem.size[1]

            if largura_imagem > altura_imagem:
                print("largura_imagem > altura_imagem")
                percentual = float(largura_desejada) / float(largura_imagem)
                altura_desejada = int((altura_imagem * percentual))
                imagem = imagem.resize((largura_desejada, altura_desejada), Image.ANTIALIAS)
            else:
                print("altura_imagem > largura_imagem")
                percentual = float(altura_desejada) / float(altura_imagem)
                largura_desejada = int((largura_imagem * percentual))
                imagem = imagem.resize((largura_desejada, altura_desejada), Image.ANTIALIAS)
            imagem.save('{}-{}x{}.jpg'.format(f,imagem.size[0], imagem.size[1]))
            os.remove(f)

```

Muito Obrigado e até breve!

**Comment by bvrpythondev** [comment]
Concordo o problema é que os videos demoram para sair

**Comment by faustoct** [comment]
cara... da uma segurada.. ele da fazendo o lance de gratis.. nego fica furioso pra ver o proximo passo kkk.. ele ta na campus party.. agora soh em agosto, de deus :)
vc pode adiantar as proximas etapas .. ja pensei nisso :D

**Comment by danielschmitz** [comment]
> 
> 
> Concordo o problema é que os videos demoram para sair

pra mim isso nao é problema

**Comment by leodutra** [comment]
O Filipe foi claro, no primeiro vídeo, que adoraria que qualquer um tivesse seu proprio video-maker.
Talvez ele sequer consiga acompanhar um projeto open source porque já tem lá seu trabalho, seu canal e programa por hobbie.

Vamos criando o que acharmos legal.  A princípio estou compilando uma versão com merge de muitos PRs, organizados, para uma futura evolução. 

Tenho posto uma força em termos uma org com vários projetos, um para cada propósito... contendo suas APIs e robots contidos para que possam ser importados e utilizados on-demand. Mas daí não sei da aceitação do pessoal.

Isso permitiria que projetos como o seu fossem criados e utilizados, no futuro, em workflows customizados.

Sobre a questão de aprendizagem, isso vai um pouco contra uma ideia de expansão e de projeto amplo.

Então ou o projeto serve para aprendizagem e a org surge como um fork com foco em evolução, ou o projeto principal vira a org e os estudos ficam por conta de planos particulares.

Ainda não sabemos como será.

**Comment by danielschmitz** [comment]
Conforme em #77, esse projeto possivelmente nao terá PRs, talvez no README no final contendo informações sobre os projetos do video-maker, como o seu @bvrpythondev em python. Eu acredito que o "video-maker-professional" rsrs estará no repo do @leodutra que já está fazendo várias coisa legais. 

por enquanto estou fechando a issue e podemos ir convesando sobre o video-maker em python no seu repo @bvrpythondev, beleza?

**Comment by filipedeschamps** [comment]
Turma, obrigado por toda discussão! Exato, este repositório aqui ficará como referência educacional dos vídeos e sugiro que o MVP seja evoluído em outro lugar, como apontado na issue #77 e que faremos referência no README de tudo que esse projeto aqui teve de spinoff 👍
