### ISSUE TITLE
Dúvida: porque usar const no for... of

### ISSUE THREAD

**Issue by Marcos012** [filipedeschamps/video-maker#84]
Por que no robô `text.js` o
```
 for (const sentence of content.sentences) 
``` 
é uma `const` e não `let`?

**Comment by leodutra** [comment]
For in e for of podem utilizar const porque uma nova variável é criada a cada atribuição.
For( ; ; ) não.

**Comment by faustoct** [comment]
cara não sei rs.. a cada iteração é uma declaração de const nova então poderia ser let, const, var.. eu acho..

**Comment by faustoct** [comment]
galera gosta do hype :)

**Comment by faustoct** [comment]
pfv fechem a issue :)

**Comment by leodutra** [comment]
Só ler a especificação da ECMA. 
A cada loop o escopo de `for..in` e `for..of` é recriado então não ocorre erro, nem no Node.js, nem em browsers.

Agora preferência, quanto a isso, é uma grande perda de tempo como qualquer outro preciosismo com estética.

`const` é quase sempre a melhor opção quando possível pois permite otimização automática da engine V8.

**Comment by faustoct** [comment]
@leodutra boa :)
