### ISSUE TITLE
[Atualizado 01/05] Passo a Passo para executar o projeto pela primeira vez

### ISSUE THREAD

**Issue by hebertlima** [filipedeschamps/video-maker#89]
E ae galera!
Estou vendo que alguns devs aqui estão com problemas para rodar o projeto, talvez por que alguns não estão acompanhando a serie no [YouTube](https://www.youtube.com/watch?v=kjhu1LEmRpY&list=PLMdYygf53DP4YTVeu0JxVnWq01uXrLwHi) e por pegarem o "bonde andando" estão pulando algumas etapas do projeto e indo direto para o `node index.js`, então aqui vai a transcrição do passo-a-passo (que está sendo explicado nos vídeos) detalhado de como rodar o projeto para os desavisados de primeira viagem :stuck_out_tongue_winking_eye:

## Start ##
Vou partir do princípio que você caiu na playlist e é aspirantes a programação e não está familiarizados com o **Git** ou **Node.js**, então primeiro você precisa instalar o [Node.js](https://nodejs.org/en/) no seu pc e seguir o procedimento padrão de instalação **next->next->ok**, recomendo você baixar o [Git](https://git-scm.com/downloads) e instalar na sua maquina, depois basta copiar a URL do projeto conforme abaixo:

![Start](https://i.imgsafe.org/cb/cb0daa65df.gif)

## Clonando o Repositório ##
Com o Git e o Node.js instalado na sua maquina e a **URL** do projeto em mãos, cria em algum lugar do seu pc uma pasta para criarmos uma copia do repositório, dentro dela abra o **cmd** ou **powershell** e digite os comandos abaixo:
```
git clone https://github.com/filipedeschamps/video-maker.git
cd video-maker
npm install
```

![Clone](https://i.imgsafe.org/ca/caed010086.gif)

## Api: Algorithmia ##
É necessário criar a sua chave de acesso para poder testar os robôs, pra isso você precisa acessar o site do [Algorithmia](https://algorithmia.com/), aqui não tem muito segredo, basta acessar e se cadastrar, depois de logar na sua conta, na Dashboard procure no menu **Api Keys** e **copie**.

![Algorithmin](https://i.imgsafe.org/ba/ba1d23897c.gif)

vá até a pasta do projeto onde você clonou o repositório, navegue até a pasta **video-maker\credentials**, crie um arquivo de texto e renomeie para `algorithmia.json`, dentro desse arquivo você irá colocar a `API` que copiou do site **Algorithmia** na estrutura abaixo:
``` js
{
  "apiKey": "API_KEY_AQUI"
}
```

## Api: Watson ##
Você precisa criar também as credenciais do *Watson* no site da [IBM](https://cloud.ibm.com/login), também não tem segredo, basta se cadastrar, quando estiver logado no menu superior clique em **Catálogo**, depois dentro de **IA** procure por *Natural Language Understanding*

![IBM](https://i.imgsafe.org/ba/bab0fc4ecd.jpeg)

clicando nele na nova página vai aparece um botão "criar" no final da página, uma vez que o serviço for criado, você será redirecionado para a página de gerenciamento do serviço que você acabou de criar, no menu lateral esquerdo procure por **Credenciais de Serviços** e depois clique em **Auto-generated service credentials** destacado abaixo, então copie as *Credenciais*:

![IBM](https://i.imgsafe.org/ba/bace46f16b.jpeg)

Novamente, voltando na pasta do projeto ainda dentro da pasta **video-maker\credentials** você ira criar um novo arquivo de texto com o nome `watson-nlu.json` e dentro desse arquivo você vai colar as credenciais que copiou anteriormente:
``` js
{
  "apikey" : "...",
  "iam_apikey_description" : "...",
  "iam_apikey_name": "...",
  "iam_role_crn": "...",
  "iam_serviceid_crn": "...",
  "url": "..."
}
```

## Setup: Google Cloud Plataform ##
Antes de criarmos as api's que iremos utilizar é necessário vincular a nossa conta do Google com o [Google Cloud Plataform](https://cloud.google.com/), na página do **Google Cloud Plataform** você irá clicar no botão **Faça uma Avaliação Gratuita**:

![google-cloud](https://i.imgsafe.org/61/61ce83ca22.png)

 em seguida marque a opção **Termos e Condições**

![google-cloud-step1](https://i.imgsafe.org/62/621a2df511.png)

> Ps.: É importante lembrar que alguns recursos do **Google Cloud Plataform** são **Pagos**, por esse motivo é necessário inserir as informações de pagamento, mas fique tranquilo porque iremos utilizar apenas os recursos **Gratuitos**

![google-cloud-pay](https://i.imgsafe.org/62/6253ce8142.jpeg)

## Criando o Projeto ##

Agora é a hora de criarmos um projeto que iremos vincular as Api's que vamos utilizar, para isso basta clicar no menu do topo da página "**Selecionar projeto**" e depois em "**Novo Projeto**":

![image](https://user-images.githubusercontent.com/34013325/55571155-52e3d400-56db-11e9-998f-bd99ab647403.png)

de um nome ao projeto e clique no botão **criar:**

![image](https://user-images.githubusercontent.com/34013325/55571267-963e4280-56db-11e9-9b21-7f028caa05c1.png)

após isso o projeto começará a ser criado e assim que terminar um menu vai aparecer com o projeto que acabamos de criar então você irá seleciona-lo:

![image](https://user-images.githubusercontent.com/34013325/55571506-064cc880-56dc-11e9-804b-f14003dccc09.png)

## Api: Custom Search API ##

Com o projeto criado agora é hora de habilitarmos e configurarmos a Api, você irá clicar no menu lateral esquerdo no topo navegar até **API's e Serviços** > **Bibliotecas**:

![image](https://user-images.githubusercontent.com/34013325/55572521-22ea0000-56de-11e9-89cc-f477fe18bf65.png)

no campo de pesquisa basta procurar por **Custom Search API**, clicar em **Ativar**, e aguardar até a ativação da api:

![image](https://user-images.githubusercontent.com/34013325/55572661-78bea800-56de-11e9-9ae3-fbc87758aa84.png)

Após a ativação vai aparecer uma mensagem solicitando a criação das credenciais da API, então basta você clicar em **Criar Credenciais**:

![image](https://user-images.githubusercontent.com/34013325/55572835-eb2f8800-56de-11e9-8292-fc3c4bf74084.png)

Procure por **Custom Search API** no dropdown e clique em "**Preciso de quais credenciais?**"

![image](https://user-images.githubusercontent.com/34013325/55572958-2cc03300-56df-11e9-8bc1-17641ba5138e.png)

Após isso irá aparecer sua Api Key, você vai copia-la e clicar no botão concluir, voltando a pasta do projeto você vai navegar até **video-maker/credentials** e irá criar um novo arquivo chamado **google-search.json** com o conteúdo abaixo:

```
{
  "apiKey": "API_KEY_AQUI"
}
```

## Api: Custom Search Enginer ##
Agora iremos configurar o nosso motor de busca personalizado do google, para isso você vai acessar o [Custom Search Engine](https://cse.google.com/cse/create/new), e irá informar o **site a pesquisar** coloque **google.com**, ire selecionar o idioma que preferir *no vídeo o Filipe deixa Inglês então aconselho deixar em inglês*, e por fim clique em **Opções avançadas** e para o esquema iremos utilizar o mais genérico **Thing**, pronto tudo preenchido você irá clicar em **criar**:

> PS.: Para saber mais sobre o schema que o Filipe cita no vídeo acesse [schema.org](https://schema.org/docs/full.html)

![image](https://user-images.githubusercontent.com/34013325/55578410-38662680-56ec-11e9-80ea-06ff9e25ba3f.png)

Agora basta clicar em **Painel de Controle** na nova tela nós iremos habilitar a opção **Pesquisa de imagens** e depois iremos clicar no botão **Copiar para área de transferência**"

![image](https://user-images.githubusercontent.com/34013325/55574756-8a567e80-56e3-11e9-99ea-d307547c781f.png)

> Ps.: Existem diversas opções que eu aconselho futuramente você testar e descobrir o que cada uma dela faz 😋 

![image](https://user-images.githubusercontent.com/34013325/55574920-0355d600-56e4-11e9-8f36-822a62224fab.png)

Voltando no arquivo **google-search.json** iremos criar uma nova propriedade e iremos colar o código identificador do mecanismo de busca que criamos, identificado por `searchEngineId`, no final irá ficar assim:

```
{
  "apiKey": "API_KEY_AQUI"
  "searchEngineId": "ID_MECANISMO_DE_BUSCA"
}
```

## Api: YouTube ##

Chegou a hora de configurarmos a api do youtube!, como fizemos na api custom search iremos fazer o mesmo com a api do YoutTube, então basta acessar o [Google Cloud](https://cloud.google.com/) e habilitar o serviço do YouTube, clicando no menu Lateral **Apis e Serviços -> Biblioteca**, na caixa de pesquisa procure por **YouTube**, e click no botão Ativar: 

![ezgif-5-fa13fd3c8407](https://user-images.githubusercontent.com/34013325/57034414-d08cf800-6c25-11e9-9867-03024a30028a.gif)

> Ps. No vídeo o Filipe orienta a criar um novo projeto para adicionar a api do Youtube, porem aqui, estou usando o mesmo projeto que criei para o video-maker, mas caso queria criar um novo projeto basta seguir os passos de **Criando o Projeto** que está no começo desse guia!

Agora clique na guia **Tela de consentimento OAuth** 
![image](https://user-images.githubusercontent.com/34013325/57034753-c0294d00-6c26-11e9-8ee9-ff5e12ea6470.png)

Em seguida preencha apenas o campo "nome do aplicativo", futuramente você pode voltar aqui para personalizar com as outras informações caso desejar:

![image](https://user-images.githubusercontent.com/34013325/57034907-1d250300-6c27-11e9-8c9f-e2e0d4e95b95.png)

Clique no dropdown **Criar credenciais** e escolha **ID do Cliente OAuth**:
![image](https://user-images.githubusercontent.com/34013325/57035299-1054df00-6c28-11e9-9a04-a4cef439e41e.png)

Aqui não tem muito segredo, escolha **Aplicativo da Web** para o **Tipo de Aplicativo**, escolha um **nome do aplicativo**, no primeiro campo insira o endereço **http://localhost:5000** e no segundo **http://localhost:5000/oauth2callback** e clique no botão criar:

![image](https://user-images.githubusercontent.com/34013325/57035477-85281900-6c28-11e9-829a-1c0c074bc478.png)

Após ser criada, irá aparecer uma janela com as credenciais, você pode dar ok, pois iremos baixar as credencias como na tela abaixo:

![image](https://user-images.githubusercontent.com/34013325/57036076-aa695700-6c29-11e9-8c4d-fc78fecdae46.png)

renomeio o arquivo para **youtube.json** e salve dentro da pasta **video-maker/credentials** 😄

## 1.., 2..., 3... Testando! ##
Agora dentro da pasta **video-maker** você pode abrir o **cmd** ou **powershell** e executar o comando:
```
node index.js
```
![ezgif-5-924644a4b21d](https://user-images.githubusercontent.com/34013325/55579383-79f7d100-56ee-11e9-9bba-b92704a85b08.gif)

>**Dica Extra** Para quem estiver usando o Adobe After Effects, eu não consegui encontrar a extenção apartir do cloud creative, mas encontrei no proprio site da [Adobe aqui](https://helpx.adobe.com/download-install/kb/creative-cloud-apps-download.html) 😃

**Comment by filipedeschamps** [comment]
Nossa @hebertlima matou a pau!!!! Sério, fico emocionado quando vejo essas coisas! Muito obrigado :) o vídeo sobre as credenciais da API oficial do Google sai nessa segunda 👍

**Comment by azludium** [comment]
Agora ficou lindo Hebert, grato pela carinho e pela dedicação, até um ignóbil em programação com eu consegue

**Comment by hebertlima** [comment]
@filipedeschamps que isso cara é o minimo! quero contribuir com o que eu puder, esse projeto vai ficar massa demais :laughing:! @azludium conforme for saindo as video aulas irei atualizando pra deixar o mais facil possível assim todo mundo pode testar mesmo sem saber muito sobre programação :stuck_out_tongue_winking_eye:

**Comment by Kelvao** [comment]
Acho válido colocar isso no readme do projeto, com algumas sessões sobre as funcionalidades e link para os videos.

**Comment by hebertlima** [comment]
@Kelvao boa, vou adicionar essas seções sobre as funcionalidades :laughing:

**Comment by danielschmitz** [comment]
@hebertlima Alterei o título para ficar mais claro, oK? Parabéns pelo tópico

**Comment by rafabp82** [comment]
Fiz exatamente o que o passo-a-passo diz, deu tudo certo até a hora que fui rodar, rs. Deu o seguinte erro:
internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: C:\Users\Rafael\Downloads\video-maker\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Rafael\Downloads\video-maker\video-maker\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

Alguém sabe o que é isso?

**Comment by diegomagikal** [comment]
@rafabp82 o seu arquivo ```google-search.json```está com um erro de sintaxe... verifique linha por linha, deve ter esquecido de alguma vírgula, aspas ou algo assim!

**Comment by DharanaVentura** [comment]
> Fiz exatamente o que o passo-a-passo diz, deu tudo certo até a hora que fui rodar, rs. Deu o seguinte erro:
> internal/modules/cjs/loader.js:723
> throw err;
> ^
> 
> SyntaxError: C:\Users\Rafael\Downloads\video-maker\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
> at JSON.parse ()
> at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (C:\Users\Rafael\Downloads\video-maker\video-maker\robots\image.js:6:33)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
> 
> Alguém sabe o que é isso?

Conseguiu resolver? O meu erro é idêntico ao seu, Estou até agora tentando achar erro de sintaxe, já fiz o pap do #125 várias vezes... rsrsrs

**Comment by diegomagikal** [comment]
@DharanaVentura poste seu ```google-search.json``` aí...

**Comment by DharanaVentura** [comment]
> @DharanaVentura poste seu `google-search.json` aí...

{
  "apiKey": "AIzaSyBKX70U47sJuGNbKBtA5PvsXbtboI"
  "searchEngineId": "016916573647549:1mzefrn4"
}


Não estou expondo a chave original.

Thankyou.

internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: C:\Users\dhara\node\geratube\credentials\google-search.json: Unexpected string in JSON at position 56
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\dhara\node\geratube\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by diegomagikal** [comment]
@DharanaVentura está faltando uma vírgula depois do valor de apiKey:

```"apiKey": "AIzaSyBKX70U47sJuGNbKBtA5PvsXbtboI",```

**Comment by DharanaVentura** [comment]
Obrigada, e desculpe a falta de atenção.

**Comment by rafabp82** [comment]
> @DharanaVentura está faltando uma vírgula depois do valor de apiKey:
> 
> `"apiKey": "AIzaSyBKX70U47sJuGNbKBtA5PvsXbtboI",`

Obrigado pela dica, agora rodou, porém dá outro erro após ele baixar as imagens:


(node:7900) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content

    at ChildProcess.onExit (C:\Users\Rafael\Downloads\video-maker\video-maker\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.cp.emit (C:\Users\Rafael\Downloads\video-maker\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:7900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by doug-simon** [comment]
> > @DharanaVentura está faltando uma vírgula depois do valor de apiKey:
> > `"apiKey": "AIzaSyBKX70U47sJuGNbKBtA5PvsXbtboI",`
> 
> Obrigado pela dica, agora rodou, porém dá outro erro após ele baixar as imagens:
> 
> (node:7900) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro Inv�lido - /content
> 
> ```
> at ChildProcess.onExit (C:\Users\Rafael\Downloads\video-maker\video-maker\node_modules\gm\lib\command.js:301:17)
> at ChildProcess.emit (events.js:189:13)
> at ChildProcess.cp.emit (C:\Users\Rafael\Downloads\video-maker\video-maker\node_modules\cross-spawn\lib\enoent.js:40:29)
> at maybeClose (internal/child_process.js:970:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> ```
> (node:7900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:7900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Eu estava com o mesmo erro e achei a solução aqui: https://github.com/filipedeschamps/video-maker/issues/110#issuecomment-480595553

**Comment by jpfurlan** [comment]
Alguem pode me ajudar esta dando esse erro. 
$ node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\PC\Desktop\video-maker\video-maker\robots\te
xt.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by hebertlima** [comment]
Galera adicionei o tutorial sobre como criar as credenciais do youtube, vocês acham necessário criar uma explicação sobre o affter effects também? eu particulamente tive uns probleminhas pra ele rodar assim como  o um macete do imahemagick no windows 10

**Comment by Beaast-exe** [comment]
@hebertlima #155 eu segui tudo e nao funciona ...

**Comment by onibusmoc** [comment]
erro algume me ajuda??
video-maker\credentials\google-search.json: Unexpected string in JSON at position 60

**Comment by hebertlima** [comment]
> 
> 
> @hebertlima #155 eu segui tudo e nao funciona ...

desculpa demora @Beaast-exe, eu abri uma pr no seu repo corrigindo o problema de autenticação, no caso vc apenas colocou a url errada 😄 da uma olhada [aqui](https://github.com/Beaast-exe/youtube-video-maker/compare/master...hebertlima:patch-1?expand=1#diff-866138791efc9494be5fd2fa4c37a14b)

**Comment by onibusmoc** [comment]
Preciso muito da ajuda de voces, alguem sabe consegue resolver?

C:\Users\serje\Desktop\Nova pasta\video-maker>node index.js
internal/modules/cjs/loader.js:723
    throw err;
    ^

SyntaxError: C:\Users\user\Desktop\Nova pasta\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\serje\Desktop\Nova pasta\video-maker\robots\image.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by hebertlima** [comment]
> 
> 
> Preciso muito da ajuda de voces, alguem sabe consegue resolver?
> 
> C:\Users\serje\Desktop\Nova pasta\video-maker>node index.js
> internal/modules/cjs/loader.js:723
> throw err;
> ^
> 
> SyntaxError: C:\Users\user\Desktop\Nova pasta\video-maker\credentials\google-search.json: Unexpected string in JSON at position 60
> at JSON.parse ()
> at Object.Module._extensions..json (internal/modules/cjs/loader.js:720:27)
> at Module.load (internal/modules/cjs/loader.js:600:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
> at Function.Module._load (internal/modules/cjs/loader.js:531:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:22:18)
> at Object. (C:\Users\serje\Desktop\Nova pasta\video-maker\robots\image.js:5:33)
> at Module._compile (internal/modules/cjs/loader.js:701:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

tem algo escrito errado dentro do **google-search.json** talvez vc esqueceu uma virgulra `(,)` ou dois pontos `(;)` em algum lugar

**Comment by onibusmoc** [comment]
Ajuda ai galera esse Erro como posso resolver?


> [video-robot] Sentence created: ./content/5-sentence.png
> [video-robot] Sentence created: ./content/6-sentence.png
> [video-robot] YouTube thumbnail created
> [video-robot] Starting After Effects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn Program FilesAdobeAdobe After Effects CC 2019aerender ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by onibusmoc** [comment]
Me ajuda ai galera, como resolver esse Erro?

> [video-robot] Sentence created: ./content/5-sentence.png
> [video-robot] Sentence created: ./content/6-sentence.png
> [video-robot] YouTube thumbnail created
> [video-robot] Starting After Effects
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn Program FilesAdobeAdobe After Effects CC 2019aerender ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hebertlima** [comment]
@onibusoc você precisa corrigir o o caminho que o robo video.js esta chamando o aerender.exe

**Comment by onibusmoc** [comment]
Agora esse erro


PROGRESS:  0:01:14:29 (2250): 1 segundos
PROGRESS:  13/05/2019 18:40:33: composi��o conclu�da main.
PROGRESS:  Tempo total decorrido: 13 min, 8 s
LoadLibrary "n" failed!
LoadLibrary "n" failed!
> [video-robot] After Effects closed
> [youtube-robot] Starting...
> [youtube-robot] Listening on http://localhost:5000
(node:15568) UnhandledPromiseRejectionWarning: Error: Cannot find module '../credentials/google-youtube.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at createOAuthClient (C:\Users\serje\Desktop\X\video-maker\robots\youtube.js:42:27)
    at authenticateWithOAuth (C:\Users\serje\Desktop\X\video-maker\robots\youtube.js:18:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rafaeljustinox** [comment]
> credentials/google-youtube.json

Verifique se você tem exatamente esse arquivo "credentials/google-youtube.json"

**Comment by 8uch3ch4** [comment]
Bom dia, Galeraaa 
Estou com esse erro, 

PS C:\Users\Usuario\video-maker-master> node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../credentials/algorithmia.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Usuario\video-maker-master\robots\text.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
PS C:\Users\Usuario\video-maker-master>

sou um novato em programação, já olhei tudo esse post, e não estou entendendo muito

**Comment by WSantos79** [comment]
Na parte de criar a credencial da Custom Search API está diferente, nao consigo fazer igual ao tutorial, alguém pode ajudar?
![custom search](https://user-images.githubusercontent.com/58752564/70944189-caf6ed80-200f-11ea-8add-8163c9d05737.PNG)
