### ISSUE TITLE
Problema na captura e crop de imagens do google search

### ISSUE THREAD

**Issue by diegohamaz** [filipedeschamps/video-maker#92]
Pessoal,

Estou com um problema aqui nessa função

 `    const response = await customSearch.cse.list({
      auth: googleSearchCredentials.apiKey,
      cx: googleSearchCredentials.searchEngineId,
      q: query,
      searchType: 'image',
      num: 2
    })`

estou recebendo 

(node:19434) UnhandledPromiseRejectionWarning: Error: null

e minhas credenciais "aparentemente" estão todas corretas meu json esta assim

{
  "apiKey": "AIzaSyABEyg5uSKQ..........................",
  "searchEngineId":"013723144432942052828:u2322.........."
}

alguem tem ideia porque nao lista as imagens??

obrigado !

**Comment by diegohamaz** [comment]
Já entendi o que aconteceu pode fechar , o google search estava desativado para retornar imagens e so me retornava NULL , ativando em https://cse.google.com funcionou , obrigado

**Comment by felipealfah** [comment]
@diegohamaz conseguiu resolver o erro?? Aqui ta da mesma Forma, Ele baixa as imagens mas na hora de converter e começar a rodar o Robo de Video retorna esse erro.

**Comment by diegohamaz** [comment]
@felipealfah no comentario acima citei a resolução.
