### ISSUE TITLE
Problemas ao ler e gravar os arquivos em disco

### ISSUE THREAD

**Issue by leandroungari** [filipedeschamps/video-maker#96]
Pessoal, eu montei um projeto que utiliza a função de ler e escrever o arquivo em disco que Filipe mostra no vídeo desse projeto.

```
import fs from "fs";

const stateFilePath = "./app.json";
const datasetFilePath = "./dataset.json";

const load = (filePath) => {
  const fileBuffer = fs.readFileSync(
    filePath, "utf8"
  );
  return JSON.parse(fileBuffer);
}

const store = (filePath, data) => {
 
  const contentString = JSON.stringify(data);
  fs.writeFileSync(filePath, contentString);
}
```
O código está praticamente idêntico, o problema é que no meu a escrita em disco só é realizada quando eu finalizo o programa no node.js, sendo que a leitura e gravação são chamadas várias vezes durante a execução do programa.

A minha aplicação consiste em um terminal simples, que fica em loop recebendo os comandos dos usuários e executando as respectivas tarefas.

Como exemplo, tem a função de leitura de datasets, que seriam arquivos em <code>json</code> ou <code>csv</code>. Essa é a função que recebe um objeto de comandos, basicamente na ideia de chave/valor.

```
prompt(commands = {}) {
  while(this.isRunning) {
      
    const message = readLineSync.question("$ ", {limit: null});

    const currentCommand = this.processMessage(message);

    if(Object.keys(commands).includes(currentCommand.type)) {
      commands[currentCommand.type](...currentCommand.options);
    }
    else console.log("  command not found, try again.");  
  }
}
```
Como exemplo de comandos tem esses:
```
{
  "load-dataset": (type, name, from) => {
     loadDataset({type, name, from});
  },
  "list-dataset": () => {
      listDataset();
  },
  "exit": () => {
    this.stop();
  }
}
```
No comando <code>load-dataset</code>, é lido os dados de um arquivo externo, esse novos dataset precisa ser incluído no estado da aplicação, então usando as duas primeiras funções, eu leio a versão em disco, atualizo ela e, em seguida, gravo novamente.

O problema é que a gravação é postergada para quando eu encerro a aplicação, então qualquer leitura que eu realizo vai estar errada porque o estado da aplicação estará desatualizado.

**Comment by vsalbuq** [comment]
@leandroungari Não entendi o problema. Pode explicar melhor?

Você quis dizer que chama as funções em vários pontos, mas ele só grava de fato no final?

**Comment by leandroungari** [comment]
> @leandroungari Não entendi o problema. Pode explicar melhor?
> 
> Você quis dizer que chama as funções em vários pontos, mas ele só grava de fato no final?

Isso, mas um instante, vou explicar melhor.

**Comment by leandroungari** [comment]
> @leandroungari Não entendi o problema. Pode explicar melhor?
> 
> Você quis dizer que chama as funções em vários pontos, mas ele só grava de fato no final?

Perfeito, mas

**Comment by leandroungari** [comment]
Fiquei o dia inteiro nisso ontem. Não é nem perto de uma solução, mas pensei no seguinte. Pode estar acontecendo um conflito entre a leitura e gravação dos arquivos, as quais usam <code>readFileSync</code> e <code>writeFileSync</code>, com o <code>readLineSync.question()</code> ou qualquer outro método do <code>readLineSync</code> que eu tenha tentado. 
Só por detalhe essa variável é do pacote <code>readline-sync</code>.

Para minha solução temporária pensei, já que a escrita do arquivo está sendo travada e deixada para o termino do programa, vou ter que fazer o programa esperar antes de ler e executar a próxima instrução do usuário. Então fiz o seguinte:

```
prompt(commands = {}) {
  while(this.isRunning) {
    setTimeout(() => {
      console.log("oi");    
    }, 5000);

    const message = readLineSync.question("$ ", {
      limit: null
    });
  ...
}
``` 
Coloquei um <code>setTimeout</code> antes da leitura do comando. Só que está feito errado, porque na prática ele só trava o <code>console.log()</code>, enquanto o restante do código seria executado de modo assíncrono. Certo?

**Então, justamente por isso que eu acho que está funcionando**, de algum jeito a leitura no terminal e a leitura/gravação de arquivos, uma está travando a outra antes da anterior terminar, com o <code>setTimeout</code> é como se fosse criado uma outra <code>thread</code> com um novo <code>buffer</code> de leitura e escrita livre, assim eu leio o comando e gravo o arquivo no momento desejado.

**O por quê, eu não sei!**

**Comment by danielschmitz** [comment]
Seria interessante postar seu repo pra entender melhor o que está acontecendo

**Comment by leandroungari** [comment]
Esse é o [repositório](https://github.com/leandroungari/database-comparative/blob/master/src/interpreter/index.js), o link direciona para o arquivo do interpretador descrito anteriormente.

**Comment by danielschmitz** [comment]
@leandroungari Seus problemas estão no ` fs.writeFileSync(filePath, contentString);` no state.js. A escrita do arquivo é assíncrona! Para resolver isso você tem que usar o [createWriteStream](https://nodejs.org/api/fs.html#fs_fs_createwritestream_path_options)

**Comment by leandroungari** [comment]
Obrigado pela sugestão. A minha ideia de usar o <code>fs.writeFileSync()</code> é que eu tivesse a garantia de que, se o usuário precisar dos dados atualizados nesse arquivo já no próximo comando, os dados estariam persistidos, mesmo que houvesse perda de desempenho. Contudo, ele está sendo bloqueado como descrito antes.

**Comment by danielschmitz** [comment]
Mude seu store para:

```js
const store = (filePath, data) => new Promise((resolve, reject) => {
    const contentString = JSON.stringify(data);
    const opts = {} // algumas opcoes se precisar (veja api)
    fs.writeFile(filePath, contentString , opts, (err) => {
      if (err) reject(err)
      else resolve()
    })
  })
```

Então você pode chamar o seu store assim:

```js
const storeState = async (state) => await store(stateFilePath, state);
```

Dessa forma vc garante que o arquivo é salvo e o fluxo de código só continue depois disso ocorrer

**Comment by leandroungari** [comment]
Obrigado @danielschmitz !
