### ISSUE TITLE
Problema de autenticação mesmo com todas as keys criadas

### ISSUE THREAD

**Issue by Gummygamer** [filipedeschamps/video-maker#98]
Já chequei o básico de todas as credenciais necessárias, mas obtenho um erro típico de problema com as keys.

Deixo meu output de console aqui:

Type a Wikipedia search term: Reinforcement learning

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 2
(node:490) UnhandledPromiseRejectionWarning: authorization required
(node:490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:490) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Viniciusog** [comment]
Sim, eu fiz a mesma coisa. Havia escrito 'apiKey', sendo que era 'apikey'. Após mudar o nome o problema foi resolvido

**Comment by eliaskill** [comment]
estou com erro aqui

(node:1180) UnhandledPromiseRejectionWarning: Error: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.
    at Gaxios.<anonymous> (C:\Users\PCzin\Desktop\py\video-maker-master 01042019\video-maker-master\node_modules\gaxios\build\src\gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\PCzin\Desktop\py\video-maker-master 01042019\video-maker-master\node_modules\gaxios\build\src\gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS C:\Users\PCzin\Desktop\py\video-maker-master 01042019\video-maker-master>

**Comment by Gummygamer** [comment]
Confimado que era o mesmo problema para mim, agora estou no passo do After Effects. Vou fechar a issue.
